/* CatCards — traduzioni ES (generato). Per aggiungere una lingua: copia questo file, traduci i valori, aggiungi il codice a LANGS in index.html) */
(window.LANG_DB = window.LANG_DB || {})["es"] = {
 "ui": {
  "tagline": "Fotografía a tu gato y conviértelo en una carta coleccionable",
  "tab_crea": "📸 Crear",
  "tab_carte": "📚 Cartas",
  "tab_dojo": "🥋 Dojo",
  "tab_mondo": "🌍 Mundo",
  "tab_mercato": "🔁 Mercado",
  "tab_boss": "🤖 Jefes",
  "tab_pal": "🏋️ Gimnasio",
  "tab_med": "🏅 Medallas",
  "tab_reg": "📖 Reglas",
  "drop_title": "Toca para hacer o subir una foto",
  "drop_sub": "JPG o PNG — mejor si el gato se ve bien",
  "cat_name": "Nombre del gato (opcional)",
  "gen_btn": "✨ Generar la carta",
  "dl_card": "⬇️ Descargar la carta (PNG)",
  "regen_btn": "🔁 Regenerar el dibujo (30 puntos)",
  "new_card": "🔄 Nueva carta",
  "coll_title": "📚 Tu colección",
  "dojo_title": "🥋 Dojo",
  "your_card": "Tu carta",
  "opponent": "Oponente",
  "fight_btn": "⚔️ ¡Pelea!",
  "tourn4": "🏆 Torneo de 4",
  "tourn8": "🏆 Torneo de 8",
  "albo": "📊 Palmarés",
  "pub_sum": "🗂️ Elige qué cartas publicar en el Mundo",
  "player_name": "Tu nombre de jugador (obligatorio, mín 3 letras)",
  "pub_btn": "📤 Publicar las cartas elegidas",
  "duel_title": "⚡ Reta a un amigo",
  "duel_champ": "Tu campeón para el duelo",
  "qr_show": "📱 Mostrar mi QR",
  "qr_scan": "📷 Escanear el suyo",
  "world_title": "🌍 Arena Mundial",
  "my_world": "🐱 Tus cartas en el mundo",
  "my_online": "Tu carta para los retos online",
  "find_btn": "🔄 Buscar rivales en el mundo",
  "leader_title": "🏅 Clasificación mundial",
  "leader_more": "⬇️ Mostrar más posiciones",
  "market_title": "🔁 Mercado",
  "trade_title": "🔄 Intercambio (trueque)",
  "trade_browse": "🔍 Ver cartas para intercambiar",
  "trader_ask": "💰 Pedir consejo al Mercader",
  "auc_title": "⚖️ Subastas",
  "auc_create": "🔨 Subastar una carta",
  "auc_refresh": "🔄 Actualizar subastas",
  "boss_title": "🤖 Jefes de la Arena",
  "boss_chall": "Tu retador (cartas publicadas)",
  "gym_title": "🏋️ Gimnasio",
  "gym_student": "El alumno de hoy",
  "gym_pantry": "🍽️ Despensa — compra y gánatelo jugando",
  "coach_ask": "🎓 Pedir consejo al Coach",
  "mis_title": "📅 Misiones de hoy",
  "med_title": "🏅 Medallero",
  "reg_title": "📖 Las reglas de CatCards",
  "opt_title": "⚙️ Opciones",
  "locked_title": "Se requiere acceso",
  "locked_txt": "Puntos, Mercado, retos y entrenamientos viven en tu cuenta: inicia sesión para usar Dojo, Mundo, Mercado, Jefes y Gimnasio.",
  "login_google": "🔵 Entrar con Google",
  "login_hint": "Inicia sesión: puntos, Mercado y retos viven en tu cuenta",
  "logout": "Salir",
  "close": "✖ Cerrar",
  "skip_intro": "⏭️ Saltar la presentación",
  "bet_title": "🥊 El rincón del Tío Rocco",
  "bet_sub": "🎲 Pronóstico",
  "bet_skip": "Sin apuesta, ¡al combate!",
  "bet_back": "↩️ Volver (cancelar el combate)",
  "points_lbl": "💰 Tus puntos:",
  "dl_short": "⬇️ Descargar",
  "nick_btn": "✏️ Cambiar apodo",
  "theme_btn": "▶️ Escuchar el tema",
  "retire_btn": "🚪 Retirar del mundo",
  "frame_btn": "🎨 Marco de Oro (100 puntos)",
  "del_btn": "🗑️ Eliminar"
 },
 "stat": {},
 "rarity": {},
 "ann": {
  "red": "Desde la esquina roja... {n}... «{k}»!",
  "blue": "Desde la esquina azul... {n}... «{k}»!"
 },
 "nicks": {
  "n01": "El Sócrates de la Lata",
  "n02": "El Barón Colmillo Torcido",
  "n03": "El Coloso de las Brasas",
  "n04": "El Gladiador del Asfalto",
  "n05": "El Quesito Durmiente",
  "n06": "El Monolito de Felpa",
  "n07": "El Maestro Lamedor Zen",
  "n08": "El Imperturbable Zen",
  "n09": "La Fortaleza Blanda Inamovible",
  "n10": "El Radar del Más Allá del Sofá",
  "n11": "El Radar de los Males",
  "n12": "Su Suavidad Hipnótica",
  "n13": "El Veterano del Ronroneo",
  "n14": "El Triste Hipnotista Felino",
  "n15": "El Panzer de Seda",
  "n16": "El Escape en Llamas",
  "n17": "El Ovillo Hipnótico",
  "n18": "La Garra de Jengibre",
  "n19": "El Dirigible de Mesa",
  "n20": "El Bastión de Pelo",
  "n21": "El Mejilla de Acero",
  "n22": "El Fantasma del Sofá",
  "n23": "La Furia del Trastero",
  "n24": "El Tornado de Pelo",
  "n25": "La Sombra de la Despensa",
  "n26": "El Ninja del Alféizar",
  "n27": "La Avalancha Rojiza",
  "n28": "El Sicario de las Cortinas",
  "n29": "El Terror de los Ovillos",
  "n30": "La Locomotora Perezosa",
  "n31": "El Filósofo del Radiador",
  "n32": "El Huracán en Pantuflas",
  "n33": "El Guepardo de Salón",
  "n34": "La Esfinge del Frigorífico",
  "n35": "El Relámpago Socarrón",
  "n36": "El Cojín Asesino",
  "n37": "La Bestia del Balcón",
  "n38": "El General Zarpazo",
  "n39": "El Acróbata de Medianoche",
  "n40": "El Sultán de la Siesta",
  "n41": "El Tigre de la Moqueta",
  "n42": "El Fantasma de la Escalera",
  "n43": "El Destructor de Sofás",
  "n44": "La Pantera del Rellano",
  "n45": "El Barón de los Bocaditos",
  "n46": "El Emperador de la Cesta",
  "n47": "El Pirata del Pescado Fresco",
  "n48": "El Rayo de Peluche",
  "n49": "El Campeón de las Croquetas",
  "n50": "El Estratega del Desván",
  "n51": "El Monstruo de las Zapatillas",
  "n52": "La Duquesa con Garras",
  "n53": "El Vikingo Aterciopelado",
  "n54": "El Enigma Bigotudo",
  "n55": "El Ciclón Silencioso",
  "n56": "La Zarpa del Destino",
  "n57": "El Rey del Cartón",
  "n58": "La Emboscada Permanente",
  "n59": "El Meteorito Blando",
  "n60": "La Leyenda del Patio",
  "n61": "El Guardián del Cuenco",
  "n62": "El Ojo de la Noche",
  "n63": "El Samurái Despeluchado",
  "n64": "La Furia Tricolor",
  "n65": "El Profesor de Emboscadas",
  "n66": "El Almirante de los Tejados",
  "n67": "La Apisonadora",
  "n68": "La Peste Elegante",
  "n69": "El Volcán Somnoliento",
  "n70": "La Garra de Terciopelo",
  "n71": "El Bandido de la Cocina",
  "n72": "El Centinela del Frigo",
  "n73": "El Dragón del Cojín",
  "n74": "El Eco del Maullido",
  "n75": "El Maestro del Ronroneo",
  "n76": "La Tormenta de Bolsillo",
  "n77": "El Gigante Amable",
  "n78": "El Último Callejero",
  "n79": "El Cazador de Lagartijas",
  "n80": "La Novena Vida"
 },
 "descrs": {
  "d01": "Duerme 20 horas al día y las otras 4 entrena para dormir mejor.",
  "d02": "Nunca ha perdido una batalla contra un calcetín.",
  "d03": "Cree que el frigorífico le debe explicaciones.",
  "d04": "Maestro en el arte de ocupar justo donde querías sentarte.",
  "d05": "Ha tirado tres jarrones. Todos culpables.",
  "d06": "Habla tres idiomas: ronroneo, maullido y desprecio.",
  "d07": "Corre a las 4 de la mañana por razones que no nos incumben.",
  "d08": "Un guerrero nato, siempre que el sofá esté a menos de dos metros.",
  "d09": "Su cuenco está medio vacío. Siempre. Incluso lleno.",
  "d10": "Mira fijamente la pared porque la pared empezó primero.",
  "d11": "Ex callejero, ahora alto ejecutivo de la siesta.",
  "d12": "Ronronea como un tractor y araña como una navaja.",
  "d13": "El veterinario aún lo recuerda en sus pesadillas.",
  "d14": "No persigue ratones: envía avisos de desahucio.",
  "d15": "Sabe abrir tres tipos de puertas y finge que no.",
  "d16": "La caja vale más que el regalo. Siempre.",
  "d17": "Doctorado en miradas de juicio.",
  "d18": "Lucha contra el crimen. El crimen es la aspiradora.",
  "d19": "Cada silla de la casa es suya. También la tuya.",
  "d20": "Entrena en las cortinas cuando nadie mira.",
  "d21": "Pasatiempo favorito: tirar cosas de las mesas con elegancia.",
  "d22": "Maúlla en do menor cuando el cuenco está vacío.",
  "d23": "Nadie lo ha visto llegar. Solo irse con la cena.",
  "d24": "Pesa justo lo necesario para inmovilizarte las piernas.",
  "d25": "Las lagartijas del barrio han puesto precio a su cabeza.",
  "d26": "Duerme en posturas que desafían la física y el sentido común.",
  "d27": "Entendió el láser. Finge que no, por lástima.",
  "d28": "Un cruce entre un cojín y un cepo.",
  "d29": "Vigila el barrio desde la ventana como un jefe de estado.",
  "d30": "Su ronroneo cura el estrés. Sus uñas lo causan.",
  "d31": "Come como un lobo, duerme como una piedra, reina como un rey.",
  "d32": "El único gato que ganó una discusión con un pepino.",
  "d33": "Se ofende si lo miras. Se ofende si no lo miras.",
  "d34": "Tiene tres escondites secretos. El mejor: en medio del pasillo.",
  "d35": "De pequeño cayó en un cuenco de nata. Nunca se recuperó.",
  "d36": "Enseña yoga a los gatos del barrio. Primera lección: ignorar a todos.",
  "d37": "El cartero pidió el traslado.",
  "d38": "Colecciona gomas de pelo. Nadie sabe dónde las esconde.",
  "d39": "Cuando hay tormenta, protege la casa. Desde debajo de la cama.",
  "d40": "Su mirada ha espantado a dos perros y un fontanero.",
  "d41": "Vive para tres cosas: comer, dormir y juzgarte.",
  "d42": "Una vez vio un ratón. Ambos aún lo cuentan.",
  "d43": "Elegantísimo hasta que se cae del alféizar.",
  "d44": "Adoptó a una familia de humanos. Los está adiestrando bien.",
  "d45": "No se sube a la mesa. La mesa baja a su nivel.",
  "d46": "Sabe exactamente cuándo abres el atún. Incluso a una manzana.",
  "d47": "El ovillo ya estaba así cuando llegó.",
  "d48": "Mitad gato, mitad sirena de alarma de las 5 a.m.",
  "d49": "Pelea con honor, gana con estilo, duerme sin vergüenza.",
  "d50": "Lo último que ven las alfombras antes del final."
 },
 "battle": {
  "skip": "⏭️ Presentación saltada: ¡al grano!",
  "open": "🎤 SEÑORAS Y SEÑOREEES… ¡bienvenidos a la Arena CatCards!",
  "red": "🔴 Esquina roja: {NAME}, «{nick}»! {rec}",
  "blue": "🔵 Esquina azul: {NAME}, «{nick}»! {rec}",
  "debut": "¡En su debut en la arena!",
  "theme": "🎵 Suena el tema de entrada de {name}…",
  "ding": "🔔 ¡DING DING DING!",
  "first_fast": "⚡ ¡{name} es más rápido y ataca primero!",
  "first_surprise": "😼 ¡{name} sorprende a todos y empieza!",
  "round_end": "🔔 ¡Fin del asalto {round}! Los gatos vuelven a su esquina a lamerse…",
  "charmed_skip": "😍 ¡{name} está embelesado y pierde el turno!",
  "chant": "🎺 Desde las gradas: «{NAME}! {NAME}!»",
  "pu_yarn": "🧶 ¡Un ovillo rueda a la arena! {name} juega y recupera {hp} PV",
  "pu_catnip": "🌿 ¡Hierba gatera! {name} está eufórico: próximo golpe DOBLE (pero algo mareado…)",
  "pu_box": "📦 ¡Una caja de cartón! {name} no se resiste: pierde el turno pero es INTOCABLE!",
  "pu_fish": "🐟 ¡Un pez fresco vuela a la arena! {name} rebosa energía: +agilidad por 3 turnos",
  "purr_heal": "💗 {name} ronronea y recupera {hp} PV",
  "double_paw": "🐾 ¡Doble Zarpazo! ¡{name} ataca otra vez!",
  "box_dodge": "📦 {opp} está escondido en la caja: ¡el golpe de {name} falla!",
  "dodge": "💨 {name} intenta {move} pero {opp} esquiva!",
  "final_blow": "⏱️ El tiempo se ralentiza… ¡GOLPE FINAL!",
  "hit": "{icon} {name} usa {move}!{crit}{catnip}  −{dmg} PV",
  "crit_tag": " 💥 ¡CRÍTICO!",
  "catnip_tag": " 🌿 ¡POTENCIADO!",
  "dev1": "😱 ¡Golpe devastador!",
  "dev2": "🎙️ ¡El público enloquece!",
  "dev3": "💢 ¡Qué potencia impresionante!",
  "on_fire": "🔥 ¡{name} está ON FIRE! ¡Tres golpes seguidos!",
  "on_ropes": "🎙️ ¡{opp} está contra las cuerdas! El público contiene la respiración…",
  "clever": "✨ ¡Jugada astuta! {opp} queda confuso y perderá un turno!",
  "nine_lives": "🐈 ¡{opp} usa una de sus Nueve Vidas y aguanta con 1 PV!",
  "charm_hit": "✨ ¡{opp} queda embelesado por el encanto de {name}!",
  "replay": "📹 REPETICIÓN del golpe final…",
  "winner": "🏆 ¡{name} gana el combate!",
  "win_points": "💰 ¡+10 puntos por la victoria!",
  "boss_points": "💰 ¡+10 puntos: has domado a un Jefe de la Arena!",
  "boss_noprize": "🎖️ Jefe ya vencido hoy: gloria sí, premio mañana.",
  "boss_survives": "🤖 El Jefe sigue en pie... el intento de hoy se fue: hasta mañana (quizá con hierba gatera 🌿).",
  "tourn_champ": "👑 ¡{name} es el CAMPEÓN del torneo!",
  "world_ok": "🌍 ¡Resultado registrado en la Arena Mundial!",
  "bet_win": "🎲 ¡Acertaste! Apostaste {stake} a {name}: +{gain} puntos (total: {total})",
  "bet_lose": "🎲 Fallaste: −{stake} puntos (total: {total}). ¡La próxima irá mejor!",
  "stake": "🎁 En juego — victoria: {win} · derrota: +{lose} XP",
  "stake_pts": "+{pt} puntos y +{xp} XP",
  "stake_nopts": "+{xp} XP (sin puntos en local)",
  "boss_stake_note": " — puntos solo en la 1ª victoria del día",
  "entry_catnip": "🌿 ¡{name} entra en la arena ya cargado de hierba gatera!"
 },
 "chars": {
  "rocco_warn": "Ojo con su {stat}: ahí te come.",
  "rocco_70": "Chaval, a este lo tumbas antes del gong. No te confíes y ciérralo rápido.",
  "rocco_55": "Eres el favorito, pero los favoritos que se duermen acaban en la lona. Pega primero.",
  "rocco_50": "Cincuenta-cincuenta, chaval: gana el que tenga más hambre. Si tienes 50 puntos, la hierba gatera los vale.",
  "rocco_35": "No te miento: es más grande que tú. Sin hierba gatera yo no haría este combate.",
  "rocco_lose": "Hazle caso al viejo Rocco: este te rompe. Vuelve al gimnasio, sube un nivel y LUEGO hablamos. Si insistes, al menos la hierba gatera.",
  "baratto_great": "🤑 ¡Un chollo! Recibes mucho más de lo que das — ciérralo rápido.",
  "baratto_good": "👍 Buen trato: sales ganando. El Mercader aprueba.",
  "baratto_even": "⚖️ Intercambio parejo: decide con el corazón, no con la cartera.",
  "baratto_bad": "😾 Pierdes algo... ¿seguro? El Mercader tuerce los bigotes.",
  "baratto_terrible": "🙀 ¡Pésimo trato! Das mucho más de lo que recibes. Olvídalo.",
  "baratto_empty": "¡No tienes cartas para trocar! Crea algunas y vuelve: el bazar es para negocios, no caridad.",
  "inc_100a": "¡CIEN PUNTOS! ¡Qué locura magnífica! 😼",
  "inc_100b": "¡Una oferta de reyes! ¿Y quién se atreve a subir?",
  "inc_50a": "¡Cincuenta! ¡El público tiembla, señores!",
  "inc_50b": "¡Buena cifra! ¡La subasta se calienta!",
  "inc_bata": "¡Y sube otra vez! ¡No paran!",
  "inc_batb": "¡Batalla hasta el último punto, qué espectáculo!",
  "inc_starta": "¡Primera puja en la mesa! ¿Quién da más?",
  "inc_startb": "¡Empezamos! ¡Adjudicado al que no se rinda!",
  "baffo_open": [
   "¡Miau, recluta! ",
   "Escucha al viejo Baffo: ",
   "Suelta la croqueta y escucha: ",
   "En mis tiempos no había cojines blandos. ",
   "Bigotes tiesos y orejas alerta: "
  ],
  "baffo_empty": "¡El gimnasio está vacío! Tráeme un alumno desde la pestaña 📸 Crear.",
  "baffo_indiff_afford": "El punto débil de {name} es {stat} ({val}): entrénala con el combo {combo} (60 puntos), puedes permitírtelo.",
  "baffo_indiff_save": "El punto débil de {name} es {stat} ({val}), pero solo se entrena con el combo {combo} (60 puntos): te faltan {miss}, ve ahorrando.",
  "baffo_indiff_alt": " O mientras tanto refuerza {stat2} ({val2}) con {food} (25 puntos).",
  "baffo_weak": "El punto más débil de {name} es {stat} ({val}): dale {food}.",
  "baffo_combo": "Tienes {pts} puntos: el combo {combo} ({tgt}) sube dos cosas en un solo descanso — caro pero útil si tienes prisa.",
  "baffo_record_bad": "Con {w} victorias y {l} derrotas hace falta garra, no mimos.",
  "baffo_unbeaten": "Está invicto: cuidado no se le suba a la cabeza.",
  "baffo_margin": "Margen de entrenamiento agotado: solo las victorias en el Mundo desbloquean más progreso.",
  "baffo_broke": "Y las arcas lloran ({pts} puntos): gana alguna apuesta mundial.",
  "baffo_fit": "{name} está en plena forma. Que pelee, que el banquillo ablanda los músculos."
 }
};
