/* CatCards — traduzioni IT (generato). Per aggiungere una lingua: copia questo file, traduci i valori, aggiungi il codice a LANGS in index.html) */
(window.LANG_DB = window.LANG_DB || {})["it"] = {
 "ui": {
  "tagline": "Fotografa il tuo gatto e trasformalo in una carta da collezione",
  "tab_crea": "📸 Crea",
  "tab_carte": "📚 Carte",
  "tab_dojo": "🥋 Dojo",
  "tab_mondo": "🌍 Mondo",
  "tab_mercato": "🔁 Mercato",
  "tab_boss": "🤖 Boss",
  "tab_pal": "🏋️ Palestra",
  "tab_med": "🏅 Medagliere",
  "tab_reg": "📖 Regole",
  "drop_title": "Tocca per scattare o caricare una foto",
  "drop_sub": "JPG o PNG — meglio se il gatto è ben visibile",
  "cat_name": "Nome del gatto (opzionale)",
  "gen_btn": "✨ Genera la carta",
  "dl_card": "⬇️ Scarica la carta (PNG)",
  "regen_btn": "🔁 Rigenera il disegno (30 punti)",
  "new_card": "🔄 Nuova carta",
  "coll_title": "📚 La tua collezione",
  "dojo_title": "🥋 Dojo",
  "your_card": "La tua carta",
  "opponent": "Avversario",
  "fight_btn": "⚔️ Combatti!",
  "tourn4": "🏆 Torneo a 4",
  "tourn8": "🏆 Torneo a 8",
  "albo": "📊 Albo d'oro",
  "pub_sum": "🗂️ Scegli quali carte pubblicare nel Mondo",
  "player_name": "Il tuo nome giocatore (obbligatorio, min 3 lettere)",
  "pub_btn": "📤 Pubblica le carte selezionate",
  "duel_title": "⚡ Sfida un amico",
  "duel_champ": "Il tuo campione per il duello",
  "qr_show": "📱 Mostra il mio QR",
  "qr_scan": "📷 Inquadra il suo",
  "world_title": "🌍 Arena Mondiale",
  "my_world": "🐱 Le tue carte nel mondo",
  "my_online": "La tua carta per le sfide online",
  "find_btn": "🔄 Cerca sfidanti nel mondo",
  "leader_title": "🏅 Classifica mondiale",
  "leader_more": "⬇️ Mostra altre posizioni",
  "market_title": "🔁 Mercato",
  "trade_title": "🔄 Scambio (baratto)",
  "trade_browse": "🔍 Sfoglia carte da scambiare",
  "trader_ask": "💰 Chiedi consiglio al Mercante",
  "auc_title": "⚖️ Aste",
  "auc_create": "🔨 Metti una carta all'asta",
  "auc_refresh": "🔄 Aggiorna aste",
  "boss_title": "🤖 Boss dell'Arena",
  "boss_chall": "Il tuo sfidante (carte pubblicate)",
  "gym_title": "🏋️ Palestra",
  "gym_student": "L'allievo di oggi",
  "gym_pantry": "🍽️ Dispensa — compra, poi guadagnatelo col gioco",
  "coach_ask": "🎓 Chiedi un consiglio al Coach",
  "mis_title": "📅 Missioni di oggi",
  "med_title": "🏅 Medagliere",
  "reg_title": "📖 Le regole di CatCards",
  "opt_title": "⚙️ Opzioni",
  "locked_title": "Serve l'accesso",
  "locked_txt": "Punti, Mercato, sfide e allenamenti vivono sul tuo account: per usare Dojo, Mondo, Mercato, Boss e Palestra devi prima accedere.",
  "login_google": "🔵 Accedi con Google",
  "login_hint": "Accedi: punti, Mercato e sfide vivono sul tuo account",
  "logout": "Esci",
  "close": "✖ Chiudi",
  "skip_intro": "⏭️ Salta la presentazione",
  "bet_title": "🥊 L'angolo di Zio Rocco",
  "bet_sub": "🎲 Pronostico",
  "bet_skip": "Non scommetto, via al match!",
  "bet_back": "↩️ Torna indietro (annulla il match)",
  "points_lbl": "💰 I tuoi punti:",
  "dl_short": "⬇️ Scarica",
  "nick_btn": "✏️ Cambia soprannome",
  "theme_btn": "▶️ Ascolta il tema",
  "retire_btn": "🚪 Ritira dal mondo",
  "frame_btn": "🎨 Cornice d'Oro (100 punti)",
  "del_btn": "🗑️ Elimina"
 },
 "stat": {},
 "rarity": {},
 "ann": {
  "red": "Dall'angolo rosso... {n}... «{k}»!",
  "blue": "Dall'angolo blu... {n}... «{k}»!"
 },
 "nicks": {
  "n01": "Il Socrate della Latta",
  "n02": "Il Barone Zanna Storta",
  "n03": "Il Colosso della Brace",
  "n04": "Il Gladiatore dell'Asfalto",
  "n05": "Lo Stracchino Dormiente",
  "n06": "Il Monolito di Felpa",
  "n07": "Il Mastro Leccatore Zen",
  "n08": "L'Imperturbabile Zen",
  "n09": "L'Inamovibile Fortezza Morbida",
  "n10": "Il Radar dell'Oltredivano",
  "n11": "Il Radar del Malanno",
  "n12": "Sua Morbidezza Ipnotica",
  "n13": "Il Veterano delle Fusa",
  "n14": "Il Triste Ipnotista Felino",
  "n15": "Il Panzer di Seta",
  "n16": "La Marmitta Infuocata",
  "n17": "Il Batuffolo Ipnotico",
  "n18": "L'Artiglio allo Zenzero",
  "n19": "Il Dirigibile Centro-Tavola",
  "n20": "Il Bastione di Pelo",
  "n21": "Il Guancia d'Acciaio",
  "n22": "Lo Spettro del Divano",
  "n23": "La Furia del Sottoscala",
  "n24": "Il Tornado di Pelo",
  "n25": "L'Ombra della Dispensa",
  "n26": "Il Ninja del Davanzale",
  "n27": "La Valanga Fulva",
  "n28": "Il Sicario delle Tende",
  "n29": "Il Terrore dei Gomitoli",
  "n30": "La Locomotiva Pigra",
  "n31": "Il Filosofo del Termosifone",
  "n32": "L'Uragano in Pantofole",
  "n33": "Il Ghepardo da Salotto",
  "n34": "La Sfinge del Frigorifero",
  "n35": "Il Lampo Sornione",
  "n36": "Il Cuscino Assassino",
  "n37": "La Belva del Balcone",
  "n38": "Il Generale Graffio",
  "n39": "L'Acrobata di Mezzanotte",
  "n40": "Il Sultano del Sonnellino",
  "n41": "La Tigre della Moquette",
  "n42": "Il Fantasma delle Scale",
  "n43": "Il Distruttore di Divani",
  "n44": "La Pantera del Pianerottolo",
  "n45": "Il Barone dei Bocconcini",
  "n46": "L'Imperatore del Cestino",
  "n47": "Il Pirata del Pesce Fresco",
  "n48": "La Saetta Peluche",
  "n49": "Il Campione dei Croccantini",
  "n50": "Lo Stratega del Sottotetto",
  "n51": "Il Mostro delle Ciabatte",
  "n52": "La Duchessa Artigliata",
  "n53": "Il Vichingo Vellutato",
  "n54": "L'Enigma Baffuto",
  "n55": "Il Ciclone Silenzioso",
  "n56": "La Zampa del Destino",
  "n57": "Il Re del Cartone",
  "n58": "L'Agguato Permanente",
  "n59": "Il Meteorite Morbido",
  "n60": "La Leggenda del Cortile",
  "n61": "Il Guardiano della Ciotola",
  "n62": "L'Occhio della Notte",
  "n63": "Il Samurai Spelacchiato",
  "n64": "La Furia Tricolore",
  "n65": "Il Professore di Agguati",
  "n66": "L'Ammiraglio dei Tetti",
  "n67": "Il Rullo Compressore",
  "n68": "La Peste Elegante",
  "n69": "Il Vulcano Sonnolento",
  "n70": "L'Artiglio di Velluto",
  "n71": "Il Bandito della Cucina",
  "n72": "La Sentinella del Frigo",
  "n73": "Il Drago del Cuscino",
  "n74": "L'Eco del Miagolio",
  "n75": "Il Maestro di Fusa",
  "n76": "La Tempesta Tascabile",
  "n77": "Il Gigante Gentile",
  "n78": "L'Ultimo Randagio",
  "n79": "Il Cacciatore di Lucertole",
  "n80": "La Nona Vita"
 },
 "descrs": {
  "d01": "Dorme 20 ore al giorno e nelle altre 4 si allena a dormire meglio.",
  "d02": "Non ha mai perso una battaglia contro un calzino.",
  "d03": "Crede che il frigorifero gli debba delle spiegazioni.",
  "d04": "Maestro nell'arte di occupare esattamente il posto dove volevi sederti.",
  "d05": "Ha rovesciato tre vasi. Tutti colpevoli.",
  "d06": "Parla tre lingue: fusa, miagolio e disprezzo.",
  "d07": "Corre alle 4 del mattino per motivi che non ci è dato sapere.",
  "d08": "Un guerriero nato, purché il divano sia a meno di due metri.",
  "d09": "La sua ciotola è mezza vuota. Sempre. Anche piena.",
  "d10": "Fissa il muro perché il muro ha iniziato per primo.",
  "d11": "Ex randagio, ora dirigente d'azienda del pisolino.",
  "d12": "Fa le fusa come un trattore e graffia come un rasoio.",
  "d13": "Il veterinario lo ricorda ancora nei suoi incubi.",
  "d14": "Non insegue i topi: manda avvisi di sfratto.",
  "d15": "Sa aprire tre tipi di porte e finge di non saperlo.",
  "d16": "La scatola vale più del regalo. Sempre.",
  "d17": "Ha un dottorato in sguardi di giudizio.",
  "d18": "Combatte il crimine. Il crimine è l'aspirapolvere.",
  "d19": "Ogni sedia della casa è sua. Anche la tua.",
  "d20": "Si allena sulle tende quando nessuno guarda.",
  "d21": "Il suo passatempo preferito: buttare cose dai tavoli con eleganza.",
  "d22": "Miagola in Do minore quando la ciotola è vuota.",
  "d23": "Nessuno l'ha mai visto arrivare. Solo partire con la cena.",
  "d24": "Pesa il giusto: esattamente quanto serve per bloccarti le gambe.",
  "d25": "Le lucertole del quartiere hanno organizzato una taglia su di lui.",
  "d26": "Dorme in posizioni che sfidano la fisica e il buonsenso.",
  "d27": "Ha capito come funziona il laser. Finge di no per pietà.",
  "d28": "Un incrocio tra un cuscino e una tagliola.",
  "d29": "Sorveglia il quartiere dalla finestra come un capo di stato.",
  "d30": "Le sue fusa curano lo stress. Le sue unghie lo causano.",
  "d31": "Mangia come un lupo, dorme come un sasso, regna come un re.",
  "d32": "L'unico gatto che ha vinto una discussione con un cetriolo.",
  "d33": "Si offende se lo guardi. Si offende se non lo guardi.",
  "d34": "Ha tre nascondigli segreti. Il migliore: in mezzo al corridoio.",
  "d35": "Da piccolo cadde in una ciotola di panna. Non si è più ripreso.",
  "d36": "Insegna yoga ai gatti del vicinato. Prima lezione: ignorare tutti.",
  "d37": "Il postino ha chiesto il trasferimento.",
  "d38": "Colleziona elastici per capelli. Nessuno sa dove li nasconda.",
  "d39": "Quando c'è un temporale, protegge la casa. Da sotto il letto.",
  "d40": "Il suo sguardo ha fatto scappare due cani e un idraulico.",
  "d41": "Vive per tre cose: mangiare, dormire e giudicarti.",
  "d42": "Una volta ha visto un topo. Ne parlano ancora entrambi.",
  "d43": "Elegantissimo finché non cade dal davanzale.",
  "d44": "Ha adottato una famiglia di umani. Li sta addestrando bene.",
  "d45": "Non sale sul tavolo. Il tavolo si abbassa al suo livello.",
  "d46": "Sa esattamente quando apri il tonno. Anche dall'altro isolato.",
  "d47": "Il gomitolo era già così quando è arrivato.",
  "d48": "Metà gatto, metà sirena d'allarme delle 5 del mattino.",
  "d49": "Combatte con onore, vince con stile, dorme senza vergogna.",
  "d50": "L'ultima cosa che i tappeti vedono prima della fine."
 }
};
