(window.LANG_DB=window.LANG_DB||{})["it"] = {
  "ui": {
    "tagline": "Fotografa il tuo gatto e trasformalo in una carta da collezione",
    "tab_crea": "📸 Crea",
    "tab_carte": "📚 Carte",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Mondo",
    "tab_mercato": "🔁 Mercato",
    "tab_boss": "🤖 Boss",
    "tab_pal": "🏋️ Palestra",
    "tab_med": "🏅 Medagliere",
    "tab_reg": "📖 Regole",
    "drop_title": "Tocca per scattare o caricare una foto",
    "drop_sub": "JPG o PNG — meglio se il gatto è ben visibile",
    "cat_name": "Nome del gatto (opzionale)",
    "gen_btn": "✨ Genera la carta",
    "dl_card": "⬇️ Scarica la carta (PNG)",
    "regen_btn": "🔁 Rigenera il disegno (30 punti)",
    "new_card": "🔄 Nuova carta",
    "coll_title": "📚 La tua collezione",
    "dojo_title": "🥋 Dojo",
    "your_card": "La tua carta",
    "opponent": "Avversario",
    "fight_btn": "⚔️ Combatti!",
    "tourn4": "🏆 Torneo a 4",
    "tourn8": "🏆 Torneo a 8",
    "albo": "📊 Albo d'oro",
    "pub_sum": "🗂️ Scegli quali carte pubblicare nel Mondo",
    "player_name": "Il tuo nome giocatore (obbligatorio, min 3 lettere)",
    "pub_btn": "📤 Pubblica le carte selezionate",
    "duel_title": "⚡ Sfida un amico",
    "duel_champ": "Il tuo campione per il duello",
    "qr_show": "📱 Mostra il mio QR",
    "qr_scan": "📷 Inquadra il suo",
    "world_title": "🌍 Arena Mondiale",
    "my_world": "🐱 Le tue carte nel mondo",
    "my_online": "La tua carta per le sfide online",
    "find_btn": "🔄 Cerca sfidanti nel mondo",
    "leader_title": "🏅 Classifica mondiale",
    "leader_more": "⬇️ Mostra altre posizioni",
    "market_title": "🔁 Mercato",
    "trade_title": "🔄 Scambio (baratto)",
    "trade_browse": "🔍 Sfoglia carte da scambiare",
    "trader_ask": "💰 Chiedi consiglio al Mercante",
    "auc_title": "⚖️ Aste",
    "auc_create": "🔨 Metti una carta all'asta",
    "auc_refresh": "🔄 Aggiorna aste",
    "boss_title": "🤖 Boss dell'Arena",
    "boss_chall": "Il tuo sfidante (carte pubblicate)",
    "gym_title": "🏋️ Palestra",
    "gym_student": "L'allievo di oggi",
    "gym_pantry": "🍽️ Dispensa — compra, poi guadagnatelo col gioco",
    "coach_ask": "🎓 Chiedi un consiglio al Coach",
    "mis_title": "📅 Missioni di oggi",
    "med_title": "🏅 Medagliere",
    "reg_title": "📖 Le regole di CatCards",
    "opt_title": "⚙️ Opzioni",
    "locked_title": "Serve l'accesso",
    "locked_txt": "Punti, Mercato, sfide e allenamenti vivono sul tuo account: per usare Dojo, Mondo, Mercato, Boss e Palestra devi prima accedere.",
    "login_google": "🔵 Accedi con Google",
    "login_hint": "Accedi: punti, Mercato e sfide vivono sul tuo account",
    "logout": "Esci",
    "close": "✖ Chiudi",
    "skip_intro": "⏭️ Salta la presentazione",
    "bet_title": "🥊 L'angolo di Zio Rocco",
    "bet_sub": "🎲 Pronostico",
    "bet_skip": "Non scommetto, via al match!",
    "bet_back": "↩️ Torna indietro (annulla il match)",
    "points_lbl": "💰 I tuoi punti:",
    "dl_short": "⬇️ Scarica",
    "nick_btn": "✏️ Cambia soprannome",
    "theme_btn": "▶️ Ascolta il tema",
    "retire_btn": "🚪 Ritira dal mondo",
    "frame_btn": "🎨 Cornice d'Oro (100 punti)",
    "del_btn": "🗑️ Elimina",
    "coach_greet": "Miao, recluta. Scegli un allievo e mettiamoci al lavoro.",
    "gym_combo": "🌟 Combo Premium — due statistiche, un solo riposo",
    "bet_choose": "Scegli la puntata e su chi scommettere. Se sbagli, perdi la puntata.",
    "bet_insufficient": "Punti insufficienti per scommettere (minimo 10).",
    "tab_sent": "🗺️ Sentiero",
    "opt_ai_sum": "🤖 Impostazioni AI",
    "opt_key_label": "Chiave API Gemini",
    "opt_test_key": "🧪 Prova la chiave",
    "opt_backup_label": "Backup della collezione",
    "opt_export": "💾 Esporta backup",
    "opt_import": "📂 Importa backup",
    "opt_gift_label": "🎁 Codice regalo",
    "opt_redeem": "Riscatta punti",
    "opt_av_label": "Audio e presentazioni",
    "snd_on": "🔊 Suoni: ON",
    "snd_off": "🔇 Suoni: OFF",
    "pres_on": "🎬 Presentazioni: ON",
    "pres_skip": "⏭️ Presentazioni: SALTATE",
    "bt_bracket": "📋 Tabellone",
    "qr_desc1": "Duello dal vivo, telefono contro telefono: vale punti, medaglie e scommesse come una sfida mondiale.",
    "qr_desc2": "Uno dei due mostra il QR, l'altro lo inquadra: il duello si gioca sul telefono di chi inquadra.",
    "coll_one": "1 carta salvata",
    "coll_many": "{n} carte salvate",
    "coll_none": "Nessuna carta ancora: creane una nella scheda 📸 Crea, o importa un backup da ⚙️ Opzioni.",
    "xp_line": "📈 Livello {lvl} — {inLvl}/100 XP (≈ {w} vittorie mondiali al Lv.{next})",
    "opt_ai_desc": "Senza chiave API uso un filtro cartoon integrato e gratuito. Con una chiave <strong>Google Gemini</strong> il cartoon è generato dall'AI (qualità molto superiore). Creala gratis su <strong>aistudio.google.com</strong> → «Get API key».",
    "tab_award": "🏆 Award",
    "publish_btn": "🌍 Pubblica sul mondo",
    "pub_moved": "Per pubblicare o ritirare una carta, toccala nella scheda 📚 Carte.",
    "ask_name_title": "Come ti chiami?",
    "ask_name_desc": "È il nome che vedranno gli sfidanti (min 3 lettere).",
    "ask_name_ok": "Salva e pubblica",
    "ask_name_cancel": "Annulla",
    "hub_fight": "Combatti",
    "hub_cards": "Carte",
    "hub_glory": "Gloria",
    "hub_social": "Sociale",
    "tab_opz": "⚙️ Opzioni",
    "tab_gang": "🛡️ Gang"
  },
  "stat": {
    "Forza": "Forza",
    "Intelligenza": "Intelligenza",
    "Destrezza": "Destrezza",
    "Velocità": "Velocità",
    "Fascino": "Fascino",
    "Indifferenza": "Indifferenza"
  },
  "rarity": {
    "Comune": "Comune",
    "Rara": "Rara",
    "Epica": "Epica",
    "Leggendaria": "Leggendaria"
  },
  "ann": {
    "red": "Dall'angolo rosso... {n}... «{k}»!",
    "blue": "Dall'angolo blu... {n}... «{k}»!"
  },
  "nicks": {
    "n01": "Il Socrate della Latta",
    "n02": "Il Barone Zanna Storta",
    "n03": "Il Colosso della Brace",
    "n04": "Il Gladiatore dell'Asfalto",
    "n05": "Lo Stracchino Dormiente",
    "n06": "Il Monolito di Felpa",
    "n07": "Il Mastro Leccatore Zen",
    "n08": "L'Imperturbabile Zen",
    "n09": "L'Inamovibile Fortezza Morbida",
    "n10": "Il Radar dell'Oltredivano",
    "n11": "Il Radar del Malanno",
    "n12": "Sua Morbidezza Ipnotica",
    "n13": "Il Veterano delle Fusa",
    "n14": "Il Triste Ipnotista Felino",
    "n15": "Il Panzer di Seta",
    "n16": "La Marmitta Infuocata",
    "n17": "Il Batuffolo Ipnotico",
    "n18": "L'Artiglio allo Zenzero",
    "n19": "Il Dirigibile Centro-Tavola",
    "n20": "Il Bastione di Pelo",
    "n21": "Il Guancia d'Acciaio",
    "n22": "Lo Spettro del Divano",
    "n23": "La Furia del Sottoscala",
    "n24": "Il Tornado di Pelo",
    "n25": "L'Ombra della Dispensa",
    "n26": "Il Ninja del Davanzale",
    "n27": "La Valanga Fulva",
    "n28": "Il Sicario delle Tende",
    "n29": "Il Terrore dei Gomitoli",
    "n30": "La Locomotiva Pigra",
    "n31": "Il Filosofo del Termosifone",
    "n32": "L'Uragano in Pantofole",
    "n33": "Il Ghepardo da Salotto",
    "n34": "La Sfinge del Frigorifero",
    "n35": "Il Lampo Sornione",
    "n36": "Il Cuscino Assassino",
    "n37": "La Belva del Balcone",
    "n38": "Il Generale Graffio",
    "n39": "L'Acrobata di Mezzanotte",
    "n40": "Il Sultano del Sonnellino",
    "n41": "La Tigre della Moquette",
    "n42": "Il Fantasma delle Scale",
    "n43": "Il Distruttore di Divani",
    "n44": "La Pantera del Pianerottolo",
    "n45": "Il Barone dei Bocconcini",
    "n46": "L'Imperatore del Cestino",
    "n47": "Il Pirata del Pesce Fresco",
    "n48": "La Saetta Peluche",
    "n49": "Il Campione dei Croccantini",
    "n50": "Lo Stratega del Sottotetto",
    "n51": "Il Mostro delle Ciabatte",
    "n52": "La Duchessa Artigliata",
    "n53": "Il Vichingo Vellutato",
    "n54": "L'Enigma Baffuto",
    "n55": "Il Ciclone Silenzioso",
    "n56": "La Zampa del Destino",
    "n57": "Il Re del Cartone",
    "n58": "L'Agguato Permanente",
    "n59": "Il Meteorite Morbido",
    "n60": "La Leggenda del Cortile",
    "n61": "Il Guardiano della Ciotola",
    "n62": "L'Occhio della Notte",
    "n63": "Il Samurai Spelacchiato",
    "n64": "La Furia Tricolore",
    "n65": "Il Professore di Agguati",
    "n66": "L'Ammiraglio dei Tetti",
    "n67": "Il Rullo Compressore",
    "n68": "La Peste Elegante",
    "n69": "Il Vulcano Sonnolento",
    "n70": "L'Artiglio di Velluto",
    "n71": "Il Bandito della Cucina",
    "n72": "La Sentinella del Frigo",
    "n73": "Il Drago del Cuscino",
    "n74": "L'Eco del Miagolio",
    "n75": "Il Maestro di Fusa",
    "n76": "La Tempesta Tascabile",
    "n77": "Il Gigante Gentile",
    "n78": "L'Ultimo Randagio",
    "n79": "Il Cacciatore di Lucertole",
    "n80": "La Nona Vita"
  },
  "descrs": {
    "d01": "Dorme 20 ore al giorno e nelle altre 4 si allena a dormire meglio.",
    "d02": "Non ha mai perso una battaglia contro un calzino.",
    "d03": "Crede che il frigorifero gli debba delle spiegazioni.",
    "d04": "Maestro nell'arte di occupare esattamente il posto dove volevi sederti.",
    "d05": "Ha rovesciato tre vasi. Tutti colpevoli.",
    "d06": "Parla tre lingue: fusa, miagolio e disprezzo.",
    "d07": "Corre alle 4 del mattino per motivi che non ci è dato sapere.",
    "d08": "Un guerriero nato, purché il divano sia a meno di due metri.",
    "d09": "La sua ciotola è mezza vuota. Sempre. Anche piena.",
    "d10": "Fissa il muro perché il muro ha iniziato per primo.",
    "d11": "Ex randagio, ora dirigente d'azienda del pisolino.",
    "d12": "Fa le fusa come un trattore e graffia come un rasoio.",
    "d13": "Il veterinario lo ricorda ancora nei suoi incubi.",
    "d14": "Non insegue i topi: manda avvisi di sfratto.",
    "d15": "Sa aprire tre tipi di porte e finge di non saperlo.",
    "d16": "La scatola vale più del regalo. Sempre.",
    "d17": "Ha un dottorato in sguardi di giudizio.",
    "d18": "Combatte il crimine. Il crimine è l'aspirapolvere.",
    "d19": "Ogni sedia della casa è sua. Anche la tua.",
    "d20": "Si allena sulle tende quando nessuno guarda.",
    "d21": "Il suo passatempo preferito: buttare cose dai tavoli con eleganza.",
    "d22": "Miagola in Do minore quando la ciotola è vuota.",
    "d23": "Nessuno l'ha mai visto arrivare. Solo partire con la cena.",
    "d24": "Pesa il giusto: esattamente quanto serve per bloccarti le gambe.",
    "d25": "Le lucertole del quartiere hanno organizzato una taglia su di lui.",
    "d26": "Dorme in posizioni che sfidano la fisica e il buonsenso.",
    "d27": "Ha capito come funziona il laser. Finge di no per pietà.",
    "d28": "Un incrocio tra un cuscino e una tagliola.",
    "d29": "Sorveglia il quartiere dalla finestra come un capo di stato.",
    "d30": "Le sue fusa curano lo stress. Le sue unghie lo causano.",
    "d31": "Mangia come un lupo, dorme come un sasso, regna come un re.",
    "d32": "L'unico gatto che ha vinto una discussione con un cetriolo.",
    "d33": "Si offende se lo guardi. Si offende se non lo guardi.",
    "d34": "Ha tre nascondigli segreti. Il migliore: in mezzo al corridoio.",
    "d35": "Da piccolo cadde in una ciotola di panna. Non si è più ripreso.",
    "d36": "Insegna yoga ai gatti del vicinato. Prima lezione: ignorare tutti.",
    "d37": "Il postino ha chiesto il trasferimento.",
    "d38": "Colleziona elastici per capelli. Nessuno sa dove li nasconda.",
    "d39": "Quando c'è un temporale, protegge la casa. Da sotto il letto.",
    "d40": "Il suo sguardo ha fatto scappare due cani e un idraulico.",
    "d41": "Vive per tre cose: mangiare, dormire e giudicarti.",
    "d42": "Una volta ha visto un topo. Ne parlano ancora entrambi.",
    "d43": "Elegantissimo finché non cade dal davanzale.",
    "d44": "Ha adottato una famiglia di umani. Li sta addestrando bene.",
    "d45": "Non sale sul tavolo. Il tavolo si abbassa al suo livello.",
    "d46": "Sa esattamente quando apri il tonno. Anche dall'altro isolato.",
    "d47": "Il gomitolo era già così quando è arrivato.",
    "d48": "Metà gatto, metà sirena d'allarme delle 5 del mattino.",
    "d49": "Combatte con onore, vince con stile, dorme senza vergogna.",
    "d50": "L'ultima cosa che i tappeti vedono prima della fine."
  },
  "battle": {
    "skip": "⏭️ Presentazione saltata: dritti al sodo!",
    "open": "🎤 SIGNORE E SIGNORIIII… benvenuti all'Arena CatCards!",
    "red": "🔴 Angolo rosso: {NAME}, «{nick}»! {rec}",
    "blue": "🔵 Angolo blu: {NAME}, «{nick}»! {rec}",
    "debut": "Al suo debutto in arena!",
    "theme": "🎵 Risuona il tema d'ingresso di {name}…",
    "ding": "🔔 DING DING DING!",
    "first_fast": "⚡ {name} è più veloce e attacca per primo!",
    "first_surprise": "😼 {name} sorprende tutti e parte per primo!",
    "round_end": "🔔 Fine del round {round}! I gatti tornano agli angoli a leccarsi il pelo…",
    "charmed_skip": "😍 {name} è ammaliato e perde il turno!",
    "chant": "🎺 Dagli spalti: «{NAME}! {NAME}!»",
    "pu_yarn": "🧶 Un gomitolo rotola nell'arena! {name} ci gioca e recupera {hp} HP",
    "pu_catnip": "🌿 Erba gatta nell'arena! {name} è su di giri: prossimo colpo RADDOPPIATO (ma è un po' sballato…)",
    "pu_box": "📦 Una scatola di cartone! {name} non resiste e ci si infila: salta il turno ma è IMPRENDIBILE!",
    "pu_fish": "🐟 Un pesce fresco vola nell'arena! {name} guizza di energia: +agilità per 3 turni",
    "purr_heal": "💗 {name} fa le fusa e recupera {hp} HP",
    "double_paw": "🐾 Doppia Zampata! {name} attacca ancora!",
    "box_dodge": "📦 {opp} è rintanato nella scatola: il colpo di {name} va a vuoto!",
    "dodge": "💨 {name} tenta {move} ma {opp} schiva!",
    "final_blow": "⏱️ Il tempo rallenta… COLPO FINALE!",
    "hit": "{icon} {name} usa {move}!{crit}{catnip}  −{dmg} HP",
    "crit_tag": " 💥 CRITICO!",
    "catnip_tag": " 🌿 POTENZIATO!",
    "dev1": "😱 Colpo devastante!",
    "dev2": "🎙️ Il pubblico è in delirio!",
    "dev3": "💢 Che potenza impressionante!",
    "on_fire": "🔥 {name} è ON FIRE! Tre colpi a segno di fila!",
    "on_ropes": "🎙️ {opp} è alle corde! Il pubblico trattiene il fiato…",
    "clever": "✨ Mossa astuta! {opp} resta confuso e perderà il turno!",
    "nine_lives": "🐈 {opp} sfrutta una delle sue Nove Vite e resta in piedi con 1 HP!",
    "charm_hit": "✨ {opp} resta ammaliato dal fascino di {name}!",
    "replay": "📹 REPLAY del colpo finale…",
    "winner": "🏆 {name} vince il combattimento!",
    "win_points": "💰 +10 punti per la vittoria!",
    "boss_points": "💰 +10 punti: hai domato un Boss dell'Arena!",
    "boss_noprize": "🎖️ Boss già battuto oggi: gloria sì, premio domani.",
    "boss_survives": "🤖 Il Boss resta in piedi... il tentativo di oggi è andato: appuntamento a domani (magari con l'erba gatta 🌿).",
    "tourn_champ": "👑 {name} è il CAMPIONE del torneo!",
    "world_ok": "🌍 Risultato registrato nell'Arena Mondiale!",
    "bet_win": "🎲 Pronostico azzeccato! Avevi puntato {stake} su {name}: +{gain} punti (totale: {total})",
    "bet_lose": "🎲 Pronostico sbagliato: −{stake} punti (totale: {total}). Andrà meglio la prossima!",
    "stake": "🎁 In palio — vittoria: {win} · sconfitta: +{lose} XP",
    "stake_pts": "+{pt} punti e +{xp} XP",
    "stake_nopts": "+{xp} XP (nessun punto in locale)",
    "boss_stake_note": " — punti solo alla prima vittoria del giorno",
    "entry_catnip": "🌿 {name} entra in arena già carico di erba gatta!"
  },
  "chars": {
    "rocco_warn": "Occhio alla sua {stat}: lì ti mangia.",
    "rocco_70": "Ragazzo, questo lo stendi prima del gong. Non ti montare la testa e chiudi in fretta.",
    "rocco_55": "Sei favorito, ma i favoriti che dormono finiscono al tappeto. Colpisci per primo.",
    "rocco_50": "Cinquanta e cinquanta, ragazzo: qui decide chi ha più fame. Se hai 50 punti, l'erba gatta li vale tutti.",
    "rocco_35": "Non ti mento: è più grosso di te. Senza erba gatta io questo match non lo farei.",
    "rocco_lose": "Ascolta il vecchio Rocco: questo ti spezza. Torna in palestra, cresci un livello, POI ne riparliamo. Se proprio vuoi farlo, almeno l'erba gatta.",
    "baratto_great": "🤑 Affarone! Ricevi molto più di quel che dai — chiudi in fretta.",
    "baratto_good": "👍 Buon affare: ci guadagni. Il Mercante approva.",
    "baratto_even": "⚖️ Scambio alla pari: decidi col cuore, non col portafoglio.",
    "baratto_bad": "😾 Ci rimetti un po'... sicuro? Il Mercante storce i baffi.",
    "baratto_terrible": "🙀 Pessimo affare! Dai molto più di quel che prendi. Lascia perdere.",
    "baratto_empty": "Non hai carte da barattare! Creane qualcuna e torna: al bazar si fanno affari, non beneficenza.",
    "inc_100a": "CENTO PUNTI! Che follia magnifica! 😼",
    "inc_100b": "Offerta da re! E chi osa rilanciare ora?",
    "inc_50a": "Cinquanta! Il pubblico freme, signori!",
    "inc_50b": "Bella cifra! L'asta si scalda!",
    "inc_bata": "E rilancia ancora! Non si fermano più!",
    "inc_batb": "Battaglia all'ultimo punto, che spettacolo!",
    "inc_starta": "Prima offerta sul banco! Chi dà di più?",
    "inc_startb": "Si parte! Aggiudicato a chi non molla!",
    "baffo_open": [
      "Miao, recluta! ",
      "Ascolta il vecchio Baffo: ",
      "Sputa il croccantino e ascolta: ",
      "Ai miei tempi niente cuscini morbidi. ",
      "Baffi dritti e orecchie tese: "
    ],
    "baffo_empty": "La palestra è vuota! Portami un allievo dalla scheda 📸 Crea.",
    "baffo_indiff_afford": "Il punto debole di {name} è {stat} ({val}): allenala col combo {combo} (60 punti), puoi permettertelo.",
    "baffo_indiff_save": "Il punto debole di {name} è {stat} ({val}), ma si allena solo col combo {combo} (60 punti): ti mancano {miss} punti, mettili da parte.",
    "baffo_indiff_alt": " Oppure intanto rinforza {stat2} ({val2}) con {food} (25 punti).",
    "baffo_weak": "Il punto più debole di {name} è {stat} ({val}): dagli {food}.",
    "baffo_combo": "Hai {pts} punti: il combo {combo} ({tgt}) cresce due cose in un solo riposo — caro ma conveniente se vai di fretta.",
    "baffo_record_bad": "Con {w} vittorie e {l} sconfitte serve grinta, non coccole.",
    "baffo_unbeaten": "È imbattuto: attento che non si monti la testa.",
    "baffo_margin": "Margine di allenamento finito: solo le vittorie nel mondo sbloccano nuovi progressi.",
    "baffo_broke": "E le casse piangono ({pts} punti): vinci qualche scommessa mondiale.",
    "baffo_fit": "{name} è in forma smagliante. Fallo combattere, che la panchina infiacchisce i muscoli.",
    "felini_open": [
      "Ascolta il Manager: ",
      "Ho fiutato l’affare: ",
      "Il ring è una scacchiera: ",
      "Parlano i numeri, ragazzo: "
    ],
    "felini_checking": "Un attimo, consulto i registri…",
    "felini_noauth": "Prima accedi, ragazzo: gli affari si fanno con un nome sul contratto.",
    "felini_nocard": "Non hai un campione pubblicato. Pubblica una carta e parliamo d’affari.",
    "felini_resting": "😴 {name} sta recuperando: torna quando è di nuovo pronto e parliamo di strategia.",
    "felini_norank": "Il tuo campione non risulta nel ranking: ripubblicalo e torna da me.",
    "felini_loss_streak": "{name} ha perso {n} di fila (🧊): toglilo dal giro per un po’, portalo da il Coach, e fallo tornare affamato.",
    "felini_champ": "{name} è il CAMPIONE 👑: difendi la corona{chaser}.",
    "felini_chaser": ", e occhio a {name} (#2, {elo} pt) che scalpita",
    "felini_target": "il prossimo incontro giusto per {name} (#{rk}) è {tname} di {owner} (#{trk}, {elo} pt): {verdict}",
    "felini_v_risky": "rischioso, ma se lo batti fai il botto in classifica.",
    "felini_v_beatable": "sulla carta è battibile: vittoria di gestione.",
    "felini_v_even": "incontro alla pari, di quelli che piacciono al pubblico.",
    "felini_prob_low": "Ma parliamoci chiaro: Zio Rocco stima solo il {p}% di vittoria. Io aspetterei — palestra, un livello in più, POI si firma il contratto.",
    "felini_prob_mid": "Le probabilità dicono {p}%: match aperto, decidono i nervi (e magari l’erba gatta 🌿).",
    "felini_prob_high": "Zio Rocco stima un {p}% di vittoria: alla portata. Vai e chiudi il match.",
    "felini_belt": "E ricordatelo: quello ha la CINTURA 👑 — la classifica non conta niente, lo batti e sei TU il campione.",
    "felini_hot": "Occhio però: è un avversario tosto, arriva da una striscia di {n} vittorie 🔥.",
    "felini_cold": "E ti dirò: è in crisi nera (🧊 {n} sconfitte di fila) — il momento perfetto per colpirlo.",
    "felini_catnip_need": "Il mio consiglio da bordo ring: investi 50 punti nell’erba gatta 🌿 prima del match — contro uno così serve il turbo.",
    "felini_catnip_broke": "Servirebbe l’erba gatta 🌿, ma le casse piangono ({pts} punti): o trovi punti, o scegli un bersaglio più morbido.",
    "felini_catnip_opt": "Erba gatta 🌿? Facoltativa: incontro alla pari, decideranno i nervi.",
    "felini_catnip_no": "Niente erba gatta: ce la fa con le sue zampe, risparmia i punti.",
    "felini_notarget": "nessun bersaglio di altri proprietari sopra di te ora (o riposano tutti): difendi la posizione, o ripassa più tardi.",
    "felini_margin": "E ha ancora {n} punti di margine in palestra: un buon pasto prima del match non ha mai ucciso nessuno.",
    "trader_open": [
      "Psst, amico: ",
      "Affari, affari! ",
      "Il Mercante sa tutto: ",
      "Tra noi che ce ne intendiamo: "
    ],
    "trader_best": "tieniti stretto {name}, quello vale oro: non cederlo per due spiccioli.",
    "trader_worst": "se proprio devi dare qualcosa, parti da {name} — ne hai di meglio in mano.",
    "trader_commons": "Hai un mucchio di {rar} ({n}): scambiane un paio per qualcosa di più raro, fidati.",
    "trader_gem": "E occhio: c’è una {rar} di {owner} in vetrina — se hai un buon doppione, tenta lo scambio prima che la prenda un altro.",
    "trader_browse": "Premi «Sfoglia carte da scambiare» e fammi vedere cosa gira: ti dico io se c’è un affare.",
    "rocco_catnip": "🌿 Bravo ragazzo. Ora entra lì e fatti valere: il primo colpo sarà un treno.",
    "baffo_all_rest": "😴 Tutti i tuoi allievi stanno riposando: torna quando qualcuno è pronto e ci mettiamo al lavoro."
  },
  "titles": {
    "world": "SFIDA MONDIALE",
    "live": "SFIDA DAL VIVO",
    "boss": "BOSS DELL'ARENA",
    "quarti": "QUARTI DI FINALE",
    "semi": "SEMIFINALE",
    "finale": "FINALE",
    "sentiero": "SENTIERO"
  },
  "gym": {
    "lbl_allena": "Allena:",
    "lbl_start": "▶️ Inizia l'allenamento!",
    "fn_croc": "Croccantini",
    "fn_pollo": "Pollo",
    "fn_topo": "Topolino",
    "fn_erba": "Erba gatta",
    "fn_pesce": "Pesce",
    "fn_chicche": "Chicche",
    "fn_bistecca": "Bistecca del Guerriero",
    "fn_scarica": "Scarica Felina",
    "fn_fascino": "Fascino Fatale",
    "fn_trono": "Trono di Piume",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Forza",
    "ft_topo": "🧠 Intelligenza",
    "ft_erba": "🎯 Destrezza",
    "ft_pesce": "⚡ Velocità",
    "ft_chicche": "✨ Fascino",
    "ft_bistecca": "💪 Forza + ❤️ HP",
    "ft_scarica": "⚡ Velocità + 🎯 Destrezza",
    "ft_fascino": "✨ Fascino + 🧠 Intelligenza",
    "ft_trono": "😼 Indifferenza + ❤️ HP",
    "gn_gomitolo": "Acchiappa il gomitolo",
    "gn_topo": "Caccia al topo",
    "gn_piuma": "Segui la piuma",
    "gn_corda": "Tiro alla corda",
    "gn_porta": "Sfonda la porta",
    "gn_laser": "Caccia al laser",
    "gn_memory": "Memory delle scatolette",
    "gn_pesca": "Pesca al volo",
    "gn_scatto": "Scatto felino",
    "gn_scalata": "Scalata della libreria",
    "gn_fusa": "Ritmo delle fusa",
    "gn_sfilata": "La Sfilata",
    "gn_zen": "Zen del gatto",
    "gn_sguardi": "Gara di sguardi",
    "ga_gomitolo": "Agilità — 🌿 erba gatta (Destrezza) e 🐟 pesce (Velocità)",
    "ga_topo": "Fisico — 🍗 pollo (Forza) e 🥫 croccantini (HP)",
    "ga_piuma": "Mente — 🐁 topolino (Intelligenza) e 🧀 chicche (Fascino)",
    "ga_corda": "Forza — 🍗 pollo (Forza)",
    "ga_porta": "Forza — 🍗 pollo (Forza)",
    "ga_laser": "Destrezza — 🌿 erba gatta (Destrezza)",
    "ga_memory": "Intelligenza — 🐁 topolino (Intelligenza)",
    "ga_pesca": "Velocità — 🐟 pesce (Velocità)",
    "ga_scatto": "Velocità — 🐟 pesce (Velocità)",
    "ga_scalata": "HP — 🥫 croccantini (HP)",
    "ga_fusa": "Fascino — 🧀 chicche (Fascino)",
    "ga_sfilata": "Fascino — 🧀 chicche (Fascino)",
    "ga_zen": "Indifferenza — 🛋️ cuscino reale (Indifferenza)",
    "ga_sguardi": "Indifferenza — 🛋️ cuscino reale (Indifferenza)",
    "gd_gomitolo": "Il gomitolo schizza per il riquadro e accelera a ogni presa: toccalo più volte che puoi in <strong>10 secondi</strong>.<br>🚫 Meno di 5 prese: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_topo": "I topi sbucano dalle tane e spariscono subito: colpiscili appena appaiono, per <strong>15 secondi</strong>.<br>🚫 Meno di 5 colpi: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_piuma": "Le piume colorate lampeggiano in sequenza: ripetila toccandole nello stesso ordine. Ogni round la sequenza si allunga; un errore chiude l'allenamento.<br>🚫 Meno di 3 round: cibo sprecato · ✅ 3-4: bonus ×1 · 🌟 5+: bonus ×2",
    "gd_corda": "Martella il pulsante <strong>TIRA</strong> per trascinare il cagnone oltre la linea: lui tira indietro di continuo, non mollare per <strong>10 secondi</strong>.<br>🚫 Meno di 8 strappi: cibo sprecato · ✅ 8-15: bonus ×1 · 🌟 16+: bonus ×2",
    "gd_porta": "La barra di potenza sfreccia avanti e indietro: tocca quando è nella <strong>zona verde</strong> per caricare la zampata. Colpisci più forte che puoi in <strong>12 secondi</strong>.<br>🚫 Meno di 5 colpi buoni: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_laser": "Il puntino rosso appare e sparisce sempre più in fretta: toccalo prima che svanisca, per <strong>12 secondi</strong>.<br>🚫 Meno di 6 prese: cibo sprecato · ✅ 6-11: bonus ×1 · 🌟 12+: bonus ×2",
    "gd_memory": "Scopri le carte a due a due e abbina le coppie uguali a memoria, in <strong>30 secondi</strong>.<br>🚫 Meno di 3 coppie: cibo sprecato · ✅ 3-4: bonus ×1 · 🌟 5+: bonus ×2",
    "gd_pesca": "Il pesce guizza sott'acqua e affiora solo per un istante: toccalo <strong>proprio quando salta fuori</strong>. Le finestre si accorciano. Hai <strong>14 secondi</strong>.<br>🚫 Meno di 5 prese: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_scatto": "Aspetta il <strong>verde</strong> e tocca il più in fretta possibile: si misura il tuo riflesso. 5 round — chi parte in anticipo perde il round.<br>🚫 Meno di 2 scatti buoni: cibo sprecato · ✅ 2-3: bonus ×1 · 🌟 4+: bonus ×2",
    "gd_scalata": "Il gatto salta di mensola in mensola: tocca <strong>quando la piattaforma è allineata</strong> per saltarci sopra. Un salto sbagliato e cadi. Sali più in alto che puoi.<br>🚫 Meno di 5 mensole: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_fusa": "Il cerchio si stringe a tempo: tocca <strong>quando arriva sul bersaglio</strong>, a ritmo di fusa. Più sei preciso, più il ritmo accelera.<br>🚫 Meno di 5 colpi a tempo: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_sfilata": "In passerella appare una freccia: <strong>scorri (swipe) nella sua direzione</strong> per fare la posa. Le frecce arrivano sempre più in fretta, hai <strong>16 secondi</strong>.<br>🚫 Meno di 6 pose: cibo sprecato · 🌟 12+: bonus ×2",
    "gd_zen": "La disciplina dell'indifferenza: <strong>ignora ogni distrazione</strong> (🐭 topo, 🪶 piuma, 🔴 laser) e tocca <strong>solo il cuscino 🛋️</strong> quando appare. Toccare una distrazione ti fa perdere il round. Hai <strong>14 secondi</strong>.<br>🚫 Meno di 5 cuscini: cibo sprecato · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_sguardi": "<strong>Tieni premuto</strong> e non muoverti: chi resta impassibile vince. Ma se appare un 😹 solletico devi <strong>lasciare subito</strong>, poi ripremere. Resisti più a lungo che puoi.<br>🚫 Meno di 8 secondi di impassibilità: cibo sprecato · ✅ 8-13: bonus ×1 · 🌟 14+: bonus ×2",
    "tr_wasted_h": "🙀 Cibo sprecato!",
    "tr_wasted_b": "Punteggio: <strong>{score}</strong> — sotto la soglia minima.<br><br>{ic} Il {food} è andato perso e {name} ora riposa per un'ora.<br><br>😼 <em>«Ai miei tempi ci si allenava pure bendati.»</em>",
    "tr_coach_wasted": "🙀 Solo {score} punti?! Cibo sprecato.",
    "tr_perfect_h": "🌟 Allenamento perfetto!",
    "tr_ok_h": "✅ Allenamento riuscito!",
    "tr_bonus2": " — bonus raddoppiato!",
    "tr_online": "🌍 Carta aggiornata anche nell'Arena Mondiale.<br>",
    "tr_body": "Punteggio: <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> per {name}</span><br><br>{online}😴 Ora un'ora di riposo: i muscoli crescono dormendo.",
    "tr_coach_perfect": "😼 {score} punti! {name} ha la stoffa del campione.",
    "tr_coach_ok": "👍 {score} punti, onesto lavoro. {name} cresce.",
    "gi_none": "Nessun allievo: crea prima una carta.",
    "gi_info": "Lv.{lv} · margine di allenamento: <strong>{used}/{cap}</strong> usato <span style=\"color:var(--muted)\">(+3 per ogni livello: si sale vincendo nel mondo)</span>",
    "gi_resting": "<br>😴 Sta riposando: torna tra {min} minuti",
    "gi_ready": "<br>✅ Pronto ad allenarsi!",
    "gi_nofood": "😼 Coach Baffo: «Niente cibo per {name}: margine di allenamento esaurito. Vinci incontri per salire di livello (+3 di margine a livello), poi si torna a tavola.»",
    "gi_pick_opt": "— scegli un allievo —",
    "gi_pick": "👉 Scegli un allievo qui sopra per iniziare.",
    "gi_pick_alert": "Scegli prima un allievo dal menu qui sopra."
  },
  "powers": {
    "pn_0": "Nove Vite",
    "pn_1": "Agguato Perfetto",
    "pn_2": "Fusa Rigeneranti",
    "pn_3": "Doppia Zampata",
    "pn_4": "Modalità Liquido",
    "pn_5": "Sguardo Ipnotico",
    "pn_6": "Armatura di Pigrizia",
    "pn_7": "Caos Felino",
    "pd_0": "la prima volta che va KO resta a 1 HP",
    "pd_1": "il suo primo attacco è sempre critico",
    "pd_2": "recupera HP a ogni suo turno",
    "pd_3": "25% di probabilità di attaccare due volte",
    "pd_4": "schiva molto più spesso",
    "pd_5": "ammalia con il doppio della probabilità",
    "pd_6": "subisce il 20% di danni in meno",
    "pd_7": "i suoi danni sono imprevedibili (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Vinci 1 sfida mondiale",
    "m_world2": "Vinci 2 sfide mondiali",
    "m_fight3": "Combatti 3 incontri (vanno bene anche locali)",
    "m_tourn": "Vinci un torneo (a 4 o a 8)",
    "m_upset": "L'Impresa: batti nel mondo un avversario con più Elo del tuo",
    "m_train1": "Completa un allenamento riuscito",
    "m_gom10": "Fai 10+ ad Acchiappa il gomitolo",
    "m_topo10": "Fai 10+ alla Caccia al topo",
    "m_piuma5": "Arriva a 5 round con Segui la piuma",
    "m_boss": "Doma un Boss dell'Arena",
    "m_bet": "Vinci una scommessa",
    "m_catnip": "Vinci un incontro partendo con l'erba gatta",
    "m_card": "Crea una carta nuova",
    "m_qr": "Gioca una sfida dal vivo (QR)",
    "a_prima_carta_nm": "Prima carta",
    "a_prima_carta_ds": "Crea la tua prima carta",
    "a_coll5_nm": "Collezionista",
    "a_coll5_ds": "5 carte in collezione",
    "a_coll10_nm": "Gattaro seriale",
    "a_coll10_ds": "10 carte in collezione",
    "a_epica_nm": "Che rarità!",
    "a_epica_ds": "Ottieni una carta Epica",
    "a_legg_nm": "Leggendaria!",
    "a_legg_ds": "Ottieni una Leggendaria",
    "a_win1_nm": "Prima vittoria",
    "a_win1_ds": "Vinci una sfida mondiale",
    "a_win10_nm": "Veterano",
    "a_win10_ds": "Vinci 10 sfide mondiali",
    "a_win50_nm": "Leggenda",
    "a_win50_ds": "Vinci 50 sfide mondiali",
    "a_t4_nm": "Campione",
    "a_t4_ds": "Vinci un torneo a 4",
    "a_t8_nm": "Dominatore",
    "a_t8_ds": "Vinci un torneo a 8",
    "a_pub_nm": "Nel mondo",
    "a_pub_ds": "Pubblica una carta",
    "a_wwin_nm": "Tripletta",
    "a_wwin_ds": "Vinci 3 sfide mondiali di fila",
    "a_bet_nm": "Bookmaker",
    "a_bet_ds": "Vinci una scommessa",
    "a_ricco_nm": "Riccone",
    "a_ricco_ds": "Possiedi 150 punti",
    "a_onore_nm": "Ritiro con onore",
    "a_onore_ds": "Ritira una carta con record positivo",
    "a_disfatta_nm": "Disfatta",
    "a_disfatta_ds": "Perdi 10 sfide mondiali di fila",
    "bm_ds": "Sconfiggi {name} (Div. {tier})",
    "bmall_nm": "Ammazzaboss",
    "bmall_ds": "Sconfiggi tutti e 64 i Boss dell'Arena",
    "cx_rar4": "Il poker: una carta per ogni rarità",
    "cx_razze3": "Scopri 3 razze diverse",
    "cx_razze5": "Scopri 5 razze diverse",
    "cx_razze10": "Scopri 10 razze diverse",
    "cx_pot4": "Colleziona 4 poteri speciali diversi",
    "cx_pot8": "Colleziona tutti gli 8 poteri speciali",
    "cx_lv5": "Porta un gatto al livello 5",
    "cx_hp100": "Una carta con 100+ HP",
    "cx_oro": "Una carta con la Cornice d'Oro",
    "p_done": "fatto",
    "p_won": "✓ conquistata",
    "p_towin": "🔒 da conquistare",
    "p_howto": "Come si ottiene:",
    "p_reward": "Premio:",
    "p_unlocked": "Sbloccata il",
    "cx_open": "(tocca per aprire)",
    "cx_h_rar": "💎 Rarità",
    "cx_h_pow": "🌟 Poteri speciali",
    "cx_h_breeds": "🐱 Razze scoperte",
    "cx_nobreeds": "Ancora nessuna: la razza arriva con l'analisi AI della foto.",
    "cx_h_objs": "🎯 Obiettivi",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> obiettivi <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex: {ic} {txt}! +{pt} punti",
    "mis_tris_line": "🎉 Tris completato: +10 punti bonus incassati. A domani!",
    "mis_toast_tris": "🎉 TRIS! Missione «{txt}» e giornata completa: +5 e +10 bonus!",
    "mis_toast_done": "📅 Missione completata: {ic} {txt}! +5 punti",
    "med_toast": "🏅 Medaglia sbloccata: {ic} {nm}! +{pt} punti",
    "bm_sum": "🤖 Boss domati — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>",
    "a_sentiero_done_nm": "Viandante delle Nove Vite",
    "a_sentiero_done_ds": "Completa tutto il Sentiero (100 tappe)"
  },
  "reg": {
    "r_h_cards": "🎴 Le carte",
    "r_p_cards": "Fotografa un gatto e diventa una carta: l'AI lo ridisegna in cartoon e ne analizza aspetto e carattere per generare <strong>statistiche</strong> (un gattone robusto avrà più Forza), <strong>razza</strong>, <strong>descrizione</strong>, <strong>potere speciale</strong> e <strong>3 mosse</strong> (💥 potente ma imprecisa, ⚡ rapida e quasi infallibile, ✨ astuta che può confondere). La <strong>rarità</strong> è sorteggiata dall'impronta della foto: 55% Comune, 28% Rara, 13% Epica, 4% Leggendaria (Epiche e Leggendarie brillano e hanno statistiche col bonus). La stessa foto dà sempre la stessa carta.",
    "r_h_xp": "⭐ Esperienza e livelli",
    "r_p_xp": "Le carte crescono combattendo: <strong>sfide mondiali e dal vivo: 25 XP a vittoria, 10 a sconfitta</strong> · <strong>arena locale e tornei: 5 e 2</strong>. Ogni 100 XP: +1 livello = <strong>+4 HP, +3% attacco e +3 di margine palestra</strong>. Gli specchi (carta contro sé stessa) non contano.",
    "r_h_pts": "💰 I punti (la moneta)",
    "r_p_pts": "Si guadagnano con: <strong>+10 per ogni vittoria mondiale o dal vivo</strong>, +10 per ogni Boss domato, 📅 missioni giornaliere (5 l'una, +10 il tris: max 25 al giorno), scommesse vinte, medaglie (10-100 punti l'una) e 🎁 codici regalo. Le vittorie locali: zero punti. Si <strong>spendono</strong> in: scommesse (puntata 10-100), cibo in palestra (20-25), 🌿 vantaggio mondiale (50), 🎨 Cornice d'Oro (100), 🔁 rigenerazione del disegno (30). Perdere un incontro non costa punti: solo le scommesse sbagliate.",
    "r_h_bet": "🎲 Le scommesse",
    "r_p_bet": "Nelle <strong>sfide mondiali e dal vivo</strong>: prima del match scegli la puntata e su chi puntare (⭐ favorito a quota bassa, 🐾 underdog a quota alta). Vinci la puntata × (quota − 1); se sbagli perdi la puntata. Niente scommesse in locale e nei tornei.",
    "r_h_rest": "😴 Il riposo",
    "r_p_rest": "Dopo ogni incontro vero (locale 1v1, mondiale, dal vivo) e ogni allenamento, i gatti coinvolti riposano <strong>1 ora</strong>: non possono combattere né mangiare. Il riposo è visibile a tutti, anche online. I tornei sono esibizioni e non stancano.",
    "r_h_gym": "🏋️ La palestra",
    "r_p_gym": "Ogni livello sblocca <strong>+3 punti di margine allenamento</strong>. Compri un alimento (🥫 HP · 🍗 Forza · 🐁 Intelligenza · 🌿 Destrezza · 🐟 Velocità · 🧀 Fascino) e il gatto se lo guadagna con l'esercizio abbinato: 🧶 gomitolo (agilità), 🐭 caccia al topo (fisico), 🪶 segui la piuma (mente). Soglie: <strong>sotto 5 punti cibo sprecato, 5-9 bonus ×1, 10+ bonus ×2</strong> (per la piuma: 3 e 5 round). Le carte pubblicate si aggiornano online da sole. Coach Baffo dà consigli gratis.",
    "r_h_world": "🌍 L'Arena Mondiale",
    "r_p_world": "Accedi con Google (o email), scegli il nome giocatore (uno per account, rinominabile ovunque in un colpo) e <strong>pubblica le carte che vuoi</strong>: solo le pubblicate e attive possono sfidare online. Sfidi le carte degli altri, il risultato finisce nel registro e in classifica (ordinata per % di vittorie). Puoi <strong>🚪 ritirare</strong> una carta: resta in classifica come \"ritirata\" ma nessuno può più sfidarla. Il pallino rosso su Mondo ti avvisa quando le tue carte hanno combattuto in tua assenza.",
    "r_h_rank": "📊 Il ranking (stile UFC)",
    "r_p_rank1": "Ogni carta pubblicata ha un punteggio <strong>Elo</strong>, che parte da <strong>1000</strong>. A ogni incontro il vincitore <strong>prende</strong> punti e lo sconfitto <strong>cede gli stessi punti</strong> — e la quantità dipende dalla differenza di forza: battere un avversario <strong>più forte</strong> vale fino a <strong>~32 punti</strong>, battere uno molto più debole ne vale il minimo, <strong>8</strong> (vincere facile rende poco, l'impresa rende tanto). Nessuna carta scende mai sotto quota 100. Il calcolo lo fa il server, uguale per tutti.",
    "r_p_rank2": "La classifica ufficiale è in ordine di Elo, ma la cintura è un'altra cosa: <strong>campione si diventa SOLO battendo il campione in carica 👑</strong> in una sfida mondiale o dal vivo. Puoi superarlo di punti quanto vuoi: resti primo contendente finché non lo stendi sul ring. Il campione sta sempre in cima al ranking, e chi è stato campione conserva per sempre il 🏆. Puoi sfidare solo chi sta <strong>da 5 posizioni sopra a 5 sotto</strong> la tua: per il titolo bisogna scalare (in top 5 il campione è a tiro). Il ranking mostra le strisce — 🔥 vittorie di fila, 🧊 sconfitte di fila, e la miglior striscia di sempre. Il <strong>🎩 Manager</strong> studia i numeri e ti consiglia il prossimo incontro giusto, se conviene l'erba gatta 🌿, e quando è meglio ritirarsi un po' in palestra.",
    "r_h_cat": "🃏 Il Catdex",
    "r_p_cat": "L'album della collezione, in fondo alla scheda 📚 Carte: tiene il conto di <strong>rarità, razze e poteri speciali</strong> che hai scoperto (le caselle mancanti restano ❓) e premia i traguardi con punti <strong>una tantum</strong> — dal poker di rarità (+25) alle 10 razze diverse (+25) fino a tutti gli 8 poteri (+30). La razza la scrive l'AI quando crei la carta: nomi simili (es. \"soriano\" e \"europeo soriano\") contano come una famiglia sola. Per completarlo serve una cosa soltanto: fotografare gatti nuovi.",
    "r_h_mis": "📅 Le missioni giornaliere",
    "r_p_mis": "Ogni mezzanotte arrivano <strong>3 missioni</strong>, uguali per tutto il mondo: una di combattimento, una di palestra, una a sorpresa (boss, scommesse, QR…). Ognuna paga <strong>5 punti</strong>, il tris completo altri <strong>10 di bonus</strong>. Le trovi in cima al 🏅 Medagliere, con la spunta ✅ su quelle già fatte. Massimo 25 punti al giorno: quanto basta per un allenamento, o poco più.",
    "r_h_boss": "🤖 I Boss dell'Arena",
    "r_p_boss": "<strong>64 leggende in 8 divisioni</strong> a difficoltà crescente: dai Randagi di Quartiere (facili) fino ai Boss Finali come il 🌑 Gatto Mammone o 🤖 MIAO-9000, mostruosi. Ogni giorno ne sono attive <strong>2, uguali per tutto il mondo</strong> (le decide la data). Batterne uno paga <strong>+10 punti e 25 XP</strong>. Attenzione: hai <strong>UN solo tentativo al giorno per boss</strong> — vinto, perso o abbandonato, si torna domani. Scegli bene il gatto prima di scendere in arena. Perdere costa solo 2 XP di consolazione. Dopo il match il gatto <strong>riposa un'ora</strong> come in ogni incontro vero, e l'erba gatta 🌿 comprata prima vale anche qui. Contro i Boss scendono in campo <strong>solo le carte pubblicate nel Mondo</strong>, e i boss <strong>non toccano il ranking Elo</strong>. Ogni boss ha la sua medaglia (sezione «🤖 Boss domati» nel 🏅 Medagliere, premi più ricchi per le divisioni alte), più la 🏆 Ammazzaboss per chi li doma tutti e 64.",
    "r_h_qr": "⚡ La sfida dal vivo (QR)",
    "r_p_qr": "Due telefoni: uno mostra il QR della sua carta (🥋 Dojo → 📱), l'altro lo inquadra (📷) e il duello si gioca sul suo schermo. <strong>Vale come una sfida mondiale</strong>: punti, XP pieni, medaglie, riposo, scommesse e risultato registrato se le carte sono pubblicate.",
    "r_h_tourn": "🏆 Tornei e medagliere",
    "r_p_tourn": "Tornei a 4 o 8 tra le tue carte e i rivali: esibizioni automatiche con tabellone (XP ridotti, nessun riposo, nessun punto). Il <strong>🏅 Medagliere</strong> ha 25 medaglie con premi in punti (9 sono dei Boss) — tocca una medaglia per scoprire come si conquista. Occhio alla 💀 Disfatta…",
    "r_h_fight": "⚔️ Il combattimento",
    "r_p_fight": "Automatico a turni: Velocità decide chi parte (di solito), Forza il danno, Destrezza le schivate, Intelligenza i critici (×1.6), Fascino ammalia, Indifferenza riduce i danni. Nessun colpo toglie più del 38% degli HP. Poteri speciali, power-up casuali (🧶🌿📦🐟), colpo finale al rallentatore e replay. La presentazione si può saltare (⏭️ o da Opzioni).",
    "mgr_greet": "Il ring è una scacchiera, ragazzo. Scegli il campione e ti dico la prossima mossa.",
    "mis_desc": "Tre incarichi nuovi ogni mezzanotte, uguali per tutto il mondo: <strong>5 punti</strong> l'uno, <strong>+10 di bonus</strong> se completi il tris.",
    "med_desc": "Le medaglie premiano con punti: spendili in scommesse, vantaggio mondiale, Cornice d'Oro, rigenerazioni e nella dispensa della Palestra.",
    "boss_intro": "64 leggende in 8 divisioni: ogni giorno ne compaiono 2, uguali per tutto il mondo. Batterle paga <strong>+10 punti</strong>, XP pieni e una medaglia dedicata. <strong>Un solo tentativo al giorno per boss</strong>, vinto o perso; i boss non toccano il ranking Elo. Combattono solo le carte <strong>pubblicate nel Mondo</strong>."
  },
  "boss": {
    "div_1": "Randagi di Quartiere",
    "div_2": "Domestici Ribelli",
    "div_3": "Nobili e Aristogatti",
    "div_4": "Bestie Selvatiche",
    "div_5": "Miti e Leggende",
    "div_6": "Spettri e Soprannaturale",
    "div_7": "Divinità Feline",
    "div_8": "Boss Finali",
    "di_1": "Dai vicoli del quartiere",
    "di_2": "Dai salotti in subbuglio",
    "di_3": "Dai saloni della nobiltà",
    "di_4": "Dalle terre selvagge",
    "di_5": "Dalle antiche leggende",
    "di_6": "Dall'aldilà felino",
    "di_7": "Dai troni celesti",
    "di_8": "Dalla fine di ogni cosa",
    "bu_already_beaten": "✅ già domato",
    "bu_beaten_today": "🎖️ Domato oggi: premio ritirato.",
    "bu_failed_today": "💥 Tentativo di oggi fallito.",
    "bu_one_try": "Un solo tentativo al giorno per boss: torna domani.",
    "bu_btn_beaten": "✅ Battuto oggi",
    "bu_btn_tomorrow": "⏳ Torna domani",
    "bu_btn_fight": "⚔️ Sfida {name}",
    "bu_bestiary_sum": "📖 Bestiario — <strong>{done}/{tot}</strong> domati <span class=\"count\">{open}</span>",
    "bu_stats_unknown": "Statistiche ignote: affronta {name} per svelarle.",
    "bu_beaten_tag": "✅ domato",
    "bu_never_tag": "🔒 mai affrontato",
    "bu_mystery_desc": "Un boss della divisione «{div}» ancora avvolto nel mistero. Compare a rotazione: battilo per aggiungerlo al Bestiario.",
    "bu_close": "✖ Chiudi",
    "bu_already_today": "⏳ Hai già sfidato {name} oggi: un solo tentativo al giorno per boss, vinto o perso. Torna domani!",
    "bu_only_world": "Contro i Boss combattono solo le carte pubblicate nel Mondo: pubblicane una dalla scheda 🌍.",
    "bu_resting": "😴 {name} sta riposando: torna tra {min} minuti.",
    "bu_pub_first": "— pubblica prima una carta nel Mondo —",
    "bn_latta": "Il Micio di Latta",
    "bk_latta": "La Scatoletta Vivente",
    "bl_latta": "Convinto di essere una scatoletta. Duro fuori, tonno dentro.",
    "bn_b02": "Baffo Mozzo",
    "bk_b02": "Il Ladro del Mercato",
    "bl_b02": "Ruba al mercato e sparisce prima che tu dica «miao».",
    "bn_b03": "Zampasporca",
    "bk_b03": "Il Signore dei Bidoni",
    "bl_b03": "Regna sui bidoni del quartiere, immune a ogni disgusto.",
    "bn_b04": "La Palla di Pelo",
    "bk_b04": "Il Rullo Compressore",
    "bl_b04": "Rotola addosso e non si ferma. Semplice, ma efficace.",
    "bn_b05": "Trippa Molle",
    "bk_b05": "Il Pigrone",
    "bl_b05": "Troppo pigro per schivare, troppo grasso per cadere.",
    "bn_b06": "Fiuto",
    "bk_b06": "Il Segugio Felino",
    "bl_b06": "Segue l'odore del cibo in capo al mondo.",
    "bn_b07": "Mezza Coda",
    "bk_b07": "Il Furioso",
    "bl_b07": "Perse metà coda, guadagnò il doppio della rabbia.",
    "bn_b08": "Il Gatto del Fornaio",
    "bk_b08": "Il Forno Vivente",
    "bl_b08": "Profuma di pane, morde di brace.",
    "bn_b09": "Divano Distrutto",
    "bk_b09": "L'Artiglio del Cuoio",
    "bl_b09": "Le sue unghie tagliano il cuoio come burro.",
    "bn_b10": "Il Re del Frigo",
    "bk_b10": "Sua Maestà Affamata",
    "bl_b10": "Apre gli sportelli con la sola forza della fame.",
    "bn_b11": "Micetta Viziata",
    "bk_b11": "L'Angelo con gli Artigli",
    "bl_b11": "Fiocco rosa, artigli d'acciaio.",
    "bn_b12": "Palla di Lana",
    "bk_b12": "La Trappola Soffice",
    "bl_b12": "Sembra tenero. È una trappola.",
    "bn_b13": "Sveglia delle 4",
    "bk_b13": "L'Incubo Notturno",
    "bl_b13": "Ti attacca quando meno te l'aspetti: le 4 del mattino.",
    "bn_b14": "Il Gatto della Tastiera",
    "bk_b14": "Il Sabotatore",
    "bl_b14": "Cammina sui nervi. E sui tasti.",
    "bn_b15": "Tenda Strappata",
    "bk_b15": "Lo Scalatore",
    "bl_b15": "Si arrampica dove non dovrebbe. Sempre.",
    "bn_b16": "Vaso Rotto",
    "bk_b16": "L'Innocente Distruttore",
    "bl_b16": "Lascia distruzione e uno sguardo angelico.",
    "bn_barone": "Il Barone von Baffen",
    "bk_barone": "L'Artiglio Aristocratico",
    "bl_barone": "Duella secondo l'antico galateo: prima l'inchino, poi la doppia zampata.",
    "bn_b18": "Contessa Vellutata",
    "bk_b18": "Lo Sguardo che Stordisce",
    "bl_b18": "Una pelliccia così morbida da stordire l'avversario.",
    "bn_b19": "Sir Graffio III",
    "bk_b19": "Il Duellante",
    "bl_b19": "Spadaccino leggendario, mai perso un duello all'alba.",
    "bn_b20": "Madame Persia",
    "bk_b20": "La Regina del Cuscino",
    "bl_b20": "Regna dal cuscino di seta e non si alza per nessuno.",
    "bn_b21": "Il Duca Certosino",
    "bk_b21": "L'Acciaio Grigio",
    "bl_b21": "Grigio come l'acciaio, freddo come il ferro.",
    "bn_b22": "Lady Siam",
    "bk_b22": "Il Colpo di Ghiaccio",
    "bl_b22": "Occhi di zaffiro, colpo che gela il sangue.",
    "bn_b23": "Don Gattone",
    "bk_b23": "Il Padrino",
    "bl_b23": "Il padrino del vicolo: offerte che non puoi rifiutare.",
    "bn_b24": "Il Maggiordomo Smoking",
    "bk_b24": "L'Ombra Elegante",
    "bl_b24": "Bianco e nero, impeccabile e letale.",
    "bn_sfinge": "La Sfinge di Cortile",
    "bk_sfinge": "L'Enigma Peloso",
    "bl_sfinge": "Ti fissa finché non confessi. Parla solo per indovinelli.",
    "bn_b26": "Zanna di Lince",
    "bk_b26": "L'Agguato",
    "bl_b26": "Non lo senti arrivare. Lo senti solo dopo.",
    "bn_b27": "Il Gatto Selvatico",
    "bk_b27": "L'Indomito",
    "bl_b27": "Non è mai stato addomesticato. Mai lo sarà.",
    "bn_b28": "Ombra della Giungla",
    "bk_b28": "Il Silenzio Nero",
    "bl_b28": "Nero come la notte, silenzioso come la morte.",
    "bn_b29": "Ruggito",
    "bk_b29": "La Grande Voce",
    "bl_b29": "Piccolo di taglia, enorme di voce.",
    "bn_b30": "Artiglio delle Nevi",
    "bk_b30": "Il Colpo Gelido",
    "bl_b30": "Scende dalle vette con un colpo che congela.",
    "bn_b31": "La Tigre di Cartone",
    "bk_b31": "L'Inganno a Strisce",
    "bl_b31": "Sembra finta finché non ti azzanna.",
    "bn_b32": "Il Puma dei Tetti",
    "bk_b32": "Il Saltatore",
    "bl_b32": "Salta da un palazzo all'altro senza sfiorare terra.",
    "bn_nonna": "La Nonna dei Vicoli",
    "bk_nonna": "Sette Vite e Mezza",
    "bl_nonna": "Le sue fusa curano, le sue sberle educano.",
    "bn_pescatore": "Il Pescatore Fantasma",
    "bk_pescatore": "La Rete del Destino",
    "bl_pescatore": "Appare nelle notti di nebbia, odore di sardine e vendetta.",
    "bn_b35": "Il Gatto con gli Stivali",
    "bk_b35": "La Lama Leggendaria",
    "bl_b35": "Lo spadaccino delle fiabe, in carne, pelo e stivali.",
    "bn_b36": "Bastet Minore",
    "bk_b36": "La Sacerdotessa",
    "bl_b36": "Sacerdotessa dai nove anelli, guardiana dei riti.",
    "bn_b37": "Il Gatto Guardiano",
    "bk_b37": "Il Custode della Soglia",
    "bl_b37": "Custodisce la soglia del granaio sacro da secoli.",
    "bn_b38": "Coda di Volpe",
    "bk_b38": "I Nove Inganni",
    "bl_b38": "Nove code, nove inganni, nessuna pietà.",
    "bn_b39": "Il Randagio Immortale",
    "bk_b39": "Otto Vite Spese",
    "bl_b39": "Dicono abbia già speso otto vite. Ne resta una.",
    "bn_b40": "Maneki il Portafortuna",
    "bk_b40": "La Zampa del Destino",
    "bl_b40": "La zampa alzata che sigilla i destini altrui.",
    "bn_spettro": "Lo Spettro dei Tetti",
    "bk_spettro": "L'Ombra di Mezzanotte",
    "bl_spettro": "Nessuno l'ha mai visto arrivare. Molti andarsene con la cena.",
    "bn_b42": "Il Gatto Nero del Venerdì",
    "bk_b42": "La Sfortuna Fatta Pelo",
    "bl_b42": "Porta sfortuna a chiunque osi sfidarlo.",
    "bn_b43": "Occhi nel Buio",
    "bk_b43": "Il Predatore Invisibile",
    "bl_b43": "Lo vedi solo quando è già troppo tardi.",
    "bn_b44": "Il Mietitore Baffuto",
    "bk_b44": "Il Signore della Nona Vita",
    "bl_b44": "Viene a riscuotere la tua nona vita.",
    "bn_b45": "Fantasma del Camino",
    "bk_b45": "La Cenere Vivente",
    "bl_b45": "Vive nella cenere calda del camino.",
    "bn_b46": "La Strega Gatta",
    "bk_b46": "L'Incantatrice",
    "bl_b46": "Trasforma i topi in tempeste con un miagolio.",
    "bn_b47": "Il Vampiro Persiano",
    "bk_b47": "Il Succhia-Velocità",
    "bl_b47": "Succhia la Velocità agli avversari e la fa sua.",
    "bn_b48": "Ectoplasma Felino",
    "bk_b48": "L'Intoccabile",
    "bl_b48": "Non puoi colpire ciò che non è solido.",
    "bn_imperatore": "L'Imperatore Soriano",
    "bk_imperatore": "Il Trono di Cuscini",
    "bl_imperatore": "Regna dal cuscino più alto. Il suo caos detta le regole.",
    "bn_b50": "Bastet la Dea",
    "bk_b50": "L'Antica Protettrice",
    "bl_b50": "L'antica dea protettrice di tutti i gatti.",
    "bn_b51": "Il Gatto di Schrödinger",
    "bk_b51": "Vivo e Morto",
    "bl_b51": "Vivo e morto insieme, finché non lo attacchi.",
    "bn_b52": "Ra-Miao il Sole",
    "bk_b52": "L'Accecante",
    "bl_b52": "Accecante: brucia chi osa guardarlo.",
    "bn_b53": "Sekhmet Felina",
    "bk_b53": "La Furia Divina",
    "bl_b53": "La furia divina fatta artigli.",
    "bn_b54": "Il Guardiano delle Piramidi",
    "bk_b54": "Mille Dinastie",
    "bl_b54": "Vecchio di mille dinastie, immoto come la pietra.",
    "bn_b55": "Luna Crescente",
    "bk_b55": "La Dea della Notte",
    "bl_b55": "La dea della notte: al buio è invincibile.",
    "bn_b56": "Il Gatto delle Stelle",
    "bk_b56": "Il Manto Cosmico",
    "bl_b56": "Il suo manto è un cielo di costellazioni.",
    "bn_mammone": "Il Gatto Mammone",
    "bk_mammone": "La Leggenda delle Leggende",
    "bl_mammone": "Il mostro delle fiabe. Enorme, antico e permaloso.",
    "bn_b58": "Behemoth",
    "bk_b58": "Il Colosso dell'Abisso",
    "bl_b58": "Il colosso che dorme sotto i vulcani.",
    "bn_b59": "Il Primo Gatto",
    "bk_b59": "L'Antenato",
    "bl_b59": "Colui da cui discendono tutti i mici del mondo.",
    "bn_b60": "Divoratore di Nove Soli",
    "bk_b60": "Il Mito Cosmico",
    "bl_b60": "Il mito che ingoia i soli, uno dopo l'altro.",
    "bn_b61": "Il Signore dei Randagi",
    "bk_b61": "Il Re di Tutti",
    "bl_b61": "Comanda ogni gatto randagio del mondo.",
    "bn_b62": "Chronos Felino",
    "bk_b62": "Il Mangiatore di Tempo",
    "bl_b62": "Mangia il tempo e invecchia gli avversari.",
    "bn_b63": "Il Gatto Vuoto",
    "bk_b63": "L'Assenza Fatta Felino",
    "bl_b63": "L'assenza fatta felino. Il nulla che miagola.",
    "bn_b64": "MIAO-9000",
    "bk_b64": "Il Gatto-Macchina Definitivo",
    "bl_b64": "Il gatto-macchina definitivo. Errore: pietà non trovata."
  },
  "world": {
    "w_recent": "📜 Ultimi 5 incontri delle tue carte",
    "w_open": "(tocca per aprire)",
    "w_beat": "{w} di {wo} ha battuto {l} di {lo}",
    "w_rank_champ": "👑 #1",
    "w_rank_n": "#{rk} in classifica",
    "w_retired": "🚪 ritirata",
    "w_record": "{w} V / {l} S",
    "w_none_pub": "Nessuna tua carta è ancora pubblicata.",
    "w_reactivate": "↩️ Riattiva",
    "w_retire": "🚪 Ritira",
    "w_rank_suffix": "in classifica",
    "w_by": "di",
    "w_anon": "anonimo",
    "w_wc_champ": "👑 CAMPIONE DEL MONDO",
    "w_wc_rank": "#{rk} nel ranking",
    "w_elo": "pt Elo",
    "w_exchamp": "🏆 ex campione",
    "w_beststreak": "miglior striscia 🔥{n}",
    "w_sw": "🔥 {n} di fila",
    "w_sl": "🧊 {n} ko di fila",
    "w_resting": "😴 Sta riposando: torna tra {min} minuti",
    "w_not_ranked": "⏳ {name} non è ancora nel ranking (appena pubblicata? riprova tra poco con 🔄).",
    "w_no_challengers": "📊 {name} è #{rk}, ma nessuno sfidante nel raggio ±5 al momento. Invita qualcuno a pubblicare!",
    "w_you_rank": "📊 {name} è #{rk} nel ranking. Ecco chi può sfidare (da 5 posizioni sopra a 5 sotto):",
    "w_rests_short": "😴 riposa ({min}m)",
    "w_btn_fight": "⚔️ Sfida",
    "w_ldr_champ": "CAMPIONE",
    "w_ex": "ex",
    "w_maxstreak": "max 🔥{n}",
    "w_none_rank": "Nessuna carta in ranking: pubblicane una!",
    "w_record_c": "{w}V/{l}S",
    "w_selrest": "😴 riposa",
    "w_selmarket": "🔒 al mercato",
    "w_fav": "⭐ favorito",
    "w_underdog": "🐾 underdog",
    "w_quota": "quota",
    "w_ifwin": "se vince: +{n} punti",
    "prize_line": "🎁 <strong>In palio:</strong> vittoria +10 punti e +25 XP · sconfitta +10 XP",
    "w_catnip_ready": "🌿 Erba gatta PRONTA per questo match ✔",
    "w_catnip_btn": "🌿 Dagli l'erba gatta — primo colpo raddoppiato (50 punti)",
    "w_catnip_need": "Servono 50 punti (ne hai {pts}).",
    "w_pick_champ_opt": "— scegli un campione —",
    "w_all_resting": "😴 tutti i gatti sono a riposo — torna più tardi",
    "w_pub_first_opt": "— pubblica prima una carta —",
    "w_loading": "Carico la classifica…"
  },
  "mkt": {
    "mkt_desc": "Scambia o vendi le tue carte con gli altri giocatori. La carta cambia proprietario con tutto (Elo, vittorie, livello); mentre è in trattativa resta congelata e non combatte. Serve essere connessi e avere carte pubblicate nel Mondo.",
    "trd_greet": "Benvenuto al bazar, amico! Sono Mister Baratto: chiedi pure, so io come si fanno i buoni affari.",
    "inc_greet": "Signori, si apre l'incanto! Chi offre? Chi rilancia?",
    "mkt_browse_btn": "🔍 Sfoglia carte da scambiare",
    "mkt_filter_ph": "Filtra per proprietario (es. Lu…)",
    "mkt_notactive": "⚠️ Il Mercato non è ancora attivo sul server (manca il passaggio di configurazione). Le altre funzioni dell'app funzionano normalmente.",
    "mkt_recv_h": "📥 Proposte ricevute",
    "mkt_offers": "{owner} ti offre <strong>{from}</strong> in cambio della tua <strong>{to}</strong>",
    "mkt_compare_btn": "🔍 Confronta",
    "mkt_accept": "✅ Accetta",
    "mkt_reject": "✖ Rifiuta",
    "mkt_none_recv": "Nessuna proposta ricevuta.",
    "mkt_sent_h": "📤 Proposte inviate",
    "mkt_sent": "Hai offerto <strong>{from}</strong> per <strong>{to}</strong> di {owner}",
    "mkt_cancel": "↩️ Annulla",
    "mkt_login": "Accedi per scambiare.",
    "mkt_loading": "Carico…",
    "mkt_err_load": "❌ Errore {code} nel caricare le carte.",
    "mkt_none_avail": "Nessuna carta disponibile per lo scambio.",
    "mkt_neterr": "Errore di rete.",
    "mkt_none_of": "Nessuna carta di «{q}».",
    "mkt_propose": "🔄 Proponi",
    "mkt_this_card": "questa carta",
    "mkt_give_get": "Dai <strong>{give}</strong> → Ricevi <strong>{get}</strong>",
    "mkt_level": "📈 Livello",
    "mkt_baratto_label": "😼 <strong>Mister Baratto</strong>:",
    "mkt_loading_cmp": "Carico il confronto…",
    "mkt_cmp_title": "🔄 Confronto scambio",
    "mkt_accept_trade": "✅ Accetta lo scambio",
    "mkt_close": "↩️ Chiudi",
    "mkt_err_cmp": "Errore nel caricare il confronto.",
    "mkt_close2": "Chiudi",
    "mkt_trade_h": "🔄 Scambio",
    "mkt_need_card": "Per scambiare ti serve almeno una TUA carta pubblicata e attiva nel Mondo (e non a riposo).",
    "mkt_closeX": "✖ Chiudi",
    "mkt_propose_h": "🔄 Proponi scambio",
    "mkt_want": "Vuoi <strong>{name}</strong>{owner}.",
    "mkt_tap_offer": "Tocca la TUA carta da offrire:",
    "mkt_do_trade": "🔄 Scambia",
    "mkt_cancelX": "✖ Annulla",
    "mkt_pick_offer": "Tocca prima una tua carta da offrire.",
    "mkt_notactive2": "⚠️ Il Mercato non è ancora attivo sul server: manca il passaggio di configurazione (SQL della tappa 2).",
    "mkt_trade_fail": "Scambio non proposto: {t}",
    "mkt_sent_ok": "🔄 Proposta inviata! In attesa di risposta.",
    "mkt_neterr2": "Errore di rete: {m}",
    "mkt_op_fail": "Operazione fallita: {t}",
    "mkt_trade_done": "✅ Scambio fatto! Le carte hanno cambiato proprietario.",
    "mkt_rejected": "Proposta rifiutata.",
    "mkt_cancelled": "↩️ Proposta annullata.",
    "mkt_received": "🎁 Hai ricevuto {name} nello scambio!",
    "mkt_login_first": "Accedi prima (scheda 🌍 Mondo).",
    "mkt_auc_h": "🔨 Asta",
    "mkt_need_free": "Ti serve una carta pubblicata e libera (non già al mercato) da mettere all'asta.",
    "mkt_put_auc_h": "🔨 Metti all'asta",
    "mkt_tap_sell": "Tocca la carta da vendere:",
    "mkt_min_price": "Prezzo minimo (punti)",
    "mkt_duration": "Durata",
    "mkt_h1": "1 ora",
    "mkt_h6": "6 ore",
    "mkt_h24": "24 ore",
    "mkt_d2": "2 giorni",
    "mkt_hold_auc": "🔨 Bandisci l'asta",
    "mkt_pick_card": "Tocca prima una carta.",
    "mkt_auc_notactive": "⚠️ Le aste non sono ancora attive sul server (manca il SQL).",
    "mkt_auc_fail": "Asta non creata: {t}",
    "mkt_auc_ok": "🔨 Asta bandita! La tua carta è ora al mercato.",
    "mkt_auc_notactive2": "⚠️ Aste non ancora attive sul server (manca il passaggio SQL).",
    "mkt_err": "Errore {code}.",
    "mkt_no_auc": "Nessuna asta in corso. Bandiscine una!",
    "mkt_curbid": "💰 {n} pt di {owner}",
    "mkt_nobid": "nessuna offerta",
    "mkt_your_auc": "🔨 la tua asta",
    "mkt_withdraw": "↩️ Ritira",
    "mkt_bid_btn": "💰 Rilancia",
    "mkt_base": "Base {n} pt",
    "mkt_history": "📜 Storico offerte",
    "mkt_min_bid": "Devi offrire almeno {n} punti.",
    "mkt_no_points": "Non hai abbastanza punti (ne hai {p}).",
    "mkt_bid_fail": "Offerta rifiutata: {t}",
    "mkt_no_bids": "Ancora nessuna offerta.",
    "mkt_bid_line": "💰 {n} pt — {owner} · {when}",
    "mkt_err2": "Errore.",
    "mkt_confirm_withdraw": "Ritirare la carta dall'asta?",
    "mkt_withdraw_fail": "Non ritirata: {t}",
    "mkt_withdrawn": "↩️ Asta ritirata."
  },
  "sent": {
    "sent_title": "🗺️ Il Sentiero delle Nove Vite",
    "sent_desc": "Un lungo viaggio a tappe per ogni tua carta: sfida i gatti del sentiero uno dopo l'altro. Ogni vittoria sblocca la tappa dopo e ti regala la figurina di quel gatto per l'Album. Si gioca offline, senza scommesse né riposo: se perdi, riprovi.",
    "sent_pick": "Chi cammina sul sentiero",
    "pick_card": "👆 Scegli una carta qui sopra per iniziare il viaggio.",
    "no_card": "Prima crea una carta, poi si parte per il sentiero.",
    "progress": "<strong>{name}</strong> — tappa {done}/{tot} superate.",
    "more_soon": "🚧 Le prossime zone del sentiero arrivano presto…",
    "stage": "Tappa",
    "zone_done": "🎉 Zona completata! +{pts} punti e una nuova pagina d'Album.",
    "got_fig": "📒 Nuova figurina: {name}!",
    "album_sum": "📒 Album — <strong>{done}/{tot}</strong> figurine <span class=\"count\">{open}</span>",
    "z_1": "I Vicoli",
    "z_2": "I Giardini",
    "z_3": "La Foresta",
    "z_4": "La Montagna",
    "z_5": "La Città",
    "z_6": "Il Deserto",
    "z_7": "Il Mare",
    "z_8": "Le Terre di Ghiaccio",
    "z_9": "Il Vulcano",
    "z_10": "Il Cosmo",
    "bn_s01": "Micetto",
    "bk_s01": "Il Novellino",
    "bl_s01": "Il primo gatto che incontri: curioso, impaccia, ma ci mette il cuore.",
    "bn_s02": "Rovista",
    "bk_s02": "Il Re dei Rifiuti",
    "bl_s02": "Conosce ogni cassonetto del quartiere e cosa ci trovi dentro.",
    "bn_s03": "Calzino",
    "bk_s03": "Il Dormiglione",
    "bl_s03": "Bianco e nero, sempre sul cofano più caldo del vicolo.",
    "bn_s04": "Scatolino",
    "bk_s04": "L'Agguato di Cartone",
    "bl_s04": "Vive in una scatola e salta fuori quando meno te lo aspetti.",
    "bn_s05": "Mezzanotte",
    "bk_s05": "L'Ombra del Vicolo",
    "bl_s05": "Nero come la notte, lo vedi solo per gli occhi che brillano.",
    "bn_s06": "Panna",
    "bk_s06": "Il Goloso",
    "bl_s06": "Ha sempre i baffi sporchi di latte e un sorriso soddisfatto.",
    "bn_s07": "Corda",
    "bk_s07": "Il Musicante",
    "bl_s07": "Suona la sua chitarra scordata sotto i lampioni, per due croccantini.",
    "bn_s08": "Sardina",
    "bk_s08": "Il Pescivendolo",
    "bl_s08": "Non molla mai il suo pesce: dovrai sudartelo.",
    "bn_s09": "Saetta",
    "bk_s09": "Il Fulmine del Vicolo",
    "bl_s09": "Rimbalza da un muro all'altro: prendilo se ci riesci.",
    "bn_s10": "Zampaguercia",
    "bk_s10": "Il Re dei Vicoli",
    "bl_s10": "Un occhio solo e mille cicatrici: comanda tutti i randagi. Il primo vero ostacolo.",
    "bn_s11": "Aliflor",
    "bk_s11": "Il Cacciafarfalle",
    "bl_s11": "Insegue farfalle tutto il giorno, non ne prende mai una.",
    "bn_s12": "Girasole",
    "bk_s12": "Il Dormiglione al Sole",
    "bl_s12": "Dorme dove batte il sole e si sposta insieme a lui.",
    "bn_s13": "Ronzio",
    "bk_s13": "Il Pungiglione",
    "bl_s13": "Ha imparato a sue spese che le api pungono. Ancora ci prova.",
    "bn_s14": "Cinguetto",
    "bk_s14": "Lo Spia-uccelli",
    "bl_s14": "Osserva gli uccellini dalla finestra per ore, immobile.",
    "bn_s15": "Ranocchio",
    "bk_s15": "Lo Spaventa-rane",
    "bl_s15": "Salta nello stagno e fa scappare tutte le rane.",
    "bn_s16": "Spina",
    "bk_s16": "Il Ferito di Rose",
    "bl_s16": "Mille graffi tra i rovi, ma il roseto è suo.",
    "bn_s17": "Lumaca",
    "bk_s17": "Il Paziente",
    "bl_s17": "Osserva le lumache muoversi. È l'unico più lento di loro.",
    "bn_s18": "Zampilla",
    "bk_s18": "Lo Schizza-fontana",
    "bl_s18": "Gioca con l'acqua della fontana e torna sempre zuppo.",
    "bn_s19": "Riccio",
    "bk_s19": "L'Amico Spinoso",
    "bl_s19": "Ha fatto amicizia con un riccio. Non chiedere come.",
    "bn_s20": "Vecchio Salice",
    "bk_s20": "Il Signore del Giardino",
    "bl_s20": "Il gatto più anziano del giardino: saggio, calmo e intoccabile.",
    "bn_s21": "Fungo",
    "bk_s21": "Il Cercatore",
    "bl_s21": "Fiuta i funghi migliori del bosco, e schiva quelli cattivi.",
    "bn_s22": "Piumanotte",
    "bk_s22": "Il Rivale del Gufo",
    "bl_s22": "Sfida il gufo ogni notte a chi resta sveglio più a lungo.",
    "bn_s23": "Ghianda",
    "bk_s23": "L'Accumulatore",
    "bl_s23": "Ruba ghiande agli scoiattoli e le nasconde ovunque.",
    "bn_s24": "Furbetto",
    "bk_s24": "L'Astuto",
    "bl_s24": "Cammina come una volpe e pensa come una volpe.",
    "bn_s25": "Zanna",
    "bk_s25": "Il Guardiano del Territorio",
    "bl_s25": "Difende la sua radura da chiunque, cinghiali compresi.",
    "bn_s26": "Ragnatela",
    "bk_s26": "L'Impigliato",
    "bl_s26": "Finisce sempre nelle ragnatele, ma non molla mai.",
    "bn_s27": "Pigna",
    "bk_s27": "Lo Scalapini",
    "bl_s27": "Si arrampica sui pini più alti solo per guardare in basso.",
    "bn_s28": "Cerbiatto",
    "bk_s28": "Il Cacciatore Silenzioso",
    "bl_s28": "Segue i cervi nel bosco senza farsi sentire.",
    "bn_s29": "Lupetto",
    "bk_s29": "Il Cucciolo Selvaggio",
    "bl_s29": "Cresciuto tra i lupi, ne ha imparato l'ululato.",
    "bn_s30": "Orsone",
    "bk_s30": "La Bestia della Foresta",
    "bl_s30": "Grosso come un orso: il re incontrastato del bosco.",
    "bn_s31": "Scarponcino",
    "bk_s31": "Il Segui-escursionisti",
    "bl_s31": "Segue gli escursionisti in cima sperando in un panino.",
    "bn_s32": "Saltacapre",
    "bk_s32": "Lo Spaventa-capre",
    "bl_s32": "Fa sobbalzare le capre sui dirupi solo per divertimento.",
    "bn_s33": "Sassolino",
    "bk_s33": "L'Equilibrista",
    "bl_s33": "Sta in equilibrio sui massi più scomodi della montagna.",
    "bn_s34": "Aquilotto",
    "bk_s34": "Il Rivale dell'Aquila",
    "bl_s34": "Contende all'aquila le vette più alte, senza ali.",
    "bn_s35": "Tendina",
    "bk_s35": "Il Ladro dell'Accampamento",
    "bl_s35": "Svaligia le tende dei campeggiatori nella notte.",
    "bn_s36": "Cima",
    "bk_s36": "L'Abitante delle Vette",
    "bl_s36": "Vive dove l'aria è sottile e nessun altro gatto osa.",
    "bn_s37": "Ventaccio",
    "bk_s37": "Lo Scapigliato",
    "bl_s37": "Il vento di montagna gli ha arruffato il pelo per sempre.",
    "bn_s38": "Rampino",
    "bk_s38": "Lo Scalatore",
    "bl_s38": "Si arrampica su pareti dove nemmeno le capre vanno.",
    "bn_s39": "Campanella",
    "bk_s39": "Il Montanaro",
    "bl_s39": "Porta un campanello al collo: lo senti prima di vederlo.",
    "bn_s40": "Cornabianca",
    "bk_s40": "Il Re della Montagna",
    "bl_s40": "Corna da ariete e zampe di ferro: domina ogni cima.",
    "bn_s41": "Taxi",
    "bk_s41": "Lo Schiva-auto",
    "bl_s41": "Attraversa il traffico più caotico senza un graffio.",
    "bn_s42": "Tegola",
    "bk_s42": "Il Predatore dei Tetti",
    "bl_s42": "Regna sui tetti della grande città, di tegola in tegola.",
    "bn_s43": "Margherita",
    "bk_s43": "Il Razziatore di Pizze",
    "bl_s43": "Nessun cartone di pizza è al sicuro con lui in giro.",
    "bn_s44": "Semaforo",
    "bk_s44": "Il Guarda-traffico",
    "bl_s44": "Aspetta sempre il verde. Un gatto molto civile.",
    "bn_s45": "Parkour",
    "bk_s45": "L'Acrobata dei Tetti",
    "bl_s45": "Salta da un palazzo all'altro come nei film.",
    "bn_s46": "Neon",
    "bk_s46": "Il Poltrone al Neon",
    "bl_s46": "Dorme sotto le insegne luminose, al caldo della città.",
    "bn_s47": "Metrò",
    "bk_s47": "Il Gatto della Metro",
    "bl_s47": "Conosce ogni tunnel e ogni banchina sottoterra.",
    "bn_s48": "Jazz",
    "bk_s48": "Il Gatto del Vicolo",
    "bl_s48": "Miagola a tempo di jazz dietro i locali, la notte.",
    "bn_s49": "Grattacielo",
    "bk_s49": "Lo Scala-torri",
    "bl_s49": "Ha scalato il palazzo più alto solo per la vista.",
    "bn_s50": "Notturno",
    "bk_s50": "Il Boss della Città",
    "bl_s50": "Comanda ogni vicolo dopo il tramonto. La città è sua.",
    "bn_s51": "Cactino",
    "bk_s51": "Lo Schiva-cactus",
    "bl_s51": "Corre tra i cactus senza mai pungersi. Quasi mai.",
    "bn_s52": "Coda-uncino",
    "bk_s52": "Il Diffidente",
    "bl_s52": "Tiene d'occhio ogni scorpione: è già stato punto una volta.",
    "bn_s53": "Dunetta",
    "bk_s53": "Il Corridore delle Dune",
    "bl_s53": "Sale e scende le dune come fossero cuscini.",
    "bn_s54": "Palmetta",
    "bk_s54": "Il Poltrone dell'Oasi",
    "bl_s54": "Ha trovato l'unica ombra del deserto e non la molla.",
    "bn_s55": "Sibilo",
    "bk_s55": "L'Incantaserpenti",
    "bl_s55": "Fissa i serpenti finché non si arrendono.",
    "bn_s56": "Solleone",
    "bk_s56": "L'Arso dal Sole",
    "bl_s56": "Il sole del deserto gli ha scaldato il carattere.",
    "bn_s57": "Anfora",
    "bk_s57": "Il Gatto delle Rovine",
    "bl_s57": "Vive tra le rovine antiche, custode di segreti di sabbia.",
    "bn_s58": "Gobba",
    "bk_s58": "Il Segui-cammelli",
    "bl_s58": "Segue le carovane per le briciole dei viaggiatori.",
    "bn_s59": "Turbine",
    "bk_s59": "Il Sopravvissuto alle Tempeste",
    "bl_s59": "È passato attraverso mille tempeste di sabbia. È ancora qui.",
    "bn_s60": "Leontino",
    "bk_s60": "La Sfinge del Deserto",
    "bl_s60": "Immobile come una statua, antico come la sabbia. Parla per enigmi.",
    "bn_s61": "Chela",
    "bk_s61": "L'Acchiappa-granchi",
    "bl_s61": "Insegue i granchi sulla battigia, ci rimette sempre un baffo.",
    "bn_s62": "Conchiglia",
    "bk_s62": "Il Collezionista",
    "bl_s62": "Raccoglie conchiglie e le nasconde nella sabbia.",
    "bn_s63": "Onda",
    "bk_s63": "Lo Schiva-onde",
    "bl_s63": "Sfida le onde e scappa un attimo prima di bagnarsi.",
    "bn_s64": "Amo",
    "bk_s64": "Il Pescatore",
    "bl_s64": "Pesca con la zampa meglio di molti pescatori.",
    "bn_s65": "Gabbiano",
    "bk_s65": "Il Rivale del Gabbiano",
    "bl_s65": "Contende ai gabbiani ogni briciola del molo.",
    "bn_s66": "Vela",
    "bk_s66": "Il Clandestino",
    "bl_s66": "Si imbarca di nascosto e nessuno se ne accorge.",
    "bn_s67": "Arrembaggio",
    "bk_s67": "Il Gatto Pirata",
    "bl_s67": "Benda su un occhio e una zampa sempre pronta all'assalto.",
    "bn_s68": "Tentacolo",
    "bk_s68": "Il Domatore di Polpi",
    "bl_s68": "L'unico che gioca coi polpi e ne esce vincitore.",
    "bn_s69": "Foca",
    "bk_s69": "L'Amico del Mare",
    "bl_s69": "Nuota con le foche come se fosse nato tra loro.",
    "bn_s70": "Leviatano",
    "bk_s70": "Il Re del Mare",
    "bl_s70": "Grande come una balena: comanda ogni onda dell'oceano.",
    "sent_fight": "⚔️ Combatti",
    "sent_back": "↩️ Indietro",
    "sent_replay": "⚔️ Rigioca",
    "bn_s71": "Nevischio",
    "bk_s71": "Il Cattura-fiocchi",
    "bl_s71": "Cerca di afferrare i fiocchi di neve con le zampe, uno per uno.",
    "bn_s72": "Pupazzo",
    "bk_s72": "Il Costruttore di Neve",
    "bl_s72": "Costruisce pupazzi di neve e poi li abbatte per gioco.",
    "bn_s73": "Ghiacciolo",
    "bk_s73": "Lo Scivolone",
    "bl_s73": "Scivola sul ghiaccio senza mai fermarsi davvero.",
    "bn_s74": "Pinguino",
    "bk_s74": "Il Rivale del Pinguino",
    "bl_s74": "Sfida i pinguini a chi scivola più lontano sulla pancia.",
    "bn_s75": "Sciatore",
    "bk_s75": "Il Discesista",
    "bl_s75": "Scende i pendii innevati più veloce di uno slittino.",
    "bn_s76": "Orsetto",
    "bk_s76": "L'Amico dell'Orso Bianco",
    "bl_s76": "Ha adottato un cucciolo d'orso polare. O è il contrario?",
    "bn_s77": "Bufera",
    "bk_s77": "Il Camminatore di Tormente",
    "bl_s77": "Attraversa le tormente di neve come se fosse una brezza.",
    "bn_s78": "Pietrella",
    "bk_s78": "Il Lanciatore di Ghiaccio",
    "bl_s78": "Fa scivolare pietre sul ghiaccio con mira perfetta.",
    "bn_s79": "Cristallo",
    "bk_s79": "L'Ammira-cristalli",
    "bl_s79": "Passa ore a fissare i cristalli di ghiaccio che brillano.",
    "bn_s80": "Re Gelo",
    "bk_s80": "Il Sovrano del Ghiaccio",
    "bl_s80": "Il suo respiro gela i laghi. Nessuno regge il suo sguardo di ghiaccio.",
    "bn_s81": "Brace",
    "bk_s81": "Il Tizzone",
    "bl_s81": "Cammina sui carboni ardenti senza scottarsi le zampe.",
    "bn_s82": "Cratere",
    "bk_s82": "L'Abitante del Cratere",
    "bl_s82": "Vive sull'orlo del vulcano, dove fa un caldo infernale.",
    "bn_s83": "Ossidiana",
    "bk_s83": "Il Gatto di Pietra Nera",
    "bl_s83": "Duro e lucido come vetro vulcanico.",
    "bn_s84": "Boato",
    "bk_s84": "L'Esplosivo",
    "bl_s84": "Quando si arrabbia, trema tutta la montagna.",
    "bn_s85": "Petardo",
    "bk_s85": "Il Miccia Corta",
    "bl_s85": "Si accende per un nonnulla e parte all'attacco.",
    "bn_s86": "Sorgente",
    "bk_s86": "Il Poltrone delle Terme",
    "bl_s86": "Sonnecchia nelle pozze calde vicino alla lava.",
    "bn_s87": "Arsura",
    "bk_s87": "Il Rovente",
    "bl_s87": "Al suo passaggio l'aria trema per il calore.",
    "bn_s88": "Fiammella",
    "bk_s88": "Il Custode del Fuoco",
    "bl_s88": "Tiene viva l'antica fiamma del vulcano.",
    "bn_s89": "Lucerna",
    "bk_s89": "La Fiamma Eterna",
    "bl_s89": "Brucia da mille anni e non si spegne mai.",
    "bn_s90": "Draghetto",
    "bk_s90": "Il Drago del Vulcano",
    "bl_s90": "Sputa faville e comanda la lava. Il re del fuoco.",
    "bn_s91": "Lunetta",
    "bk_s91": "Il Gatto della Luna",
    "bl_s91": "Salta di cratere in cratere sulla luna, leggero come una piuma.",
    "bn_s92": "Stellina",
    "bk_s92": "Il Raccogli-stelle",
    "bl_s92": "Colleziona stelle cadenti in un barattolo (dice lui).",
    "bn_s93": "Anello",
    "bk_s93": "Il Signore degli Anelli",
    "bl_s93": "Vive sugli anelli di Saturno, in equilibrio perfetto.",
    "bn_s94": "Cometa",
    "bk_s94": "Il Viaggiatore",
    "bl_s94": "Sfreccia nello spazio lasciando una scia luminosa.",
    "bn_s95": "Razzo",
    "bk_s95": "L'Astronauta",
    "bl_s95": "È salito su un razzo per gioco e non è più sceso.",
    "bn_s96": "Disco",
    "bk_s96": "L'Amico degli Alieni",
    "bl_s96": "Ha fatto amicizia con creature di altri mondi.",
    "bn_s97": "Meteora",
    "bk_s97": "Il Desiderio",
    "bl_s97": "Passa così in fretta che devi esprimere un desiderio.",
    "bn_s98": "Vuoto",
    "bk_s98": "Il Buco Nero",
    "bl_s98": "Inghiotte tutto ciò che gli si avvicina, persino la luce.",
    "bn_s99": "Polvere",
    "bk_s99": "Il Manto di Stelle",
    "bl_s99": "Il suo pelo è fatto di polvere di galassie.",
    "bn_s100": "Sovrano Cosmico",
    "bk_s100": "Il Signore delle Nove Vite",
    "bl_s100": "L'ultimo avversario del Sentiero. Antico come l'universo, invincibile come una leggenda."
  },
  "msg": {
    "del_card_confirm": "Eliminare la carta di {name}? Verranno cancellate anche le sue statistiche di combattimento.",
    "nick_set": "🥊 {name} ora è «{nick}»",
    "retire_login": "Per ritirare una carta dal mondo devi prima accedere (scheda 🌍 Mondo).",
    "retire_confirm": "Ritirare {name} dall'Arena Mondiale? Resterà in classifica con il suo record come «ritirata», ma nessuno potrà più sfidarla. (Ripubblicandola tornerà in attività.)",
    "err_http": "Errore: HTTP {code}",
    "card_not_pub": "Questa carta non risulta pubblicata (o non è tua).",
    "retired_ok": "🚪 {name} si è ritirata dal mondo con onore. Il suo record resta in classifica.",
    "err_net": "Errore di rete: {m}",
    "code_copied": "Codice copiato! Invialo a un amico (es. su WhatsApp): lo incollerà nella sua app per sfidare {name}. Nota: il codice è lungo perché contiene anche la foto.",
    "audio_quota": "⛔ Quota giornaliera di Gemini esaurita.\n\nLe clip già fatte sono salvate. Riprendi domani (la quota si azzera) e completerà solo le mancanti.",
    "audio_err": "🎙️ Errore audio ({lang}): {err}",
    "same_cat": "Un gatto non può combattere contro sé stesso! Scegli due carte diverse.",
    "backup_confirm": "Importare il backup? Sostituirà collezione, rivali e statistiche attuali ({n} carte nel backup).",
    "backup_invalid": "File di backup non valido.",
    "share_unsupported": "La condivisione diretta non è supportata da questo browser: usa «Scarica» e allega l'immagine.",
    "card_gone_local": "Questa carta non è più nella tua collezione locale.",
    "news_beaten": "💥 {loser} è stata battuta da {winner} {by} {owner} — ora riposa 😴",
    "world_login": "Accedi prima (in cima alla scheda Mondo) per sfidare online.",
    "out_of_range": "🔒 Fuori portata: {name} è #{ro}, tu sei #{rm}. Puoi sfidare solo tra 5 posizioni sopra e 5 sotto: scala il ranking!",
    "opp_trading": "🔄 {name} è impegnata in uno scambio: non è sfidabile ora.",
    "opp_resting": "😴 {name} è appena andato a riposo: riprova tra {min} minuti.",
    "need_pub_card": "Per sfidare online serve una TUA carta pubblicata e attiva: pubblicane una da «Scegli quali carte pubblicare».",
    "catnip_have": "Vantaggio già acquistato: vale per il tuo prossimo incontro.",
    "catnip_need": "Servono 50 punti (ne hai {pts}). Vinci scommesse e medaglie!",
    "catnip_confirm": "Spendere 50 punti? La tua carta inizierà il prossimo incontro con l'erba gatta (primo colpo raddoppiato).",
    "catnip_ready": "🌿 Vantaggio pronto: vale per il tuo prossimo incontro!",
    "regen_cost": "Rigenerare il disegno costa 30 punti (ne hai {pts}).",
    "regen_confirm": "Spendere 30 punti per un nuovo disegno AI?",
    "frame_have": "{name} sfoggia già la Cornice d'Oro!",
    "frame_cost": "La Cornice d'Oro costa 100 punti (ne hai {pts}).",
    "frame_confirm": "Spendere 100 punti per la Cornice d'Oro di {name}? Resterà per sempre.",
    "food_need": "💰 Servono {cost} punti (ne hai {pts}): vincile nel mondo!",
    "train_cancel": "↩️ Allenamento annullato: {cost} punti restituiti.",
    "pick_champ": "Scegli prima il tuo campione nel menu qui sopra.",
    "qr_gen_fail": "Generatore QR non caricato: ricarica la pagina con internet attivo.",
    "qr_read_fail": "Lettore QR non caricato: serve internet.",
    "cam_fail": "Fotocamera non disponibile: {m}",
    "qr_invalid": "QR non valido.",
    "qr_self": "Hai inquadrato la tua stessa carta!"
  },
  "moves": {
    "ma_0": "Graffio",
    "ma_1": "Agguato",
    "ma_2": "Sguardo",
    "ma_3": "Balzo",
    "ma_4": "Zampata",
    "ma_5": "Miagolio",
    "ma_6": "Assalto",
    "ma_7": "Fusa",
    "mb_0": "Fulmineo",
    "mb_1": "del Divano",
    "mb_2": "di Disprezzo",
    "mb_3": "Cosmico",
    "mb_4": "Selvaggio",
    "mb_5": "Notturno",
    "mb_6": "delle 4 del Mattino",
    "mb_7": "Ipnotiche"
  },
  "instr": {
    "i_pianoforte": "pianoforte",
    "i_tromba": "tromba",
    "i_chitarra": "chitarra",
    "i_archi": "archi",
    "i_organo": "organo",
    "i_marimba": "marimba",
    "theme_line": "{stile} in {ton}, {instr}"
  },
  "breeds": {
    "b_soriano": "Soriano",
    "b_tigrato": "Tigrato",
    "b_europeo": "Europeo",
    "b_comune": "Gatto comune",
    "b_certosino": "Certosino",
    "b_siamese": "Siamese",
    "b_persiano": "Persiano",
    "b_mainecoon": "Maine Coon",
    "b_ragdoll": "Ragdoll",
    "b_sphynx": "Sphynx",
    "b_bengala": "Bengala",
    "b_british": "British",
    "b_norvegese": "Norvegese",
    "b_angora": "Angora",
    "b_birmano": "Birmano",
    "b_abissino": "Abissino",
    "b_esotico": "Esotico",
    "b_siberiano": "Siberiano",
    "b_scottish": "Scottish Fold",
    "b_rex": "Rex",
    "b_blurusso": "Blu di Russia",
    "b_orientale": "Orientale",
    "b_turco": "Turco Van",
    "b_savana": "Savannah",
    "b_bombay": "Bombay",
    "c_bianco": "bianco",
    "c_nero": "nero",
    "c_grigio": "grigio",
    "c_blu": "blu",
    "c_rosso": "rosso",
    "c_crema": "crema",
    "c_marrone": "marrone",
    "c_fulvo": "fulvo",
    "c_tartarugato": "tartarugato",
    "c_tricolore": "tricolore",
    "c_bicolore": "bicolore",
    "c_maculato": "maculato",
    "c_striato": "striato",
    "c_pointed": "colorpoint",
    "coat_lungo": "a pelo lungo",
    "coat_corto": "a pelo corto"
  },
  "award": {
    "title": "🏆 Gli Award del Sabato Sera",
    "host": "Pippo Baffo",
    "subtitle": "Ogni sabato sera il gran galà: premi, punti e gloria per le carte migliori della settimana.",
    "promo_when": "SABATO, ORE 21:00",
    "promo_line": "🎬 Prossima puntata con {host}",
    "promo_cd": "tra {d}g {h}h {m}m",
    "promo_soon": "tra {h}h {m}m",
    "promo_live": "🔴 È il momento! La cerimonia sta per iniziare…",
    "noms_title": "✨ Le nomination di questa settimana",
    "noms_sub": "Chi è in testa adesso — aggiornato dal vivo",
    "noms_empty": "Ancora nessun incontro questa settimana. Combatti nel Mondo per entrare in classifica!",
    "past_title": "📼 Le puntate precedenti",
    "past_empty": "La prima serata di gala è questo sabato. Torna qui per vedere i vincitori!",
    "hall_title": "🏛️ Hall of Fame — i record di sempre",
    "hall_empty": "Nessun record ancora: qualcuno sarà il primo a scriverlo.",
    "by": "di",
    "pts": "+{p} pt",
    "week_of": "Serata del {d}",
    "aw_mvp": "MVP — Gatto della Settimana",
    "aw_instancabile": "Instancabile",
    "aw_cecchino": "Cecchino",
    "aw_dominatore": "Dominatore",
    "d_mvp": "più vittorie",
    "d_instancabile": "più incontri",
    "d_cecchino": "miglior percentuale",
    "d_dominatore": "striscia più lunga",
    "hof_striscia": "Striscia Leggendaria",
    "hof_veterano": "Veterano",
    "hof_recordman": "Recordman di Vittorie",
    "hof_winrate": "Miglior Percentuale",
    "val_mvp": "{n} vittorie",
    "val_instancabile": "{n} incontri",
    "val_cecchino": "{n}%",
    "val_dominatore": "striscia di {n}",
    "val_striscia": "{n} di fila",
    "val_veterano": "{n} incontri",
    "val_recordman": "{n} vittorie",
    "val_winrate": "{n}%",
    "cer_title": "GRAN GALÀ DEL SABATO SERA",
    "cer_open": "🎩 Signore e signori… benvenuti al Gran Galà! Sono {host}, e stasera premiamo i gatti più in gamba della settimana!",
    "cer_drumroll": "🥁 Rullo di fusa…",
    "cer_gold": "🥇 La zampa d’oro va a… {name}, di {owner}!",
    "cer_silver": "🥈 Argento per {name}, di {owner}.",
    "cer_bronze": "🥉 Bronzo per {name}, di {owner}.",
    "cer_pts": "✨ +{p} punti!",
    "cer_q_mvp": "Il più vincente di tutti!",
    "cer_q_instancabile": "Non si è fermato un attimo!",
    "cer_q_cecchino": "Preciso come un cecchino!",
    "cer_q_dominatore": "Una striscia da paura!",
    "cer_mvp_finale": "🌟 E ora il premio più ambìto della serata… il Gatto della Settimana!",
    "cer_close": "🎉 È tutto per stasera! Applausi ai nostri campioni. Ci vediamo sabato prossimo!",
    "cer_none": "Questa settimana nessun premio: si è combattuto troppo poco! Tornate a lottare.",
    "btn_replay": "🎬 Rivedi la serata",
    "btn_skip": "Salta ▶▶",
    "cer_preview": "ANTEPRIMA — classifica in corso",
    "pl_1": "La serata dove i gatti diventano leggende.",
    "pl_2": "Smoking, riflettori e fusa: si parte!",
    "pl_3": "Nove vite, un solo palco.",
    "pl_4": "Chi si porta a casa la zampa d’oro?",
    "pl_5": "Croccantini rossi e tappeto… pure rosso.",
    "pl_6": "Applausi, coriandoli e qualche graffio.",
    "pl_7": "Il sabato più elegante del vicinato.",
    "pl_8": "Solo i mici più tosti salgono sul palco.",
    "pl_9": "Luci, camera… miao!",
    "pl_10": "Stasera si premia chi ha graffiato più forte.",
    "place_1": "Primo posto · Oro",
    "place_2": "Secondo posto · Argento",
    "place_3": "Terzo posto · Bronzo",
    "full_mvp": "Il gatto con più vittorie mondiali della settimana. Il migliore, semplicemente.",
    "full_instancabile": "Chi ha disputato più incontri di tutti: mai fermo, sempre sul ring.",
    "full_cecchino": "La miglior percentuale di vittorie (almeno 5 incontri): precisione, non fortuna.",
    "full_dominatore": "La striscia di vittorie consecutive più lunga della settimana.",
    "react_1": "Che zampata!",
    "react_2": "Applausi, prego! 👏",
    "react_3": "Da pelo d’oca!",
    "react_4": "Un vero fenomeno!",
    "react_5": "Miao che classe!",
    "react_6": "Il pubblico impazzisce!",
    "cer_podium": "🏆 E ora… il podio!",
    "cer_suspense": "🥁 …e il vincitore è…",
    "cer_hall_intro": "🏛️ E ora… i Record di Sempre!",
    "cer_hall_hold": "Questo record resta saldo. Che campione!",
    "cer_record_broken": "Nuovo record! {name} entra nella leggenda!",
    "rec_new": "NUOVO RECORD!",
    "aw_inlizza": "in lizza",
    "cont_title": "Gli inseguitori",
    "cer_contenders": "E occhio a questi: erano a un soffio dal podio!",
    "notif_win": "🏆 Hai vinto {list}! +{pts} punti sul tuo saldo.",
    "notif_more": "e altri {n}",
    "aw_ammazza": "Ammazza-giganti",
    "d_ammazza": "l'upset più grande",
    "full_ammazza": "Ha battuto un avversario con molto più Elo di lui: l'impresa della settimana.",
    "cer_q_ammazza": "Davide contro Golia!",
    "val_ammazza": "{n} Elo di scarto",
    "aw_beniamino": "Beniamino",
    "d_beniamino": "il più sfidato",
    "full_beniamino": "Il gatto che gli altri hanno sfidato di più: una vera star.",
    "cer_q_beniamino": "Tutti lo vogliono sfidare!",
    "val_beniamino": "{n} sfide ricevute",
    "aw_debuttante": "Debuttante",
    "d_debuttante": "miglior carta nuova",
    "full_debuttante": "La miglior carta creata questa settimana, per numero di vittorie.",
    "cer_q_debuttante": "Nato per combattere!",
    "val_debuttante": "{n} vittorie",
    "aw_astro": "Astro nascente",
    "d_astro": "maggior scalata Elo",
    "full_astro": "Chi ha guadagnato più punti Elo questa settimana: in rampa di lancio.",
    "cer_q_astro": "In ascesa inarrestabile!",
    "val_astro": "+{n} Elo",
    "aw_pantofolaio": "Pantofolaio",
    "d_pantofolaio": "ha combattuto meno",
    "full_pantofolaio": "Il premio-scherzo: tra chi è sceso in campo, ha combattuto pochissimo.",
    "cer_q_pantofolaio": "Il divano lo chiama!",
    "val_pantofolaio": "solo {n} incontri",
    "hof_piccoelo": "Picco Elo",
    "val_piccoelo": "{n} Elo",
    "hof_regno": "Regno più lungo",
    "val_regno": "{n} giorni",
    "hof_muro": "Il Muro",
    "val_muro": "{n} difese",
    "hof_pluricampione": "Pluricampione",
    "val_pluricampione": "{n} titoli",
    "hof_novevite": "Le Nove Vite",
    "val_novevite": "Sentiero completo"
  },
  "gang": {
    "login": "Accedi per usare i clan.",
    "none_title": "🛡️ I Clan",
    "none_sub": "Unisciti a un clan o creane uno tuo. Insieme si combatte in squadra.",
    "create": "Crea il tuo clan",
    "name_ph": "Nome del clan",
    "emblem": "Emblema",
    "create_btn": "🛡️ Crea clan",
    "board": "📋 Bacheca — clan esistenti",
    "board_empty": "Nessun clan ancora. Sii il primo a crearne uno!",
    "members_n": "{n} membri",
    "cards_n": "{n} carte",
    "apply": "Richiedi",
    "applied": "✅ Richiesta inviata",
    "full": "Pieno",
    "invites": "✉️ I tuoi inviti",
    "invited_by": "invito da {who}",
    "accept": "Accetta",
    "decline": "Rifiuta",
    "members": "👥 Membri",
    "leader": "👑 capo",
    "roster": "🃏 Roster",
    "roster_empty": "Roster vuoto. Aggiungi le tue carte!",
    "add_card": "➕ Aggiungi",
    "add_none": "Nessuna carta da aggiungere",
    "remove": "Togli",
    "apps": "📥 Richieste di ingresso",
    "apps_empty": "Nessuna richiesta.",
    "approve": "Accetta",
    "reject": "Rifiuta",
    "leave": "🚪 Esci dal clan",
    "disband": "💥 Sciogli il clan",
    "leave_confirm": "Uscire dal clan?",
    "disband_confirm": "Sei il capo: se esci, il clan si scioglie. Confermi?",
    "created": "🛡️ Clan creato!",
    "order_hint": "(il capo può riordinare con ▲▼)",
    "inv_title": "✉️ Invita giocatori",
    "inv_browse": "🔎 Sfoglia i giocatori",
    "invite_btn": "Invita",
    "invited_lbl": "✅ Invitato",
    "no_free": "Nessun giocatore libero da invitare.",
    "search_ph": "Cerca un clan…",
    "more": "Carica altri",
    "open_lbl": "Aperto",
    "closed_lbl": "🔒 Chiuso",
    "browse_others": "📋 Sfoglia gli altri clan",
    "set_open": "🔓 Apri il clan",
    "set_closed": "🔒 Chiudi il clan",
    "search_player": "Cerca un giocatore…",
    "see_cards": "Vedi le carte",
    "back": "Indietro",
    "no_cards": "Nessuna carta pubblicata.",
    "invite_sent": "✉️ Invito inviato!",
    "kick": "Espelli",
    "kick_confirm": "Espellere questo membro dal clan?",
    "joined_msg": "🛡️ Sei entrato in un clan!",
    "kicked_msg": "🚪 Non fai più parte del clan.",
    "changed_msg": "Il tuo clan è cambiato.",
    "attack": "⚔️ Attacca",
    "war_won": "🏆 Guerra vinta! +30 punti-clan",
    "war_lost": "💥 Guerra persa. +5 di consolazione",
    "no_fresh": "Nessuna carta fresca da schierare (sono a riposo).",
    "enemy_empty": "Il clan avversario non ha carte nel roster.",
    "pts": "pt",
    "war_confirm": "Attaccare {name}? Le tue carte poi riposeranno un’ora."
  }
};
