/* CatCards — traduzioni DE (generato). Per aggiungere una lingua: copia questo file, traduci i valori, aggiungi il codice a LANGS in index.html) */
(window.LANG_DB = window.LANG_DB || {})["de"] = {
 "ui": {
  "tagline": "Fotografiere deine Katze und mach sie zur Sammelkarte",
  "tab_crea": "📸 Neu",
  "tab_carte": "📚 Karten",
  "tab_dojo": "🥋 Dojo",
  "tab_mondo": "🌍 Welt",
  "tab_mercato": "🔁 Markt",
  "tab_boss": "🤖 Bosse",
  "tab_pal": "🏋️ Studio",
  "tab_med": "🏅 Medaillen",
  "tab_reg": "📖 Regeln",
  "drop_title": "Tippe, um ein Foto zu machen oder hochzuladen",
  "drop_sub": "JPG oder PNG — die Katze sollte gut sichtbar sein",
  "cat_name": "Name der Katze (optional)",
  "gen_btn": "✨ Karte erstellen",
  "dl_card": "⬇️ Karte herunterladen (PNG)",
  "regen_btn": "🔁 Bild neu zeichnen (30 Punkte)",
  "new_card": "🔄 Neue Karte",
  "coll_title": "📚 Deine Sammlung",
  "dojo_title": "🥋 Dojo",
  "your_card": "Deine Karte",
  "opponent": "Gegner",
  "fight_btn": "⚔️ Kämpfen!",
  "tourn4": "🏆 4er-Turnier",
  "tourn8": "🏆 8er-Turnier",
  "albo": "📊 Ehrentafel",
  "pub_sum": "🗂️ Wähle Karten für die Welt",
  "player_name": "Dein Spielername (Pflicht, mind. 3 Buchstaben)",
  "pub_btn": "📤 Ausgewählte Karten veröffentlichen",
  "duel_title": "⚡ Fordere einen Freund heraus",
  "duel_champ": "Dein Champion fürs Duell",
  "qr_show": "📱 Meinen QR zeigen",
  "qr_scan": "📷 Seinen scannen",
  "world_title": "🌍 Welt-Arena",
  "my_world": "🐱 Deine Karten in der Welt",
  "my_online": "Deine Karte für Online-Kämpfe",
  "find_btn": "🔄 Gegner weltweit suchen",
  "leader_title": "🏅 Weltrangliste",
  "leader_more": "⬇️ Mehr Plätze anzeigen",
  "market_title": "🔁 Markt",
  "trade_title": "🔄 Tausch",
  "trade_browse": "🔍 Karten zum Tauschen ansehen",
  "trader_ask": "💰 Den Händler um Rat fragen",
  "auc_title": "⚖️ Auktionen",
  "auc_create": "🔨 Karte versteigern",
  "auc_refresh": "🔄 Auktionen aktualisieren",
  "boss_title": "🤖 Arena-Bosse",
  "boss_chall": "Dein Herausforderer (veröffentlichte Karten)",
  "gym_title": "🏋️ Trainingsstudio",
  "gym_student": "Der Schüler des Tages",
  "gym_pantry": "🍽️ Vorrat — kaufen, dann im Spiel verdienen",
  "coach_ask": "🎓 Den Coach um Rat fragen",
  "mis_title": "📅 Heutige Missionen",
  "med_title": "🏅 Medaillensammlung",
  "reg_title": "📖 Die CatCards-Regeln",
  "opt_title": "⚙️ Einstellungen",
  "locked_title": "Anmeldung erforderlich",
  "locked_txt": "Punkte, Markt, Kämpfe und Training hängen an deinem Konto: melde dich an für Dojo, Welt, Markt, Bosse und Studio.",
  "login_google": "🔵 Mit Google anmelden",
  "login_hint": "Anmelden: Punkte, Markt und Kämpfe hängen an deinem Konto",
  "logout": "Abmelden",
  "close": "✖ Schließen",
  "skip_intro": "⏭️ Vorstellung überspringen",
  "bet_title": "🥊 Onkel Roccos Ecke",
  "bet_sub": "🎲 Wette",
  "bet_skip": "Keine Wette, auf in den Kampf!",
  "bet_back": "↩️ Zurück (Kampf abbrechen)",
  "points_lbl": "💰 Deine Punkte:",
  "dl_short": "⬇️ Herunterladen",
  "nick_btn": "✏️ Spitznamen ändern",
  "theme_btn": "▶️ Titelmusik abspielen",
  "retire_btn": "🚪 Aus der Welt zurückziehen",
  "frame_btn": "🎨 Goldrahmen (100 Punkte)",
  "del_btn": "🗑️ Löschen"
 },
 "stat": {},
 "rarity": {},
 "ann": {
  "red": "Aus der roten Ecke... {n}... „{k}\"!",
  "blue": "Aus der blauen Ecke... {n}... „{k}\"!"
 },
 "nicks": {
  "n01": "Der Dosen-Sokrates",
  "n02": "Baron Schiefzahn",
  "n03": "Der Glut-Koloss",
  "n04": "Der Asphalt-Gladiator",
  "n05": "Der Schlafende Weichkäse",
  "n06": "Der Plüsch-Monolith",
  "n07": "Der Zen-Leckermeister",
  "n08": "Der Unerschütterliche Zen",
  "n09": "Die Unbewegliche Weiche Festung",
  "n10": "Das Hinterm-Sofa-Radar",
  "n11": "Das Unheil-Radar",
  "n12": "Seine Hypnotische Weichheit",
  "n13": "Der Schnurr-Veteran",
  "n14": "Der Traurige Katzenhypnotiseur",
  "n15": "Der Seiden-Panzer",
  "n16": "Der Feurige Auspuff",
  "n17": "Der Hypnotische Wattebausch",
  "n18": "Die Ingwer-Kralle",
  "n19": "Der Tisch-Zeppelin",
  "n20": "Die Fell-Bastion",
  "n21": "Die Stahlwange",
  "n22": "Das Sofagespenst",
  "n23": "Die Wut aus der Abstellkammer",
  "n24": "Der Fell-Tornado",
  "n25": "Der Schatten der Speisekammer",
  "n26": "Der Fensterbrett-Ninja",
  "n27": "Die Rote Lawine",
  "n28": "Der Gardinen-Killer",
  "n29": "Der Schrecken der Wollknäuel",
  "n30": "Die Faule Lokomotive",
  "n31": "Der Heizkörper-Philosoph",
  "n32": "Der Orkan in Pantoffeln",
  "n33": "Der Wohnzimmer-Gepard",
  "n34": "Die Kühlschrank-Sphinx",
  "n35": "Der Verschmitzte Blitz",
  "n36": "Das Killer-Kissen",
  "n37": "Die Balkon-Bestie",
  "n38": "General Kratzer",
  "n39": "Der Mitternachts-Akrobat",
  "n40": "Der Sultan des Nickerchens",
  "n41": "Der Teppich-Tiger",
  "n42": "Das Treppengespenst",
  "n43": "Der Sofa-Zerstörer",
  "n44": "Der Treppenabsatz-Panther",
  "n45": "Der Baron der Häppchen",
  "n46": "Der Kaiser des Körbchens",
  "n47": "Der Frischfisch-Pirat",
  "n48": "Der Plüsch-Blitz",
  "n49": "Der Trockenfutter-Champion",
  "n50": "Der Dachboden-Stratege",
  "n51": "Das Pantoffel-Monster",
  "n52": "Die Bekrallte Herzogin",
  "n53": "Der Samt-Wikinger",
  "n54": "Das Schnurrbart-Rätsel",
  "n55": "Der Stille Wirbelsturm",
  "n56": "Die Pfote des Schicksals",
  "n57": "Der Karton-König",
  "n58": "Der Dauerhinterhalt",
  "n59": "Der Weiche Meteorit",
  "n60": "Die Hof-Legende",
  "n61": "Der Napf-Wächter",
  "n62": "Das Auge der Nacht",
  "n63": "Der Zerzauste Samurai",
  "n64": "Die Dreifarbige Furie",
  "n65": "Der Professor der Hinterhalte",
  "n66": "Der Admiral der Dächer",
  "n67": "Die Dampfwalze",
  "n68": "Die Elegante Plage",
  "n69": "Der Schläfrige Vulkan",
  "n70": "Die Samtkralle",
  "n71": "Der Küchen-Bandit",
  "n72": "Der Kühlschrank-Wachposten",
  "n73": "Der Kissen-Drache",
  "n74": "Das Echo des Miauens",
  "n75": "Der Meister des Schnurrens",
  "n76": "Der Taschensturm",
  "n77": "Der Sanfte Riese",
  "n78": "Der Letzte Streuner",
  "n79": "Der Eidechsen-Jäger",
  "n80": "Das Neunte Leben"
 },
 "descrs": {
  "d01": "Schläft 20 Stunden am Tag und trainiert die anderen 4, besser zu schlafen.",
  "d02": "Hat noch nie einen Kampf gegen eine Socke verloren.",
  "d03": "Glaubt, der Kühlschrank schulde ihm eine Erklärung.",
  "d04": "Meister darin, genau den Platz zu besetzen, wo du sitzen wolltest.",
  "d05": "Hat drei Vasen umgeworfen. Alle waren schuldig.",
  "d06": "Spricht drei Sprachen: Schnurren, Miau und Verachtung.",
  "d07": "Rennt um 4 Uhr morgens aus Gründen, die wir nie erfahren werden.",
  "d08": "Ein geborener Krieger, solange das Sofa keine zwei Meter entfernt ist.",
  "d09": "Sein Napf ist halb leer. Immer. Auch wenn er voll ist.",
  "d10": "Starrt die Wand an, weil die Wand angefangen hat.",
  "d11": "Ehemaliger Streuner, jetzt Führungskraft im Nickerchen-Wesen.",
  "d12": "Schnurrt wie ein Traktor und kratzt wie ein Rasiermesser.",
  "d13": "Der Tierarzt sieht ihn noch in seinen Albträumen.",
  "d14": "Jagt keine Mäuse: verschickt Räumungsbescheide.",
  "d15": "Kann drei Arten von Türen öffnen und tut so, als ob nicht.",
  "d16": "Der Karton ist mehr wert als das Geschenk. Immer.",
  "d17": "Hat einen Doktortitel in vorwurfsvollen Blicken.",
  "d18": "Bekämpft das Verbrechen. Das Verbrechen ist der Staubsauger.",
  "d19": "Jeder Stuhl im Haus gehört ihm. Auch deiner.",
  "d20": "Trainiert an den Gardinen, wenn niemand hinsieht.",
  "d21": "Lieblingshobby: Dinge elegant vom Tisch werfen.",
  "d22": "Miaut in c-Moll, wenn der Napf leer ist.",
  "d23": "Niemand sieht ihn kommen. Nur mit dem Abendessen verschwinden.",
  "d24": "Wiegt genau so viel, wie nötig ist, um deine Beine festzunageln.",
  "d25": "Die Eidechsen der Nachbarschaft haben ein Kopfgeld auf ihn ausgesetzt.",
  "d26": "Schläft in Positionen, die Physik und Verstand trotzen.",
  "d27": "Hat den Laserpointer durchschaut. Tut aus Mitleid so, als ob nicht.",
  "d28": "Eine Kreuzung aus Kissen und Bärenfalle.",
  "d29": "Überwacht die Nachbarschaft vom Fenster aus wie ein Staatsoberhaupt.",
  "d30": "Sein Schnurren heilt Stress. Seine Krallen verursachen ihn.",
  "d31": "Frisst wie ein Wolf, schläft wie ein Stein, herrscht wie ein König.",
  "d32": "Die einzige Katze, die je eine Diskussion mit einer Gurke gewonnen hat.",
  "d33": "Ist beleidigt, wenn du ihn ansiehst. Und wenn nicht, auch.",
  "d34": "Hat drei Geheimverstecke. Das beste: mitten im Flur.",
  "d35": "Fiel als Kätzchen in eine Schüssel Sahne. Hat sich nie davon erholt.",
  "d36": "Lehrt Nachbarskatzen Yoga. Erste Lektion: alle ignorieren.",
  "d37": "Der Postbote hat um Versetzung gebeten.",
  "d38": "Sammelt Haargummis. Niemand weiß, wo er sie versteckt.",
  "d39": "Bei Gewitter beschützt er das Haus. Von unterm Bett aus.",
  "d40": "Sein Blick hat zwei Hunde und einen Klempner vertrieben.",
  "d41": "Lebt für drei Dinge: fressen, schlafen und dich verurteilen.",
  "d42": "Sah einmal eine Maus. Beide erzählen noch heute davon.",
  "d43": "Höchst elegant, bis er vom Fensterbrett fällt.",
  "d44": "Hat eine Menschenfamilie adoptiert. Die Erziehung läuft gut.",
  "d45": "Er springt nicht auf den Tisch. Der Tisch senkt sich zu ihm herab.",
  "d46": "Weiß genau, wann du die Thunfischdose öffnest. Auch einen Block entfernt.",
  "d47": "Das Wollknäuel war schon so, als er ankam.",
  "d48": "Halb Katze, halb 5-Uhr-Alarmsirene.",
  "d49": "Kämpft mit Ehre, siegt mit Stil, schläft ohne Scham.",
  "d50": "Das Letzte, was Teppiche vor ihrem Ende sehen."
 }
};
