(window.LANG_DB=window.LANG_DB||{})["en"] = {
  "ui": {
    "tagline": "Snap your cat and turn it into a collectible card",
    "tab_crea": "📸 Create",
    "tab_carte": "📚 Cards",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 World",
    "tab_mercato": "🔁 Market",
    "tab_boss": "🤖 Bosses",
    "tab_pal": "🏋️ Gym",
    "tab_med": "🏅 Medals",
    "tab_reg": "📖 Rules",
    "drop_title": "Tap to take or upload a photo",
    "drop_sub": "JPG or PNG — best if the cat is clearly visible",
    "cat_name": "Cat's name (optional)",
    "gen_btn": "✨ Create the card",
    "dl_card": "⬇️ Download the card (PNG)",
    "regen_btn": "🔁 Redraw the art (30 points)",
    "new_card": "🔄 New card",
    "coll_title": "📚 Your collection",
    "dojo_title": "🥋 Dojo",
    "your_card": "Your card",
    "opponent": "Opponent",
    "fight_btn": "⚔️ Fight!",
    "tourn4": "🏆 4-cat tourney",
    "tourn8": "🏆 8-cat tourney",
    "albo": "📊 Hall of fame",
    "pub_sum": "🗂️ Choose which cards to publish to the World",
    "player_name": "Your player name (required, min 3 letters)",
    "pub_btn": "📤 Publish selected cards",
    "duel_title": "⚡ Challenge a friend",
    "duel_champ": "Your champion for the duel",
    "qr_show": "📱 Show my QR",
    "qr_scan": "📷 Scan theirs",
    "world_title": "🌍 World Arena",
    "my_world": "🐱 Your cards in the world",
    "my_online": "Your card for online matches",
    "find_btn": "🔄 Find challengers worldwide",
    "leader_title": "🏅 World ranking",
    "leader_more": "⬇️ Show more ranks",
    "market_title": "🔁 Market",
    "trade_title": "🔄 Trade (barter)",
    "trade_browse": "🔍 Browse cards to trade",
    "trader_ask": "💰 Ask the Merchant for advice",
    "auc_title": "⚖️ Auctions",
    "auc_create": "🔨 Put a card up for auction",
    "auc_refresh": "🔄 Refresh auctions",
    "boss_title": "🤖 Arena Bosses",
    "boss_chall": "Your challenger (published cards)",
    "gym_title": "🏋️ Gym",
    "gym_student": "Today's student",
    "gym_pantry": "🍽️ Pantry — buy, then earn it in the minigame",
    "coach_ask": "🎓 Ask the Coach for advice",
    "mis_title": "📅 Today's missions",
    "med_title": "🏅 Medal collection",
    "reg_title": "📖 CatCards rules",
    "opt_title": "⚙️ Options",
    "locked_title": "Sign-in required",
    "locked_txt": "Points, Market, matches and training live on your account: sign in to use Dojo, World, Market, Bosses and Gym.",
    "login_google": "🔵 Sign in with Google",
    "login_hint": "Sign in: points, Market and matches live on your account",
    "logout": "Sign out",
    "close": "✖ Close",
    "skip_intro": "⏭️ Skip the intro",
    "bet_title": "🥊 Uncle Rocco's corner",
    "bet_sub": "🎲 Betting",
    "bet_skip": "No bet, on with the match!",
    "bet_back": "↩️ Go back (cancel the match)",
    "points_lbl": "💰 Your points:",
    "dl_short": "⬇️ Download",
    "nick_btn": "✏️ Change nickname",
    "theme_btn": "▶️ Play theme song",
    "retire_btn": "🚪 Retire from the world",
    "frame_btn": "🎨 Golden Frame (100 points)",
    "del_btn": "🗑️ Delete"
  },
  "stat": {},
  "rarity": {},
  "ann": {
    "red": "From the red corner... {n}... \"{k}\"!",
    "blue": "From the blue corner... {n}... \"{k}\"!"
  },
  "nicks": {
    "n01": "The Tin-Can Socrates",
    "n02": "Baron Crookfang",
    "n03": "The Ember Colossus",
    "n04": "The Asphalt Gladiator",
    "n05": "The Sleeping Softcheese",
    "n06": "The Fleece Monolith",
    "n07": "The Zen Master Licker",
    "n08": "The Unshakable Zen",
    "n09": "The Immovable Soft Fortress",
    "n10": "The Beyond-the-Couch Radar",
    "n11": "The Mischief Radar",
    "n12": "His Hypnotic Softness",
    "n13": "The Purring Veteran",
    "n14": "The Sad Feline Hypnotist",
    "n15": "The Silk Panzer",
    "n16": "The Flaming Muffler",
    "n17": "The Hypnotic Puffball",
    "n18": "The Ginger Claw",
    "n19": "The Centerpiece Blimp",
    "n20": "The Bastion of Fur",
    "n21": "The Steel Cheek",
    "n22": "The Couch Phantom",
    "n23": "The Understairs Fury",
    "n24": "The Fur Tornado",
    "n25": "The Pantry Shadow",
    "n26": "The Windowsill Ninja",
    "n27": "The Tawny Avalanche",
    "n28": "The Curtain Assassin",
    "n29": "The Terror of Yarn Balls",
    "n30": "The Lazy Locomotive",
    "n31": "The Radiator Philosopher",
    "n32": "The Hurricane in Slippers",
    "n33": "The Living-Room Cheetah",
    "n34": "The Refrigerator Sphinx",
    "n35": "The Sly Lightning",
    "n36": "The Killer Pillow",
    "n37": "The Balcony Beast",
    "n38": "General Scratch",
    "n39": "The Midnight Acrobat",
    "n40": "The Sultan of Naps",
    "n41": "The Carpet Tiger",
    "n42": "The Staircase Ghost",
    "n43": "The Couch Destroyer",
    "n44": "The Landing Panther",
    "n45": "The Baron of Morsels",
    "n46": "The Emperor of the Basket",
    "n47": "The Fresh-Fish Pirate",
    "n48": "The Plush Thunderbolt",
    "n49": "The Kibble Champion",
    "n50": "The Attic Strategist",
    "n51": "The Slipper Monster",
    "n52": "The Clawed Duchess",
    "n53": "The Velvet Viking",
    "n54": "The Whiskered Enigma",
    "n55": "The Silent Cyclone",
    "n56": "The Paw of Destiny",
    "n57": "The Cardboard King",
    "n58": "The Permanent Ambush",
    "n59": "The Soft Meteorite",
    "n60": "The Courtyard Legend",
    "n61": "The Bowl Guardian",
    "n62": "The Eye of the Night",
    "n63": "The Scruffy Samurai",
    "n64": "The Tricolor Fury",
    "n65": "The Professor of Ambushes",
    "n66": "The Admiral of the Rooftops",
    "n67": "The Steamroller",
    "n68": "The Elegant Pest",
    "n69": "The Sleepy Volcano",
    "n70": "The Velvet Claw",
    "n71": "The Kitchen Bandit",
    "n72": "The Fridge Sentinel",
    "n73": "The Cushion Dragon",
    "n74": "The Echo of the Meow",
    "n75": "The Master of Purrs",
    "n76": "The Pocket Tempest",
    "n77": "The Gentle Giant",
    "n78": "The Last Stray",
    "n79": "The Lizard Hunter",
    "n80": "The Ninth Life"
  },
  "descrs": {
    "d01": "Sleeps 20 hours a day and spends the other 4 training to sleep better.",
    "d02": "Has never lost a battle against a sock.",
    "d03": "Believes the refrigerator owes him an explanation.",
    "d04": "Master of the art of occupying exactly where you wanted to sit.",
    "d05": "Knocked over three vases. All of them guilty.",
    "d06": "Speaks three languages: purr, meow and contempt.",
    "d07": "Runs at 4 a.m. for reasons beyond our understanding.",
    "d08": "A born warrior, as long as the couch is within two meters.",
    "d09": "His bowl is half empty. Always. Even when full.",
    "d10": "Stares at the wall because the wall started it.",
    "d11": "Former stray, now a senior executive of napping.",
    "d12": "Purrs like a tractor and scratches like a razor.",
    "d13": "The vet still remembers him in his nightmares.",
    "d14": "Doesn't chase mice: serves eviction notices.",
    "d15": "Can open three kinds of doors and pretends he can't.",
    "d16": "The box is worth more than the gift. Always.",
    "d17": "Holds a PhD in judgmental stares.",
    "d18": "Fights crime. The crime is the vacuum cleaner.",
    "d19": "Every chair in the house is his. Including yours.",
    "d20": "Trains on the curtains when nobody's watching.",
    "d21": "Favorite hobby: elegantly knocking things off tables.",
    "d22": "Meows in C minor when the bowl is empty.",
    "d23": "No one ever sees him coming. Only leaving with dinner.",
    "d24": "Weighs exactly enough to pin your legs down.",
    "d25": "The neighborhood lizards have put a bounty on him.",
    "d26": "Sleeps in positions that defy physics and common sense.",
    "d27": "Figured out the laser pointer. Pretends otherwise out of pity.",
    "d28": "A cross between a pillow and a bear trap.",
    "d29": "Surveys the neighborhood from the window like a head of state.",
    "d30": "His purrs cure stress. His claws cause it.",
    "d31": "Eats like a wolf, sleeps like a rock, reigns like a king.",
    "d32": "The only cat who ever won an argument with a cucumber.",
    "d33": "Gets offended if you look at him. Gets offended if you don't.",
    "d34": "Has three secret hideouts. The best one: the middle of the hallway.",
    "d35": "Fell into a bowl of cream as a kitten. Never recovered.",
    "d36": "Teaches yoga to neighborhood cats. Lesson one: ignore everyone.",
    "d37": "The mailman requested a transfer.",
    "d38": "Collects hair ties. Nobody knows where he hides them.",
    "d39": "When a storm hits, he protects the house. From under the bed.",
    "d40": "His stare has scared off two dogs and a plumber.",
    "d41": "Lives for three things: eating, sleeping and judging you.",
    "d42": "Once saw a mouse. They both still talk about it.",
    "d43": "Extremely elegant until he falls off the windowsill.",
    "d44": "Adopted a family of humans. Training them well.",
    "d45": "He doesn't climb on the table. The table lowers itself to him.",
    "d46": "Knows exactly when you open the tuna. Even from a block away.",
    "d47": "The yarn ball was already like that when he got there.",
    "d48": "Half cat, half 5 a.m. alarm siren.",
    "d49": "Fights with honor, wins with style, sleeps without shame.",
    "d50": "The last thing carpets see before the end."
  },
  "battle": {
    "skip": "⏭️ Intro skipped: straight to the action!",
    "open": "🎤 LADIES AND GENTLEMEEEN… welcome to the CatCards Arena!",
    "red": "🔴 Red corner: {NAME}, «{nick}»! {rec}",
    "blue": "🔵 Blue corner: {NAME}, «{nick}»! {rec}",
    "debut": "Making an arena debut!",
    "theme": "🎵 {name}'s entrance theme plays…",
    "ding": "🔔 DING DING DING!",
    "first_fast": "⚡ {name} is faster and strikes first!",
    "first_surprise": "😼 {name} surprises everyone and goes first!",
    "round_end": "🔔 End of round {round}! The cats return to their corners to lick their fur…",
    "charmed_skip": "😍 {name} is charmed and loses the turn!",
    "chant": "🎺 From the stands: «{NAME}! {NAME}!»",
    "pu_yarn": "🧶 A ball of yarn rolls into the arena! {name} plays with it and recovers {hp} HP",
    "pu_catnip": "🌿 Catnip in the arena! {name} is buzzing: next hit DOUBLED (but a bit woozy…)",
    "pu_box": "📦 A cardboard box! {name} can't resist and climbs in: skips the turn but is UNTOUCHABLE!",
    "pu_fish": "🐟 A fresh fish flies into the arena! {name} darts with energy: +agility for 3 turns",
    "purr_heal": "💗 {name} purrs and recovers {hp} HP",
    "double_paw": "🐾 Double Paw Strike! {name} attacks again!",
    "box_dodge": "📦 {opp} is hidden in the box: {name}'s hit misses!",
    "dodge": "💨 {name} tries {move} but {opp} dodges!",
    "final_blow": "⏱️ Time slows down… FINAL BLOW!",
    "hit": "{icon} {name} uses {move}!{crit}{catnip}  −{dmg} HP",
    "crit_tag": " 💥 CRITICAL!",
    "catnip_tag": " 🌿 BOOSTED!",
    "dev1": "😱 Devastating hit!",
    "dev2": "🎙️ The crowd goes wild!",
    "dev3": "💢 What crushing power!",
    "on_fire": "🔥 {name} is ON FIRE! Three hits in a row!",
    "on_ropes": "🎙️ {opp} is on the ropes! The crowd holds its breath…",
    "clever": "✨ Clever move! {opp} is confused and will lose a turn!",
    "nine_lives": "🐈 {opp} uses one of its Nine Lives and stays up with 1 HP!",
    "charm_hit": "✨ {opp} is charmed by {name}'s charm!",
    "replay": "📹 REPLAY of the final blow…",
    "winner": "🏆 {name} wins the fight!",
    "win_points": "💰 +10 points for the win!",
    "boss_points": "💰 +10 points: you tamed an Arena Boss!",
    "boss_noprize": "🎖️ Boss already beaten today: glory yes, prize tomorrow.",
    "boss_survives": "🤖 The Boss stays standing... today's attempt is gone: see you tomorrow (maybe with catnip 🌿).",
    "tourn_champ": "👑 {name} is the tournament CHAMPION!",
    "world_ok": "🌍 Result recorded in the World Arena!",
    "bet_win": "🎲 Right call! You bet {stake} on {name}: +{gain} points (total: {total})",
    "bet_lose": "🎲 Wrong call: −{stake} points (total: {total}). Better luck next time!",
    "stake": "🎁 At stake — win: {win} · loss: +{lose} XP",
    "stake_pts": "+{pt} points and +{xp} XP",
    "stake_nopts": "+{xp} XP (no points locally)",
    "boss_stake_note": " — points only on the first win of the day",
    "entry_catnip": "🌿 {name} enters the arena already loaded with catnip!"
  },
  "chars": {
    "rocco_warn": "Watch his {stat}: that's where he eats you alive.",
    "rocco_70": "Kid, you'll drop this one before the bell. Don't get cocky — finish it fast.",
    "rocco_55": "You're the favorite, but favorites who sleep hit the canvas. Strike first.",
    "rocco_50": "Fifty-fifty, kid: this goes to whoever's hungrier. If you've got 50 points, the catnip's worth every one.",
    "rocco_35": "I won't lie: he's bigger than you. Without catnip I wouldn't take this fight.",
    "rocco_lose": "Listen to old Rocco: this one breaks you. Back to the gym, gain a level, THEN we talk. If you must fight, at least take the catnip.",
    "baratto_great": "🤑 Steal of a deal! You get way more than you give — close it fast.",
    "baratto_good": "👍 Good deal: you come out ahead. The Merchant approves.",
    "baratto_even": "⚖️ Even trade: decide with your heart, not your wallet.",
    "baratto_bad": "😾 You lose a little... sure about this? The Merchant twitches his whiskers.",
    "baratto_terrible": "🙀 Terrible deal! You give far more than you get. Forget it.",
    "baratto_empty": "No cards to barter! Make some and come back: the bazaar's for deals, not charity.",
    "inc_100a": "A HUNDRED POINTS! Magnificent madness! 😼",
    "inc_100b": "A kingly bid! And who dares raise it now?",
    "inc_50a": "Fifty! The crowd is trembling, ladies and gentlemen!",
    "inc_50b": "Fine sum! The auction's heating up!",
    "inc_bata": "And another raise! They just won't stop!",
    "inc_batb": "A battle to the last point — what a show!",
    "inc_starta": "First bid on the block! Who gives more?",
    "inc_startb": "Here we go! Sold to whoever won't quit!",
    "baffo_open": [
      "Meow, recruit! ",
      "Listen to old Baffo: ",
      "Spit out that kibble and listen: ",
      "In my day, no soft cushions. ",
      "Whiskers straight, ears up: "
    ],
    "baffo_empty": "The gym is empty! Bring me a student from the 📸 Create tab.",
    "baffo_indiff_afford": "{name}'s weak spot is {stat} ({val}): train it with the {combo} combo (60 points) — you can afford it.",
    "baffo_indiff_save": "{name}'s weak spot is {stat} ({val}), but it only trains with the {combo} combo (60 points): you're {miss} short — save up.",
    "baffo_indiff_alt": " Or meanwhile boost {stat2} ({val2}) with {food} (25 points).",
    "baffo_weak": "{name}'s weakest stat is {stat} ({val}): give it {food}.",
    "baffo_combo": "You have {pts} points: the {combo} combo ({tgt}) grows two things in a single rest — pricey but handy if you're in a hurry.",
    "baffo_record_bad": "With {w} wins and {l} losses, he needs grit, not cuddles.",
    "baffo_unbeaten": "He's unbeaten: just don't let him get a big head.",
    "baffo_margin": "Training margin used up: only World wins unlock more progress.",
    "baffo_broke": "And the coffers are dry ({pts} points): win a few World bets.",
    "baffo_fit": "{name} is in top shape. Send him to fight — the bench softens the muscles.",
    "felini_open": [
      "Listen to the Manager: ",
      "I smell a deal: ",
      "The ring is a chessboard: ",
      "The numbers talk, kid: "
    ],
    "felini_checking": "One moment, let me check the records…",
    "felini_noauth": "Sign in first, kid: business needs a name on the contract.",
    "felini_nocard": "You haven’t got a champion in the ring. Publish a card and let’s talk business.",
    "felini_resting": "😴 {name} is recovering: come back when it’s ready again and we’ll talk strategy.",
    "felini_norank": "Your champion isn’t in the rankings: republish it and come back to me.",
    "felini_loss_streak": "{name} has lost {n} in a row (🧊): pull it off the circuit for a while, take it to the Coach, and bring it back hungry.",
    "felini_champ": "{name} is the CHAMPION 👑: defend the crown{chaser}.",
    "felini_chaser": ", and watch out for {name} (#2, {elo} pts) who’s champing at the bit",
    "felini_target": "the right next bout for {name} (#{rk}) is {tname} owned by {owner} (#{trk}, {elo} pts): {verdict}",
    "felini_v_risky": "risky, but beat it and you make a killing in the standings.",
    "felini_v_beatable": "on paper it’s beatable: a manager’s win.",
    "felini_v_even": "an even bout, the kind the crowd loves.",
    "felini_prob_low": "But let’s be clear: Uncle Rocco puts your win odds at just {p}%. I’d wait — gym, one more level, THEN we sign the contract.",
    "felini_prob_mid": "The odds say {p}%: an open match, nerves will decide it (and maybe some catnip 🌿).",
    "felini_prob_high": "Uncle Rocco reckons a {p}% win chance: within reach. Go and close the match.",
    "felini_belt": "And remember: that one holds the BELT 👑 — the ranking means nothing, beat it and YOU’re the champion.",
    "felini_hot": "Careful though: it’s a tough opponent, riding a streak of {n} wins 🔥.",
    "felini_cold": "And I’ll tell you: it’s in a deep slump (🧊 {n} losses in a row) — the perfect moment to strike.",
    "felini_catnip_need": "My ringside advice: invest 50 points in catnip 🌿 before the match — against one like that you need the turbo.",
    "felini_catnip_broke": "You’d want catnip 🌿, but the coffers are crying ({pts} points): either find points, or pick a softer target.",
    "felini_catnip_opt": "Catnip 🌿? Optional: an even match, nerves will decide.",
    "felini_catnip_no": "No catnip: it’ll manage on its own paws, save your points.",
    "felini_notarget": "no target from other owners above you right now (or they’re all resting): defend your position, or check back later.",
    "felini_margin": "And it still has {n} points of gym margin left: a good meal before the match never hurt anyone.",
    "trader_open": [
      "Psst, friend: ",
      "Deals, deals! ",
      "The Merchant knows all: ",
      "Between us who know our stuff: "
    ],
    "trader_best": "hold on tight to {name}, that one’s worth gold: don’t give it up for pennies.",
    "trader_worst": "if you really must trade something, start with {name} — you’ve got better in hand.",
    "trader_commons": "You’ve got a pile of {rar} cards ({n}): trade a couple for something rarer, trust me.",
    "trader_gem": "And watch out: there’s a {rar} from {owner} on the shelf — if you’ve got a good spare, try the trade before someone else grabs it.",
    "trader_browse": "Hit «Browse cards to trade» and show me what’s around: I’ll tell you if there’s a deal."
  }
};
