(window.LANG_DB=window.LANG_DB||{})["de"] = {
  "ui": {
    "tagline": "Fotografiere deine Katze und mach sie zur Sammelkarte",
    "tab_crea": "📸 Neu",
    "tab_carte": "📚 Karten",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Welt",
    "tab_mercato": "🔁 Markt",
    "tab_boss": "🤖 Bosse",
    "tab_pal": "🏋️ Studio",
    "tab_med": "🏅 Medaillen",
    "tab_reg": "📖 Regeln",
    "drop_title": "Tippe, um ein Foto zu machen oder hochzuladen",
    "drop_sub": "JPG oder PNG — die Katze sollte gut sichtbar sein",
    "cat_name": "Name der Katze (optional)",
    "gen_btn": "✨ Karte erstellen",
    "dl_card": "⬇️ Karte herunterladen (PNG)",
    "regen_btn": "🔁 Bild neu zeichnen (30 Punkte)",
    "new_card": "🔄 Neue Karte",
    "coll_title": "📚 Deine Sammlung",
    "dojo_title": "🥋 Dojo",
    "your_card": "Deine Karte",
    "opponent": "Gegner",
    "fight_btn": "⚔️ Kämpfen!",
    "tourn4": "🏆 4er-Turnier",
    "tourn8": "🏆 8er-Turnier",
    "albo": "📊 Ehrentafel",
    "pub_sum": "🗂️ Wähle Karten für die Welt",
    "player_name": "Dein Spielername (Pflicht, mind. 3 Buchstaben)",
    "pub_btn": "📤 Ausgewählte Karten veröffentlichen",
    "duel_title": "⚡ Fordere einen Freund heraus",
    "duel_champ": "Dein Champion fürs Duell",
    "qr_show": "📱 Meinen QR zeigen",
    "qr_scan": "📷 Seinen scannen",
    "world_title": "🌍 Welt-Arena",
    "my_world": "🐱 Deine Karten in der Welt",
    "my_online": "Deine Karte für Online-Kämpfe",
    "find_btn": "🔄 Gegner weltweit suchen",
    "leader_title": "🏅 Weltrangliste",
    "leader_more": "⬇️ Mehr Plätze anzeigen",
    "market_title": "🔁 Markt",
    "trade_title": "🔄 Tausch",
    "trade_browse": "🔍 Karten zum Tauschen ansehen",
    "trader_ask": "💰 Den Händler um Rat fragen",
    "auc_title": "⚖️ Auktionen",
    "auc_create": "🔨 Karte versteigern",
    "auc_refresh": "🔄 Auktionen aktualisieren",
    "boss_title": "🤖 Arena-Bosse",
    "boss_chall": "Dein Herausforderer (veröffentlichte Karten)",
    "gym_title": "🏋️ Trainingsstudio",
    "gym_student": "Der Schüler des Tages",
    "gym_pantry": "🍽️ Vorrat — kaufen, dann im Spiel verdienen",
    "coach_ask": "🎓 Den Coach um Rat fragen",
    "mis_title": "📅 Heutige Missionen",
    "med_title": "🏅 Medaillensammlung",
    "reg_title": "📖 Die CatCards-Regeln",
    "opt_title": "⚙️ Einstellungen",
    "locked_title": "Anmeldung erforderlich",
    "locked_txt": "Punkte, Markt, Kämpfe und Training hängen an deinem Konto: melde dich an für Dojo, Welt, Markt, Bosse und Studio.",
    "login_google": "🔵 Mit Google anmelden",
    "login_hint": "Anmelden: Punkte, Markt und Kämpfe hängen an deinem Konto",
    "logout": "Abmelden",
    "close": "✖ Schließen",
    "skip_intro": "⏭️ Vorstellung überspringen",
    "bet_title": "🥊 Onkel Roccos Ecke",
    "bet_sub": "🎲 Wette",
    "bet_skip": "Keine Wette, auf in den Kampf!",
    "bet_back": "↩️ Zurück (Kampf abbrechen)",
    "points_lbl": "💰 Deine Punkte:",
    "dl_short": "⬇️ Herunterladen",
    "nick_btn": "✏️ Spitznamen ändern",
    "theme_btn": "▶️ Titelmusik abspielen",
    "retire_btn": "🚪 Aus der Welt zurückziehen",
    "frame_btn": "🎨 Goldrahmen (100 Punkte)",
    "del_btn": "🗑️ Löschen",
    "coach_greet": "Miau, Rekrut. Wähle einen Schützling und legen wir los.",
    "gym_combo": "🌟 Premium-Combo — zwei Werte, eine einzige Ruhe",
    "bet_choose": "Wähle den Einsatz und auf wen du setzt. Liegst du falsch, verlierst du den Einsatz.",
    "bet_insufficient": "Nicht genug Punkte zum Wetten (mindestens 10).",
    "tab_sent": "🗺️ Pfad",
    "opt_ai_sum": "🤖 KI-Einstellungen",
    "opt_key_label": "Gemini-API-Schlüssel",
    "opt_test_key": "🧪 Schlüssel testen",
    "opt_backup_label": "Sammlungs-Backup",
    "opt_export": "💾 Backup exportieren",
    "opt_import": "📂 Backup importieren",
    "opt_gift_label": "🎁 Geschenkcode",
    "opt_redeem": "Punkte einlösen",
    "opt_av_label": "Audio und Präsentationen",
    "snd_on": "🔊 Ton: AN",
    "snd_off": "🔇 Ton: AUS",
    "pres_on": "🎬 Präsentationen: AN",
    "pres_skip": "⏭️ Präsentationen: ÜBERSPRUNGEN",
    "bt_bracket": "📋 Turnierbaum",
    "qr_desc1": "Live-Duell, Handy gegen Handy: zählt für Punkte, Medaillen und Wetten wie ein Welt-Duell.",
    "qr_desc2": "Einer zeigt den QR, der andere scannt ihn: das Duell läuft auf dem Handy des Scanners.",
    "coll_one": "1 gespeicherte Karte",
    "coll_many": "{n} gespeicherte Karten",
    "coll_none": "Noch keine Karten: erstelle eine im Reiter 📸 Erstellen, oder importiere ein Backup aus ⚙️ Optionen.",
    "xp_line": "📈 Level {lvl} — {inLvl}/100 XP (≈ {w} Weltsiege bis Lv.{next})",
    "opt_ai_desc": "Ohne API-Schlüssel nutze ich einen eingebauten, kostenlosen Cartoon-Filter. Mit einem <strong>Google-Gemini</strong>-Schlüssel wird der Cartoon von der KI erzeugt (viel bessere Qualität). Erstelle ihn gratis auf <strong>aistudio.google.com</strong> → «Get API key».",
    "tab_award": "🏆 Awards",
    "publish_btn": "🌍 In der Welt veröffentlichen",
    "pub_moved": "Zum Veröffentlichen/Zurückziehen einer Karte tippe sie im Reiter 📚 Karten an.",
    "ask_name_title": "Wie heißt du?",
    "ask_name_desc": "Der Name, den Herausforderer sehen (min. 3 Zeichen).",
    "ask_name_ok": "Speichern & veröffentlichen",
    "ask_name_cancel": "Abbrechen",
    "hub_fight": "Kämpfen",
    "hub_cards": "Karten",
    "hub_glory": "Ruhm",
    "hub_social": "Sozial",
    "tab_opz": "⚙️ Optionen",
    "tab_gang": "🛡️ Gang"
  },
  "stat": {
    "Forza": "Stärke",
    "Intelligenza": "Intelligenz",
    "Destrezza": "Geschick",
    "Velocità": "Geschwindigkeit",
    "Fascino": "Charme",
    "Indifferenza": "Gleichgültigkeit"
  },
  "rarity": {
    "Comune": "Gewöhnlich",
    "Rara": "Selten",
    "Epica": "Episch",
    "Leggendaria": "Legendär"
  },
  "ann": {
    "red": "Aus der roten Ecke... {n}... „{k}\"!",
    "blue": "Aus der blauen Ecke... {n}... „{k}\"!"
  },
  "nicks": {
    "n01": "Der Dosen-Sokrates",
    "n02": "Baron Schiefzahn",
    "n03": "Der Glut-Koloss",
    "n04": "Der Asphalt-Gladiator",
    "n05": "Der Schlafende Weichkäse",
    "n06": "Der Plüsch-Monolith",
    "n07": "Der Zen-Leckermeister",
    "n08": "Der Unerschütterliche Zen",
    "n09": "Die Unbewegliche Weiche Festung",
    "n10": "Das Hinterm-Sofa-Radar",
    "n11": "Das Unheil-Radar",
    "n12": "Seine Hypnotische Weichheit",
    "n13": "Der Schnurr-Veteran",
    "n14": "Der Traurige Katzenhypnotiseur",
    "n15": "Der Seiden-Panzer",
    "n16": "Der Feurige Auspuff",
    "n17": "Der Hypnotische Wattebausch",
    "n18": "Die Ingwer-Kralle",
    "n19": "Der Tisch-Zeppelin",
    "n20": "Die Fell-Bastion",
    "n21": "Die Stahlwange",
    "n22": "Das Sofagespenst",
    "n23": "Die Wut aus der Abstellkammer",
    "n24": "Der Fell-Tornado",
    "n25": "Der Schatten der Speisekammer",
    "n26": "Der Fensterbrett-Ninja",
    "n27": "Die Rote Lawine",
    "n28": "Der Gardinen-Killer",
    "n29": "Der Schrecken der Wollknäuel",
    "n30": "Die Faule Lokomotive",
    "n31": "Der Heizkörper-Philosoph",
    "n32": "Der Orkan in Pantoffeln",
    "n33": "Der Wohnzimmer-Gepard",
    "n34": "Die Kühlschrank-Sphinx",
    "n35": "Der Verschmitzte Blitz",
    "n36": "Das Killer-Kissen",
    "n37": "Die Balkon-Bestie",
    "n38": "General Kratzer",
    "n39": "Der Mitternachts-Akrobat",
    "n40": "Der Sultan des Nickerchens",
    "n41": "Der Teppich-Tiger",
    "n42": "Das Treppengespenst",
    "n43": "Der Sofa-Zerstörer",
    "n44": "Der Treppenabsatz-Panther",
    "n45": "Der Baron der Häppchen",
    "n46": "Der Kaiser des Körbchens",
    "n47": "Der Frischfisch-Pirat",
    "n48": "Der Plüsch-Blitz",
    "n49": "Der Trockenfutter-Champion",
    "n50": "Der Dachboden-Stratege",
    "n51": "Das Pantoffel-Monster",
    "n52": "Die Bekrallte Herzogin",
    "n53": "Der Samt-Wikinger",
    "n54": "Das Schnurrbart-Rätsel",
    "n55": "Der Stille Wirbelsturm",
    "n56": "Die Pfote des Schicksals",
    "n57": "Der Karton-König",
    "n58": "Der Dauerhinterhalt",
    "n59": "Der Weiche Meteorit",
    "n60": "Die Hof-Legende",
    "n61": "Der Napf-Wächter",
    "n62": "Das Auge der Nacht",
    "n63": "Der Zerzauste Samurai",
    "n64": "Die Dreifarbige Furie",
    "n65": "Der Professor der Hinterhalte",
    "n66": "Der Admiral der Dächer",
    "n67": "Die Dampfwalze",
    "n68": "Die Elegante Plage",
    "n69": "Der Schläfrige Vulkan",
    "n70": "Die Samtkralle",
    "n71": "Der Küchen-Bandit",
    "n72": "Der Kühlschrank-Wachposten",
    "n73": "Der Kissen-Drache",
    "n74": "Das Echo des Miauens",
    "n75": "Der Meister des Schnurrens",
    "n76": "Der Taschensturm",
    "n77": "Der Sanfte Riese",
    "n78": "Der Letzte Streuner",
    "n79": "Der Eidechsen-Jäger",
    "n80": "Das Neunte Leben"
  },
  "descrs": {
    "d01": "Schläft 20 Stunden am Tag und trainiert die anderen 4, besser zu schlafen.",
    "d02": "Hat noch nie einen Kampf gegen eine Socke verloren.",
    "d03": "Glaubt, der Kühlschrank schulde ihm eine Erklärung.",
    "d04": "Meister darin, genau den Platz zu besetzen, wo du sitzen wolltest.",
    "d05": "Hat drei Vasen umgeworfen. Alle waren schuldig.",
    "d06": "Spricht drei Sprachen: Schnurren, Miau und Verachtung.",
    "d07": "Rennt um 4 Uhr morgens aus Gründen, die wir nie erfahren werden.",
    "d08": "Ein geborener Krieger, solange das Sofa keine zwei Meter entfernt ist.",
    "d09": "Sein Napf ist halb leer. Immer. Auch wenn er voll ist.",
    "d10": "Starrt die Wand an, weil die Wand angefangen hat.",
    "d11": "Ehemaliger Streuner, jetzt Führungskraft im Nickerchen-Wesen.",
    "d12": "Schnurrt wie ein Traktor und kratzt wie ein Rasiermesser.",
    "d13": "Der Tierarzt sieht ihn noch in seinen Albträumen.",
    "d14": "Jagt keine Mäuse: verschickt Räumungsbescheide.",
    "d15": "Kann drei Arten von Türen öffnen und tut so, als ob nicht.",
    "d16": "Der Karton ist mehr wert als das Geschenk. Immer.",
    "d17": "Hat einen Doktortitel in vorwurfsvollen Blicken.",
    "d18": "Bekämpft das Verbrechen. Das Verbrechen ist der Staubsauger.",
    "d19": "Jeder Stuhl im Haus gehört ihm. Auch deiner.",
    "d20": "Trainiert an den Gardinen, wenn niemand hinsieht.",
    "d21": "Lieblingshobby: Dinge elegant vom Tisch werfen.",
    "d22": "Miaut in c-Moll, wenn der Napf leer ist.",
    "d23": "Niemand sieht ihn kommen. Nur mit dem Abendessen verschwinden.",
    "d24": "Wiegt genau so viel, wie nötig ist, um deine Beine festzunageln.",
    "d25": "Die Eidechsen der Nachbarschaft haben ein Kopfgeld auf ihn ausgesetzt.",
    "d26": "Schläft in Positionen, die Physik und Verstand trotzen.",
    "d27": "Hat den Laserpointer durchschaut. Tut aus Mitleid so, als ob nicht.",
    "d28": "Eine Kreuzung aus Kissen und Bärenfalle.",
    "d29": "Überwacht die Nachbarschaft vom Fenster aus wie ein Staatsoberhaupt.",
    "d30": "Sein Schnurren heilt Stress. Seine Krallen verursachen ihn.",
    "d31": "Frisst wie ein Wolf, schläft wie ein Stein, herrscht wie ein König.",
    "d32": "Die einzige Katze, die je eine Diskussion mit einer Gurke gewonnen hat.",
    "d33": "Ist beleidigt, wenn du ihn ansiehst. Und wenn nicht, auch.",
    "d34": "Hat drei Geheimverstecke. Das beste: mitten im Flur.",
    "d35": "Fiel als Kätzchen in eine Schüssel Sahne. Hat sich nie davon erholt.",
    "d36": "Lehrt Nachbarskatzen Yoga. Erste Lektion: alle ignorieren.",
    "d37": "Der Postbote hat um Versetzung gebeten.",
    "d38": "Sammelt Haargummis. Niemand weiß, wo er sie versteckt.",
    "d39": "Bei Gewitter beschützt er das Haus. Von unterm Bett aus.",
    "d40": "Sein Blick hat zwei Hunde und einen Klempner vertrieben.",
    "d41": "Lebt für drei Dinge: fressen, schlafen und dich verurteilen.",
    "d42": "Sah einmal eine Maus. Beide erzählen noch heute davon.",
    "d43": "Höchst elegant, bis er vom Fensterbrett fällt.",
    "d44": "Hat eine Menschenfamilie adoptiert. Die Erziehung läuft gut.",
    "d45": "Er springt nicht auf den Tisch. Der Tisch senkt sich zu ihm herab.",
    "d46": "Weiß genau, wann du die Thunfischdose öffnest. Auch einen Block entfernt.",
    "d47": "Das Wollknäuel war schon so, als er ankam.",
    "d48": "Halb Katze, halb 5-Uhr-Alarmsirene.",
    "d49": "Kämpft mit Ehre, siegt mit Stil, schläft ohne Scham.",
    "d50": "Das Letzte, was Teppiche vor ihrem Ende sehen."
  },
  "battle": {
    "skip": "⏭️ Vorstellung übersprungen: ab in den Kampf!",
    "open": "🎤 MEINE DAMEN UND HERREEEN… willkommen in der CatCards-Arena!",
    "red": "🔴 Rote Ecke: {NAME}, „{nick}\"! {rec}",
    "blue": "🔵 Blaue Ecke: {NAME}, „{nick}\"! {rec}",
    "debut": "Beim Arena-Debüt!",
    "theme": "🎵 {name}s Einzugsmelodie erklingt…",
    "ding": "🔔 DING DING DING!",
    "first_fast": "⚡ {name} ist schneller und schlägt zuerst zu!",
    "first_surprise": "😼 {name} überrascht alle und legt los!",
    "round_end": "🔔 Ende von Runde {round}! Die Katzen kehren in ihre Ecken zurück…",
    "charmed_skip": "😍 {name} ist verzaubert und verliert den Zug!",
    "chant": "🎺 Von den Rängen: „{NAME}! {NAME}!\"",
    "pu_yarn": "🧶 Ein Wollknäuel rollt herein! {name} spielt und heilt {hp} HP",
    "pu_catnip": "🌿 Katzenminze! {name} dreht auf: nächster Treffer VERDOPPELT (aber leicht benommen…)",
    "pu_box": "📦 Ein Karton! {name} kann nicht widerstehen: setzt aus, ist aber UNBERÜHRBAR!",
    "pu_fish": "🐟 Ein frischer Fisch fliegt herein! {name} sprüht vor Energie: +Agilität für 3 Züge",
    "purr_heal": "💗 {name} schnurrt und heilt {hp} HP",
    "double_paw": "🐾 Doppelter Pfotenschlag! {name} greift erneut an!",
    "box_dodge": "📦 {opp} versteckt sich im Karton: {name}s Treffer geht daneben!",
    "dodge": "💨 {name} versucht {move}, doch {opp} weicht aus!",
    "final_blow": "⏱️ Die Zeit verlangsamt sich… ENDSCHLAG!",
    "hit": "{icon} {name} setzt {move} ein!{crit}{catnip}  −{dmg} HP",
    "crit_tag": " 💥 KRITISCH!",
    "catnip_tag": " 🌿 VERSTÄRKT!",
    "dev1": "😱 Verheerender Treffer!",
    "dev2": "🎙️ Das Publikum rast!",
    "dev3": "💢 Was für eine Wucht!",
    "on_fire": "🔥 {name} ist HEISS! Drei Treffer in Folge!",
    "on_ropes": "🎙️ {opp} ist in den Seilen! Das Publikum hält den Atem an…",
    "clever": "✨ Cleverer Zug! {opp} ist verwirrt und verliert einen Zug!",
    "nine_lives": "🐈 {opp} nutzt eines seiner Neun Leben und bleibt mit 1 HP stehen!",
    "charm_hit": "✨ {opp} erliegt {name}s Charme!",
    "replay": "📹 WIEDERHOLUNG des Endschlags…",
    "winner": "🏆 {name} gewinnt den Kampf!",
    "win_points": "💰 +10 Punkte für den Sieg!",
    "boss_points": "💰 +10 Punkte: du hast einen Arena-Boss bezwungen!",
    "boss_noprize": "🎖️ Boss heute schon besiegt: Ruhm ja, Belohnung morgen.",
    "boss_survives": "🤖 Der Boss bleibt stehen... der heutige Versuch ist weg: bis morgen (vielleicht mit Katzenminze 🌿).",
    "tourn_champ": "👑 {name} ist der Turnier-CHAMPION!",
    "world_ok": "🌍 Ergebnis in der Welt-Arena gespeichert!",
    "bet_win": "🎲 Richtig getippt! Du hast {stake} auf {name} gesetzt: +{gain} Punkte (gesamt: {total})",
    "bet_lose": "🎲 Falsch getippt: −{stake} Punkte (gesamt: {total}). Nächstes Mal!",
    "stake": "🎁 Auf dem Spiel — Sieg: {win} · Niederlage: +{lose} XP",
    "stake_pts": "+{pt} Punkte und +{xp} XP",
    "stake_nopts": "+{xp} XP (keine Punkte lokal)",
    "boss_stake_note": " — Punkte nur beim ersten Sieg des Tages",
    "entry_catnip": "🌿 {name} betritt die Arena schon voll Katzenminze!"
  },
  "chars": {
    "rocco_warn": "Pass auf seine {stat} auf: da frisst er dich.",
    "rocco_70": "Junge, den legst du vor dem Gong um. Werd nicht übermütig — mach's schnell.",
    "rocco_55": "Du bist Favorit, aber Favoriten, die pennen, landen auf der Matte. Schlag zuerst zu.",
    "rocco_50": "Fifty-fifty, Junge: hier gewinnt der Hungrigere. Wenn du 50 Punkte hast, ist die Katzenminze jeden wert.",
    "rocco_35": "Ich lüg nicht: er ist größer als du. Ohne Katzenminze würde ich den Kampf lassen.",
    "rocco_lose": "Hör auf den alten Rocco: der bricht dich. Zurück ins Studio, ein Level hoch, DANN reden wir. Wenn's sein muss, wenigstens die Katzenminze.",
    "baratto_great": "🤑 Ein Schnäppchen! Du kriegst viel mehr, als du gibst — mach schnell.",
    "baratto_good": "👍 Guter Deal: du machst Plus. Der Händler nickt.",
    "baratto_even": "⚖️ Fairer Tausch: entscheide mit dem Herzen, nicht dem Geldbeutel.",
    "baratto_bad": "😾 Du verlierst etwas... sicher? Dem Händler zucken die Schnurrhaare.",
    "baratto_terrible": "🙀 Mieser Deal! Du gibst viel mehr, als du bekommst. Vergiss es.",
    "baratto_empty": "Keine Karten zum Tauschen! Mach welche und komm wieder: der Basar ist für Geschäfte, nicht für Almosen.",
    "inc_100a": "HUNDERT PUNKTE! Herrlicher Wahnsinn! 😼",
    "inc_100b": "Ein königliches Gebot! Und wer wagt jetzt mehr?",
    "inc_50a": "Fünfzig! Das Publikum zittert, meine Herrschaften!",
    "inc_50b": "Schöne Summe! Die Auktion wird heiß!",
    "inc_bata": "Und noch ein Gebot! Die hören nicht mehr auf!",
    "inc_batb": "Ein Kampf bis zum letzten Punkt — was für ein Spektakel!",
    "inc_starta": "Erstes Gebot am Pult! Wer bietet mehr?",
    "inc_startb": "Los geht's! Zugeschlagen, wer nicht aufgibt!",
    "baffo_open": [
      "Miau, Rekrut! ",
      "Hör auf den alten Baffo: ",
      "Spuck das Trockenfutter aus und hör zu: ",
      "Zu meiner Zeit gab es keine weichen Kissen. ",
      "Schnurrhaare gerade, Ohren gespitzt: "
    ],
    "baffo_empty": "Das Studio ist leer! Bring mir einen Schüler aus dem Tab 📸 Neu.",
    "baffo_indiff_afford": "{name}s Schwäche ist {stat} ({val}): trainiere sie mit dem Combo {combo} (60 Punkte) — kannst du dir leisten.",
    "baffo_indiff_save": "{name}s Schwäche ist {stat} ({val}), aber die trainiert nur mit dem Combo {combo} (60 Punkte): dir fehlen {miss} — spar sie an.",
    "baffo_indiff_alt": " Oder stärke inzwischen {stat2} ({val2}) mit {food} (25 Punkte).",
    "baffo_weak": "{name}s schwächster Wert ist {stat} ({val}): gib ihm {food}.",
    "baffo_combo": "Du hast {pts} Punkte: der Combo {combo} ({tgt}) steigert zwei Werte in einer Pause — teuer, aber praktisch, wenn's eilt.",
    "baffo_record_bad": "Mit {w} Siegen und {l} Niederlagen braucht er Biss, keine Streicheleinheiten.",
    "baffo_unbeaten": "Er ist ungeschlagen: pass auf, dass er nicht abhebt.",
    "baffo_margin": "Trainingsspielraum aufgebraucht: nur Siege in der Welt schalten mehr frei.",
    "baffo_broke": "Und die Kasse ist leer ({pts} Punkte): gewinn ein paar Welt-Wetten.",
    "baffo_fit": "{name} ist topfit. Lass ihn kämpfen — die Bank macht die Muskeln weich.",
    "felini_open": [
      "Hör auf den Manager: ",
      "Ich wittere ein Geschäft: ",
      "Der Ring ist ein Schachbrett: ",
      "Die Zahlen sprechen, Junge: "
    ],
    "felini_checking": "Einen Moment, ich sehe in den Unterlagen nach…",
    "felini_noauth": "Melde dich zuerst an, Junge: Geschäfte macht man mit einem Namen auf dem Vertrag.",
    "felini_nocard": "Du hast keinen veröffentlichten Champion. Veröffentliche eine Karte, dann reden wir übers Geschäft.",
    "felini_resting": "😴 {name} erholt sich gerade: komm zurück, wenn er wieder bereit ist, dann reden wir über Strategie.",
    "felini_norank": "Dein Champion taucht nicht im Ranking auf: veröffentliche ihn neu und komm wieder zu mir.",
    "felini_loss_streak": "{name} hat {n} in Folge verloren (🧊): nimm ihn eine Weile aus dem Verkehr, bring ihn zu dem Coach, und lass ihn hungrig zurückkommen.",
    "felini_champ": "{name} ist der CHAMPION 👑: verteidige die Krone{chaser}.",
    "felini_chaser": ", und pass auf {name} auf (#2, {elo} Pkt.), der schon scharrt",
    "felini_target": "der richtige nächste Kampf für {name} (#{rk}) ist {tname} von {owner} (#{trk}, {elo} Pkt.): {verdict}",
    "felini_v_risky": "riskant, aber schlägst du ihn, machst du im Ranking den großen Sprung.",
    "felini_v_beatable": "auf dem Papier schlagbar: ein Sieg des Managements.",
    "felini_v_even": "ein ausgeglichener Kampf, wie ihn das Publikum liebt.",
    "felini_prob_low": "Aber reden wir Klartext: Onkel Rocco schätzt deine Siegchance auf nur {p}%. Ich würde warten — Training, ein Level mehr, DANN unterschreiben wir den Vertrag.",
    "felini_prob_mid": "Die Wahrscheinlichkeit sagt {p}%: offener Kampf, die Nerven entscheiden (und vielleicht die Katzenminze 🌿).",
    "felini_prob_high": "Onkel Rocco schätzt {p}% Siegchance: machbar. Geh und mach den Kampf klar.",
    "felini_belt": "Und merk dir: der hat den GÜRTEL 👑 — das Ranking zählt nichts, schlägst du ihn, bist DU der Champion.",
    "felini_hot": "Aber Vorsicht: ein zäher Gegner, kommt aus einer Serie von {n} Siegen 🔥.",
    "felini_cold": "Und ich sag dir: er steckt tief in der Krise (🧊 {n} Niederlagen in Folge) — der perfekte Moment zuzuschlagen.",
    "felini_catnip_need": "Mein Rat von der Ringecke: investier 50 Punkte in Katzenminze 🌿 vor dem Kampf — gegen so einen brauchst du den Turbo.",
    "felini_catnip_broke": "Katzenminze 🌿 wäre nötig, aber die Kasse weint ({pts} Punkte): entweder du findest Punkte oder du wählst ein weicheres Ziel.",
    "felini_catnip_opt": "Katzenminze 🌿? Optional: ausgeglichener Kampf, die Nerven entscheiden.",
    "felini_catnip_no": "Keine Katzenminze: der schafft es auf eigenen Pfoten, spar dir die Punkte.",
    "felini_notarget": "gerade kein Ziel von anderen Besitzern über dir (oder alle ruhen sich aus): verteidige die Position oder schau später wieder vorbei.",
    "felini_margin": "Und er hat noch {n} Punkte Trainingsspielraum: eine gute Mahlzeit vor dem Kampf hat noch keinem geschadet.",
    "trader_open": [
      "Psst, Freund: ",
      "Geschäfte, Geschäfte! ",
      "Der Händler weiß alles: ",
      "Unter uns Kennern: "
    ],
    "trader_best": "halt {name} gut fest, die ist Gold wert: gib sie nicht für ein paar Münzen her.",
    "trader_worst": "wenn du wirklich etwas hergeben musst, fang mit {name} an — du hast Besseres in der Hand.",
    "trader_commons": "Du hast einen Haufen {rar} ({n}): tausch ein paar gegen etwas Selteneres, glaub mir.",
    "trader_gem": "Und pass auf: da ist eine {rar} von {owner} in der Auslage — wenn du ein gutes Duplikat hast, versuch den Tausch, bevor ein anderer sie schnappt.",
    "trader_browse": "Drück auf «Karten zum Tauschen durchstöbern» und zeig mir, was so umgeht: ich sag dir, ob ein Geschäft dabei ist.",
    "rocco_catnip": "🌿 Braver Junge. Jetzt geh da rein und zeig es ihnen: der erste Treffer wird ein Güterzug.",
    "baffo_all_rest": "😴 Alle deine Schützlinge ruhen sich aus: komm zurück, wenn einer bereit ist, dann legen wir los."
  },
  "titles": {
    "world": "WELT-DUELL",
    "live": "LIVE-DUELL",
    "boss": "ARENA-BOSS",
    "quarti": "VIERTELFINALE",
    "semi": "HALBFINALE",
    "finale": "FINALE",
    "sentiero": "DER PFAD"
  },
  "gym": {
    "lbl_allena": "Trainiert:",
    "lbl_start": "▶️ Training starten!",
    "fn_croc": "Trockenfutter",
    "fn_pollo": "Hähnchen",
    "fn_topo": "Mäuschen",
    "fn_erba": "Katzenminze",
    "fn_pesce": "Fisch",
    "fn_chicche": "Leckerli",
    "fn_bistecca": "Kriegersteak",
    "fn_scarica": "Katzen-Schock",
    "fn_fascino": "Fataler Charme",
    "fn_trono": "Federthron",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Stärke",
    "ft_topo": "🧠 Intelligenz",
    "ft_erba": "🎯 Geschick",
    "ft_pesce": "⚡ Geschwindigkeit",
    "ft_chicche": "✨ Charme",
    "ft_bistecca": "💪 Stärke + ❤️ HP",
    "ft_scarica": "⚡ Geschwindigkeit + 🎯 Geschick",
    "ft_fascino": "✨ Charme + 🧠 Intelligenz",
    "ft_trono": "😼 Gleichgültigkeit + ❤️ HP",
    "gn_gomitolo": "Fang das Wollknäuel",
    "gn_topo": "Mäusejagd",
    "gn_piuma": "Folge der Feder",
    "gn_corda": "Tauziehen",
    "gn_porta": "Brich die Tür",
    "gn_laser": "Laserjagd",
    "gn_memory": "Dosen-Memory",
    "gn_pesca": "Blitzangeln",
    "gn_scatto": "Katzensprint",
    "gn_scalata": "Regal-Klettern",
    "gn_fusa": "Schnurr-Rhythmus",
    "gn_sfilata": "Die Modenschau",
    "gn_zen": "Katzen-Zen",
    "gn_sguardi": "Blickduell",
    "ga_gomitolo": "Agilität — 🌿 Katzenminze (Geschick) und 🐟 Fisch (Geschwindigkeit)",
    "ga_topo": "Physis — 🍗 Hähnchen (Stärke) und 🥫 Trockenfutter (HP)",
    "ga_piuma": "Verstand — 🐁 Mäuschen (Intelligenz) und 🧀 Leckerli (Charme)",
    "ga_corda": "Stärke — 🍗 Hähnchen (Stärke)",
    "ga_porta": "Stärke — 🍗 Hähnchen (Stärke)",
    "ga_laser": "Geschick — 🌿 Katzenminze (Geschick)",
    "ga_memory": "Intelligenz — 🐁 Mäuschen (Intelligenz)",
    "ga_pesca": "Geschwindigkeit — 🐟 Fisch (Geschwindigkeit)",
    "ga_scatto": "Geschwindigkeit — 🐟 Fisch (Geschwindigkeit)",
    "ga_scalata": "HP — 🥫 Trockenfutter (HP)",
    "ga_fusa": "Charme — 🧀 Leckerli (Charme)",
    "ga_sfilata": "Charme — 🧀 Leckerli (Charme)",
    "ga_zen": "Gleichgültigkeit — 🛋️ Königskissen (Gleichgültigkeit)",
    "ga_sguardi": "Gleichgültigkeit — 🛋️ Königskissen (Gleichgültigkeit)",
    "gd_gomitolo": "Das Wollknäuel flitzt durch das Feld und wird mit jedem Fang schneller: tippe es so oft wie möglich in <strong>10 Sekunden</strong> an.<br>🚫 Weniger als 5 Fänge: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_topo": "Die Mäuse tauchen aus ihren Löchern auf und verschwinden sofort: triff sie, sobald sie erscheinen, für <strong>15 Sekunden</strong>.<br>🚫 Weniger als 5 Treffer: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_piuma": "Die bunten Federn blinken in einer Folge: wiederhole sie, indem du sie in derselben Reihenfolge antippst. Jede Runde wird die Folge länger; ein Fehler beendet das Training.<br>🚫 Weniger als 3 Runden: Futter verschwendet · ✅ 3-4: Bonus ×1 · 🌟 5+: Bonus ×2",
    "gd_corda": "Hämmere auf den <strong>ZIEH</strong>-Knopf, um den großen Hund über die Linie zu ziehen: er zieht ständig zurück, lass <strong>10 Sekunden</strong> lang nicht los.<br>🚫 Weniger als 8 Rucke: Futter verschwendet · ✅ 8-15: Bonus ×1 · 🌟 16+: Bonus ×2",
    "gd_porta": "Der Kraftbalken saust hin und her: tippe, wenn er in der <strong>grünen Zone</strong> ist, um den Pfotenhieb aufzuladen. Schlage so hart wie möglich in <strong>12 Sekunden</strong>.<br>🚫 Weniger als 5 gute Treffer: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_laser": "Der rote Punkt erscheint und verschwindet immer schneller: tippe ihn an, bevor er verblasst, für <strong>12 Sekunden</strong>.<br>🚫 Weniger als 6 Fänge: Futter verschwendet · ✅ 6-11: Bonus ×1 · 🌟 12+: Bonus ×2",
    "gd_memory": "Decke die Karten paarweise auf und finde die gleichen Paare aus dem Gedächtnis, in <strong>30 Sekunden</strong>.<br>🚫 Weniger als 3 Paare: Futter verschwendet · ✅ 3-4: Bonus ×1 · 🌟 5+: Bonus ×2",
    "gd_pesca": "Der Fisch flitzt unter Wasser und taucht nur einen Augenblick auf: tippe ihn <strong>genau dann, wenn er herausspringt</strong>. Die Fenster werden kürzer. Du hast <strong>14 Sekunden</strong>.<br>🚫 Weniger als 5 Fänge: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_scatto": "Warte auf <strong>Grün</strong> und tippe so schnell wie möglich: es misst deinen Reflex. 5 Runden — wer zu früh startet, verliert die Runde.<br>🚫 Weniger als 2 gute Sprints: Futter verschwendet · ✅ 2-3: Bonus ×1 · 🌟 4+: Bonus ×2",
    "gd_scalata": "Die Katze springt von Regal zu Regal: tippe, <strong>wenn die Plattform ausgerichtet ist</strong>, um hinaufzuspringen. Ein Fehlsprung und du fällst. Klettere so hoch wie möglich.<br>🚫 Weniger als 5 Regale: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_fusa": "Der Ring zieht sich im Takt zusammen: tippe, <strong>wenn er das Ziel erreicht</strong>, im Rhythmus des Schnurrens. Je präziser du bist, desto schneller der Takt.<br>🚫 Weniger als 5 Treffer im Takt: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_sfilata": "Auf dem Laufsteg erscheint ein Pfeil: <strong>wische in seine Richtung</strong>, um die Pose einzunehmen. Die Pfeile kommen immer schneller, du hast <strong>16 Sekunden</strong>.<br>🚫 Weniger als 6 Posen: Futter verschwendet · 🌟 12+: Bonus ×2",
    "gd_zen": "Die Disziplin der Gleichgültigkeit: <strong>ignoriere jede Ablenkung</strong> (🐭 Maus, 🪶 Feder, 🔴 Laser) und tippe <strong>nur das Kissen 🛋️</strong> an, wenn es erscheint. Eine Ablenkung zu berühren kostet die Runde. Du hast <strong>14 Sekunden</strong>.<br>🚫 Weniger als 5 Kissen: Futter verschwendet · ✅ 5-9: Bonus ×1 · 🌟 10+: Bonus ×2",
    "gd_sguardi": "<strong>Halte gedrückt</strong> und beweg dich nicht: wer regungslos bleibt, gewinnt. Aber wenn ein 😹 Kitzeln erscheint, musst du <strong>sofort loslassen</strong> und dann wieder drücken. Halte so lange wie möglich durch.<br>🚫 Weniger als 8 Sekunden Regungslosigkeit: Futter verschwendet · ✅ 8-13: Bonus ×1 · 🌟 14+: Bonus ×2",
    "tr_wasted_h": "🙀 Futter verschwendet!",
    "tr_wasted_b": "Punktzahl: <strong>{score}</strong> — unter der Mindestschwelle.<br><br>{ic} Das {food} ist verloren und {name} ruht jetzt eine Stunde.<br><br>😼 <em>«Zu meiner Zeit trainierte man mit verbundenen Augen.»</em>",
    "tr_coach_wasted": "🙀 Nur {score} Punkte?! Futter verschwendet.",
    "tr_perfect_h": "🌟 Perfektes Training!",
    "tr_ok_h": "✅ Training geschafft!",
    "tr_bonus2": " — Bonus verdoppelt!",
    "tr_online": "🌍 Karte auch in der Welt-Arena aktualisiert.<br>",
    "tr_body": "Punktzahl: <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> für {name}</span><br><br>{online}😴 Jetzt eine Stunde Ruhe: Muskeln wachsen im Schlaf.",
    "tr_coach_perfect": "😼 {score} Punkte! {name} hat das Zeug zum Champion.",
    "tr_coach_ok": "👍 {score} Punkte, ehrliche Arbeit. {name} wächst.",
    "gi_none": "Kein Schützling: erstelle zuerst eine Karte.",
    "gi_info": "Lv.{lv} · Trainingsspielraum: <strong>{used}/{cap}</strong> genutzt <span style=\"color:var(--muted)\">(+3 pro Level: du steigst durch Siege in der Welt auf)</span>",
    "gi_resting": "<br>😴 Er ruht sich aus: komm in {min} Minuten wieder",
    "gi_ready": "<br>✅ Bereit zum Training!",
    "gi_nofood": "😼 Der Coach: «Kein Futter für {name}: Trainingsspielraum aufgebraucht. Gewinne Kämpfe, um aufzusteigen (+3 Spielraum pro Level), dann geht es zurück an den Tisch.»",
    "gi_pick_opt": "— wähle einen Schützling —",
    "gi_pick": "👉 Wähle oben einen Schützling, um zu starten.",
    "gi_pick_alert": "Wähle zuerst oben im Menü einen Schützling."
  },
  "powers": {
    "pn_0": "Neun Leben",
    "pn_1": "Perfekter Hinterhalt",
    "pn_2": "Regenerierendes Schnurren",
    "pn_3": "Doppelter Pfotenhieb",
    "pn_4": "Flüssig-Modus",
    "pn_5": "Hypnotischer Blick",
    "pn_6": "Faulheits-Rüstung",
    "pn_7": "Katzen-Chaos",
    "pd_0": "beim ersten K.o. bleibt es bei 1 HP",
    "pd_1": "sein erster Angriff ist immer kritisch",
    "pd_2": "erholt bei jedem Zug HP",
    "pd_3": "25% Chance, zweimal anzugreifen",
    "pd_4": "weicht viel öfter aus",
    "pd_5": "bezaubert mit doppelter Chance",
    "pd_6": "erleidet 20% weniger Schaden",
    "pd_7": "sein Schaden ist unberechenbar (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Gewinne 1 Welt-Duell",
    "m_world2": "Gewinne 2 Welt-Duelle",
    "m_fight3": "Bestreite 3 Kämpfe (lokale zählen auch)",
    "m_tourn": "Gewinne ein Turnier (4 oder 8)",
    "m_upset": "Die Sensation: besiege in der Welt einen Gegner mit höherem Elo als deinem",
    "m_train1": "Schließe ein erfolgreiches Training ab",
    "m_gom10": "Erreiche 10+ bei Fang das Wollknäuel",
    "m_topo10": "Erreiche 10+ bei Mäusejagd",
    "m_piuma5": "Erreiche 5 Runden bei Folge der Feder",
    "m_boss": "Bezwinge einen Arena-Boss",
    "m_bet": "Gewinne eine Wette",
    "m_catnip": "Gewinne einen Kampf mit Katzenminze zu Beginn",
    "m_card": "Erstelle eine neue Karte",
    "m_qr": "Spiele ein Live-Duell (QR)",
    "a_prima_carta_nm": "Erste Karte",
    "a_prima_carta_ds": "Erstelle deine erste Karte",
    "a_coll5_nm": "Sammler",
    "a_coll5_ds": "5 Karten in der Sammlung",
    "a_coll10_nm": "Katzen-Junkie",
    "a_coll10_ds": "10 Karten in der Sammlung",
    "a_epica_nm": "Welche Seltenheit!",
    "a_epica_ds": "Erhalte eine Epische Karte",
    "a_legg_nm": "Legendär!",
    "a_legg_ds": "Erhalte eine Legendäre",
    "a_win1_nm": "Erster Sieg",
    "a_win1_ds": "Gewinne ein Welt-Duell",
    "a_win10_nm": "Veteran",
    "a_win10_ds": "Gewinne 10 Welt-Duelle",
    "a_win50_nm": "Legende",
    "a_win50_ds": "Gewinne 50 Welt-Duelle",
    "a_t4_nm": "Champion",
    "a_t4_ds": "Gewinne ein 4er-Turnier",
    "a_t8_nm": "Dominator",
    "a_t8_ds": "Gewinne ein 8er-Turnier",
    "a_pub_nm": "In der Welt",
    "a_pub_ds": "Veröffentliche eine Karte",
    "a_wwin_nm": "Dreierpack",
    "a_wwin_ds": "Gewinne 3 Welt-Duelle in Folge",
    "a_bet_nm": "Buchmacher",
    "a_bet_ds": "Gewinne eine Wette",
    "a_ricco_nm": "Reicher Kater",
    "a_ricco_ds": "Besitze 150 Punkte",
    "a_onore_nm": "Ehrenvoller Rücktritt",
    "a_onore_ds": "Ziehe eine Karte mit positiver Bilanz zurück",
    "a_disfatta_nm": "Debakel",
    "a_disfatta_ds": "Verliere 10 Welt-Duelle in Folge",
    "bm_ds": "Besiege {name} (Div. {tier})",
    "bmall_nm": "Boss-Bezwinger",
    "bmall_ds": "Besiege alle 64 Arena-Bosse",
    "cx_rar4": "Der Vierling: eine Karte für jede Seltenheit",
    "cx_razze3": "Entdecke 3 verschiedene Rassen",
    "cx_razze5": "Entdecke 5 verschiedene Rassen",
    "cx_razze10": "Entdecke 10 verschiedene Rassen",
    "cx_pot4": "Sammle 4 verschiedene Spezialkräfte",
    "cx_pot8": "Sammle alle 8 Spezialkräfte",
    "cx_lv5": "Bring eine Katze auf Level 5",
    "cx_hp100": "Eine Karte mit 100+ HP",
    "cx_oro": "Eine Karte mit dem Goldrahmen",
    "p_done": "erledigt",
    "p_won": "✓ errungen",
    "p_towin": "🔒 zu erringen",
    "p_howto": "So bekommst du sie:",
    "p_reward": "Belohnung:",
    "p_unlocked": "Freigeschaltet am",
    "cx_open": "(zum Öffnen tippen)",
    "cx_h_rar": "💎 Seltenheit",
    "cx_h_pow": "🌟 Spezialkräfte",
    "cx_h_breeds": "🐱 Entdeckte Rassen",
    "cx_nobreeds": "Noch keine: die Rasse kommt aus der KI-Analyse des Fotos.",
    "cx_h_objs": "🎯 Ziele",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> Ziele <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex: {ic} {txt}! +{pt} Punkte",
    "mis_tris_line": "🎉 Trio geschafft: +10 Bonuspunkte kassiert. Bis morgen!",
    "mis_toast_tris": "🎉 TRIO! Mission «{txt}» und ganzer Tag: +5 und +10 Bonus!",
    "mis_toast_done": "📅 Mission erfüllt: {ic} {txt}! +5 Punkte",
    "med_toast": "🏅 Medaille freigeschaltet: {ic} {nm}! +{pt} Punkte",
    "bm_sum": "🤖 Bosse bezwungen — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>",
    "a_sentiero_done_nm": "Wanderer der Neun Leben",
    "a_sentiero_done_ds": "Schließe den ganzen Pfad ab (100 Etappen)"
  },
  "reg": {
    "r_h_cards": "🎴 Die Karten",
    "r_p_cards": "Fotografiere eine Katze und sie wird zur Karte: die KI zeichnet sie als Cartoon neu und analysiert Aussehen und Charakter, um <strong>Werte</strong> (ein kräftiger Kater hat mehr Stärke), <strong>Rasse</strong>, <strong>Beschreibung</strong>, <strong>Spezialkraft</strong> und <strong>3 Angriffe</strong> (💥 stark aber ungenau, ⚡ schnell und fast unfehlbar, ✨ listig und verwirrend) zu erzeugen. Die <strong>Seltenheit</strong> wird aus dem Fingerabdruck des Fotos gelost: 55% Gewöhnlich, 28% Selten, 13% Episch, 4% Legendär (Epische und Legendäre glänzen und haben Bonuswerte). Dasselbe Foto ergibt immer dieselbe Karte.",
    "r_h_xp": "⭐ Erfahrung und Level",
    "r_p_xp": "Karten wachsen durch Kämpfen: <strong>Welt- und Live-Duelle: 25 XP pro Sieg, 10 pro Niederlage</strong> · <strong>lokale Arena und Turniere: 5 und 2</strong>. Alle 100 XP: +1 Level = <strong>+4 HP, +3% Angriff und +3 Trainingsspielraum</strong>. Spiegelkämpfe (Karte gegen sich selbst) zählen nicht.",
    "r_h_pts": "💰 Die Punkte (die Währung)",
    "r_p_pts": "Man verdient sie mit: <strong>+10 pro Welt- oder Live-Sieg</strong>, +10 pro bezwungenem Boss, 📅 Tagesmissionen (je 5, +10 für das Trio: max. 25 pro Tag), gewonnenen Wetten, Medaillen (10-100 Punkte je) und 🎁 Geschenkcodes. Lokale Siege: null Punkte. Man <strong>gibt sie aus</strong> für: Wetten (Einsatz 10-100), Futter im Training (20-25), 🌿 Weltvorteil (50), 🎨 Goldrahmen (100), 🔁 Neuzeichnen des Bildes (30). Einen Kampf zu verlieren kostet keine Punkte: nur falsche Wetten.",
    "r_h_bet": "🎲 Die Wetten",
    "r_p_bet": "In <strong>Welt- und Live-Duellen</strong>: vor dem Kampf wählst du den Einsatz und auf wen du setzt (⭐ Favorit zu niedriger Quote, 🐾 Außenseiter zu hoher Quote). Du gewinnst den Einsatz × (Quote − 1); liegst du falsch, verlierst du den Einsatz. Keine Wetten lokal oder in Turnieren.",
    "r_h_rest": "😴 Die Ruhe",
    "r_p_rest": "Nach jedem echten Kampf (lokal 1v1, Welt, Live) und jedem Training ruhen die beteiligten Katzen <strong>1 Stunde</strong>: sie können weder kämpfen noch fressen. Die Ruhe ist für alle sichtbar, auch online. Turniere sind Schaukämpfe und ermüden nicht.",
    "r_h_gym": "🏋️ Das Training",
    "r_p_gym": "Jedes Level schaltet <strong>+3 Punkte Trainingsspielraum</strong> frei. Du kaufst ein Futter (🥫 HP · 🍗 Stärke · 🐁 Intelligenz · 🌿 Geschick · 🐟 Geschwindigkeit · 🧀 Charme) und die Katze verdient es sich mit der passenden Übung: 🧶 Wollknäuel (Agilität), 🐭 Mäusejagd (Physis), 🪶 Folge der Feder (Verstand). Schwellen: <strong>unter 5 Punkten Futter verschwendet, 5-9 Bonus ×1, 10+ Bonus ×2</strong> (bei der Feder: 3 und 5 Runden). Veröffentlichte Karten aktualisieren sich online von selbst. Der Coach gibt kostenlos Rat.",
    "r_h_world": "🌍 Die Welt-Arena",
    "r_p_world": "Melde dich mit Google (oder E-Mail) an, wähle deinen Spielernamen (einer pro Konto, überall auf einmal umbenennbar) und <strong>veröffentliche die Karten, die du willst</strong>: nur veröffentlichte, aktive Karten können online herausfordern. Du forderst die Karten anderer heraus, das Ergebnis kommt ins Protokoll und in die Rangliste (nach Sieg-% sortiert). Du kannst eine Karte <strong>🚪 zurückziehen</strong>: sie bleibt als „zurückgezogen\" in der Rangliste, aber niemand kann sie mehr herausfordern. Der rote Punkt bei Welt sagt dir, wenn deine Karten in deiner Abwesenheit gekämpft haben.",
    "r_h_rank": "📊 Die Rangliste (UFC-Stil)",
    "r_p_rank1": "Jede veröffentlichte Karte hat eine <strong>Elo</strong>-Wertung, die bei <strong>1000</strong> beginnt. In jedem Kampf <strong>nimmt</strong> der Sieger Punkte und der Verlierer <strong>gibt dieselben Punkte ab</strong> — und die Menge hängt vom Kräfteunterschied ab: einen <strong>stärkeren</strong> Gegner zu schlagen ist bis zu <strong>~32 Punkte</strong> wert, einen viel schwächeren das Minimum, <strong>8</strong> (leichte Siege bringen wenig, die Sensation viel). Keine Karte fällt je unter 100. Die Berechnung macht der Server, für alle gleich.",
    "r_p_rank2": "Die offizielle Rangliste geht nach Elo, aber der Gürtel ist eine andere Sache: <strong>Champion wird man NUR, indem man den amtierenden Champion 👑 schlägt</strong> in einem Welt- oder Live-Duell. Du kannst ihn punktemäßig beliebig überholen: du bleibst erster Herausforderer, bis du ihn im Ring niederstreckst. Der Champion steht immer an der Spitze der Rangliste, und wer einmal Champion war, behält für immer die 🏆. Du kannst nur die herausfordern, die <strong>von 5 Plätzen über bis 5 unter</strong> dir stehen: für den Titel musst du klettern (in den Top 5 ist der Champion in Reichweite). Die Rangliste zeigt die Serien — 🔥 Siege in Folge, 🧊 Niederlagen in Folge, und die beste Serie aller Zeiten. Der <strong>🎩 Manager</strong> studiert die Zahlen und rät dir zum richtigen nächsten Kampf, ob Katzenminze 🌿 sich lohnt, und wann es besser ist, sich eine Weile ins Training zurückzuziehen.",
    "r_h_cat": "🃏 Der Catdex",
    "r_p_cat": "Das Sammelalbum, unten im Reiter 📚 Karten: es zählt die <strong>Seltenheiten, Rassen und Spezialkräfte</strong>, die du entdeckt hast (fehlende Felder bleiben ❓) und belohnt Meilensteine mit <strong>einmaligen</strong> Punkten — vom Seltenheits-Vierling (+25) über 10 verschiedene Rassen (+25) bis zu allen 8 Kräften (+30). Die Rasse schreibt die KI, wenn du die Karte erstellst: ähnliche Namen (z. B. „getigert\" und „Europäisch getigert\") zählen als eine Familie. Zum Vervollständigen braucht es nur eines: neue Katzen fotografieren.",
    "r_h_mis": "📅 Die Tagesmissionen",
    "r_p_mis": "Jede Mitternacht kommen <strong>3 Missionen</strong>, für die ganze Welt gleich: eine Kampf-, eine Trainings-, eine Überraschungsmission (Boss, Wetten, QR…). Jede zahlt <strong>5 Punkte</strong>, das komplette Trio weitere <strong>10 Bonus</strong>. Du findest sie oben im 🏅 Medaillenschrank, mit ✅ bei den bereits erledigten. Maximal 25 Punkte pro Tag: gerade genug für ein Training, oder etwas mehr.",
    "r_h_boss": "🤖 Die Arena-Bosse",
    "r_p_boss": "<strong>64 Legenden in 8 Divisionen</strong> mit steigender Schwierigkeit: von den Streunern des Viertels (leicht) bis zu Endbossen wie dem 🌑 Gatto Mammone oder 🤖 MIAO-9000, monströs. Jeden Tag sind <strong>2 aktiv, für die ganze Welt gleich</strong> (das Datum entscheidet sie). Einen zu schlagen zahlt <strong>+10 Punkte und 25 XP</strong>. Achtung: du hast <strong>nur EINEN Versuch pro Boss und Tag</strong> — gewonnen, verloren oder abgebrochen, es geht morgen weiter. Wähle deine Katze gut, bevor du in die Arena steigst. Verlieren kostet nur 2 Trost-XP. Nach dem Kampf <strong>ruht die Katze eine Stunde</strong> wie in jedem echten Kampf, und zuvor gekaufte Katzenminze 🌿 gilt auch hier. Gegen Bosse treten <strong>nur in der Welt veröffentlichte Karten</strong> an, und Bosse <strong>berühren die Elo-Rangliste nicht</strong>. Jeder Boss hat seine Medaille (Bereich «🤖 Bezwungene Bosse» im 🏅 Medaillenschrank, reichere Belohnungen für höhere Divisionen), plus den 🏆 Boss-Bezwinger für wer alle 64 bezwingt.",
    "r_h_qr": "⚡ Das Live-Duell (QR)",
    "r_p_qr": "Zwei Handys: eines zeigt den QR seiner Karte (🥋 Dojo → 📱), das andere scannt ihn (📷) und das Duell läuft auf dessen Bildschirm. <strong>Es zählt wie ein Welt-Duell</strong>: Punkte, volle XP, Medaillen, Ruhe, Wetten und ein aufgezeichnetes Ergebnis, wenn die Karten veröffentlicht sind.",
    "r_h_tourn": "🏆 Turniere und Medaillenschrank",
    "r_p_tourn": "Turniere mit 4 oder 8 zwischen deinen Karten und Rivalen: automatische Schaukämpfe mit Turnierbaum (reduzierte XP, keine Ruhe, keine Punkte). Der <strong>🏅 Medaillenschrank</strong> hat 25 Medaillen mit Punktbelohnungen (9 gehören zu Bossen) — tippe eine Medaille an, um zu erfahren, wie man sie erringt. Vorsicht vor dem 💀 Debakel…",
    "r_h_fight": "⚔️ Der Kampf",
    "r_p_fight": "Automatisch und rundenbasiert: Geschwindigkeit entscheidet, wer beginnt (meist), Stärke den Schaden, Geschick die Ausweichmanöver, Intelligenz die Kritischen (×1.6), Charme bezaubert, Gleichgültigkeit senkt den Schaden. Kein Treffer nimmt mehr als 38% der HP. Spezialkräfte, zufällige Power-ups (🧶🌿📦🐟), ein Schlussschlag in Zeitlupe und Replay. Die Präsentation lässt sich überspringen (⏭️ oder in den Optionen).",
    "mgr_greet": "Der Ring ist ein Schachbrett, Junge. Wähle deinen Champion und ich sage dir den nächsten Zug.",
    "mis_desc": "Drei neue Aufgaben jede Mitternacht, für die ganze Welt gleich: je <strong>5 Punkte</strong>, <strong>+10 Bonus</strong>, wenn du das Trio schaffst.",
    "med_desc": "Medaillen belohnen mit Punkten: gib sie für Wetten, den Weltvorteil, den Goldrahmen, Neuzeichnungen und in der Trainings-Speisekammer aus.",
    "boss_intro": "64 Legenden in 8 Divisionen: täglich erscheinen 2, für die ganze Welt gleich. Sie zu besiegen zahlt <strong>+10 Punkte</strong>, volle XP und eine eigene Medaille. <strong>Ein Versuch pro Boss und Tag</strong>, gewonnen oder verloren; Bosse berühren die Elo-Rangliste nicht. Nur in der Welt <strong>veröffentlichte Karten</strong> kämpfen."
  },
  "boss": {
    "div_1": "Streuner des Viertels",
    "div_2": "Rebellische Hauskatzen",
    "div_3": "Adel und Aristokatzen",
    "div_4": "Wilde Bestien",
    "div_5": "Mythen und Legenden",
    "div_6": "Geister und Übernatürliches",
    "div_7": "Katzengottheiten",
    "div_8": "Endbosse",
    "di_1": "Aus den Gassen des Viertels",
    "di_2": "Aus den aufgewühlten Wohnzimmern",
    "di_3": "Aus den Sälen des Adels",
    "di_4": "Aus den wilden Landen",
    "di_5": "Aus den alten Legenden",
    "di_6": "Aus dem Katzen-Jenseits",
    "di_7": "Von den himmlischen Thronen",
    "di_8": "Vom Ende aller Dinge",
    "bu_already_beaten": "✅ bereits bezwungen",
    "bu_beaten_today": "🎖️ Heute bezwungen: Belohnung kassiert.",
    "bu_failed_today": "💥 Heutiger Versuch gescheitert.",
    "bu_one_try": "Nur ein Versuch pro Boss und Tag: komm morgen wieder.",
    "bu_btn_beaten": "✅ Heute besiegt",
    "bu_btn_tomorrow": "⏳ Komm morgen wieder",
    "bu_btn_fight": "⚔️ Fordere {name} heraus",
    "bu_bestiary_sum": "📖 Bestiarium — <strong>{done}/{tot}</strong> bezwungen <span class=\"count\">{open}</span>",
    "bu_stats_unknown": "Werte unbekannt: stelle dich {name}, um sie aufzudecken.",
    "bu_beaten_tag": "✅ bezwungen",
    "bu_never_tag": "🔒 nie bekämpft",
    "bu_mystery_desc": "Ein Boss der Division «{div}», noch in Geheimnis gehüllt. Er erscheint im Wechsel: besiege ihn, um ihn ins Bestiarium aufzunehmen.",
    "bu_close": "✖ Schließen",
    "bu_already_today": "⏳ Du hast {name} heute schon herausgefordert: nur ein Versuch pro Boss und Tag, gewonnen oder verloren. Komm morgen wieder!",
    "bu_only_world": "Gegen Bosse kämpfen nur in der Welt veröffentlichte Karten: veröffentliche eine im 🌍-Reiter.",
    "bu_resting": "😴 {name} ruht sich aus: komm in {min} Minuten wieder.",
    "bu_pub_first": "— veröffentliche zuerst eine Karte in der Welt —",
    "bn_latta": "Das Blechkätzchen",
    "bk_latta": "Die Lebende Dose",
    "bl_latta": "Überzeugt, eine Konservendose zu sein. Hart außen, Thunfisch innen.",
    "bn_b02": "Halbschnurrbart",
    "bk_b02": "Der Marktdieb",
    "bl_b02": "Stiehlt auf dem Markt und verschwindet, bevor du «Miau» sagst.",
    "bn_b03": "Schmutzpfote",
    "bk_b03": "Der Herr der Tonnen",
    "bl_b03": "Herrscht über die Mülltonnen des Viertels, immun gegen jeden Ekel.",
    "bn_b04": "Der Fellball",
    "bk_b04": "Die Dampfwalze",
    "bl_b04": "Rollt über dich hinweg und hält nicht an. Einfach, aber wirksam.",
    "bn_b05": "Weicher Wanst",
    "bk_b05": "Der Faulpelz",
    "bl_b05": "Zu faul zum Ausweichen, zu fett zum Fallen.",
    "bn_b06": "Spürnase",
    "bk_b06": "Der Katzen-Spürhund",
    "bl_b06": "Folgt dem Duft des Futters bis ans Ende der Welt.",
    "bn_b07": "Halbschwanz",
    "bk_b07": "Der Wütende",
    "bl_b07": "Verlor den halben Schwanz, gewann die doppelte Wut.",
    "bn_b08": "Die Bäckerskatze",
    "bk_b08": "Der Lebende Ofen",
    "bl_b08": "Riecht nach Brot, beißt nach Glut.",
    "bn_b09": "Zerfetztes Sofa",
    "bk_b09": "Die Lederkralle",
    "bl_b09": "Seine Krallen schneiden Leder wie Butter.",
    "bn_b10": "Der Kühlschrankkönig",
    "bk_b10": "Seine Hungrige Majestät",
    "bl_b10": "Öffnet die Türen mit der bloßen Kraft des Hungers.",
    "bn_b11": "Verwöhntes Kätzchen",
    "bk_b11": "Der Engel mit Krallen",
    "bl_b11": "Rosa Schleife, Stahlkrallen.",
    "bn_b12": "Wollknäuel",
    "bk_b12": "Die Weiche Falle",
    "bl_b12": "Sieht zart aus. Es ist eine Falle.",
    "bn_b13": "Der 4-Uhr-Wecker",
    "bk_b13": "Der Nächtliche Albtraum",
    "bl_b13": "Greift an, wenn du am wenigsten damit rechnest: 4 Uhr morgens.",
    "bn_b14": "Die Tastaturkatze",
    "bk_b14": "Der Saboteur",
    "bl_b14": "Läuft auf den Nerven. Und auf den Tasten.",
    "bn_b15": "Zerrissener Vorhang",
    "bk_b15": "Der Kletterer",
    "bl_b15": "Klettert, wohin er nicht sollte. Immer.",
    "bn_b16": "Zerbrochene Vase",
    "bk_b16": "Der Unschuldige Zerstörer",
    "bl_b16": "Hinterlässt Zerstörung und einen engelsgleichen Blick.",
    "bn_barone": "Der Baron von Schnurren",
    "bk_barone": "Die Aristokratische Kralle",
    "bl_barone": "Duelliert nach alter Etikette: erst die Verbeugung, dann der Doppelpfotenhieb.",
    "bn_b18": "Gräfin Samt",
    "bk_b18": "Der Betäubende Blick",
    "bl_b18": "Ein Fell so weich, dass es den Gegner betäubt.",
    "bn_b19": "Sir Kratz III",
    "bk_b19": "Der Duellant",
    "bl_b19": "Legendärer Fechter, nie ein Duell im Morgengrauen verloren.",
    "bn_b20": "Madame Persia",
    "bk_b20": "Die Kissenkönigin",
    "bl_b20": "Herrscht von ihrem Seidenkissen und steht für niemanden auf.",
    "bn_b21": "Der Kartäuser-Herzog",
    "bk_b21": "Der Graue Stahl",
    "bl_b21": "Grau wie Stahl, kalt wie Eisen.",
    "bn_b22": "Lady Siam",
    "bk_b22": "Der Eisschlag",
    "bl_b22": "Saphiraugen, ein Hieb, der das Blut gefrieren lässt.",
    "bn_b23": "Don Großkater",
    "bk_b23": "Der Piate",
    "bl_b23": "Der Pate der Gasse: Angebote, die man nicht ablehnen kann.",
    "bn_b24": "Der Smoking-Butler",
    "bk_b24": "Der Elegante Schatten",
    "bl_b24": "Schwarz und weiß, makellos und tödlich.",
    "bn_sfinge": "Die Hof-Sphinx",
    "bk_sfinge": "Das Haarige Rätsel",
    "bl_sfinge": "Starrt dich an, bis du gestehst. Spricht nur in Rätseln.",
    "bn_b26": "Luchszahn",
    "bk_b26": "Der Hinterhalt",
    "bl_b26": "Du hörst ihn nicht kommen. Du spürst ihn erst danach.",
    "bn_b27": "Die Wildkatze",
    "bk_b27": "Der Ungezähmte",
    "bl_b27": "Nie gezähmt. Wird es nie sein.",
    "bn_b28": "Dschungelschatten",
    "bk_b28": "Die Schwarze Stille",
    "bl_b28": "Schwarz wie die Nacht, still wie der Tod.",
    "bn_b29": "Gebrüll",
    "bk_b29": "Die Große Stimme",
    "bl_b29": "Klein an Größe, riesig an Stimme.",
    "bn_b30": "Schneekralle",
    "bk_b30": "Der Eisige Hieb",
    "bl_b30": "Steigt von den Gipfeln herab mit einem Hieb, der gefriert.",
    "bn_b31": "Der Papptiger",
    "bk_b31": "Der Gestreifte Trug",
    "bl_b31": "Sieht falsch aus, bis er dich beißt.",
    "bn_b32": "Der Dächer-Puma",
    "bk_b32": "Der Springer",
    "bl_b32": "Springt von Gebäude zu Gebäude, ohne den Boden zu berühren.",
    "bn_nonna": "Die Gassen-Oma",
    "bk_nonna": "Sieben Leben und ein Halbes",
    "bl_nonna": "Ihr Schnurren heilt, ihre Klapse erziehen.",
    "bn_pescatore": "Der Geisterfischer",
    "bk_pescatore": "Das Netz des Schicksals",
    "bl_pescatore": "Erscheint in Nebelnächten, riecht nach Sardinen und Rache.",
    "bn_b35": "Der Gestiefelte Kater",
    "bk_b35": "Die Legendäre Klinge",
    "bl_b35": "Der Fechter der Märchen, in Fleisch, Fell und Stiefeln.",
    "bn_b36": "Kleine Bastet",
    "bk_b36": "Die Priesterin",
    "bl_b36": "Priesterin der neun Ringe, Hüterin der Riten.",
    "bn_b37": "Die Wächterkatze",
    "bk_b37": "Der Hüter der Schwelle",
    "bl_b37": "Bewacht die Schwelle des heiligen Kornspeichers seit Jahrhunderten.",
    "bn_b38": "Fuchsschwanz",
    "bk_b38": "Die Neun Täuschungen",
    "bl_b38": "Neun Schwänze, neun Täuschungen, keine Gnade.",
    "bn_b39": "Der Unsterbliche Streuner",
    "bk_b39": "Acht Verbrauchte Leben",
    "bl_b39": "Man sagt, er habe schon acht Leben verbraucht. Eines bleibt.",
    "bn_b40": "Maneki der Glücksbringer",
    "bk_b40": "Die Pfote des Schicksals",
    "bl_b40": "Die erhobene Pfote, die fremde Schicksale besiegelt.",
    "bn_spettro": "Das Dächer-Gespenst",
    "bk_spettro": "Der Mitternachtsschatten",
    "bl_spettro": "Niemand sah es je kommen. Viele sahen ihr Abendessen gehen.",
    "bn_b42": "Die Schwarze Freitagskatze",
    "bk_b42": "Das Pech in Fell",
    "bl_b42": "Bringt jedem Unglück, der es zu fordern wagt.",
    "bn_b43": "Augen im Dunkeln",
    "bk_b43": "Der Unsichtbare Jäger",
    "bl_b43": "Du siehst ihn erst, wenn es schon zu spät ist.",
    "bn_b44": "Der Schnurrbärtige Schnitter",
    "bk_b44": "Der Herr des Neunten Lebens",
    "bl_b44": "Er kommt, um dein neuntes Leben einzufordern.",
    "bn_b45": "Kamingespenst",
    "bk_b45": "Die Lebende Asche",
    "bl_b45": "Lebt in der warmen Asche des Kamins.",
    "bn_b46": "Die Hexenkatze",
    "bk_b46": "Die Bezauberin",
    "bl_b46": "Verwandelt Mäuse mit einem Miauen in Stürme.",
    "bn_b47": "Der Persische Vampir",
    "bk_b47": "Der Geschwindigkeits-Sauger",
    "bl_b47": "Saugt den Gegnern die Geschwindigkeit aus und macht sie zu seiner.",
    "bn_b48": "Katzen-Ektoplasma",
    "bk_b48": "Der Unberührbare",
    "bl_b48": "Du kannst nicht treffen, was nicht fest ist.",
    "bn_imperatore": "Der Getigerte Kaiser",
    "bk_imperatore": "Der Thron der Kissen",
    "bl_imperatore": "Herrscht vom höchsten Kissen. Sein Chaos bestimmt die Regeln.",
    "bn_b50": "Bastet die Göttin",
    "bk_b50": "Die Uralte Beschützerin",
    "bl_b50": "Die uralte Schutzgöttin aller Katzen.",
    "bn_b51": "Schrödingers Katze",
    "bk_b51": "Lebendig und Tot",
    "bl_b51": "Lebendig und tot zugleich, bis du sie angreifst.",
    "bn_b52": "Ra-Miau die Sonne",
    "bk_b52": "Der Blendende",
    "bl_b52": "Blendend: er verbrennt, wer ihn anzusehen wagt.",
    "bn_b53": "Katzen-Sekhmet",
    "bk_b53": "Die Göttliche Wut",
    "bl_b53": "Göttliche Wut aus Krallen.",
    "bn_b54": "Der Wächter der Pyramiden",
    "bk_b54": "Tausend Dynastien",
    "bl_b54": "Alt wie tausend Dynastien, reglos wie Stein.",
    "bn_b55": "Zunehmender Mond",
    "bk_b55": "Die Göttin der Nacht",
    "bl_b55": "Die Göttin der Nacht: im Dunkeln ist sie unbesiegbar.",
    "bn_b56": "Die Sternenkatze",
    "bk_b56": "Der Kosmische Mantel",
    "bl_b56": "Ihr Mantel ist ein Himmel aus Sternbildern.",
    "bn_mammone": "Der Gatto Mammone",
    "bk_mammone": "Die Legende der Legenden",
    "bl_mammone": "Das Monster der Märchen. Riesig, uralt und empfindlich.",
    "bn_b58": "Behemoth",
    "bk_b58": "Der Koloss des Abgrunds",
    "bl_b58": "Der Koloss, der unter den Vulkanen schläft.",
    "bn_b59": "Die Erste Katze",
    "bk_b59": "Der Urahn",
    "bl_b59": "Der, von dem alle Katzen der Welt abstammen.",
    "bn_b60": "Verschlinger Neun Sonnen",
    "bk_b60": "Der Kosmische Mythos",
    "bl_b60": "Der Mythos, der die Sonnen verschlingt, eine nach der anderen.",
    "bn_b61": "Der Herr der Streuner",
    "bk_b61": "Der König Aller",
    "bl_b61": "Befehligt jede Streunerkatze der Welt.",
    "bn_b62": "Katzen-Chronos",
    "bk_b62": "Der Zeitfresser",
    "bl_b62": "Frisst die Zeit und lässt die Gegner altern.",
    "bn_b63": "Die Leere Katze",
    "bk_b63": "Die Abwesenheit als Katze",
    "bl_b63": "Die Abwesenheit als Katze. Das Nichts, das miaut.",
    "bn_b64": "MIAO-9000",
    "bk_b64": "Die Ultimative Maschinen-Katze",
    "bl_b64": "Die ultimative Maschinen-Katze. Fehler: Gnade nicht gefunden."
  },
  "world": {
    "w_recent": "📜 Die letzten 5 Kämpfe deiner Karten",
    "w_open": "(zum Öffnen tippen)",
    "w_beat": "{w} von {wo} besiegte {l} von {lo}",
    "w_rank_champ": "👑 #1",
    "w_rank_n": "#{rk} in der Rangliste",
    "w_retired": "🚪 zurückgezogen",
    "w_record": "{w} S / {l} N",
    "w_none_pub": "Noch keine deiner Karten ist veröffentlicht.",
    "w_reactivate": "↩️ Reaktivieren",
    "w_retire": "🚪 Zurückziehen",
    "w_rank_suffix": "in der Rangliste",
    "w_by": "von",
    "w_anon": "anonym",
    "w_wc_champ": "👑 WELTMEISTER",
    "w_wc_rank": "#{rk} in der Rangliste",
    "w_elo": "Elo-Pkt.",
    "w_exchamp": "🏆 Ex-Champion",
    "w_beststreak": "beste Serie 🔥{n}",
    "w_sw": "🔥 {n} in Folge",
    "w_sl": "🧊 {n} KOs in Folge",
    "w_resting": "😴 Ruht sich aus: komm in {min} Minuten wieder",
    "w_not_ranked": "⏳ {name} ist noch nicht in der Rangliste (gerade veröffentlicht? versuch es gleich mit 🔄 erneut).",
    "w_no_challengers": "📊 {name} ist #{rk}, aber gerade keine Herausforderer im Bereich ±5. Lade jemanden zum Veröffentlichen ein!",
    "w_you_rank": "📊 {name} ist #{rk} in der Rangliste. Diese kann sie herausfordern (5 Plätze darüber bis 5 darunter):",
    "w_rests_short": "😴 ruht ({min}m)",
    "w_btn_fight": "⚔️ Fordern",
    "w_ldr_champ": "CHAMPION",
    "w_ex": "ex",
    "w_maxstreak": "max 🔥{n}",
    "w_none_rank": "Keine Karten in der Rangliste: veröffentliche eine!",
    "w_record_c": "{w}S/{l}N",
    "w_selrest": "😴 ruht",
    "w_selmarket": "🔒 im Markt",
    "w_fav": "⭐ Favorit",
    "w_underdog": "🐾 Außenseiter",
    "w_quota": "Quote",
    "w_ifwin": "bei Sieg: +{n} Punkte",
    "prize_line": "🎁 <strong>Im Spiel:</strong> Sieg +10 Punkte und +25 XP · Niederlage +10 XP",
    "w_catnip_ready": "🌿 Katzenminze BEREIT für diesen Kampf ✔",
    "w_catnip_btn": "🌿 Gib ihm Katzenminze — erster Treffer verdoppelt (50 Punkte)",
    "w_catnip_need": "Du brauchst 50 Punkte (du hast {pts}).",
    "w_pick_champ_opt": "— wähle einen Champion —",
    "w_all_resting": "😴 alle deine Katzen ruhen — komm später wieder",
    "w_pub_first_opt": "— veröffentliche zuerst eine Karte —",
    "w_loading": "Rangliste wird geladen…"
  },
  "mkt": {
    "mkt_desc": "Tausche oder verkaufe deine Karten mit anderen Spielern. Die Karte wechselt mit allem den Besitzer (Elo, Siege, Level); während der Verhandlung bleibt sie eingefroren und kämpft nicht. Du musst angemeldet sein und Karten in der Welt veröffentlicht haben.",
    "trd_greet": "Willkommen im Basar, Freund! Ich bin Herr Tausch: frag nur, ich weiß, wie man gute Geschäfte macht.",
    "inc_greet": "Meine Damen und Herren, die Auktion beginnt! Wer bietet? Wer erhöht?",
    "mkt_browse_btn": "🔍 Karten zum Tauschen durchstöbern",
    "mkt_filter_ph": "Nach Besitzer filtern (z. B. Lu…)",
    "mkt_notactive": "⚠️ Der Markt ist auf dem Server noch nicht aktiv (ein Einrichtungsschritt fehlt). Die übrigen App-Funktionen laufen normal.",
    "mkt_recv_h": "📥 Erhaltene Angebote",
    "mkt_offers": "{owner} bietet dir <strong>{from}</strong> im Tausch für deine <strong>{to}</strong>",
    "mkt_compare_btn": "🔍 Vergleichen",
    "mkt_accept": "✅ Annehmen",
    "mkt_reject": "✖ Ablehnen",
    "mkt_none_recv": "Keine Angebote erhalten.",
    "mkt_sent_h": "📤 Gesendete Angebote",
    "mkt_sent": "Du hast <strong>{from}</strong> für <strong>{to}</strong> von {owner} angeboten",
    "mkt_cancel": "↩️ Abbrechen",
    "mkt_login": "Melde dich an, um zu tauschen.",
    "mkt_loading": "Lädt…",
    "mkt_err_load": "❌ Fehler {code} beim Laden der Karten.",
    "mkt_none_avail": "Keine Karte zum Tauschen verfügbar.",
    "mkt_neterr": "Netzwerkfehler.",
    "mkt_none_of": "Keine Karte von «{q}».",
    "mkt_propose": "🔄 Vorschlagen",
    "mkt_this_card": "diese Karte",
    "mkt_give_get": "Du gibst <strong>{give}</strong> → Du erhältst <strong>{get}</strong>",
    "mkt_level": "📈 Level",
    "mkt_baratto_label": "😼 <strong>Herr Tausch</strong>:",
    "mkt_loading_cmp": "Vergleich wird geladen…",
    "mkt_cmp_title": "🔄 Tausch-Vergleich",
    "mkt_accept_trade": "✅ Tausch annehmen",
    "mkt_close": "↩️ Schließen",
    "mkt_err_cmp": "Fehler beim Laden des Vergleichs.",
    "mkt_close2": "Schließen",
    "mkt_trade_h": "🔄 Tausch",
    "mkt_need_card": "Zum Tauschen brauchst du mindestens EINE deiner Karten, die in der Welt veröffentlicht und aktiv ist (und nicht ruht).",
    "mkt_closeX": "✖ Schließen",
    "mkt_propose_h": "🔄 Tausch vorschlagen",
    "mkt_want": "Du willst <strong>{name}</strong>{owner}.",
    "mkt_tap_offer": "Tippe DEINE Karte zum Anbieten:",
    "mkt_do_trade": "🔄 Tauschen",
    "mkt_cancelX": "✖ Abbrechen",
    "mkt_pick_offer": "Tippe zuerst eine deiner Karten zum Anbieten an.",
    "mkt_notactive2": "⚠️ Der Markt ist auf dem Server noch nicht aktiv: ein Einrichtungsschritt fehlt (SQL aus Stufe 2).",
    "mkt_trade_fail": "Tausch nicht vorgeschlagen: {t}",
    "mkt_sent_ok": "🔄 Angebot gesendet! Warte auf Antwort.",
    "mkt_neterr2": "Netzwerkfehler: {m}",
    "mkt_op_fail": "Vorgang fehlgeschlagen: {t}",
    "mkt_trade_done": "✅ Tausch erledigt! Die Karten haben den Besitzer gewechselt.",
    "mkt_rejected": "Angebot abgelehnt.",
    "mkt_cancelled": "↩️ Angebot abgebrochen.",
    "mkt_received": "🎁 Du hast {name} im Tausch erhalten!",
    "mkt_login_first": "Melde dich zuerst an (🌍 Welt-Reiter).",
    "mkt_auc_h": "🔨 Auktion",
    "mkt_need_free": "Du brauchst eine veröffentlichte, freie Karte (nicht schon im Markt), um sie zu versteigern.",
    "mkt_put_auc_h": "🔨 Zur Auktion stellen",
    "mkt_tap_sell": "Tippe die zu verkaufende Karte:",
    "mkt_min_price": "Mindestpreis (Punkte)",
    "mkt_duration": "Dauer",
    "mkt_h1": "1 Stunde",
    "mkt_h6": "6 Stunden",
    "mkt_h24": "24 Stunden",
    "mkt_d2": "2 Tage",
    "mkt_hold_auc": "🔨 Auktion starten",
    "mkt_pick_card": "Tippe zuerst eine Karte.",
    "mkt_auc_notactive": "⚠️ Auktionen sind auf dem Server noch nicht aktiv (SQL fehlt).",
    "mkt_auc_fail": "Auktion nicht erstellt: {t}",
    "mkt_auc_ok": "🔨 Auktion gestartet! Deine Karte ist jetzt im Markt.",
    "mkt_auc_notactive2": "⚠️ Auktionen auf dem Server noch nicht aktiv (SQL-Schritt fehlt).",
    "mkt_err": "Fehler {code}.",
    "mkt_no_auc": "Keine laufende Auktion. Starte eine!",
    "mkt_curbid": "💰 {n} Pkt. von {owner}",
    "mkt_nobid": "kein Gebot",
    "mkt_your_auc": "🔨 deine Auktion",
    "mkt_withdraw": "↩️ Zurückziehen",
    "mkt_bid_btn": "💰 Bieten",
    "mkt_base": "Basis {n} Pkt.",
    "mkt_history": "📜 Gebotsverlauf",
    "mkt_min_bid": "Du musst mindestens {n} Punkte bieten.",
    "mkt_no_points": "Du hast nicht genug Punkte (du hast {p}).",
    "mkt_bid_fail": "Gebot abgelehnt: {t}",
    "mkt_no_bids": "Noch kein Gebot.",
    "mkt_bid_line": "💰 {n} Pkt. — {owner} · {when}",
    "mkt_err2": "Fehler.",
    "mkt_confirm_withdraw": "Die Karte aus der Auktion zurückziehen?",
    "mkt_withdraw_fail": "Nicht zurückgezogen: {t}",
    "mkt_withdrawn": "↩️ Auktion zurückgezogen."
  },
  "sent": {
    "sent_title": "🗺️ Der Pfad der Neun Leben",
    "sent_desc": "Eine lange Reise in Etappen für jede deiner Karten: stelle dich den Pfad-Katzen eine nach der anderen. Jeder Sieg schaltet die nächste Etappe frei und schenkt dir das Sticker-Bild dieser Katze fürs Album. Offline spielbar, ohne Wetten oder Ruhe: verlierst du, versuchst du es erneut.",
    "sent_pick": "Wer den Pfad geht",
    "pick_card": "👆 Wähle oben eine Karte, um die Reise zu beginnen.",
    "no_card": "Erstelle zuerst eine Karte, dann geht es auf den Pfad.",
    "progress": "<strong>{name}</strong> — Etappe {done}/{tot} geschafft.",
    "more_soon": "🚧 Die nächsten Zonen des Pfads kommen bald…",
    "stage": "Etappe",
    "zone_done": "🎉 Zone abgeschlossen! +{pts} Punkte und eine neue Albumseite.",
    "got_fig": "📒 Neues Sticker: {name}!",
    "album_sum": "📒 Album — <strong>{done}/{tot}</strong> Sticker <span class=\"count\">{open}</span>",
    "z_1": "Die Gassen",
    "z_2": "Die Gärten",
    "z_3": "Der Wald",
    "z_4": "Der Berg",
    "z_5": "Die Stadt",
    "z_6": "Die Wüste",
    "z_7": "Das Meer",
    "z_8": "Die Eislande",
    "z_9": "Der Vulkan",
    "z_10": "Der Kosmos",
    "bn_s01": "Kätzchen",
    "bk_s01": "Der Neuling",
    "bl_s01": "Die erste Katze, die du triffst: neugierig, tollpatschig, aber mit Herz.",
    "bn_s02": "Wühler",
    "bk_s02": "Der König des Mülls",
    "bl_s02": "Kennt jede Tonne im Viertel und was darin steckt.",
    "bn_s03": "Söckchen",
    "bk_s03": "Der Schläfer",
    "bl_s03": "Schwarz-weiß, immer auf der wärmsten Motorhaube der Gasse.",
    "bn_s04": "Kartönchen",
    "bk_s04": "Der Karton-Hinterhalt",
    "bl_s04": "Lebt in einer Schachtel und springt heraus, wenn du es am wenigsten erwartest.",
    "bn_s05": "Mitternacht",
    "bk_s05": "Der Gassenschatten",
    "bl_s05": "Schwarz wie die Nacht, du siehst ihn nur an den leuchtenden Augen.",
    "bn_s06": "Sahne",
    "bk_s06": "Der Naschkater",
    "bl_s06": "Hat immer einen Milchbart und ein zufriedenes Grinsen.",
    "bn_s07": "Saite",
    "bk_s07": "Der Straßenmusiker",
    "bl_s07": "Spielt seine verstimmte Gitarre unter den Laternen für ein paar Leckerli.",
    "bn_s08": "Sardine",
    "bk_s08": "Der Fischhändler",
    "bl_s08": "Lässt seinen Fisch nie los: den musst du dir verdienen.",
    "bn_s09": "Blitz",
    "bk_s09": "Der Gassenblitz",
    "bl_s09": "Springt von Wand zu Wand: fang ihn, wenn du kannst.",
    "bn_s10": "Einauge",
    "bk_s10": "Der König der Gassen",
    "bl_s10": "Ein Auge und tausend Narben: er befehligt die Streuner. Das erste echte Hindernis.",
    "bn_s11": "Flatter",
    "bk_s11": "Der Schmetterlingsjäger",
    "bl_s11": "Jagt den ganzen Tag Schmetterlinge, fängt nie einen.",
    "bn_s12": "Sonnenblume",
    "bk_s12": "Der Sonnenschläfer",
    "bl_s12": "Schläft, wo die Sonne hinfällt, und wandert mit ihr.",
    "bn_s13": "Summ",
    "bk_s13": "Der Stachel",
    "bl_s13": "Hat schmerzhaft gelernt, dass Bienen stechen. Versucht es trotzdem.",
    "bn_s14": "Piep",
    "bk_s14": "Der Vogelspäher",
    "bl_s14": "Beobachtet stundenlang regungslos die Vögelchen vom Fenster.",
    "bn_s15": "Fröschlein",
    "bk_s15": "Der Frosch-Schreck",
    "bl_s15": "Springt in den Teich und verscheucht alle Frösche.",
    "bn_s16": "Dorn",
    "bk_s16": "Der Rosen-Verletzte",
    "bl_s16": "Tausend Kratzer im Gestrüpp, aber das Rosenbeet gehört ihm.",
    "bn_s17": "Schnecke",
    "bk_s17": "Der Geduldige",
    "bl_s17": "Beobachtet Schnecken. Er ist das Einzige, das langsamer ist als sie.",
    "bn_s18": "Platsch",
    "bk_s18": "Der Brunnen-Spritzer",
    "bl_s18": "Spielt mit dem Brunnenwasser und kommt immer klatschnass zurück.",
    "bn_s19": "Stups",
    "bk_s19": "Der Stachlige Freund",
    "bl_s19": "Hat sich mit einem Igel angefreundet. Frag nicht wie.",
    "bn_s20": "Alte Weide",
    "bk_s20": "Der Herr des Gartens",
    "bl_s20": "Die älteste Katze im Garten: weise, ruhig und unantastbar.",
    "bn_s21": "Pilzchen",
    "bk_s21": "Der Sammler",
    "bl_s21": "Erschnüffelt die besten Pilze des Waldes und meidet die schlechten.",
    "bn_s22": "Nachtfeder",
    "bk_s22": "Der Rivale der Eule",
    "bl_s22": "Fordert die Eule jede Nacht heraus, wer länger wach bleibt.",
    "bn_s23": "Eichel",
    "bk_s23": "Der Hamsterer",
    "bl_s23": "Stiehlt den Eichhörnchen die Eicheln und versteckt sie überall.",
    "bn_s24": "Schlaukopf",
    "bk_s24": "Der Gerissene",
    "bl_s24": "Geht wie ein Fuchs und denkt wie ein Fuchs.",
    "bn_s25": "Hauer",
    "bk_s25": "Der Revierwächter",
    "bl_s25": "Verteidigt seine Lichtung gegen alle, auch Wildschweine.",
    "bn_s26": "Spinnweb",
    "bk_s26": "Der Verhedderte",
    "bl_s26": "Landet immer in Spinnweben, gibt aber nie auf.",
    "bn_s27": "Zapfen",
    "bk_s27": "Der Kiefernkletterer",
    "bl_s27": "Klettert auf die höchsten Kiefern, nur um hinabzuschauen.",
    "bn_s28": "Kitz",
    "bk_s28": "Der Stille Jäger",
    "bl_s28": "Folgt den Hirschen lautlos durch den Wald.",
    "bn_s29": "Wölfling",
    "bk_s29": "Das Wilde Junge",
    "bl_s29": "Unter Wölfen aufgewachsen, lernte er ihr Heulen.",
    "bn_s30": "Großbär",
    "bk_s30": "Die Bestie des Waldes",
    "bl_s30": "Groß wie ein Bär: der unbestrittene König des Waldes.",
    "bn_s31": "Stiefelchen",
    "bk_s31": "Der Wanderer-Verfolger",
    "bl_s31": "Folgt den Wanderern zum Gipfel in Hoffnung auf ein Brot.",
    "bn_s32": "Ziegenschreck",
    "bk_s32": "Der Ziegen-Erschrecker",
    "bl_s32": "Lässt die Ziegen auf den Klippen aufschrecken, nur zum Spaß.",
    "bn_s33": "Kiesel",
    "bk_s33": "Der Balancierer",
    "bl_s33": "Balanciert auf den unbequemsten Felsen des Bergs.",
    "bn_s34": "Adlerjunges",
    "bk_s34": "Der Rivale des Adlers",
    "bl_s34": "Streitet mit dem Adler um die höchsten Gipfel, ohne Flügel.",
    "bn_s35": "Zeltplane",
    "bk_s35": "Der Lager-Dieb",
    "bl_s35": "Plündert nachts die Zelte der Camper.",
    "bn_s36": "Gipfel",
    "bk_s36": "Der Gipfelbewohner",
    "bl_s36": "Lebt dort, wo die Luft dünn ist und keine andere Katze wagt.",
    "bn_s37": "Sturmbö",
    "bk_s37": "Der Zerzauste",
    "bl_s37": "Der Bergwind hat sein Fell für immer zerzaust.",
    "bn_s38": "Enterhaken",
    "bk_s38": "Der Kletterer",
    "bl_s38": "Erklimmt Wände, wo nicht mal Ziegen hingehen.",
    "bn_s39": "Glöckchen",
    "bk_s39": "Der Bergler",
    "bl_s39": "Trägt ein Glöckchen am Hals: du hörst ihn, bevor du ihn siehst.",
    "bn_s40": "Weißhorn",
    "bk_s40": "Der König des Bergs",
    "bl_s40": "Widderhörner und eiserne Pfoten: er beherrscht jeden Gipfel.",
    "bn_s41": "Taxi",
    "bk_s41": "Der Auto-Ausweicher",
    "bl_s41": "Überquert den wildesten Verkehr ohne einen Kratzer.",
    "bn_s42": "Ziegel",
    "bk_s42": "Der Dächer-Schleicher",
    "bl_s42": "Herrscht über die Dächer der Großstadt, Ziegel für Ziegel.",
    "bn_s43": "Margherita",
    "bk_s43": "Der Pizza-Räuber",
    "bl_s43": "Kein Pizzakarton ist sicher, wenn er umherstreift.",
    "bn_s44": "Ampel",
    "bk_s44": "Der Verkehrs-Wächter",
    "bl_s44": "Wartet immer auf Grün. Eine sehr gesittete Katze.",
    "bn_s45": "Parkour",
    "bk_s45": "Der Dächer-Akrobat",
    "bl_s45": "Springt von Gebäude zu Gebäude wie im Film.",
    "bn_s46": "Neon",
    "bk_s46": "Der Neon-Faulpelz",
    "bl_s46": "Schläft unter den Leuchtreklamen, in der Wärme der Stadt.",
    "bn_s47": "U-Bahn",
    "bk_s47": "Die U-Bahn-Katze",
    "bl_s47": "Kennt jeden Tunnel und jeden Bahnsteig unter der Erde.",
    "bn_s48": "Jazz",
    "bk_s48": "Die Gassenkatze",
    "bl_s48": "Miaut nachts im Jazz-Takt hinter den Clubs.",
    "bn_s49": "Wolkenkratzer",
    "bk_s49": "Der Turm-Kletterer",
    "bl_s49": "Erklomm das höchste Gebäude nur wegen der Aussicht.",
    "bn_s50": "Nachtstück",
    "bk_s50": "Der Boss der Stadt",
    "bl_s50": "Er befehligt jede Gasse nach Sonnenuntergang. Die Stadt gehört ihm.",
    "bn_s51": "Kaktuschen",
    "bk_s51": "Der Kaktus-Ausweicher",
    "bl_s51": "Rennt zwischen den Kakteen, ohne sich je zu stechen. Fast.",
    "bn_s52": "Hakenschwanz",
    "bk_s52": "Der Misstrauische",
    "bl_s52": "Behält jeden Skorpion im Auge: er wurde schon einmal gestochen.",
    "bn_s53": "Düne",
    "bk_s53": "Der Dünen-Läufer",
    "bl_s53": "Läuft die Dünen rauf und runter, als wären es Kissen.",
    "bn_s54": "Palme",
    "bk_s54": "Der Oasen-Faulpelz",
    "bl_s54": "Fand den einzigen Schatten der Wüste und gibt ihn nicht her.",
    "bn_s55": "Zischen",
    "bk_s55": "Der Schlangenbeschwörer",
    "bl_s55": "Starrt Schlangen an, bis sie aufgeben.",
    "bn_s56": "Gluthitze",
    "bk_s56": "Der Sonnenverbrannte",
    "bl_s56": "Die Wüstensonne hat sein Gemüt erhitzt.",
    "bn_s57": "Amphore",
    "bk_s57": "Die Ruinenkatze",
    "bl_s57": "Lebt zwischen den alten Ruinen, Hüter der Sandgeheimnisse.",
    "bn_s58": "Höcker",
    "bk_s58": "Der Kamel-Verfolger",
    "bl_s58": "Folgt den Karawanen für die Krümel der Reisenden.",
    "bn_s59": "Wirbel",
    "bk_s59": "Der Sturm-Überlebende",
    "bl_s59": "Er hat tausend Sandstürme überstanden. Immer noch da.",
    "bn_s60": "Löwig",
    "bk_s60": "Die Wüsten-Sphinx",
    "bl_s60": "Reglos wie eine Statue, alt wie der Sand. Spricht in Rätseln.",
    "bn_s61": "Schere",
    "bk_s61": "Der Krabben-Fänger",
    "bl_s61": "Jagt Krabben am Ufer, verliert immer einen Schnurrhaar.",
    "bn_s62": "Muschel",
    "bk_s62": "Der Sammler",
    "bl_s62": "Sammelt Muscheln und vergräbt sie im Sand.",
    "bn_s63": "Welle",
    "bk_s63": "Der Wellen-Ausweicher",
    "bl_s63": "Fordert die Wellen heraus und flieht kurz bevor er nass wird.",
    "bn_s64": "Haken",
    "bk_s64": "Der Angler",
    "bl_s64": "Angelt mit der Pfote besser als viele Fischer.",
    "bn_s65": "Möwe",
    "bk_s65": "Der Rivale der Möwe",
    "bl_s65": "Streitet mit den Möwen um jeden Krümel am Kai.",
    "bn_s66": "Segel",
    "bk_s66": "Der Blinde Passagier",
    "bl_s66": "Schleicht sich an Bord und niemand bemerkt es.",
    "bn_s67": "Enterung",
    "bk_s67": "Der Piratenkater",
    "bl_s67": "Augenklappe und eine Pfote stets zum Angriff bereit.",
    "bn_s68": "Tentakel",
    "bk_s68": "Der Kraken-Bändiger",
    "bl_s68": "Der Einzige, der mit Kraken spielt und gewinnt.",
    "bn_s69": "Robbe",
    "bk_s69": "Der Freund des Meeres",
    "bl_s69": "Schwimmt mit den Robben, als wäre er unter ihnen geboren.",
    "bn_s70": "Leviathan",
    "bk_s70": "Der König des Meeres",
    "bl_s70": "Groß wie ein Wal: er befehligt jede Welle des Ozeans.",
    "sent_fight": "⚔️ Kämpfen",
    "sent_back": "↩️ Zurück",
    "sent_replay": "⚔️ Nochmal",
    "bn_s71": "Schneegestöber",
    "bk_s71": "Der Flocken-Fänger",
    "bl_s71": "Versucht, die Schneeflocken mit den Pfoten zu fangen, eine nach der anderen.",
    "bn_s72": "Schneemann",
    "bk_s72": "Der Schnee-Bauer",
    "bl_s72": "Baut Schneemänner und wirft sie dann zum Spaß um.",
    "bn_s73": "Eiszapfen",
    "bk_s73": "Der Rutscher",
    "bl_s73": "Rutscht über das Eis und hält nie wirklich an.",
    "bn_s74": "Pinguin",
    "bk_s74": "Der Rivale des Pinguins",
    "bl_s74": "Fordert die Pinguine zum Bauchrutsch-Wettbewerb heraus.",
    "bn_s75": "Skifahrer",
    "bk_s75": "Der Abfahrer",
    "bl_s75": "Saust die verschneiten Hänge schneller hinab als ein Schlitten.",
    "bn_s76": "Bärchen",
    "bk_s76": "Der Freund des Eisbären",
    "bl_s76": "Hat ein Eisbärjunges adoptiert. Oder umgekehrt?",
    "bn_s77": "Schneesturm",
    "bk_s77": "Der Sturm-Wanderer",
    "bl_s77": "Durchquert Schneestürme, als wären sie eine Brise.",
    "bn_s78": "Curler",
    "bk_s78": "Der Eis-Schleuderer",
    "bl_s78": "Lässt Steine mit perfektem Ziel übers Eis gleiten.",
    "bn_s79": "Kristall",
    "bk_s79": "Der Kristall-Bewunderer",
    "bl_s79": "Starrt stundenlang die funkelnden Eiskristalle an.",
    "bn_s80": "Frostkönig",
    "bk_s80": "Der Herrscher des Eises",
    "bl_s80": "Sein Atem lässt die Seen gefrieren. Niemand hält seinem eisigen Blick stand.",
    "bn_s81": "Glut",
    "bk_s81": "Der Feuerbrand",
    "bl_s81": "Läuft über glühende Kohlen, ohne sich die Pfoten zu verbrennen.",
    "bn_s82": "Krater",
    "bk_s82": "Der Kraterbewohner",
    "bl_s82": "Lebt am Rand des Vulkans, wo es höllisch heiß ist.",
    "bn_s83": "Obsidian",
    "bk_s83": "Die Schwarzstein-Katze",
    "bl_s83": "Hart und glänzend wie vulkanisches Glas.",
    "bn_s84": "Getöse",
    "bk_s84": "Der Explosive",
    "bl_s84": "Wenn er wütend wird, bebt der ganze Berg.",
    "bn_s85": "Knallfrosch",
    "bk_s85": "Die Kurze Zündschnur",
    "bl_s85": "Entzündet sich wegen einer Kleinigkeit und greift an.",
    "bn_s86": "Quelle",
    "bk_s86": "Der Thermen-Faulpelz",
    "bl_s86": "Döst in den heißen Becken nahe der Lava.",
    "bn_s87": "Senghitze",
    "bk_s87": "Der Glühende",
    "bl_s87": "Wenn er vorbeigeht, flimmert die Luft vor Hitze.",
    "bn_s88": "Flämmchen",
    "bk_s88": "Der Feuerhüter",
    "bl_s88": "Hält die uralte Flamme des Vulkans am Leben.",
    "bn_s89": "Laterne",
    "bk_s89": "Die Ewige Flamme",
    "bl_s89": "Brennt seit tausend Jahren und erlischt nie.",
    "bn_s90": "Drachlein",
    "bk_s90": "Der Drache des Vulkans",
    "bl_s90": "Spuckt Funken und befehligt die Lava. Der König des Feuers.",
    "bn_s91": "Möndchen",
    "bk_s91": "Die Mondkatze",
    "bl_s91": "Springt von Krater zu Krater auf dem Mond, leicht wie eine Feder.",
    "bn_s92": "Sternchen",
    "bk_s92": "Der Sternen-Sammler",
    "bl_s92": "Sammelt Sternschnuppen in einem Glas (sagt er).",
    "bn_s93": "Ring",
    "bk_s93": "Der Herr der Ringe",
    "bl_s93": "Lebt auf den Ringen des Saturn, in perfekter Balance.",
    "bn_s94": "Komet",
    "bk_s94": "Der Reisende",
    "bl_s94": "Saust durchs All und hinterlässt eine leuchtende Spur.",
    "bn_s95": "Rakete",
    "bk_s95": "Der Astronaut",
    "bl_s95": "Stieg zum Spaß auf eine Rakete und kam nie wieder herunter.",
    "bn_s96": "Untertasse",
    "bk_s96": "Der Freund der Aliens",
    "bl_s96": "Hat sich mit Wesen anderer Welten angefreundet.",
    "bn_s97": "Meteor",
    "bk_s97": "Der Wunsch",
    "bl_s97": "Fliegt so schnell vorbei, dass man sich etwas wünschen muss.",
    "bn_s98": "Leere",
    "bk_s98": "Das Schwarze Loch",
    "bl_s98": "Verschlingt alles, was sich nähert, sogar das Licht.",
    "bn_s99": "Sternenstaub",
    "bk_s99": "Der Sternenmantel",
    "bl_s99": "Sein Fell besteht aus Galaxienstaub.",
    "bn_s100": "Kosmischer Herrscher",
    "bk_s100": "Der Herr der Neun Leben",
    "bl_s100": "Der letzte Gegner des Pfads. Alt wie das Universum, unbesiegbar wie eine Legende."
  },
  "msg": {
    "del_card_confirm": "Karte von {name} löschen? Auch ihre Kampfwerte werden gelöscht.",
    "nick_set": "🥊 {name} heißt jetzt «{nick}»",
    "retire_login": "Um eine Karte aus der Welt zurückzuziehen, musst du dich zuerst anmelden (🌍 Welt-Reiter).",
    "retire_confirm": "{name} aus der Welt-Arena zurückziehen? Sie bleibt mit ihrer Bilanz als „zurückgezogen\" in der Rangliste, aber niemand kann sie mehr herausfordern. (Erneutes Veröffentlichen reaktiviert sie.)",
    "err_http": "Fehler: HTTP {code}",
    "card_not_pub": "Diese Karte ist nicht veröffentlicht (oder nicht deine).",
    "retired_ok": "🚪 {name} hat sich mit Ehre aus der Welt zurückgezogen. Ihre Bilanz bleibt in der Rangliste.",
    "err_net": "Netzwerkfehler: {m}",
    "code_copied": "Code kopiert! Schick ihn einem Freund (z. B. per WhatsApp): er fügt ihn in seine App ein, um {name} herauszufordern. Hinweis: der Code ist lang, weil er auch das Foto enthält.",
    "audio_quota": "⛔ Tägliches Gemini-Kontingent aufgebraucht.\n\nDie bereits erstellten Clips sind gespeichert. Mach morgen weiter (das Kontingent wird zurückgesetzt), es ergänzt nur die fehlenden.",
    "audio_err": "🎙️ Audiofehler ({lang}): {err}",
    "same_cat": "Eine Katze kann nicht gegen sich selbst kämpfen! Wähle zwei verschiedene Karten.",
    "backup_confirm": "Backup importieren? Es ersetzt deine aktuelle Sammlung, Rivalen und Werte ({n} Karten im Backup).",
    "backup_invalid": "Ungültige Backup-Datei.",
    "share_unsupported": "Direktes Teilen wird von diesem Browser nicht unterstützt: nutze «Herunterladen» und hänge das Bild an.",
    "card_gone_local": "Diese Karte ist nicht mehr in deiner lokalen Sammlung.",
    "news_beaten": "💥 {loser} wurde von {winner} {by} {owner} besiegt — ruht jetzt 😴",
    "world_login": "Melde dich zuerst an (oben im Welt-Reiter), um online herauszufordern.",
    "out_of_range": "🔒 Außer Reichweite: {name} ist #{ro}, du bist #{rm}. Du kannst nur zwischen 5 Plätzen darüber und 5 darunter herausfordern: klettere in der Rangliste!",
    "opp_trading": "🔄 {name} ist in einem Tausch: gerade nicht herausforderbar.",
    "opp_resting": "😴 {name} ist gerade zur Ruhe gegangen: versuch es in {min} Minuten erneut.",
    "need_pub_card": "Zum Online-Herausfordern brauchst du EINE deiner Karten veröffentlicht und aktiv: veröffentliche eine über «Wähle, welche Karten veröffentlicht werden».",
    "catnip_have": "Vorteil bereits gekauft: gilt für deinen nächsten Kampf.",
    "catnip_need": "Du brauchst 50 Punkte (du hast {pts}). Gewinne Wetten und Medaillen!",
    "catnip_confirm": "50 Punkte ausgeben? Deine Karte startet den nächsten Kampf mit Katzenminze (erster Treffer verdoppelt).",
    "catnip_ready": "🌿 Vorteil bereit: gilt für deinen nächsten Kampf!",
    "regen_cost": "Das Neuzeichnen kostet 30 Punkte (du hast {pts}).",
    "regen_confirm": "30 Punkte für eine neue KI-Zeichnung ausgeben?",
    "frame_have": "{name} trägt bereits den Goldrahmen!",
    "frame_cost": "Der Goldrahmen kostet 100 Punkte (du hast {pts}).",
    "frame_confirm": "100 Punkte für {name}s Goldrahmen ausgeben? Er bleibt für immer.",
    "food_need": "💰 Du brauchst {cost} Punkte (du hast {pts}): gewinn sie in der Welt!",
    "train_cancel": "↩️ Training abgebrochen: {cost} Punkte erstattet.",
    "pick_champ": "Wähle zuerst deinen Champion im Menü oben.",
    "qr_gen_fail": "QR-Generator nicht geladen: lade die Seite mit Internet neu.",
    "qr_read_fail": "QR-Leser nicht geladen: Internet nötig.",
    "cam_fail": "Kamera nicht verfügbar: {m}",
    "qr_invalid": "Ungültiger QR.",
    "qr_self": "Du hast deine eigene Karte gescannt!"
  },
  "moves": {
    "ma_0": "Kratzer",
    "ma_1": "Hinterhalt",
    "ma_2": "Blick",
    "ma_3": "Sprung",
    "ma_4": "Pfotenhieb",
    "ma_5": "Miauen",
    "ma_6": "Angriff",
    "ma_7": "Schnurren",
    "mb_0": "Blitz",
    "mb_1": "Sofa",
    "mb_2": "Verächtlich",
    "mb_3": "Kosmisch",
    "mb_4": "Wild",
    "mb_5": "Nächtlich",
    "mb_6": "4-Uhr",
    "mb_7": "Hypnotisch"
  },
  "instr": {
    "i_pianoforte": "Klavier",
    "i_tromba": "Trompete",
    "i_chitarra": "Gitarre",
    "i_archi": "Streicher",
    "i_organo": "Orgel",
    "i_marimba": "Marimba",
    "theme_line": "{stile} in {ton}, {instr}"
  },
  "breeds": {
    "b_soriano": "Getigert",
    "b_tigrato": "Getigert",
    "b_europeo": "Europäer",
    "b_comune": "Hauskatze",
    "b_certosino": "Kartäuser",
    "b_siamese": "Siam",
    "b_persiano": "Perser",
    "b_mainecoon": "Maine Coon",
    "b_ragdoll": "Ragdoll",
    "b_sphynx": "Sphynx",
    "b_bengala": "Bengal",
    "b_british": "Britisch Kurzhaar",
    "b_norvegese": "Norwegische Waldkatze",
    "b_angora": "Angora",
    "b_birmano": "Heilige Birma",
    "b_abissino": "Abessinier",
    "b_esotico": "Exotic",
    "b_siberiano": "Sibirer",
    "b_scottish": "Scottish Fold",
    "b_rex": "Rex",
    "b_blurusso": "Russisch Blau",
    "b_orientale": "Orientalisch",
    "b_turco": "Türkisch Van",
    "b_savana": "Savannah",
    "b_bombay": "Bombay",
    "c_bianco": "weiß",
    "c_nero": "schwarz",
    "c_grigio": "grau",
    "c_blu": "blau",
    "c_rosso": "rot",
    "c_crema": "creme",
    "c_marrone": "braun",
    "c_fulvo": "falb",
    "c_tartarugato": "schildpatt",
    "c_tricolore": "dreifarbig",
    "c_bicolore": "zweifarbig",
    "c_maculato": "getupft",
    "c_striato": "gestreift",
    "c_pointed": "colourpoint",
    "coat_lungo": "Langhaar",
    "coat_corto": "Kurzhaar"
  },
  "award": {
    "title": "🏆 Die Samstagabend-Awards",
    "host": "Thomas Gottschnurr",
    "subtitle": "Jeden Samstagabend die große Gala: Preise, Punkte und Ruhm für die besten Katzen der Woche.",
    "promo_when": "SAMSTAG, 21:00 UHR",
    "promo_line": "🎬 Nächste Folge mit {host}",
    "promo_cd": "in {d}T {h}h {m}m",
    "promo_soon": "in {h}h {m}m",
    "promo_live": "🔴 Es ist so weit! Die Zeremonie beginnt gleich…",
    "noms_title": "✨ Die Nominierungen dieser Woche",
    "noms_sub": "Wer gerade führt — live",
    "noms_empty": "Noch keine Kämpfe diese Woche. Kämpfe in der Welt, um ins Ranking zu kommen!",
    "past_title": "📼 Frühere Folgen",
    "past_empty": "Die erste Gala ist diesen Samstag. Komm wieder für die Gewinner!",
    "hall_title": "🏛️ Hall of Fame — Rekorde aller Zeiten",
    "hall_empty": "Noch keine Rekorde: jemand wird der Erste sein.",
    "by": "von",
    "pts": "+{p} Pkt",
    "week_of": "Gala vom {d}",
    "aw_mvp": "MVP — Katze der Woche",
    "aw_instancabile": "Unermüdlich",
    "aw_cecchino": "Scharfschütze",
    "aw_dominatore": "Dominator",
    "d_mvp": "meiste Siege",
    "d_instancabile": "meiste Kämpfe",
    "d_cecchino": "beste Quote",
    "d_dominatore": "längste Serie",
    "hof_striscia": "Legendäre Serie",
    "hof_veterano": "Veteran",
    "hof_recordman": "Sieg-Rekordhalter",
    "hof_winrate": "Beste Quote",
    "val_mvp": "{n} Siege",
    "val_instancabile": "{n} Kämpfe",
    "val_cecchino": "{n}%",
    "val_dominatore": "{n}er-Serie",
    "val_striscia": "{n} in Folge",
    "val_veterano": "{n} Kämpfe",
    "val_recordman": "{n} Siege",
    "val_winrate": "{n}%",
    "cer_title": "GROSSE SAMSTAGABEND-GALA",
    "cer_open": "🎩 Meine Damen und Herren… willkommen zur Gala! Ich bin {host}, und heute Abend ehren wir die besten Katzen der Woche!",
    "cer_drumroll": "🥁 Schnurr-Wirbel…",
    "cer_gold": "🥇 Die goldene Pfote geht an… {name}, von {owner}!",
    "cer_silver": "🥈 Silber für {name}, von {owner}.",
    "cer_bronze": "🥉 Bronze für {name}, von {owner}.",
    "cer_pts": "✨ +{p} Punkte!",
    "cer_q_mvp": "Der Siegreichste von allen!",
    "cer_q_instancabile": "Keine Sekunde Pause!",
    "cer_q_cecchino": "Präzise wie ein Scharfschütze!",
    "cer_q_dominatore": "Was für eine Serie!",
    "cer_mvp_finale": "🌟 Und nun der begehrteste Preis des Abends… die Katze der Woche!",
    "cer_close": "🎉 Das war’s für heute! Eine Pfote Applaus für unsere Champions. Bis nächsten Samstag!",
    "cer_none": "Diese Woche keine Preise: zu wenig Kämpfe! Zurück in den Ring.",
    "btn_replay": "🎬 Gala erneut ansehen",
    "btn_skip": "Überspringen ▶▶",
    "cer_preview": "VORSCHAU — laufende Rangliste",
    "pl_1": "Die Nacht, in der Katzen zu Legenden werden.",
    "pl_2": "Smoking, Scheinwerfer und Schnurren — los geht’s!",
    "pl_3": "Neun Leben, eine Bühne.",
    "pl_4": "Wer holt sich die goldene Pfote?",
    "pl_5": "Rotes Trockenfutter und roter Teppich.",
    "pl_6": "Applaus, Konfetti und ein paar Kratzer.",
    "pl_7": "Der eleganteste Samstag der Nachbarschaft.",
    "pl_8": "Nur die zähesten Katzen betreten die Bühne.",
    "pl_9": "Licht, Kamera… miau!",
    "pl_10": "Heute ehren wir, wer am härtesten gekratzt hat.",
    "place_1": "Erster Platz · Gold",
    "place_2": "Zweiter Platz · Silber",
    "place_3": "Dritter Platz · Bronze",
    "full_mvp": "Die Katze mit den meisten Weltsiegen dieser Woche. Einfach die Beste.",
    "full_instancabile": "Hat die meisten Kämpfe bestritten: nie eine Pause, immer im Ring.",
    "full_cecchino": "Die beste Siegquote (mindestens 5 Kämpfe): Präzision, kein Glück.",
    "full_dominatore": "Die längste Serie aufeinanderfolgender Siege der Woche.",
    "react_1": "Was für ein Prankenhieb!",
    "react_2": "Applaus, bitte! 👏",
    "react_3": "Gänsehaut!",
    "react_4": "Ein echtes Phänomen!",
    "react_5": "Was für Klasse!",
    "react_6": "Das Publikum tobt!",
    "cer_podium": "🏆 Und jetzt… das Podium!",
    "cer_suspense": "🥁 …und der Gewinner ist…",
    "cer_hall_intro": "🏛️ Und nun… die Rekorde aller Zeiten!",
    "cer_hall_hold": "Dieser Rekord hält. Was für ein Champion!",
    "cer_record_broken": "Neuer Rekord! {name} wird zur Legende!",
    "rec_new": "NEUER REKORD!",
    "aw_inlizza": "im Rennen",
    "cont_title": "Die Verfolger",
    "cer_contenders": "Und Achtung: nur ein Schnurrhaar vom Podium entfernt!",
    "notif_win": "🏆 Du hast {list} gewonnen! +{pts} Punkte gutgeschrieben.",
    "notif_more": "und {n} weitere",
    "aw_ammazza": "Riesentöter",
    "d_ammazza": "die größte Überraschung",
    "full_ammazza": "Hat einen viel höher eingestuften Gegner besiegt: die Überraschung der Woche.",
    "cer_q_ammazza": "David gegen Goliat!",
    "val_ammazza": "{n} Elo Abstand",
    "aw_beniamino": "Publikumsliebling",
    "d_beniamino": "der meist Herausgeforderte",
    "full_beniamino": "Die Katze, die am häufigsten herausgefordert wurde: ein echter Star.",
    "cer_q_beniamino": "Alle wollen gegen ihn antreten!",
    "val_beniamino": "{n} Herausforderungen",
    "aw_debuttante": "Neuling der Woche",
    "d_debuttante": "bester Neuling",
    "full_debuttante": "Die beste diese Woche erstellte Karte, nach Siegen.",
    "cer_q_debuttante": "Zum Kämpfen geboren!",
    "val_debuttante": "{n} Siege",
    "aw_astro": "Aufsteiger",
    "d_astro": "größter Elo-Anstieg",
    "full_astro": "Wer diese Woche am meisten Elo gewann: im Aufwind.",
    "cer_q_astro": "Unaufhaltsamer Aufstieg!",
    "val_astro": "+{n} Elo",
    "aw_pantofolaio": "Stubenhocker",
    "d_pantofolaio": "hat am wenigsten gekämpft",
    "full_pantofolaio": "Der Spaßpreis: unter den Kämpfern der Faulste.",
    "cer_q_pantofolaio": "Das Sofa ruft!",
    "val_pantofolaio": "nur {n} Kämpfe",
    "hof_piccoelo": "Elo-Höchststand",
    "val_piccoelo": "{n} Elo",
    "hof_regno": "Längste Regentschaft",
    "val_regno": "{n} Tage",
    "hof_muro": "Die Mauer",
    "val_muro": "{n} Titelverteidigungen",
    "hof_pluricampione": "Mehrfachchampion",
    "val_pluricampione": "{n} Titel",
    "hof_novevite": "Die Neun Leben",
    "val_novevite": "Pfad komplett"
  },
  "gang": {
    "login": "Melde dich an, um Clans zu nutzen.",
    "none_title": "🛡️ Die Clans",
    "none_sub": "Tritt einem Clan bei oder gründe deinen eigenen. Zusammen kämpft man im Team.",
    "create": "Gründe deinen Clan",
    "name_ph": "Clan-Name",
    "emblem": "Emblem",
    "create_btn": "🛡️ Clan gründen",
    "board": "📋 Pinnwand — bestehende Clans",
    "board_empty": "Noch keine Clans. Sei der Erste!",
    "members_n": "{n} Mitglieder",
    "cards_n": "{n} Karten",
    "apply": "Anfragen",
    "applied": "✅ Anfrage gesendet",
    "full": "Voll",
    "invites": "✉️ Deine Einladungen",
    "invited_by": "Einladung von {who}",
    "accept": "Annehmen",
    "decline": "Ablehnen",
    "members": "👥 Mitglieder",
    "leader": "👑 Anführer",
    "roster": "🃏 Kader",
    "roster_empty": "Leerer Kader. Füge deine Karten hinzu!",
    "add_card": "➕ Hinzufügen",
    "add_none": "Keine Karten zum Hinzufügen",
    "remove": "Entfernen",
    "apps": "📥 Beitrittsanfragen",
    "apps_empty": "Keine Anfragen.",
    "approve": "Annehmen",
    "reject": "Ablehnen",
    "leave": "🚪 Clan verlassen",
    "disband": "💥 Clan auflösen",
    "leave_confirm": "Clan verlassen?",
    "disband_confirm": "Du bist der Anführer: Verlassen löst den Clan auf. Bestätigen?",
    "created": "🛡️ Clan gegründet!",
    "order_hint": "(der Anführer kann mit ▲▼ umsortieren)",
    "inv_title": "✉️ Spieler einladen",
    "inv_browse": "🔎 Spieler durchsuchen",
    "invite_btn": "Einladen",
    "invited_lbl": "✅ Eingeladen",
    "no_free": "Keine freien Spieler zum Einladen.",
    "search_ph": "Clan suchen…",
    "more": "Mehr laden",
    "open_lbl": "Offen",
    "closed_lbl": "🔒 Geschlossen",
    "browse_others": "📋 Andere Clans durchsuchen",
    "set_open": "🔓 Clan öffnen",
    "set_closed": "🔒 Clan schließen",
    "search_player": "Spieler suchen…",
    "see_cards": "Karten ansehen",
    "back": "Zurück",
    "no_cards": "Keine veröffentlichten Karten.",
    "invite_sent": "✉️ Einladung gesendet!",
    "kick": "Rauswerfen",
    "kick_confirm": "Dieses Mitglied aus dem Clan werfen?",
    "joined_msg": "🛡️ Du bist einem Clan beigetreten!",
    "kicked_msg": "🚪 Du bist nicht mehr im Clan.",
    "changed_msg": "Dein Clan hat sich geändert.",
    "attack": "⚔️ Angreifen",
    "war_won": "🏆 Krieg gewonnen! +30 Clan-Punkte",
    "war_lost": "💥 Krieg verloren. +5 Trostpunkte",
    "no_fresh": "Keine frischen Karten (sie ruhen).",
    "enemy_empty": "Der gegnerische Clan hat keine Karten.",
    "pts": "Pkt",
    "war_confirm": "{name} angreifen? Deine Karten ruhen danach eine Stunde."
  }
};
