/* CatCards — traduzioni EN (generato). Per aggiungere una lingua: copia questo file, traduci i valori, aggiungi il codice a LANGS in index.html) */
(window.LANG_DB = window.LANG_DB || {})["en"] = {
 "ui": {
  "tagline": "Snap your cat and turn it into a collectible card",
  "tab_crea": "📸 Create",
  "tab_carte": "📚 Cards",
  "tab_dojo": "🥋 Dojo",
  "tab_mondo": "🌍 World",
  "tab_mercato": "🔁 Market",
  "tab_boss": "🤖 Bosses",
  "tab_pal": "🏋️ Gym",
  "tab_med": "🏅 Medals",
  "tab_reg": "📖 Rules",
  "drop_title": "Tap to take or upload a photo",
  "drop_sub": "JPG or PNG — best if the cat is clearly visible",
  "cat_name": "Cat's name (optional)",
  "gen_btn": "✨ Create the card",
  "dl_card": "⬇️ Download the card (PNG)",
  "regen_btn": "🔁 Redraw the art (30 points)",
  "new_card": "🔄 New card",
  "coll_title": "📚 Your collection",
  "dojo_title": "🥋 Dojo",
  "your_card": "Your card",
  "opponent": "Opponent",
  "fight_btn": "⚔️ Fight!",
  "tourn4": "🏆 4-cat tourney",
  "tourn8": "🏆 8-cat tourney",
  "albo": "📊 Hall of fame",
  "pub_sum": "🗂️ Choose which cards to publish to the World",
  "player_name": "Your player name (required, min 3 letters)",
  "pub_btn": "📤 Publish selected cards",
  "duel_title": "⚡ Challenge a friend",
  "duel_champ": "Your champion for the duel",
  "qr_show": "📱 Show my QR",
  "qr_scan": "📷 Scan theirs",
  "world_title": "🌍 World Arena",
  "my_world": "🐱 Your cards in the world",
  "my_online": "Your card for online matches",
  "find_btn": "🔄 Find challengers worldwide",
  "leader_title": "🏅 World ranking",
  "leader_more": "⬇️ Show more ranks",
  "market_title": "🔁 Market",
  "trade_title": "🔄 Trade (barter)",
  "trade_browse": "🔍 Browse cards to trade",
  "trader_ask": "💰 Ask the Merchant for advice",
  "auc_title": "⚖️ Auctions",
  "auc_create": "🔨 Put a card up for auction",
  "auc_refresh": "🔄 Refresh auctions",
  "boss_title": "🤖 Arena Bosses",
  "boss_chall": "Your challenger (published cards)",
  "gym_title": "🏋️ Gym",
  "gym_student": "Today's student",
  "gym_pantry": "🍽️ Pantry — buy, then earn it in the minigame",
  "coach_ask": "🎓 Ask the Coach for advice",
  "mis_title": "📅 Today's missions",
  "med_title": "🏅 Medal collection",
  "reg_title": "📖 CatCards rules",
  "opt_title": "⚙️ Options",
  "locked_title": "Sign-in required",
  "locked_txt": "Points, Market, matches and training live on your account: sign in to use Dojo, World, Market, Bosses and Gym.",
  "login_google": "🔵 Sign in with Google",
  "login_hint": "Sign in: points, Market and matches live on your account",
  "logout": "Sign out",
  "close": "✖ Close",
  "skip_intro": "⏭️ Skip the intro",
  "bet_title": "🥊 Uncle Rocco's corner",
  "bet_sub": "🎲 Betting",
  "bet_skip": "No bet, on with the match!",
  "bet_back": "↩️ Go back (cancel the match)",
  "points_lbl": "💰 Your points:",
  "dl_short": "⬇️ Download",
  "nick_btn": "✏️ Change nickname",
  "theme_btn": "▶️ Play theme song",
  "retire_btn": "🚪 Retire from the world",
  "frame_btn": "🎨 Golden Frame (100 points)",
  "del_btn": "🗑️ Delete"
 },
 "stat": {},
 "rarity": {},
 "ann": {
  "red": "From the red corner... {n}... \"{k}\"!",
  "blue": "From the blue corner... {n}... \"{k}\"!"
 },
 "nicks": {
  "n01": "The Tin-Can Socrates",
  "n02": "Baron Crookfang",
  "n03": "The Ember Colossus",
  "n04": "The Asphalt Gladiator",
  "n05": "The Sleeping Softcheese",
  "n06": "The Fleece Monolith",
  "n07": "The Zen Master Licker",
  "n08": "The Unshakable Zen",
  "n09": "The Immovable Soft Fortress",
  "n10": "The Beyond-the-Couch Radar",
  "n11": "The Mischief Radar",
  "n12": "His Hypnotic Softness",
  "n13": "The Purring Veteran",
  "n14": "The Sad Feline Hypnotist",
  "n15": "The Silk Panzer",
  "n16": "The Flaming Muffler",
  "n17": "The Hypnotic Puffball",
  "n18": "The Ginger Claw",
  "n19": "The Centerpiece Blimp",
  "n20": "The Bastion of Fur",
  "n21": "The Steel Cheek",
  "n22": "The Couch Phantom",
  "n23": "The Understairs Fury",
  "n24": "The Fur Tornado",
  "n25": "The Pantry Shadow",
  "n26": "The Windowsill Ninja",
  "n27": "The Tawny Avalanche",
  "n28": "The Curtain Assassin",
  "n29": "The Terror of Yarn Balls",
  "n30": "The Lazy Locomotive",
  "n31": "The Radiator Philosopher",
  "n32": "The Hurricane in Slippers",
  "n33": "The Living-Room Cheetah",
  "n34": "The Refrigerator Sphinx",
  "n35": "The Sly Lightning",
  "n36": "The Killer Pillow",
  "n37": "The Balcony Beast",
  "n38": "General Scratch",
  "n39": "The Midnight Acrobat",
  "n40": "The Sultan of Naps",
  "n41": "The Carpet Tiger",
  "n42": "The Staircase Ghost",
  "n43": "The Couch Destroyer",
  "n44": "The Landing Panther",
  "n45": "The Baron of Morsels",
  "n46": "The Emperor of the Basket",
  "n47": "The Fresh-Fish Pirate",
  "n48": "The Plush Thunderbolt",
  "n49": "The Kibble Champion",
  "n50": "The Attic Strategist",
  "n51": "The Slipper Monster",
  "n52": "The Clawed Duchess",
  "n53": "The Velvet Viking",
  "n54": "The Whiskered Enigma",
  "n55": "The Silent Cyclone",
  "n56": "The Paw of Destiny",
  "n57": "The Cardboard King",
  "n58": "The Permanent Ambush",
  "n59": "The Soft Meteorite",
  "n60": "The Courtyard Legend",
  "n61": "The Bowl Guardian",
  "n62": "The Eye of the Night",
  "n63": "The Scruffy Samurai",
  "n64": "The Tricolor Fury",
  "n65": "The Professor of Ambushes",
  "n66": "The Admiral of the Rooftops",
  "n67": "The Steamroller",
  "n68": "The Elegant Pest",
  "n69": "The Sleepy Volcano",
  "n70": "The Velvet Claw",
  "n71": "The Kitchen Bandit",
  "n72": "The Fridge Sentinel",
  "n73": "The Cushion Dragon",
  "n74": "The Echo of the Meow",
  "n75": "The Master of Purrs",
  "n76": "The Pocket Tempest",
  "n77": "The Gentle Giant",
  "n78": "The Last Stray",
  "n79": "The Lizard Hunter",
  "n80": "The Ninth Life"
 },
 "descrs": {
  "d01": "Sleeps 20 hours a day and spends the other 4 training to sleep better.",
  "d02": "Has never lost a battle against a sock.",
  "d03": "Believes the refrigerator owes him an explanation.",
  "d04": "Master of the art of occupying exactly where you wanted to sit.",
  "d05": "Knocked over three vases. All of them guilty.",
  "d06": "Speaks three languages: purr, meow and contempt.",
  "d07": "Runs at 4 a.m. for reasons beyond our understanding.",
  "d08": "A born warrior, as long as the couch is within two meters.",
  "d09": "His bowl is half empty. Always. Even when full.",
  "d10": "Stares at the wall because the wall started it.",
  "d11": "Former stray, now a senior executive of napping.",
  "d12": "Purrs like a tractor and scratches like a razor.",
  "d13": "The vet still remembers him in his nightmares.",
  "d14": "Doesn't chase mice: serves eviction notices.",
  "d15": "Can open three kinds of doors and pretends he can't.",
  "d16": "The box is worth more than the gift. Always.",
  "d17": "Holds a PhD in judgmental stares.",
  "d18": "Fights crime. The crime is the vacuum cleaner.",
  "d19": "Every chair in the house is his. Including yours.",
  "d20": "Trains on the curtains when nobody's watching.",
  "d21": "Favorite hobby: elegantly knocking things off tables.",
  "d22": "Meows in C minor when the bowl is empty.",
  "d23": "No one ever sees him coming. Only leaving with dinner.",
  "d24": "Weighs exactly enough to pin your legs down.",
  "d25": "The neighborhood lizards have put a bounty on him.",
  "d26": "Sleeps in positions that defy physics and common sense.",
  "d27": "Figured out the laser pointer. Pretends otherwise out of pity.",
  "d28": "A cross between a pillow and a bear trap.",
  "d29": "Surveys the neighborhood from the window like a head of state.",
  "d30": "His purrs cure stress. His claws cause it.",
  "d31": "Eats like a wolf, sleeps like a rock, reigns like a king.",
  "d32": "The only cat who ever won an argument with a cucumber.",
  "d33": "Gets offended if you look at him. Gets offended if you don't.",
  "d34": "Has three secret hideouts. The best one: the middle of the hallway.",
  "d35": "Fell into a bowl of cream as a kitten. Never recovered.",
  "d36": "Teaches yoga to neighborhood cats. Lesson one: ignore everyone.",
  "d37": "The mailman requested a transfer.",
  "d38": "Collects hair ties. Nobody knows where he hides them.",
  "d39": "When a storm hits, he protects the house. From under the bed.",
  "d40": "His stare has scared off two dogs and a plumber.",
  "d41": "Lives for three things: eating, sleeping and judging you.",
  "d42": "Once saw a mouse. They both still talk about it.",
  "d43": "Extremely elegant until he falls off the windowsill.",
  "d44": "Adopted a family of humans. Training them well.",
  "d45": "He doesn't climb on the table. The table lowers itself to him.",
  "d46": "Knows exactly when you open the tuna. Even from a block away.",
  "d47": "The yarn ball was already like that when he got there.",
  "d48": "Half cat, half 5 a.m. alarm siren.",
  "d49": "Fights with honor, wins with style, sleeps without shame.",
  "d50": "The last thing carpets see before the end."
 }
};
