(window.LANG_DB=window.LANG_DB||{})["de"] = {
  "ui": {
    "tagline": "Fotografiere deine Katze und mach sie zur Sammelkarte",
    "tab_crea": "📸 Neu",
    "tab_carte": "📚 Karten",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Welt",
    "tab_mercato": "🔁 Markt",
    "tab_boss": "🤖 Bosse",
    "tab_pal": "🏋️ Studio",
    "tab_med": "🏅 Medaillen",
    "tab_reg": "📖 Regeln",
    "drop_title": "Tippe, um ein Foto zu machen oder hochzuladen",
    "drop_sub": "JPG oder PNG — die Katze sollte gut sichtbar sein",
    "cat_name": "Name der Katze (optional)",
    "gen_btn": "✨ Karte erstellen",
    "dl_card": "⬇️ Karte herunterladen (PNG)",
    "regen_btn": "🔁 Bild neu zeichnen (30 Punkte)",
    "new_card": "🔄 Neue Karte",
    "coll_title": "📚 Deine Sammlung",
    "dojo_title": "🥋 Dojo",
    "your_card": "Deine Karte",
    "opponent": "Gegner",
    "fight_btn": "⚔️ Kämpfen!",
    "tourn4": "🏆 4er-Turnier",
    "tourn8": "🏆 8er-Turnier",
    "albo": "📊 Ehrentafel",
    "pub_sum": "🗂️ Wähle Karten für die Welt",
    "player_name": "Dein Spielername (Pflicht, mind. 3 Buchstaben)",
    "pub_btn": "📤 Ausgewählte Karten veröffentlichen",
    "duel_title": "⚡ Fordere einen Freund heraus",
    "duel_champ": "Dein Champion fürs Duell",
    "qr_show": "📱 Meinen QR zeigen",
    "qr_scan": "📷 Seinen scannen",
    "world_title": "🌍 Welt-Arena",
    "my_world": "🐱 Deine Karten in der Welt",
    "my_online": "Deine Karte für Online-Kämpfe",
    "find_btn": "🔄 Gegner weltweit suchen",
    "leader_title": "🏅 Weltrangliste",
    "leader_more": "⬇️ Mehr Plätze anzeigen",
    "market_title": "🔁 Markt",
    "trade_title": "🔄 Tausch",
    "trade_browse": "🔍 Karten zum Tauschen ansehen",
    "trader_ask": "💰 Den Händler um Rat fragen",
    "auc_title": "⚖️ Auktionen",
    "auc_create": "🔨 Karte versteigern",
    "auc_refresh": "🔄 Auktionen aktualisieren",
    "boss_title": "🤖 Arena-Bosse",
    "boss_chall": "Dein Herausforderer (veröffentlichte Karten)",
    "gym_title": "🏋️ Trainingsstudio",
    "gym_student": "Der Schüler des Tages",
    "gym_pantry": "🍽️ Vorrat — kaufen, dann im Spiel verdienen",
    "coach_ask": "🎓 Den Coach um Rat fragen",
    "mis_title": "📅 Heutige Missionen",
    "med_title": "🏅 Medaillensammlung",
    "reg_title": "📖 Die CatCards-Regeln",
    "opt_title": "⚙️ Einstellungen",
    "locked_title": "Anmeldung erforderlich",
    "locked_txt": "Punkte, Markt, Kämpfe und Training hängen an deinem Konto: melde dich an für Dojo, Welt, Markt, Bosse und Studio.",
    "login_google": "🔵 Mit Google anmelden",
    "login_hint": "Anmelden: Punkte, Markt und Kämpfe hängen an deinem Konto",
    "logout": "Abmelden",
    "close": "✖ Schließen",
    "skip_intro": "⏭️ Vorstellung überspringen",
    "bet_title": "🥊 Onkel Roccos Ecke",
    "bet_sub": "🎲 Wette",
    "bet_skip": "Keine Wette, auf in den Kampf!",
    "bet_back": "↩️ Zurück (Kampf abbrechen)",
    "points_lbl": "💰 Deine Punkte:",
    "dl_short": "⬇️ Herunterladen",
    "nick_btn": "✏️ Spitznamen ändern",
    "theme_btn": "▶️ Titelmusik abspielen",
    "retire_btn": "🚪 Aus der Welt zurückziehen",
    "frame_btn": "🎨 Goldrahmen (100 Punkte)",
    "del_btn": "🗑️ Löschen"
  },
  "stat": {},
  "rarity": {},
  "ann": {
    "red": "Aus der roten Ecke... {n}... „{k}\"!",
    "blue": "Aus der blauen Ecke... {n}... „{k}\"!"
  },
  "nicks": {
    "n01": "Der Dosen-Sokrates",
    "n02": "Baron Schiefzahn",
    "n03": "Der Glut-Koloss",
    "n04": "Der Asphalt-Gladiator",
    "n05": "Der Schlafende Weichkäse",
    "n06": "Der Plüsch-Monolith",
    "n07": "Der Zen-Leckermeister",
    "n08": "Der Unerschütterliche Zen",
    "n09": "Die Unbewegliche Weiche Festung",
    "n10": "Das Hinterm-Sofa-Radar",
    "n11": "Das Unheil-Radar",
    "n12": "Seine Hypnotische Weichheit",
    "n13": "Der Schnurr-Veteran",
    "n14": "Der Traurige Katzenhypnotiseur",
    "n15": "Der Seiden-Panzer",
    "n16": "Der Feurige Auspuff",
    "n17": "Der Hypnotische Wattebausch",
    "n18": "Die Ingwer-Kralle",
    "n19": "Der Tisch-Zeppelin",
    "n20": "Die Fell-Bastion",
    "n21": "Die Stahlwange",
    "n22": "Das Sofagespenst",
    "n23": "Die Wut aus der Abstellkammer",
    "n24": "Der Fell-Tornado",
    "n25": "Der Schatten der Speisekammer",
    "n26": "Der Fensterbrett-Ninja",
    "n27": "Die Rote Lawine",
    "n28": "Der Gardinen-Killer",
    "n29": "Der Schrecken der Wollknäuel",
    "n30": "Die Faule Lokomotive",
    "n31": "Der Heizkörper-Philosoph",
    "n32": "Der Orkan in Pantoffeln",
    "n33": "Der Wohnzimmer-Gepard",
    "n34": "Die Kühlschrank-Sphinx",
    "n35": "Der Verschmitzte Blitz",
    "n36": "Das Killer-Kissen",
    "n37": "Die Balkon-Bestie",
    "n38": "General Kratzer",
    "n39": "Der Mitternachts-Akrobat",
    "n40": "Der Sultan des Nickerchens",
    "n41": "Der Teppich-Tiger",
    "n42": "Das Treppengespenst",
    "n43": "Der Sofa-Zerstörer",
    "n44": "Der Treppenabsatz-Panther",
    "n45": "Der Baron der Häppchen",
    "n46": "Der Kaiser des Körbchens",
    "n47": "Der Frischfisch-Pirat",
    "n48": "Der Plüsch-Blitz",
    "n49": "Der Trockenfutter-Champion",
    "n50": "Der Dachboden-Stratege",
    "n51": "Das Pantoffel-Monster",
    "n52": "Die Bekrallte Herzogin",
    "n53": "Der Samt-Wikinger",
    "n54": "Das Schnurrbart-Rätsel",
    "n55": "Der Stille Wirbelsturm",
    "n56": "Die Pfote des Schicksals",
    "n57": "Der Karton-König",
    "n58": "Der Dauerhinterhalt",
    "n59": "Der Weiche Meteorit",
    "n60": "Die Hof-Legende",
    "n61": "Der Napf-Wächter",
    "n62": "Das Auge der Nacht",
    "n63": "Der Zerzauste Samurai",
    "n64": "Die Dreifarbige Furie",
    "n65": "Der Professor der Hinterhalte",
    "n66": "Der Admiral der Dächer",
    "n67": "Die Dampfwalze",
    "n68": "Die Elegante Plage",
    "n69": "Der Schläfrige Vulkan",
    "n70": "Die Samtkralle",
    "n71": "Der Küchen-Bandit",
    "n72": "Der Kühlschrank-Wachposten",
    "n73": "Der Kissen-Drache",
    "n74": "Das Echo des Miauens",
    "n75": "Der Meister des Schnurrens",
    "n76": "Der Taschensturm",
    "n77": "Der Sanfte Riese",
    "n78": "Der Letzte Streuner",
    "n79": "Der Eidechsen-Jäger",
    "n80": "Das Neunte Leben"
  },
  "descrs": {
    "d01": "Schläft 20 Stunden am Tag und trainiert die anderen 4, besser zu schlafen.",
    "d02": "Hat noch nie einen Kampf gegen eine Socke verloren.",
    "d03": "Glaubt, der Kühlschrank schulde ihm eine Erklärung.",
    "d04": "Meister darin, genau den Platz zu besetzen, wo du sitzen wolltest.",
    "d05": "Hat drei Vasen umgeworfen. Alle waren schuldig.",
    "d06": "Spricht drei Sprachen: Schnurren, Miau und Verachtung.",
    "d07": "Rennt um 4 Uhr morgens aus Gründen, die wir nie erfahren werden.",
    "d08": "Ein geborener Krieger, solange das Sofa keine zwei Meter entfernt ist.",
    "d09": "Sein Napf ist halb leer. Immer. Auch wenn er voll ist.",
    "d10": "Starrt die Wand an, weil die Wand angefangen hat.",
    "d11": "Ehemaliger Streuner, jetzt Führungskraft im Nickerchen-Wesen.",
    "d12": "Schnurrt wie ein Traktor und kratzt wie ein Rasiermesser.",
    "d13": "Der Tierarzt sieht ihn noch in seinen Albträumen.",
    "d14": "Jagt keine Mäuse: verschickt Räumungsbescheide.",
    "d15": "Kann drei Arten von Türen öffnen und tut so, als ob nicht.",
    "d16": "Der Karton ist mehr wert als das Geschenk. Immer.",
    "d17": "Hat einen Doktortitel in vorwurfsvollen Blicken.",
    "d18": "Bekämpft das Verbrechen. Das Verbrechen ist der Staubsauger.",
    "d19": "Jeder Stuhl im Haus gehört ihm. Auch deiner.",
    "d20": "Trainiert an den Gardinen, wenn niemand hinsieht.",
    "d21": "Lieblingshobby: Dinge elegant vom Tisch werfen.",
    "d22": "Miaut in c-Moll, wenn der Napf leer ist.",
    "d23": "Niemand sieht ihn kommen. Nur mit dem Abendessen verschwinden.",
    "d24": "Wiegt genau so viel, wie nötig ist, um deine Beine festzunageln.",
    "d25": "Die Eidechsen der Nachbarschaft haben ein Kopfgeld auf ihn ausgesetzt.",
    "d26": "Schläft in Positionen, die Physik und Verstand trotzen.",
    "d27": "Hat den Laserpointer durchschaut. Tut aus Mitleid so, als ob nicht.",
    "d28": "Eine Kreuzung aus Kissen und Bärenfalle.",
    "d29": "Überwacht die Nachbarschaft vom Fenster aus wie ein Staatsoberhaupt.",
    "d30": "Sein Schnurren heilt Stress. Seine Krallen verursachen ihn.",
    "d31": "Frisst wie ein Wolf, schläft wie ein Stein, herrscht wie ein König.",
    "d32": "Die einzige Katze, die je eine Diskussion mit einer Gurke gewonnen hat.",
    "d33": "Ist beleidigt, wenn du ihn ansiehst. Und wenn nicht, auch.",
    "d34": "Hat drei Geheimverstecke. Das beste: mitten im Flur.",
    "d35": "Fiel als Kätzchen in eine Schüssel Sahne. Hat sich nie davon erholt.",
    "d36": "Lehrt Nachbarskatzen Yoga. Erste Lektion: alle ignorieren.",
    "d37": "Der Postbote hat um Versetzung gebeten.",
    "d38": "Sammelt Haargummis. Niemand weiß, wo er sie versteckt.",
    "d39": "Bei Gewitter beschützt er das Haus. Von unterm Bett aus.",
    "d40": "Sein Blick hat zwei Hunde und einen Klempner vertrieben.",
    "d41": "Lebt für drei Dinge: fressen, schlafen und dich verurteilen.",
    "d42": "Sah einmal eine Maus. Beide erzählen noch heute davon.",
    "d43": "Höchst elegant, bis er vom Fensterbrett fällt.",
    "d44": "Hat eine Menschenfamilie adoptiert. Die Erziehung läuft gut.",
    "d45": "Er springt nicht auf den Tisch. Der Tisch senkt sich zu ihm herab.",
    "d46": "Weiß genau, wann du die Thunfischdose öffnest. Auch einen Block entfernt.",
    "d47": "Das Wollknäuel war schon so, als er ankam.",
    "d48": "Halb Katze, halb 5-Uhr-Alarmsirene.",
    "d49": "Kämpft mit Ehre, siegt mit Stil, schläft ohne Scham.",
    "d50": "Das Letzte, was Teppiche vor ihrem Ende sehen."
  },
  "battle": {
    "skip": "⏭️ Vorstellung übersprungen: ab in den Kampf!",
    "open": "🎤 MEINE DAMEN UND HERREEEN… willkommen in der CatCards-Arena!",
    "red": "🔴 Rote Ecke: {NAME}, „{nick}\"! {rec}",
    "blue": "🔵 Blaue Ecke: {NAME}, „{nick}\"! {rec}",
    "debut": "Beim Arena-Debüt!",
    "theme": "🎵 {name}s Einzugsmelodie erklingt…",
    "ding": "🔔 DING DING DING!",
    "first_fast": "⚡ {name} ist schneller und schlägt zuerst zu!",
    "first_surprise": "😼 {name} überrascht alle und legt los!",
    "round_end": "🔔 Ende von Runde {round}! Die Katzen kehren in ihre Ecken zurück…",
    "charmed_skip": "😍 {name} ist verzaubert und verliert den Zug!",
    "chant": "🎺 Von den Rängen: „{NAME}! {NAME}!\"",
    "pu_yarn": "🧶 Ein Wollknäuel rollt herein! {name} spielt und heilt {hp} HP",
    "pu_catnip": "🌿 Katzenminze! {name} dreht auf: nächster Treffer VERDOPPELT (aber leicht benommen…)",
    "pu_box": "📦 Ein Karton! {name} kann nicht widerstehen: setzt aus, ist aber UNBERÜHRBAR!",
    "pu_fish": "🐟 Ein frischer Fisch fliegt herein! {name} sprüht vor Energie: +Agilität für 3 Züge",
    "purr_heal": "💗 {name} schnurrt und heilt {hp} HP",
    "double_paw": "🐾 Doppelter Pfotenschlag! {name} greift erneut an!",
    "box_dodge": "📦 {opp} versteckt sich im Karton: {name}s Treffer geht daneben!",
    "dodge": "💨 {name} versucht {move}, doch {opp} weicht aus!",
    "final_blow": "⏱️ Die Zeit verlangsamt sich… ENDSCHLAG!",
    "hit": "{icon} {name} setzt {move} ein!{crit}{catnip}  −{dmg} HP",
    "crit_tag": " 💥 KRITISCH!",
    "catnip_tag": " 🌿 VERSTÄRKT!",
    "dev1": "😱 Verheerender Treffer!",
    "dev2": "🎙️ Das Publikum rast!",
    "dev3": "💢 Was für eine Wucht!",
    "on_fire": "🔥 {name} ist HEISS! Drei Treffer in Folge!",
    "on_ropes": "🎙️ {opp} ist in den Seilen! Das Publikum hält den Atem an…",
    "clever": "✨ Cleverer Zug! {opp} ist verwirrt und verliert einen Zug!",
    "nine_lives": "🐈 {opp} nutzt eines seiner Neun Leben und bleibt mit 1 HP stehen!",
    "charm_hit": "✨ {opp} erliegt {name}s Charme!",
    "replay": "📹 WIEDERHOLUNG des Endschlags…",
    "winner": "🏆 {name} gewinnt den Kampf!",
    "win_points": "💰 +10 Punkte für den Sieg!",
    "boss_points": "💰 +10 Punkte: du hast einen Arena-Boss bezwungen!",
    "boss_noprize": "🎖️ Boss heute schon besiegt: Ruhm ja, Belohnung morgen.",
    "boss_survives": "🤖 Der Boss bleibt stehen... der heutige Versuch ist weg: bis morgen (vielleicht mit Katzenminze 🌿).",
    "tourn_champ": "👑 {name} ist der Turnier-CHAMPION!",
    "world_ok": "🌍 Ergebnis in der Welt-Arena gespeichert!",
    "bet_win": "🎲 Richtig getippt! Du hast {stake} auf {name} gesetzt: +{gain} Punkte (gesamt: {total})",
    "bet_lose": "🎲 Falsch getippt: −{stake} Punkte (gesamt: {total}). Nächstes Mal!",
    "stake": "🎁 Auf dem Spiel — Sieg: {win} · Niederlage: +{lose} XP",
    "stake_pts": "+{pt} Punkte und +{xp} XP",
    "stake_nopts": "+{xp} XP (keine Punkte lokal)",
    "boss_stake_note": " — Punkte nur beim ersten Sieg des Tages",
    "entry_catnip": "🌿 {name} betritt die Arena schon voll Katzenminze!"
  },
  "chars": {
    "rocco_warn": "Pass auf seine {stat} auf: da frisst er dich.",
    "rocco_70": "Junge, den legst du vor dem Gong um. Werd nicht übermütig — mach's schnell.",
    "rocco_55": "Du bist Favorit, aber Favoriten, die pennen, landen auf der Matte. Schlag zuerst zu.",
    "rocco_50": "Fifty-fifty, Junge: hier gewinnt der Hungrigere. Wenn du 50 Punkte hast, ist die Katzenminze jeden wert.",
    "rocco_35": "Ich lüg nicht: er ist größer als du. Ohne Katzenminze würde ich den Kampf lassen.",
    "rocco_lose": "Hör auf den alten Rocco: der bricht dich. Zurück ins Studio, ein Level hoch, DANN reden wir. Wenn's sein muss, wenigstens die Katzenminze.",
    "baratto_great": "🤑 Ein Schnäppchen! Du kriegst viel mehr, als du gibst — mach schnell.",
    "baratto_good": "👍 Guter Deal: du machst Plus. Der Händler nickt.",
    "baratto_even": "⚖️ Fairer Tausch: entscheide mit dem Herzen, nicht dem Geldbeutel.",
    "baratto_bad": "😾 Du verlierst etwas... sicher? Dem Händler zucken die Schnurrhaare.",
    "baratto_terrible": "🙀 Mieser Deal! Du gibst viel mehr, als du bekommst. Vergiss es.",
    "baratto_empty": "Keine Karten zum Tauschen! Mach welche und komm wieder: der Basar ist für Geschäfte, nicht für Almosen.",
    "inc_100a": "HUNDERT PUNKTE! Herrlicher Wahnsinn! 😼",
    "inc_100b": "Ein königliches Gebot! Und wer wagt jetzt mehr?",
    "inc_50a": "Fünfzig! Das Publikum zittert, meine Herrschaften!",
    "inc_50b": "Schöne Summe! Die Auktion wird heiß!",
    "inc_bata": "Und noch ein Gebot! Die hören nicht mehr auf!",
    "inc_batb": "Ein Kampf bis zum letzten Punkt — was für ein Spektakel!",
    "inc_starta": "Erstes Gebot am Pult! Wer bietet mehr?",
    "inc_startb": "Los geht's! Zugeschlagen, wer nicht aufgibt!",
    "baffo_open": [
      "Miau, Rekrut! ",
      "Hör auf den alten Baffo: ",
      "Spuck das Trockenfutter aus und hör zu: ",
      "Zu meiner Zeit gab es keine weichen Kissen. ",
      "Schnurrhaare gerade, Ohren gespitzt: "
    ],
    "baffo_empty": "Das Studio ist leer! Bring mir einen Schüler aus dem Tab 📸 Neu.",
    "baffo_indiff_afford": "{name}s Schwäche ist {stat} ({val}): trainiere sie mit dem Combo {combo} (60 Punkte) — kannst du dir leisten.",
    "baffo_indiff_save": "{name}s Schwäche ist {stat} ({val}), aber die trainiert nur mit dem Combo {combo} (60 Punkte): dir fehlen {miss} — spar sie an.",
    "baffo_indiff_alt": " Oder stärke inzwischen {stat2} ({val2}) mit {food} (25 Punkte).",
    "baffo_weak": "{name}s schwächster Wert ist {stat} ({val}): gib ihm {food}.",
    "baffo_combo": "Du hast {pts} Punkte: der Combo {combo} ({tgt}) steigert zwei Werte in einer Pause — teuer, aber praktisch, wenn's eilt.",
    "baffo_record_bad": "Mit {w} Siegen und {l} Niederlagen braucht er Biss, keine Streicheleinheiten.",
    "baffo_unbeaten": "Er ist ungeschlagen: pass auf, dass er nicht abhebt.",
    "baffo_margin": "Trainingsspielraum aufgebraucht: nur Siege in der Welt schalten mehr frei.",
    "baffo_broke": "Und die Kasse ist leer ({pts} Punkte): gewinn ein paar Welt-Wetten.",
    "baffo_fit": "{name} ist topfit. Lass ihn kämpfen — die Bank macht die Muskeln weich.",
    "felini_open": [
      "Hör auf den Manager: ",
      "Ich wittere ein Geschäft: ",
      "Der Ring ist ein Schachbrett: ",
      "Die Zahlen sprechen, Junge: "
    ],
    "felini_checking": "Einen Moment, ich sehe in den Unterlagen nach…",
    "felini_noauth": "Melde dich zuerst an, Junge: Geschäfte macht man mit einem Namen auf dem Vertrag.",
    "felini_nocard": "Du hast keinen veröffentlichten Champion. Veröffentliche eine Karte, dann reden wir übers Geschäft.",
    "felini_resting": "😴 {name} erholt sich gerade: komm zurück, wenn er wieder bereit ist, dann reden wir über Strategie.",
    "felini_norank": "Dein Champion taucht nicht im Ranking auf: veröffentliche ihn neu und komm wieder zu mir.",
    "felini_loss_streak": "{name} hat {n} in Folge verloren (🧊): nimm ihn eine Weile aus dem Verkehr, bring ihn zu dem Coach, und lass ihn hungrig zurückkommen.",
    "felini_champ": "{name} ist der CHAMPION 👑: verteidige die Krone{chaser}.",
    "felini_chaser": ", und pass auf {name} auf (#2, {elo} Pkt.), der schon scharrt",
    "felini_target": "der richtige nächste Kampf für {name} (#{rk}) ist {tname} von {owner} (#{trk}, {elo} Pkt.): {verdict}",
    "felini_v_risky": "riskant, aber schlägst du ihn, machst du im Ranking den großen Sprung.",
    "felini_v_beatable": "auf dem Papier schlagbar: ein Sieg des Managements.",
    "felini_v_even": "ein ausgeglichener Kampf, wie ihn das Publikum liebt.",
    "felini_prob_low": "Aber reden wir Klartext: Onkel Rocco schätzt deine Siegchance auf nur {p}%. Ich würde warten — Training, ein Level mehr, DANN unterschreiben wir den Vertrag.",
    "felini_prob_mid": "Die Wahrscheinlichkeit sagt {p}%: offener Kampf, die Nerven entscheiden (und vielleicht die Katzenminze 🌿).",
    "felini_prob_high": "Onkel Rocco schätzt {p}% Siegchance: machbar. Geh und mach den Kampf klar.",
    "felini_belt": "Und merk dir: der hat den GÜRTEL 👑 — das Ranking zählt nichts, schlägst du ihn, bist DU der Champion.",
    "felini_hot": "Aber Vorsicht: ein zäher Gegner, kommt aus einer Serie von {n} Siegen 🔥.",
    "felini_cold": "Und ich sag dir: er steckt tief in der Krise (🧊 {n} Niederlagen in Folge) — der perfekte Moment zuzuschlagen.",
    "felini_catnip_need": "Mein Rat von der Ringecke: investier 50 Punkte in Katzenminze 🌿 vor dem Kampf — gegen so einen brauchst du den Turbo.",
    "felini_catnip_broke": "Katzenminze 🌿 wäre nötig, aber die Kasse weint ({pts} Punkte): entweder du findest Punkte oder du wählst ein weicheres Ziel.",
    "felini_catnip_opt": "Katzenminze 🌿? Optional: ausgeglichener Kampf, die Nerven entscheiden.",
    "felini_catnip_no": "Keine Katzenminze: der schafft es auf eigenen Pfoten, spar dir die Punkte.",
    "felini_notarget": "gerade kein Ziel von anderen Besitzern über dir (oder alle ruhen sich aus): verteidige die Position oder schau später wieder vorbei.",
    "felini_margin": "Und er hat noch {n} Punkte Trainingsspielraum: eine gute Mahlzeit vor dem Kampf hat noch keinem geschadet.",
    "trader_open": [
      "Psst, Freund: ",
      "Geschäfte, Geschäfte! ",
      "Der Händler weiß alles: ",
      "Unter uns Kennern: "
    ],
    "trader_best": "halt {name} gut fest, die ist Gold wert: gib sie nicht für ein paar Münzen her.",
    "trader_worst": "wenn du wirklich etwas hergeben musst, fang mit {name} an — du hast Besseres in der Hand.",
    "trader_commons": "Du hast einen Haufen {rar} ({n}): tausch ein paar gegen etwas Selteneres, glaub mir.",
    "trader_gem": "Und pass auf: da ist eine {rar} von {owner} in der Auslage — wenn du ein gutes Duplikat hast, versuch den Tausch, bevor ein anderer sie schnappt.",
    "trader_browse": "Drück auf «Karten zum Tauschen durchstöbern» und zeig mir, was so umgeht: ich sag dir, ob ein Geschäft dabei ist."
  }
};
