(window.LANG_DB=window.LANG_DB||{})["fr"] = {
  "ui": {
    "tagline": "Photographie ton chat et transforme-le en carte à collectionner",
    "tab_crea": "📸 Créer",
    "tab_carte": "📚 Cartes",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Monde",
    "tab_mercato": "🔁 Marché",
    "tab_boss": "🤖 Boss",
    "tab_pal": "🏋️ Salle",
    "tab_med": "🏅 Médailles",
    "tab_reg": "📖 Règles",
    "drop_title": "Touche pour prendre ou charger une photo",
    "drop_sub": "JPG ou PNG — l'idéal : un chat bien visible",
    "cat_name": "Nom du chat (facultatif)",
    "gen_btn": "✨ Générer la carte",
    "dl_card": "⬇️ Télécharger la carte (PNG)",
    "regen_btn": "🔁 Regénérer le dessin (30 points)",
    "new_card": "🔄 Nouvelle carte",
    "coll_title": "📚 Ta collection",
    "dojo_title": "🥋 Dojo",
    "your_card": "Ta carte",
    "opponent": "Adversaire",
    "fight_btn": "⚔️ Combat !",
    "tourn4": "🏆 Tournoi à 4",
    "tourn8": "🏆 Tournoi à 8",
    "albo": "📊 Palmarès",
    "pub_sum": "🗂️ Choisis les cartes à publier dans le Monde",
    "player_name": "Ton pseudo (obligatoire, 3 lettres min)",
    "pub_btn": "📤 Publier les cartes choisies",
    "duel_title": "⚡ Défie un ami",
    "duel_champ": "Ton champion pour le duel",
    "qr_show": "📱 Montrer mon QR",
    "qr_scan": "📷 Scanner le sien",
    "world_title": "🌍 Arène Mondiale",
    "my_world": "🐱 Tes cartes dans le monde",
    "my_online": "Ta carte pour les défis en ligne",
    "find_btn": "🔄 Chercher des adversaires",
    "leader_title": "🏅 Classement mondial",
    "leader_more": "⬇️ Voir plus de positions",
    "market_title": "🔁 Marché",
    "trade_title": "🔄 Échange (troc)",
    "trade_browse": "🔍 Parcourir les cartes",
    "trader_ask": "💰 Demander conseil au Marchand",
    "auc_title": "⚖️ Enchères",
    "auc_create": "🔨 Mettre une carte aux enchères",
    "auc_refresh": "🔄 Actualiser les enchères",
    "boss_title": "🤖 Boss de l'Arène",
    "boss_chall": "Ton challenger (cartes publiées)",
    "gym_title": "🏋️ Salle de sport",
    "gym_student": "L'élève du jour",
    "gym_pantry": "🍽️ Garde-manger — achète, puis mérite-le en jouant",
    "coach_ask": "🎓 Demander conseil au Coach",
    "mis_title": "📅 Missions du jour",
    "med_title": "🏅 Médailler",
    "reg_title": "📖 Les règles de CatCards",
    "opt_title": "⚙️ Options",
    "locked_title": "Connexion requise",
    "locked_txt": "Points, Marché, défis et entraînements vivent sur ton compte : connecte-toi pour utiliser Dojo, Monde, Marché, Boss et Salle.",
    "login_google": "🔵 Connexion avec Google",
    "login_hint": "Connecte-toi : points, Marché et défis vivent sur ton compte",
    "logout": "Déconnexion",
    "close": "✖ Fermer",
    "skip_intro": "⏭️ Passer la présentation",
    "bet_title": "🥊 Le coin de Tonton Rocco",
    "bet_sub": "🎲 Pronostic",
    "bet_skip": "Pas de pari, place au match !",
    "bet_back": "↩️ Retour (annuler le match)",
    "points_lbl": "💰 Tes points:",
    "dl_short": "⬇️ Télécharger",
    "nick_btn": "✏️ Changer le surnom",
    "theme_btn": "▶️ Écouter le thème",
    "retire_btn": "🚪 Retirer du monde",
    "frame_btn": "🎨 Cadre d'Or (100 points)",
    "del_btn": "🗑️ Supprimer",
    "coach_greet": "Miaou, recrue. Choisis un élève et mettons-nous au travail.",
    "gym_combo": "🌟 Combo Premium — deux stats, un seul repos",
    "bet_choose": "Choisis la mise et sur qui parier. Si tu te trompes, tu perds la mise.",
    "bet_insufficient": "Pas assez de points pour parier (minimum 10).",
    "tab_sent": "🗺️ Sentier",
    "opt_ai_sum": "🤖 Paramètres IA",
    "opt_key_label": "Clé API Gemini",
    "opt_test_key": "🧪 Tester la clé",
    "opt_backup_label": "Sauvegarde de la collection",
    "opt_export": "💾 Exporter la sauvegarde",
    "opt_import": "📂 Importer la sauvegarde",
    "opt_gift_label": "🎁 Code cadeau",
    "opt_redeem": "Échanger les points",
    "opt_av_label": "Audio et présentations",
    "snd_on": "🔊 Sons : ON",
    "snd_off": "🔇 Sons : OFF",
    "pres_on": "🎬 Présentations : ON",
    "pres_skip": "⏭️ Présentations : SAUTÉES",
    "bt_bracket": "📋 Tableau",
    "qr_desc1": "Duel en direct, téléphone contre téléphone : il compte pour les points, médailles et paris comme un défi mondial.",
    "qr_desc2": "L'un montre le QR, l'autre le scanne : le duel se joue sur le téléphone de celui qui scanne.",
    "coll_one": "1 carte enregistrée",
    "coll_many": "{n} cartes enregistrées",
    "coll_none": "Aucune carte pour l'instant : crées-en une dans l'onglet 📸 Créer, ou importe une sauvegarde depuis ⚙️ Options.",
    "xp_line": "📈 Niveau {lvl} — {inLvl}/100 XP (≈ {w} victoires mondiales pour le niv.{next})",
    "opt_ai_desc": "Sans clé API j'utilise un filtre cartoon intégré et gratuit. Avec une clé <strong>Google Gemini</strong> le cartoon est généré par l'IA (bien meilleure qualité). Crée-la gratuitement sur <strong>aistudio.google.com</strong> → « Get API key ».",
    "tab_award": "🏆 Awards",
    "publish_btn": "🌍 Publier dans le Monde",
    "pub_moved": "Pour publier ou retirer une carte, touche-la dans l’onglet 📚 Cartes.",
    "ask_name_title": "Comment t’appelles-tu ?",
    "ask_name_desc": "Le nom que verront les adversaires (min 3 lettres).",
    "ask_name_ok": "Enregistrer et publier",
    "ask_name_cancel": "Annuler",
    "hub_fight": "Combattre",
    "hub_cards": "Cartes",
    "hub_glory": "Gloire",
    "hub_social": "Social",
    "tab_opz": "⚙️ Options",
    "tab_gang": "🛡️ Gang",
    "in_clan": "Dans {name}",
    "withdraw_clan": "Retirer",
    "withdraw_confirm": "Retirer cette carte du clan ?",
    "withdraw_done": "Carte retirée du clan.",
    "tab_terr": "🗺️ Territoire"
  },
  "stat": {
    "Forza": "Force",
    "Intelligenza": "Intelligence",
    "Destrezza": "Adresse",
    "Velocità": "Vitesse",
    "Fascino": "Charme",
    "Indifferenza": "Indifférence"
  },
  "rarity": {
    "Comune": "Commune",
    "Rara": "Rare",
    "Epica": "Épique",
    "Leggendaria": "Légendaire"
  },
  "ann": {
    "red": "Dans le coin rouge... {n}... «{k}»!",
    "blue": "Dans le coin bleu... {n}... «{k}»!"
  },
  "nicks": {
    "n01": "Le Socrate de la Boîte",
    "n02": "Le Baron Croc-Tordu",
    "n03": "Le Colosse de la Braise",
    "n04": "Le Gladiateur de l'Asphalte",
    "n05": "Le Fromage Dormant",
    "n06": "Le Monolithe de Peluche",
    "n07": "Le Maître Lécheur Zen",
    "n08": "L'Imperturbable Zen",
    "n09": "La Forteresse Douce Inamovible",
    "n10": "Le Radar de l'Outre-Canapé",
    "n11": "Le Radar des Ennuis",
    "n12": "Sa Douceur Hypnotique",
    "n13": "Le Vétéran du Ronron",
    "n14": "Le Triste Hypnotiseur Félin",
    "n15": "Le Panzer de Soie",
    "n16": "Le Pot d'Échappement Enflammé",
    "n17": "La Boule Hypnotique",
    "n18": "La Griffe au Gingembre",
    "n19": "Le Dirigeable de Table",
    "n20": "Le Bastion de Poils",
    "n21": "La Joue d'Acier",
    "n22": "Le Fantôme du Canapé",
    "n23": "La Furie du Sous-Escalier",
    "n24": "La Tornade de Poils",
    "n25": "L'Ombre du Garde-Manger",
    "n26": "Le Ninja du Rebord",
    "n27": "L'Avalanche Fauve",
    "n28": "Le Tueur de Rideaux",
    "n29": "La Terreur des Pelotes",
    "n30": "La Locomotive Paresseuse",
    "n31": "Le Philosophe du Radiateur",
    "n32": "L'Ouragan en Pantoufles",
    "n33": "Le Guépard de Salon",
    "n34": "Le Sphinx du Frigo",
    "n35": "L'Éclair Sournois",
    "n36": "Le Coussin Tueur",
    "n37": "La Bête du Balcon",
    "n38": "Le Général Griffe",
    "n39": "L'Acrobate de Minuit",
    "n40": "Le Sultan de la Sieste",
    "n41": "Le Tigre de la Moquette",
    "n42": "Le Fantôme de l'Escalier",
    "n43": "Le Destructeur de Canapés",
    "n44": "La Panthère du Palier",
    "n45": "Le Baron des Bouchées",
    "n46": "L'Empereur du Panier",
    "n47": "Le Pirate du Poisson Frais",
    "n48": "L'Éclair en Peluche",
    "n49": "Le Champion des Croquettes",
    "n50": "Le Stratège du Grenier",
    "n51": "Le Monstre des Pantoufles",
    "n52": "La Duchesse Griffue",
    "n53": "Le Viking Velouté",
    "n54": "L'Énigme à Moustaches",
    "n55": "Le Cyclone Silencieux",
    "n56": "La Patte du Destin",
    "n57": "Le Roi du Carton",
    "n58": "L'Embuscade Permanente",
    "n59": "La Météorite Moelleuse",
    "n60": "La Légende de la Cour",
    "n61": "Le Gardien de la Gamelle",
    "n62": "L'Œil de la Nuit",
    "n63": "Le Samouraï Pelé",
    "n64": "La Furie Tricolore",
    "n65": "Le Professeur d'Embuscades",
    "n66": "L'Amiral des Toits",
    "n67": "Le Rouleau Compresseur",
    "n68": "La Peste Élégante",
    "n69": "Le Volcan Somnolent",
    "n70": "La Griffe de Velours",
    "n71": "Le Bandit de la Cuisine",
    "n72": "La Sentinelle du Frigo",
    "n73": "Le Dragon du Coussin",
    "n74": "L'Écho du Miaulement",
    "n75": "Le Maître du Ronronnement",
    "n76": "La Tempête de Poche",
    "n77": "Le Doux Géant",
    "n78": "Le Dernier Errant",
    "n79": "Le Chasseur de Lézards",
    "n80": "La Neuvième Vie"
  },
  "descrs": {
    "d01": "Dort 20 heures par jour et s'entraîne à mieux dormir les 4 autres.",
    "d02": "N'a jamais perdu une bataille contre une chaussette.",
    "d03": "Pense que le frigo lui doit des explications.",
    "d04": "Maître dans l'art d'occuper exactement la place où tu voulais t'asseoir.",
    "d05": "A renversé trois vases. Tous coupables.",
    "d06": "Parle trois langues : ronron, miaou et mépris.",
    "d07": "Court à 4h du matin pour des raisons qui nous dépassent.",
    "d08": "Un guerrier né, tant que le canapé est à moins de deux mètres.",
    "d09": "Sa gamelle est à moitié vide. Toujours. Même pleine.",
    "d10": "Fixe le mur parce que le mur a commencé.",
    "d11": "Ancien errant, désormais cadre supérieur de la sieste.",
    "d12": "Ronronne comme un tracteur et griffe comme un rasoir.",
    "d13": "Le vétérinaire le revoit encore dans ses cauchemars.",
    "d14": "Ne chasse pas les souris : envoie des avis d'expulsion.",
    "d15": "Sait ouvrir trois types de portes et fait semblant de ne pas savoir.",
    "d16": "La boîte vaut plus que le cadeau. Toujours.",
    "d17": "Docteur en regards de jugement.",
    "d18": "Combat le crime. Le crime, c'est l'aspirateur.",
    "d19": "Chaque chaise de la maison est à lui. Même la tienne.",
    "d20": "S'entraîne sur les rideaux quand personne ne regarde.",
    "d21": "Passe-temps favori : faire tomber des objets avec élégance.",
    "d22": "Miaule en do mineur quand la gamelle est vide.",
    "d23": "Personne ne l'a vu arriver. Seulement repartir avec le dîner.",
    "d24": "Pèse juste ce qu'il faut pour bloquer tes jambes.",
    "d25": "Les lézards du quartier ont mis sa tête à prix.",
    "d26": "Dort dans des positions qui défient la physique et le bon sens.",
    "d27": "A compris le laser. Fait semblant par pitié.",
    "d28": "Un croisement entre un coussin et un piège à loup.",
    "d29": "Surveille le quartier depuis la fenêtre comme un chef d'État.",
    "d30": "Son ronron soigne le stress. Ses griffes le provoquent.",
    "d31": "Mange comme un loup, dort comme une pierre, règne comme un roi.",
    "d32": "Le seul chat à avoir gagné un débat contre un concombre.",
    "d33": "Se vexe si tu le regardes. Se vexe si tu ne le regardes pas.",
    "d34": "A trois cachettes secrètes. La meilleure : le milieu du couloir.",
    "d35": "Tombé dans un bol de crème étant petit. Ne s'en est jamais remis.",
    "d36": "Enseigne le yoga aux chats du quartier. Leçon un : ignorer tout le monde.",
    "d37": "Le facteur a demandé sa mutation.",
    "d38": "Collectionne les élastiques. Personne ne sait où il les cache.",
    "d39": "Quand l'orage gronde, il protège la maison. De sous le lit.",
    "d40": "Son regard a fait fuir deux chiens et un plombier.",
    "d41": "Vit pour trois choses : manger, dormir et te juger.",
    "d42": "A vu une souris un jour. Ils en parlent encore tous les deux.",
    "d43": "Très élégant jusqu'à ce qu'il tombe du rebord.",
    "d44": "A adopté une famille d'humains. Il les dresse bien.",
    "d45": "Il ne monte pas sur la table. La table descend à son niveau.",
    "d46": "Sait exactement quand tu ouvres le thon. Même à un pâté de maisons.",
    "d47": "La pelote était déjà comme ça à son arrivée.",
    "d48": "Moitié chat, moitié sirène d'alarme de 5h du matin.",
    "d49": "Se bat avec honneur, gagne avec style, dort sans honte.",
    "d50": "La dernière chose que voient les tapis avant la fin."
  },
  "battle": {
    "skip": "⏭️ Présentation zappée : droit au but !",
    "open": "🎤 MESDAMES ET MESSIEUUURS… bienvenue dans l'Arène CatCards !",
    "red": "🔴 Coin rouge : {NAME}, «{nick}» ! {rec}",
    "blue": "🔵 Coin bleu : {NAME}, «{nick}» ! {rec}",
    "debut": "Pour ses débuts dans l'arène !",
    "theme": "🎵 Le thème d'entrée de {name} retentit…",
    "ding": "🔔 DING DING DING !",
    "first_fast": "⚡ {name} est plus rapide et frappe en premier !",
    "first_surprise": "😼 {name} surprend tout le monde et commence !",
    "round_end": "🔔 Fin du round {round} ! Les chats regagnent leur coin pour se lécher…",
    "charmed_skip": "😍 {name} est envoûté et perd son tour !",
    "chant": "🎺 Des tribunes : «{NAME} ! {NAME} !»",
    "pu_yarn": "🧶 Une pelote roule dans l'arène ! {name} joue et récupère {hp} PV",
    "pu_catnip": "🌿 Herbe à chat ! {name} est excité : prochain coup DOUBLÉ (mais un peu dans les vapes…)",
    "pu_box": "📦 Un carton ! {name} ne résiste pas : passe son tour mais devient INTOUCHABLE !",
    "pu_fish": "🐟 Un poisson frais vole dans l'arène ! {name} pétille d'énergie : +agilité pour 3 tours",
    "purr_heal": "💗 {name} ronronne et récupère {hp} PV",
    "double_paw": "🐾 Double Coup de Patte ! {name} attaque encore !",
    "box_dodge": "📦 {opp} est planqué dans le carton : le coup de {name} rate !",
    "dodge": "💨 {name} tente {move} mais {opp} esquive !",
    "final_blow": "⏱️ Le temps ralentit… COUP FINAL !",
    "hit": "{icon} {name} utilise {move} !{crit}{catnip}  −{dmg} PV",
    "crit_tag": " 💥 CRITIQUE !",
    "catnip_tag": " 🌿 BOOSTÉ !",
    "dev1": "😱 Coup dévastateur !",
    "dev2": "🎙️ Le public est en délire !",
    "dev3": "💢 Quelle puissance !",
    "on_fire": "🔥 {name} est EN FEU ! Trois coups d'affilée !",
    "on_ropes": "🎙️ {opp} est dans les cordes ! Le public retient son souffle…",
    "clever": "✨ Ruse ! {opp} est confus et perdra un tour !",
    "nine_lives": "🐈 {opp} utilise une de ses Neuf Vies et reste debout avec 1 PV !",
    "charm_hit": "✨ {opp} est envoûté par le charme de {name} !",
    "replay": "📹 REPLAY du coup final…",
    "winner": "🏆 {name} remporte le combat !",
    "win_points": "💰 +10 points pour la victoire !",
    "boss_points": "💰 +10 points : tu as dompté un Boss de l'Arène !",
    "boss_noprize": "🎖️ Boss déjà battu aujourd'hui : la gloire oui, la récompense demain.",
    "boss_survives": "🤖 Le Boss reste debout... l'essai du jour est perdu : à demain (avec de l'herbe à chat 🌿, peut-être).",
    "tourn_champ": "👑 {name} est le CHAMPION du tournoi !",
    "world_ok": "🌍 Résultat enregistré dans l'Arène Mondiale !",
    "bet_win": "🎲 Bien vu ! Tu avais misé {stake} sur {name} : +{gain} points (total : {total})",
    "bet_lose": "🎲 Mauvais pronostic : −{stake} points (total : {total}). La prochaine fois !",
    "stake": "🎁 En jeu — victoire : {win} · défaite : +{lose} XP",
    "stake_pts": "+{pt} points et +{xp} XP",
    "stake_nopts": "+{xp} XP (aucun point en local)",
    "boss_stake_note": " — points seulement à la 1re victoire du jour",
    "entry_catnip": "🌿 {name} entre dans l arène déjà gonflé à l herbe à chat !"
  },
  "chars": {
    "rocco_warn": "Méfie-toi de sa {stat} : c'est là qu'il te bouffe.",
    "rocco_70": "Petit, tu le mets K.O. avant le gong. Fais pas le malin, termine vite.",
    "rocco_55": "Tu es favori, mais les favoris qui dorment finissent au tapis. Frappe le premier.",
    "rocco_50": "Cinquante-cinquante, petit : ça se joue à qui a le plus faim. Si t'as 50 points, l'herbe à chat les vaut tous.",
    "rocco_35": "Je te mens pas : il est plus costaud. Sans herbe à chat, je ferais pas ce combat.",
    "rocco_lose": "Écoute le vieux Rocco : celui-là te brise. Retourne à la salle, prends un niveau, on en reparle APRÈS. Si tu y tiens, au moins l'herbe à chat.",
    "baratto_great": "🤑 Une affaire en or ! Tu reçois bien plus que tu ne donnes — conclus vite.",
    "baratto_good": "👍 Bonne affaire : tu y gagnes. Le Marchand approuve.",
    "baratto_even": "⚖️ Échange équitable : décide avec le cœur, pas le portefeuille.",
    "baratto_bad": "😾 Tu y perds un peu... t'es sûr ? Le Marchand fronce les moustaches.",
    "baratto_terrible": "🙀 Affaire catastrophique ! Tu donnes bien plus que tu ne reçois. Laisse tomber.",
    "baratto_empty": "Aucune carte à troquer ! Fabriques-en et reviens : au bazar on fait des affaires, pas la charité.",
    "inc_100a": "CENT POINTS ! Quelle folie magnifique ! 😼",
    "inc_100b": "Une offre royale ! Et qui ose surenchérir ?",
    "inc_50a": "Cinquante ! Le public frémit, mesdames et messieurs !",
    "inc_50b": "Belle somme ! L'enchère s'échauffe !",
    "inc_bata": "Et ça surenchérit encore ! Ils ne s'arrêtent plus !",
    "inc_batb": "Un combat au dernier point, quel spectacle !",
    "inc_starta": "Première offre sur le billot ! Qui dit mieux ?",
    "inc_startb": "C'est parti ! Adjugé à celui qui ne lâche rien !",
    "baffo_open": [
      "Miaou, recrue ! ",
      "Écoute le vieux Baffo : ",
      "Recrache la croquette et écoute : ",
      "De mon temps, pas de coussins moelleux. ",
      "Moustaches droites, oreilles dressées : "
    ],
    "baffo_empty": "La salle est vide ! Amène-moi un élève depuis l'onglet 📸 Créer.",
    "baffo_indiff_afford": "Le point faible de {name}, c'est {stat} ({val}) : entraîne-la avec le combo {combo} (60 points), tu peux te le permettre.",
    "baffo_indiff_save": "Le point faible de {name}, c'est {stat} ({val}), mais ça ne s'entraîne qu'avec le combo {combo} (60 points) : il te manque {miss} points, mets-les de côté.",
    "baffo_indiff_alt": " Ou en attendant, renforce {stat2} ({val2}) avec {food} (25 points).",
    "baffo_weak": "Le point le plus faible de {name}, c'est {stat} ({val}) : donne-lui {food}.",
    "baffo_combo": "Tu as {pts} points : le combo {combo} ({tgt}) fait grimper deux choses en un seul repos — cher mais pratique si tu es pressé.",
    "baffo_record_bad": "Avec {w} victoires et {l} défaites, il lui faut du cran, pas des câlins.",
    "baffo_unbeaten": "Il est invaincu : gare à ce qu'il ne prenne pas la grosse tête.",
    "baffo_margin": "Marge d'entraînement épuisée : seules les victoires dans le Monde débloquent des progrès.",
    "baffo_broke": "Et les caisses sont vides ({pts} points) : gagne quelques paris mondiaux.",
    "baffo_fit": "{name} est en pleine forme. Fais-le combattre, le banc ramollit les muscles.",
    "felini_open": [
      "Écoute le Manager : ",
      "J’ai flairé l’affaire : ",
      "Le ring est un échiquier : ",
      "Les chiffres parlent, petit : "
    ],
    "felini_checking": "Un instant, je consulte les registres…",
    "felini_noauth": "Connecte-toi d’abord, petit : les affaires se font avec un nom sur le contrat.",
    "felini_nocard": "Tu n’as pas de champion publié. Publie une carte et parlons affaires.",
    "felini_resting": "😴 {name} récupère : reviens quand il sera de nouveau prêt et on parlera stratégie.",
    "felini_norank": "Ton champion n’apparaît pas au classement : republie-le et reviens me voir.",
    "felini_loss_streak": "{name} a perdu {n} de suite (🧊) : retire-le du circuit un moment, emmène-le chez le Coach, et fais-le revenir affamé.",
    "felini_champ": "{name} est le CHAMPION 👑 : défends la couronne{chaser}.",
    "felini_chaser": ", et méfie-toi de {name} (#2, {elo} pts) qui piaffe",
    "felini_target": "le bon prochain combat pour {name} (#{rk}) c’est {tname} de {owner} (#{trk}, {elo} pts) : {verdict}",
    "felini_v_risky": "risqué, mais si tu le bats tu fais un carton au classement.",
    "felini_v_beatable": "sur le papier il est prenable : une victoire de gestion.",
    "felini_v_even": "un combat à égalité, de ceux que le public adore.",
    "felini_prob_low": "Mais soyons clairs : Tonton Rocco estime tes chances à seulement {p}%. J’attendrais — la salle, un niveau de plus, ENSUITE on signe le contrat.",
    "felini_prob_mid": "Les probabilités disent {p}% : match ouvert, les nerfs décideront (et peut-être l’herbe à chat 🌿).",
    "felini_prob_high": "Tonton Rocco estime {p}% de victoire : à ta portée. Vas-y et boucle le match.",
    "felini_belt": "Et retiens : celui-là a la CEINTURE 👑 — le classement ne compte pas, tu le bats et c’est TOI le champion.",
    "felini_hot": "Attention quand même : c’est un adversaire coriace, sur une série de {n} victoires 🔥.",
    "felini_cold": "Et je te le dis : il est en pleine crise (🧊 {n} défaites de suite) — le moment parfait pour frapper.",
    "felini_catnip_need": "Mon conseil du coin du ring : investis 50 points dans l’herbe à chat 🌿 avant le match — contre un pareil il faut le turbo.",
    "felini_catnip_broke": "Il faudrait de l’herbe à chat 🌿, mais les caisses pleurent ({pts} points) : soit tu trouves des points, soit tu choisis une cible plus tendre.",
    "felini_catnip_opt": "De l’herbe à chat 🌿 ? Facultatif : match à égalité, les nerfs décideront.",
    "felini_catnip_no": "Pas d’herbe à chat : il s’en sort avec ses propres pattes, garde tes points.",
    "felini_notarget": "aucune cible d’autres propriétaires au-dessus de toi pour l’instant (ou ils se reposent tous) : défends ta position, ou repasse plus tard.",
    "felini_margin": "Et il lui reste encore {n} points de marge à la salle : un bon repas avant le match n’a jamais tué personne.",
    "trader_open": [
      "Psst, l’ami : ",
      "Affaires, affaires ! ",
      "Le Marchand sait tout : ",
      "Entre nous qui nous y connaissons : "
    ],
    "trader_best": "garde bien {name}, celle-là vaut de l’or : ne la cède pas pour trois francs.",
    "trader_worst": "s’il faut vraiment donner quelque chose, commence par {name} — tu as mieux en main.",
    "trader_commons": "Tu as un tas de {rar} ({n}) : échange-en deux contre quelque chose de plus rare, crois-moi.",
    "trader_gem": "Et attention : il y a une {rar} de {owner} en vitrine — si tu as un bon double, tente l’échange avant qu’un autre ne la prenne.",
    "trader_browse": "Appuie sur «Parcourir les cartes à échanger» et montre-moi ce qui circule : je te dis s’il y a une affaire.",
    "rocco_catnip": "🌿 Bravo petit. Maintenant entre là-dedans et montre-leur : le premier coup sera un train.",
    "baffo_all_rest": "😴 Tous tes élèves se reposent : reviens quand l'un d'eux est prêt et on se met au travail."
  },
  "titles": {
    "world": "DÉFI MONDIAL",
    "live": "DUEL EN DIRECT",
    "boss": "BOSS DE L'ARÈNE",
    "quarti": "QUARTS DE FINALE",
    "semi": "DEMI-FINALE",
    "finale": "FINALE",
    "sentiero": "LE SENTIER"
  },
  "gym": {
    "lbl_allena": "Entraîne :",
    "lbl_start": "▶️ Commence l'entraînement !",
    "fn_croc": "Croquettes",
    "fn_pollo": "Poulet",
    "fn_topo": "Souriceau",
    "fn_erba": "Herbe à chat",
    "fn_pesce": "Poisson",
    "fn_chicche": "Friandises",
    "fn_bistecca": "Steak du Guerrier",
    "fn_scarica": "Décharge Féline",
    "fn_fascino": "Charme Fatal",
    "fn_trono": "Trône de Plumes",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Force",
    "ft_topo": "🧠 Intelligence",
    "ft_erba": "🎯 Adresse",
    "ft_pesce": "⚡ Vitesse",
    "ft_chicche": "✨ Charme",
    "ft_bistecca": "💪 Force + ❤️ HP",
    "ft_scarica": "⚡ Vitesse + 🎯 Adresse",
    "ft_fascino": "✨ Charme + 🧠 Intelligence",
    "ft_trono": "😼 Indifférence + ❤️ HP",
    "gn_gomitolo": "Attrape la pelote",
    "gn_topo": "Chasse à la souris",
    "gn_piuma": "Suis la plume",
    "gn_corda": "Tir à la corde",
    "gn_porta": "Enfonce la porte",
    "gn_laser": "Chasse au laser",
    "gn_memory": "Memory des boîtes",
    "gn_pesca": "Pêche éclair",
    "gn_scatto": "Sprint félin",
    "gn_scalata": "Escalade de la bibliothèque",
    "gn_fusa": "Rythme du ronron",
    "gn_sfilata": "Le Défilé",
    "gn_zen": "Zen du chat",
    "gn_sguardi": "Concours de regards",
    "ga_gomitolo": "Agilité — 🌿 herbe à chat (Adresse) et 🐟 poisson (Vitesse)",
    "ga_topo": "Physique — 🍗 poulet (Force) et 🥫 croquettes (HP)",
    "ga_piuma": "Mental — 🐁 souriceau (Intelligence) et 🧀 friandises (Charme)",
    "ga_corda": "Force — 🍗 poulet (Force)",
    "ga_porta": "Force — 🍗 poulet (Force)",
    "ga_laser": "Adresse — 🌿 herbe à chat (Adresse)",
    "ga_memory": "Intelligence — 🐁 souriceau (Intelligence)",
    "ga_pesca": "Vitesse — 🐟 poisson (Vitesse)",
    "ga_scatto": "Vitesse — 🐟 poisson (Vitesse)",
    "ga_scalata": "HP — 🥫 croquettes (HP)",
    "ga_fusa": "Charme — 🧀 friandises (Charme)",
    "ga_sfilata": "Charme — 🧀 friandises (Charme)",
    "ga_zen": "Indifférence — 🛋️ coussin royal (Indifférence)",
    "ga_sguardi": "Indifférence — 🛋️ coussin royal (Indifférence)",
    "gd_gomitolo": "La pelote file dans le cadre et accélère à chaque prise : touche-la le plus de fois possible en <strong>10 secondes</strong>.<br>🚫 Moins de 5 prises : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_topo": "Les souris surgissent de leurs trous et disparaissent aussitôt : frappe-les dès qu'elles apparaissent, pendant <strong>15 secondes</strong>.<br>🚫 Moins de 5 coups : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_piuma": "Les plumes colorées clignotent en séquence : répète-la en les touchant dans le même ordre. À chaque tour la séquence s'allonge ; une erreur met fin à l'entraînement.<br>🚫 Moins de 3 tours : nourriture gâchée · ✅ 3-4 : bonus ×1 · 🌟 5+ : bonus ×2",
    "gd_corda": "Martèle le bouton <strong>TIRE</strong> pour traîner le gros chien au-delà de la ligne : il tire en arrière sans cesse, ne lâche pas pendant <strong>10 secondes</strong>.<br>🚫 Moins de 8 à-coups : nourriture gâchée · ✅ 8-15 : bonus ×1 · 🌟 16+ : bonus ×2",
    "gd_porta": "La barre de puissance file d'avant en arrière : touche quand elle est dans la <strong>zone verte</strong> pour charger le coup de patte. Frappe le plus fort possible en <strong>12 secondes</strong>.<br>🚫 Moins de 5 bons coups : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_laser": "Le point rouge apparaît et disparaît de plus en plus vite : touche-le avant qu'il ne s'efface, pendant <strong>12 secondes</strong>.<br>🚫 Moins de 6 prises : nourriture gâchée · ✅ 6-11 : bonus ×1 · 🌟 12+ : bonus ×2",
    "gd_memory": "Retourne les cartes deux par deux et associe les paires identiques de mémoire, en <strong>30 secondes</strong>.<br>🚫 Moins de 3 paires : nourriture gâchée · ✅ 3-4 : bonus ×1 · 🌟 5+ : bonus ×2",
    "gd_pesca": "Le poisson file sous l'eau et n'affleure qu'un instant : touche-le <strong>juste quand il saute</strong>. Les fenêtres se raccourcissent. Tu as <strong>14 secondes</strong>.<br>🚫 Moins de 5 prises : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_scatto": "Attends le <strong>vert</strong> et touche le plus vite possible : on mesure ton réflexe. 5 tours — partir trop tôt fait perdre le tour.<br>🚫 Moins de 2 bons sprints : nourriture gâchée · ✅ 2-3 : bonus ×1 · 🌟 4+ : bonus ×2",
    "gd_scalata": "Le chat saute d'étagère en étagère : touche <strong>quand la plateforme est alignée</strong> pour sauter dessus. Un saut raté et tu tombes. Monte le plus haut possible.<br>🚫 Moins de 5 étagères : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_fusa": "Le cercle se resserre en rythme : touche <strong>quand il atteint la cible</strong>, au rythme du ronron. Plus tu es précis, plus le rythme accélère.<br>🚫 Moins de 5 touches dans le rythme : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_sfilata": "Sur le podium apparaît une flèche : <strong>balaie (swipe) dans sa direction</strong> pour prendre la pose. Les flèches arrivent de plus en plus vite, tu as <strong>16 secondes</strong>.<br>🚫 Moins de 6 poses : nourriture gâchée · 🌟 12+ : bonus ×2",
    "gd_zen": "La discipline de l'indifférence : <strong>ignore chaque distraction</strong> (🐭 souris, 🪶 plume, 🔴 laser) et touche <strong>seulement le coussin 🛋️</strong> quand il apparaît. Toucher une distraction fait perdre le tour. Tu as <strong>14 secondes</strong>.<br>🚫 Moins de 5 coussins : nourriture gâchée · ✅ 5-9 : bonus ×1 · 🌟 10+ : bonus ×2",
    "gd_sguardi": "<strong>Maintiens</strong> et ne bouge pas : celui qui reste impassible gagne. Mais si un 😹 chatouille apparaît tu dois <strong>lâcher aussitôt</strong>, puis rappuyer. Tiens le plus longtemps possible.<br>🚫 Moins de 8 secondes d'impassibilité : nourriture gâchée · ✅ 8-13 : bonus ×1 · 🌟 14+ : bonus ×2",
    "tr_wasted_h": "🙀 Nourriture gâchée !",
    "tr_wasted_b": "Score : <strong>{score}</strong> — sous le seuil minimum.<br><br>{ic} Le {food} est perdu et {name} se repose maintenant une heure.<br><br>😼 <em>«De mon temps on s'entraînait les yeux bandés.»</em>",
    "tr_coach_wasted": "🙀 Seulement {score} points ?! Nourriture gâchée.",
    "tr_perfect_h": "🌟 Entraînement parfait !",
    "tr_ok_h": "✅ Entraînement réussi !",
    "tr_bonus2": " — bonus doublé !",
    "tr_online": "🌍 Carte aussi mise à jour dans l'Arène Mondiale.<br>",
    "tr_body": "Score : <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> pour {name}</span><br><br>{online}😴 Maintenant une heure de repos : les muscles grandissent en dormant.",
    "tr_coach_perfect": "😼 {score} points ! {name} a l'étoffe d'un champion.",
    "tr_coach_ok": "👍 {score} points, du bon travail. {name} progresse.",
    "gi_none": "Aucun élève : crée d'abord une carte.",
    "gi_info": "Niv.{lv} · marge d'entraînement : <strong>{used}/{cap}</strong> utilisée <span style=\"color:var(--muted)\">(+3 par niveau : on monte en gagnant dans le monde)</span>",
    "gi_resting": "<br>😴 Il se repose : reviens dans {min} minutes",
    "gi_ready": "<br>✅ Prêt à s'entraîner !",
    "gi_nofood": "😼 Le Coach : « Pas de nourriture pour {name} : marge d'entraînement épuisée. Gagne des combats pour monter de niveau (+3 de marge par niveau), puis on repasse à table. »",
    "gi_pick_opt": "— choisis un élève —",
    "gi_pick": "👉 Choisis un élève ci-dessus pour commencer.",
    "gi_pick_alert": "Choisis d'abord un élève dans le menu ci-dessus."
  },
  "powers": {
    "pn_0": "Neuf Vies",
    "pn_1": "Embuscade Parfaite",
    "pn_2": "Ronron Régénérant",
    "pn_3": "Double Coup de Patte",
    "pn_4": "Mode Liquide",
    "pn_5": "Regard Hypnotique",
    "pn_6": "Armure de Paresse",
    "pn_7": "Chaos Félin",
    "pd_0": "la première fois qu'il est KO il reste à 1 HP",
    "pd_1": "sa première attaque est toujours critique",
    "pd_2": "récupère des HP à chacun de ses tours",
    "pd_3": "25% de chance d'attaquer deux fois",
    "pd_4": "esquive bien plus souvent",
    "pd_5": "charme avec le double de chances",
    "pd_6": "subit 20% de dégâts en moins",
    "pd_7": "ses dégâts sont imprévisibles (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Gagne 1 défi mondial",
    "m_world2": "Gagne 2 défis mondiaux",
    "m_fight3": "Livre 3 combats (les locaux comptent aussi)",
    "m_tourn": "Gagne un tournoi (à 4 ou à 8)",
    "m_upset": "L'Exploit : bats dans le monde un adversaire avec un Elo supérieur au tien",
    "m_train1": "Termine un entraînement réussi",
    "m_gom10": "Fais 10+ à Attrape la pelote",
    "m_topo10": "Fais 10+ à Chasse à la souris",
    "m_piuma5": "Atteins 5 tours à Suis la plume",
    "m_boss": "Dompte un Boss de l'Arène",
    "m_bet": "Gagne un pari",
    "m_catnip": "Gagne un combat en partant avec l'herbe à chat",
    "m_card": "Crée une nouvelle carte",
    "m_qr": "Joue un duel en direct (QR)",
    "a_prima_carta_nm": "Première carte",
    "a_prima_carta_ds": "Crée ta première carte",
    "a_coll5_nm": "Collectionneur",
    "a_coll5_ds": "5 cartes en collection",
    "a_coll10_nm": "Fou de chats",
    "a_coll10_ds": "10 cartes en collection",
    "a_epica_nm": "Quelle rareté !",
    "a_epica_ds": "Obtiens une carte Épique",
    "a_legg_nm": "Légendaire !",
    "a_legg_ds": "Obtiens une Légendaire",
    "a_win1_nm": "Première victoire",
    "a_win1_ds": "Gagne un défi mondial",
    "a_win10_nm": "Vétéran",
    "a_win10_ds": "Gagne 10 défis mondiaux",
    "a_win50_nm": "Légende",
    "a_win50_ds": "Gagne 50 défis mondiaux",
    "a_t4_nm": "Champion",
    "a_t4_ds": "Gagne un tournoi à 4",
    "a_t8_nm": "Dominateur",
    "a_t8_ds": "Gagne un tournoi à 8",
    "a_pub_nm": "Dans le monde",
    "a_pub_ds": "Publie une carte",
    "a_wwin_nm": "Triplé",
    "a_wwin_ds": "Gagne 3 défis mondiaux d'affilée",
    "a_bet_nm": "Bookmaker",
    "a_bet_ds": "Gagne un pari",
    "a_ricco_nm": "Richard",
    "a_ricco_ds": "Possède 150 points",
    "a_onore_nm": "Retraite honorable",
    "a_onore_ds": "Retire une carte au bilan positif",
    "a_disfatta_nm": "Déroute",
    "a_disfatta_ds": "Perds 10 défis mondiaux d'affilée",
    "bm_ds": "Bats {name} (Div. {tier})",
    "bmall_nm": "Tueur de Boss",
    "bmall_ds": "Bats les 64 Boss de l'Arène",
    "cx_rar4": "Le carré : une carte pour chaque rareté",
    "cx_razze3": "Découvre 3 races différentes",
    "cx_razze5": "Découvre 5 races différentes",
    "cx_razze10": "Découvre 10 races différentes",
    "cx_pot4": "Collectionne 4 pouvoirs spéciaux différents",
    "cx_pot8": "Collectionne les 8 pouvoirs spéciaux",
    "cx_lv5": "Amène un chat au niveau 5",
    "cx_hp100": "Une carte avec 100+ HP",
    "cx_oro": "Une carte avec le Cadre d'Or",
    "p_done": "fait",
    "p_won": "✓ obtenue",
    "p_towin": "🔒 à obtenir",
    "p_howto": "Comment l'obtenir :",
    "p_reward": "Récompense :",
    "p_unlocked": "Débloquée le",
    "cx_open": "(touche pour ouvrir)",
    "cx_h_rar": "💎 Rareté",
    "cx_h_pow": "🌟 Pouvoirs spéciaux",
    "cx_h_breeds": "🐱 Races découvertes",
    "cx_nobreeds": "Aucune pour l'instant : la race vient de l'analyse IA de la photo.",
    "cx_h_objs": "🎯 Objectifs",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> objectifs <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex : {ic} {txt} ! +{pt} points",
    "mis_tris_line": "🎉 Trio complété : +10 points bonus encaissés. À demain !",
    "mis_toast_tris": "🎉 TRIO ! Mission «{txt}» et journée complète : +5 et +10 bonus !",
    "mis_toast_done": "📅 Mission accomplie : {ic} {txt} ! +5 points",
    "med_toast": "🏅 Médaille débloquée : {ic} {nm} ! +{pt} points",
    "bm_sum": "🤖 Boss domptés — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>",
    "a_sentiero_done_nm": "Voyageur des Neuf Vies",
    "a_sentiero_done_ds": "Termine tout le Sentier (100 étapes)"
  },
  "reg": {
    "r_h_cards": "🎴 Les cartes",
    "r_p_cards": "Photographie un chat et il devient une carte : l'IA le redessine en cartoon et analyse son allure et son caractère pour générer des <strong>statistiques</strong> (un gros matou aura plus de Force), une <strong>race</strong>, une <strong>description</strong>, un <strong>pouvoir spécial</strong> et <strong>3 attaques</strong> (💥 puissante mais imprécise, ⚡ rapide et presque infaillible, ✨ rusée qui peut désorienter). La <strong>rareté</strong> est tirée de l'empreinte de la photo : 55% Commune, 28% Rare, 13% Épique, 4% Légendaire (les Épiques et Légendaires brillent et ont des stats bonus). La même photo donne toujours la même carte.",
    "r_h_xp": "⭐ Expérience et niveaux",
    "r_p_xp": "Les cartes grandissent en combattant : <strong>défis mondiaux et en direct : 25 XP par victoire, 10 par défaite</strong> · <strong>arène locale et tournois : 5 et 2</strong>. Tous les 100 XP : +1 niveau = <strong>+4 HP, +3% d'attaque et +3 de marge de salle</strong>. Les miroirs (une carte contre elle-même) ne comptent pas.",
    "r_h_pts": "💰 Les points (la monnaie)",
    "r_p_pts": "On les gagne avec : <strong>+10 par victoire mondiale ou en direct</strong>, +10 par Boss dompté, 📅 missions quotidiennes (5 chacune, +10 le trio : max 25 par jour), paris gagnés, médailles (10-100 points chacune) et 🎁 codes cadeaux. Les victoires locales : zéro point. On les <strong>dépense</strong> en : paris (mise 10-100), nourriture en salle (20-25), 🌿 avantage mondial (50), 🎨 Cadre d'Or (100), 🔁 régénération du dessin (30). Perdre un combat ne coûte pas de points : seulement les mauvais paris.",
    "r_h_bet": "🎲 Les paris",
    "r_p_bet": "Dans les <strong>défis mondiaux et en direct</strong> : avant le match tu choisis la mise et sur qui parier (⭐ favori à cote basse, 🐾 outsider à cote haute). Tu gagnes la mise × (cote − 1) ; si tu te trompes tu perds la mise. Pas de paris en local ni en tournoi.",
    "r_h_rest": "😴 Le repos",
    "r_p_rest": "Après chaque vrai combat (local 1c1, mondial, en direct) et chaque entraînement, les chats concernés se reposent <strong>1 heure</strong> : ils ne peuvent ni combattre ni manger. Le repos est visible par tous, même en ligne. Les tournois sont des exhibitions et ne fatiguent pas.",
    "r_h_gym": "🏋️ La salle",
    "r_p_gym": "Chaque niveau débloque <strong>+3 points de marge d'entraînement</strong>. Tu achètes un aliment (🥫 HP · 🍗 Force · 🐁 Intelligence · 🌿 Adresse · 🐟 Vitesse · 🧀 Charme) et le chat le gagne avec l'exercice associé : 🧶 pelote (agilité), 🐭 chasse à la souris (physique), 🪶 suis la plume (mental). Seuils : <strong>sous 5 points nourriture gâchée, 5-9 bonus ×1, 10+ bonus ×2</strong> (pour la plume : 3 et 5 tours). Les cartes publiées se mettent à jour en ligne toutes seules. Le Coach donne des conseils gratuits.",
    "r_h_world": "🌍 L'Arène Mondiale",
    "r_p_world": "Connecte-toi avec Google (ou e-mail), choisis ton nom de joueur (un par compte, renommable partout d'un coup) et <strong>publie les cartes que tu veux</strong> : seules les cartes publiées et actives peuvent défier en ligne. Tu défies les cartes des autres, le résultat va dans le registre et au classement (trié par % de victoires). Tu peux <strong>🚪 retirer</strong> une carte : elle reste au classement comme « retirée » mais personne ne peut plus la défier. La pastille rouge sur Monde te prévient quand tes cartes ont combattu en ton absence.",
    "r_h_rank": "📊 Le classement (façon UFC)",
    "r_p_rank1": "Chaque carte publiée a un score <strong>Elo</strong>, qui part de <strong>1000</strong>. À chaque match le vainqueur <strong>prend</strong> des points et le perdant <strong>cède les mêmes points</strong> — et la quantité dépend de l'écart de force : battre un adversaire <strong>plus fort</strong> vaut jusqu'à <strong>~32 points</strong>, en battre un bien plus faible vaut le minimum, <strong>8</strong> (gagner facile rapporte peu, l'exploit rapporte gros). Aucune carte ne descend jamais sous 100. Le calcul est fait par le serveur, le même pour tous.",
    "r_p_rank2": "Le classement officiel est par Elo, mais la ceinture est une autre affaire : <strong>on devient champion UNIQUEMENT en battant le champion en titre 👑</strong> dans un défi mondial ou en direct. Tu peux le dépasser aux points autant que tu veux : tu restes premier prétendant jusqu'à ce que tu l'étendes sur le ring. Le champion est toujours en tête du classement, et quiconque a été champion garde le 🏆 pour toujours. Tu ne peux défier que ceux situés <strong>de 5 places au-dessus à 5 en dessous</strong> de toi : pour le titre il faut grimper (dans le top 5 le champion est à portée). Le classement montre les séries — 🔥 victoires d'affilée, 🧊 défaites d'affilée, et la meilleure série de tous les temps. Le <strong>🎩 Manager</strong> étudie les chiffres et te conseille le bon prochain match, si l'herbe à chat 🌿 vaut le coup, et quand il vaut mieux se replier un peu en salle.",
    "r_h_cat": "🃏 Le Catdex",
    "r_p_cat": "L'album de la collection, en bas de l'onglet 📚 Cartes : il tient le compte des <strong>raretés, races et pouvoirs spéciaux</strong> que tu as découverts (les cases manquantes restent ❓) et récompense les jalons avec des points <strong>uniques</strong> — du carré de raretés (+25) aux 10 races différentes (+25) jusqu'aux 8 pouvoirs (+30). La race est écrite par l'IA quand tu crées la carte : des noms proches (ex. « tigré » et « européen tigré ») comptent comme une seule famille. Pour le compléter il ne faut qu'une chose : photographier de nouveaux chats.",
    "r_h_mis": "📅 Les missions quotidiennes",
    "r_p_mis": "Chaque minuit arrivent <strong>3 missions</strong>, les mêmes pour le monde entier : une de combat, une de salle, une surprise (boss, paris, QR…). Chacune paie <strong>5 points</strong>, le trio complet <strong>10 de bonus</strong> en plus. Tu les trouves en haut du 🏅 Médaillier, avec la coche ✅ sur celles déjà faites. Maximum 25 points par jour : juste de quoi faire un entraînement, ou un peu plus.",
    "r_h_boss": "🤖 Les Boss de l'Arène",
    "r_p_boss": "<strong>64 légendes en 8 divisions</strong> à difficulté croissante : des Errants du Quartier (faciles) jusqu'aux Boss Finaux comme le 🌑 Gatto Mammone ou 🤖 MIAO-9000, monstrueux. Chaque jour <strong>2 sont actifs, les mêmes pour le monde entier</strong> (la date les décide). En battre un paie <strong>+10 points et 25 XP</strong>. Attention : tu n'as <strong>qu'UNE seule tentative par boss et par jour</strong> — gagné, perdu ou abandonné, on revient demain. Choisis bien ton chat avant d'entrer dans l'arène. Perdre ne coûte que 2 XP de consolation. Après le match le chat <strong>se repose une heure</strong> comme dans tout vrai combat, et l'herbe à chat 🌿 achetée avant vaut aussi ici. Contre les Boss ne descendent <strong>que les cartes publiées dans le Monde</strong>, et les boss <strong>ne touchent pas au classement Elo</strong>. Chaque boss a sa médaille (section « 🤖 Boss domptés » dans le 🏅 Médaillier, récompenses plus riches pour les divisions élevées), plus le 🏆 Tueur de Boss pour qui les dompte tous les 64.",
    "r_h_qr": "⚡ Le duel en direct (QR)",
    "r_p_qr": "Deux téléphones : l'un montre le QR de sa carte (🥋 Dojo → 📱), l'autre le scanne (📷) et le duel se joue sur son écran. <strong>Ça compte comme un défi mondial</strong> : points, XP pleins, médailles, repos, paris et résultat enregistré si les cartes sont publiées.",
    "r_h_tourn": "🏆 Tournois et médaillier",
    "r_p_tourn": "Tournois à 4 ou 8 entre tes cartes et les rivaux : exhibitions automatiques avec tableau (XP réduits, pas de repos, pas de points). Le <strong>🏅 Médaillier</strong> compte 25 médailles avec récompenses en points (9 sont des Boss) — touche une médaille pour découvrir comment la conquérir. Attention à la 💀 Déroute…",
    "r_h_fight": "⚔️ Le combat",
    "r_p_fight": "Automatique au tour par tour : la Vitesse décide qui commence (en général), la Force les dégâts, l'Adresse les esquives, l'Intelligence les critiques (×1.6), le Charme ensorcelle, l'Indifférence réduit les dégâts. Aucun coup n'enlève plus de 38% des HP. Pouvoirs spéciaux, bonus aléatoires (🧶🌿📦🐟), coup final au ralenti et replay. La présentation peut être sautée (⏭️ ou depuis les Options).",
    "mgr_greet": "Le ring est un échiquier, petit. Choisis ton champion et je te dis le prochain coup.",
    "mis_desc": "Trois nouvelles missions chaque minuit, les mêmes pour le monde entier : <strong>5 points</strong> chacune, <strong>+10 de bonus</strong> si tu complètes le trio.",
    "med_desc": "Les médailles récompensent en points : dépense-les en paris, avantage mondial, Cadre d'Or, régénérations et dans le garde-manger de la Salle.",
    "boss_intro": "64 légendes en 8 divisions : 2 apparaissent chaque jour, les mêmes pour le monde entier. Les battre rapporte <strong>+10 points</strong>, des XP pleins et une médaille dédiée. <strong>Une tentative par boss et par jour</strong>, gagnée ou perdue ; les boss ne touchent pas au classement Elo. Seules les cartes <strong>publiées dans le Monde</strong> combattent."
  },
  "boss": {
    "div_1": "Errants du Quartier",
    "div_2": "Domestiques Rebelles",
    "div_3": "Nobles et Aristochats",
    "div_4": "Bêtes Sauvages",
    "div_5": "Mythes et Légendes",
    "div_6": "Esprits et Surnaturel",
    "div_7": "Divinités Félines",
    "div_8": "Boss Finaux",
    "di_1": "Des ruelles du quartier",
    "di_2": "Des salons en émoi",
    "di_3": "Des salons de la noblesse",
    "di_4": "Des terres sauvages",
    "di_5": "Des légendes anciennes",
    "di_6": "De l'au-delà félin",
    "di_7": "Des trônes célestes",
    "di_8": "De la fin de toute chose",
    "bu_already_beaten": "✅ déjà dompté",
    "bu_beaten_today": "🎖️ Dompté aujourd'hui : récompense empochée.",
    "bu_failed_today": "💥 Tentative du jour échouée.",
    "bu_one_try": "Une seule tentative par boss et par jour : reviens demain.",
    "bu_btn_beaten": "✅ Battu aujourd'hui",
    "bu_btn_tomorrow": "⏳ Reviens demain",
    "bu_btn_fight": "⚔️ Défier {name}",
    "bu_bestiary_sum": "📖 Bestiaire — <strong>{done}/{tot}</strong> domptés <span class=\"count\">{open}</span>",
    "bu_stats_unknown": "Stats inconnues : affronte {name} pour les révéler.",
    "bu_beaten_tag": "✅ dompté",
    "bu_never_tag": "🔒 jamais affronté",
    "bu_mystery_desc": "Un boss de la division « {div} » encore enveloppé de mystère. Il apparaît en rotation : bats-le pour l'ajouter au Bestiaire.",
    "bu_close": "✖ Fermer",
    "bu_already_today": "⏳ Tu as déjà défié {name} aujourd'hui : une seule tentative par boss et par jour, gagnée ou perdue. Reviens demain !",
    "bu_only_world": "Contre les Boss ne combattent que les cartes publiées dans le Monde : publies-en une depuis l'onglet 🌍.",
    "bu_resting": "😴 {name} se repose : reviens dans {min} minutes.",
    "bu_pub_first": "— publie d'abord une carte dans le Monde —",
    "bn_latta": "Le Minou en Fer-blanc",
    "bk_latta": "La Boîte Vivante",
    "bl_latta": "Persuadé d'être une boîte de conserve. Dur dehors, thon dedans.",
    "bn_b02": "Demi-Moustache",
    "bk_b02": "Le Voleur du Marché",
    "bl_b02": "Vole au marché et disparaît avant que tu dises « miaou ».",
    "bn_b03": "Pattesale",
    "bk_b03": "Le Seigneur des Poubelles",
    "bl_b03": "Règne sur les poubelles du quartier, immunisé à tout dégoût.",
    "bn_b04": "La Boule de Poils",
    "bk_b04": "Le Rouleau Compresseur",
    "bl_b04": "Roule sur toi et ne s'arrête pas. Simple, mais efficace.",
    "bn_b05": "Bidon Mou",
    "bk_b05": "Le Gros Paresseux",
    "bl_b05": "Trop paresseux pour esquiver, trop gros pour tomber.",
    "bn_b06": "Flair",
    "bk_b06": "Le Limier Félin",
    "bl_b06": "Suit l'odeur de la nourriture au bout du monde.",
    "bn_b07": "Demi-Queue",
    "bk_b07": "Le Furieux",
    "bl_b07": "Perdit la moitié de sa queue, gagna le double de rage.",
    "bn_b08": "Le Chat du Boulanger",
    "bk_b08": "Le Four Vivant",
    "bl_b08": "Sent le pain, mord la braise.",
    "bn_b09": "Canapé Détruit",
    "bk_b09": "La Griffe de Cuir",
    "bl_b09": "Ses ongles coupent le cuir comme du beurre.",
    "bn_b10": "Le Roi du Frigo",
    "bk_b10": "Sa Majesté Affamée",
    "bl_b10": "Ouvre les portes par la seule force de la faim.",
    "bn_b11": "Minette Gâtée",
    "bk_b11": "L'Ange aux Griffes",
    "bl_b11": "Nœud rose, griffes d'acier.",
    "bn_b12": "Pelote de Laine",
    "bk_b12": "Le Piège Doux",
    "bl_b12": "Ça a l'air tendre. C'est un piège.",
    "bn_b13": "Le Réveil de 4h",
    "bk_b13": "Le Cauchemar Nocturne",
    "bl_b13": "Il t'attaque quand tu t'y attends le moins : 4 heures du matin.",
    "bn_b14": "Le Chat du Clavier",
    "bk_b14": "Le Saboteur",
    "bl_b14": "Marche sur les nerfs. Et sur les touches.",
    "bn_b15": "Rideau Déchiré",
    "bk_b15": "Le Grimpeur",
    "bl_b15": "Grimpe là où il ne devrait pas. Toujours.",
    "bn_b16": "Vase Brisé",
    "bk_b16": "L'Innocent Destructeur",
    "bl_b16": "Laisse la destruction et un regard angélique.",
    "bn_barone": "Le Baron von Moustachen",
    "bk_barone": "La Griffe Aristocratique",
    "bl_barone": "Duelle selon l'ancienne étiquette : d'abord la révérence, puis le double coup de patte.",
    "bn_b18": "Comtesse Velours",
    "bk_b18": "Le Regard qui Étourdit",
    "bl_b18": "Une fourrure si douce qu'elle étourdit l'adversaire.",
    "bn_b19": "Sir Griffe III",
    "bk_b19": "Le Duelliste",
    "bl_b19": "Bretteur légendaire, jamais perdu un duel à l'aube.",
    "bn_b20": "Madame Persia",
    "bk_b20": "La Reine du Coussin",
    "bl_b20": "Règne depuis son coussin de soie et ne se lève pour personne.",
    "bn_b21": "Le Duc Chartreux",
    "bk_b21": "L'Acier Gris",
    "bl_b21": "Gris comme l'acier, froid comme le fer.",
    "bn_b22": "Lady Siam",
    "bk_b22": "Le Coup de Glace",
    "bl_b22": "Yeux de saphir, coup qui glace le sang.",
    "bn_b23": "Don Gros-Matou",
    "bk_b23": "Le Parrain",
    "bl_b23": "Le parrain de la ruelle : des offres qu'on ne peut refuser.",
    "bn_b24": "Le Majordome Smoking",
    "bk_b24": "L'Ombre Élégante",
    "bl_b24": "Noir et blanc, impeccable et létal.",
    "bn_sfinge": "Le Sphinx de Cour",
    "bk_sfinge": "L'Énigme Poilue",
    "bl_sfinge": "Te fixe jusqu'à ce que tu avoues. Ne parle que par énigmes.",
    "bn_b26": "Croc de Lynx",
    "bk_b26": "L'Embuscade",
    "bl_b26": "Tu ne l'entends pas venir. Tu le sens seulement après.",
    "bn_b27": "Le Chat Sauvage",
    "bk_b27": "L'Indompté",
    "bl_b27": "Jamais apprivoisé. Jamais il ne le sera.",
    "bn_b28": "Ombre de la Jungle",
    "bk_b28": "Le Silence Noir",
    "bl_b28": "Noir comme la nuit, silencieux comme la mort.",
    "bn_b29": "Rugissement",
    "bk_b29": "La Grande Voix",
    "bl_b29": "Petit de taille, énorme de voix.",
    "bn_b30": "Griffe des Neiges",
    "bk_b30": "Le Coup Glacial",
    "bl_b30": "Descend des sommets avec un coup qui gèle.",
    "bn_b31": "Le Tigre en Carton",
    "bk_b31": "La Ruse à Rayures",
    "bl_b31": "A l'air faux jusqu'à ce qu'il te morde.",
    "bn_b32": "Le Puma des Toits",
    "bk_b32": "Le Sauteur",
    "bl_b32": "Saute d'un immeuble à l'autre sans toucher terre.",
    "bn_nonna": "La Mémé des Ruelles",
    "bk_nonna": "Sept Vies et Demie",
    "bl_nonna": "Ses ronrons soignent, ses taloches éduquent.",
    "bn_pescatore": "Le Pêcheur Fantôme",
    "bk_pescatore": "Le Filet du Destin",
    "bl_pescatore": "Apparaît les nuits de brouillard, odeur de sardines et de vengeance.",
    "bn_b35": "Le Chat Botté",
    "bk_b35": "La Lame Légendaire",
    "bl_b35": "Le bretteur des contes, en chair, en poil et en bottes.",
    "bn_b36": "Bastet Mineure",
    "bk_b36": "La Prêtresse",
    "bl_b36": "Prêtresse aux neuf anneaux, gardienne des rites.",
    "bn_b37": "Le Chat Gardien",
    "bk_b37": "Le Gardien du Seuil",
    "bl_b37": "Garde le seuil du grenier sacré depuis des siècles.",
    "bn_b38": "Queue de Renard",
    "bk_b38": "Les Neuf Ruses",
    "bl_b38": "Neuf queues, neuf ruses, aucune pitié.",
    "bn_b39": "Le Errant Immortel",
    "bk_b39": "Huit Vies Dépensées",
    "bl_b39": "On dit qu'il a déjà dépensé huit vies. Il en reste une.",
    "bn_b40": "Maneki le Porte-Bonheur",
    "bk_b40": "La Patte du Destin",
    "bl_b40": "La patte levée qui scelle le destin des autres.",
    "bn_spettro": "Le Spectre des Toits",
    "bk_spettro": "L'Ombre de Minuit",
    "bl_spettro": "Personne ne l'a jamais vu arriver. Beaucoup ont vu partir leur dîner.",
    "bn_b42": "Le Chat Noir du Vendredi",
    "bk_b42": "La Malchance en Poils",
    "bl_b42": "Porte malheur à quiconque ose le défier.",
    "bn_b43": "Yeux dans le Noir",
    "bk_b43": "Le Prédateur Invisible",
    "bl_b43": "Tu ne le vois que lorsqu'il est déjà trop tard.",
    "bn_b44": "Le Faucheur Moustachu",
    "bk_b44": "Le Seigneur de la Neuvième Vie",
    "bl_b44": "Il vient réclamer ta neuvième vie.",
    "bn_b45": "Fantôme de la Cheminée",
    "bk_b45": "La Cendre Vivante",
    "bl_b45": "Vit dans la cendre chaude de la cheminée.",
    "bn_b46": "La Chatte Sorcière",
    "bk_b46": "L'Enchanteresse",
    "bl_b46": "Transforme les souris en tempêtes d'un miaulement.",
    "bn_b47": "Le Vampire Persan",
    "bk_b47": "Le Suce-Vitesse",
    "bl_b47": "Aspire la Vitesse des adversaires et la fait sienne.",
    "bn_b48": "Ectoplasme Félin",
    "bk_b48": "L'Intouchable",
    "bl_b48": "Tu ne peux frapper ce qui n'est pas solide.",
    "bn_imperatore": "L'Empereur Tigré",
    "bk_imperatore": "Le Trône de Coussins",
    "bl_imperatore": "Règne depuis le coussin le plus haut. Son chaos dicte les règles.",
    "bn_b50": "Bastet la Déesse",
    "bk_b50": "L'Antique Protectrice",
    "bl_b50": "L'antique déesse protectrice de tous les chats.",
    "bn_b51": "Le Chat de Schrödinger",
    "bk_b51": "Vivant et Mort",
    "bl_b51": "Vivant et mort à la fois, jusqu'à ce que tu l'attaques.",
    "bn_b52": "Ra-Miaou le Soleil",
    "bk_b52": "L'Aveuglant",
    "bl_b52": "Aveuglant : il brûle qui ose le regarder.",
    "bn_b53": "Sekhmet Féline",
    "bk_b53": "La Furie Divine",
    "bl_b53": "La furie divine faite de griffes.",
    "bn_b54": "Le Gardien des Pyramides",
    "bk_b54": "Mille Dynasties",
    "bl_b54": "Vieux de mille dynasties, immobile comme la pierre.",
    "bn_b55": "Lune Croissante",
    "bk_b55": "La Déesse de la Nuit",
    "bl_b55": "La déesse de la nuit : dans le noir elle est invincible.",
    "bn_b56": "Le Chat des Étoiles",
    "bk_b56": "Le Manteau Cosmique",
    "bl_b56": "Son manteau est un ciel de constellations.",
    "bn_mammone": "Le Gatto Mammone",
    "bk_mammone": "La Légende des Légendes",
    "bl_mammone": "Le monstre des contes. Énorme, antique et susceptible.",
    "bn_b58": "Béhémoth",
    "bk_b58": "Le Colosse de l'Abîme",
    "bl_b58": "Le colosse qui dort sous les volcans.",
    "bn_b59": "Le Premier Chat",
    "bk_b59": "L'Ancêtre",
    "bl_b59": "Celui dont descendent tous les matous du monde.",
    "bn_b60": "Dévoreur de Neuf Soleils",
    "bk_b60": "Le Mythe Cosmique",
    "bl_b60": "Le mythe qui engloutit les soleils, l'un après l'autre.",
    "bn_b61": "Le Seigneur des Errants",
    "bk_b61": "Le Roi de Tous",
    "bl_b61": "Commande chaque chat errant du monde.",
    "bn_b62": "Chronos Félin",
    "bk_b62": "Le Mangeur de Temps",
    "bl_b62": "Mange le temps et vieillit les adversaires.",
    "bn_b63": "Le Chat du Vide",
    "bk_b63": "L'Absence Faite Félin",
    "bl_b63": "L'absence faite félin. Le néant qui miaule.",
    "bn_b64": "MIAO-9000",
    "bk_b64": "Le Chat-Machine Ultime",
    "bl_b64": "Le chat-machine ultime. Erreur : pitié introuvable."
  },
  "world": {
    "w_recent": "📜 Les 5 derniers combats de tes cartes",
    "w_open": "(touche pour ouvrir)",
    "w_beat": "{w} de {wo} a battu {l} de {lo}",
    "w_rank_champ": "👑 #1",
    "w_rank_n": "#{rk} au classement",
    "w_retired": "🚪 retirée",
    "w_record": "{w} V / {l} D",
    "w_none_pub": "Aucune de tes cartes n'est encore publiée.",
    "w_reactivate": "↩️ Réactiver",
    "w_retire": "🚪 Retirer",
    "w_rank_suffix": "au classement",
    "w_by": "de",
    "w_anon": "anonyme",
    "w_wc_champ": "👑 CHAMPION DU MONDE",
    "w_wc_rank": "#{rk} au classement",
    "w_elo": "pts Elo",
    "w_exchamp": "🏆 ancien champion",
    "w_beststreak": "meilleure série 🔥{n}",
    "w_sw": "🔥 {n} d'affilée",
    "w_sl": "🧊 {n} KO d'affilée",
    "w_resting": "😴 Il se repose : reviens dans {min} minutes",
    "w_not_ranked": "⏳ {name} n'est pas encore au classement (à peine publiée ? réessaie bientôt avec 🔄).",
    "w_no_challengers": "📊 {name} est #{rk}, mais aucun adversaire à ±5 pour l'instant. Invite quelqu'un à publier !",
    "w_you_rank": "📊 {name} est #{rk} au classement. Voici qui elle peut défier (de 5 places au-dessus à 5 en dessous) :",
    "w_rests_short": "😴 se repose ({min}m)",
    "w_btn_fight": "⚔️ Défier",
    "w_ldr_champ": "CHAMPION",
    "w_ex": "ex",
    "w_maxstreak": "max 🔥{n}",
    "w_none_rank": "Aucune carte au classement : publies-en une !",
    "w_record_c": "{w}V/{l}D",
    "w_selrest": "😴 se repose",
    "w_selmarket": "🔒 au marché",
    "w_fav": "⭐ favori",
    "w_underdog": "🐾 outsider",
    "w_quota": "cote",
    "w_ifwin": "si gagne : +{n} points",
    "prize_line": "🎁 <strong>En jeu :</strong> victoire +10 points et +25 XP · défaite +10 XP",
    "w_catnip_ready": "🌿 Herbe à chat PRÊTE pour ce match ✔",
    "w_catnip_btn": "🌿 Donne-lui de l'herbe à chat — premier coup doublé (50 points)",
    "w_catnip_need": "Il faut 50 points (tu en as {pts}).",
    "w_pick_champ_opt": "— choisis un champion —",
    "w_all_resting": "😴 tous tes chats se reposent — reviens plus tard",
    "w_pub_first_opt": "— publie d'abord une carte —",
    "w_loading": "Chargement du classement…"
  },
  "mkt": {
    "mkt_desc": "Échange ou vends tes cartes avec les autres joueurs. La carte change de propriétaire avec tout (Elo, victoires, niveau) ; pendant la négociation elle reste gelée et ne combat pas. Il faut être connecté et avoir des cartes publiées dans le Monde.",
    "trd_greet": "Bienvenue au bazar, l'ami ! Je suis Monsieur Troc : demande, je sais comment on fait les bonnes affaires.",
    "inc_greet": "Mesdames et messieurs, la vente commence ! Qui offre ? Qui surenchérit ?",
    "mkt_browse_btn": "🔍 Parcourir les cartes à échanger",
    "mkt_filter_ph": "Filtrer par propriétaire (ex. Lu…)",
    "mkt_notactive": "⚠️ Le Marché n'est pas encore actif sur le serveur (une étape de configuration manque). Les autres fonctions marchent normalement.",
    "mkt_recv_h": "📥 Offres reçues",
    "mkt_offers": "{owner} t'offre <strong>{from}</strong> en échange de ta <strong>{to}</strong>",
    "mkt_compare_btn": "🔍 Comparer",
    "mkt_accept": "✅ Accepter",
    "mkt_reject": "✖ Refuser",
    "mkt_none_recv": "Aucune offre reçue.",
    "mkt_sent_h": "📤 Offres envoyées",
    "mkt_sent": "Tu as offert <strong>{from}</strong> pour <strong>{to}</strong> de {owner}",
    "mkt_cancel": "↩️ Annuler",
    "mkt_login": "Connecte-toi pour échanger.",
    "mkt_loading": "Chargement…",
    "mkt_err_load": "❌ Erreur {code} au chargement des cartes.",
    "mkt_none_avail": "Aucune carte disponible à l'échange.",
    "mkt_neterr": "Erreur réseau.",
    "mkt_none_of": "Aucune carte de « {q} ».",
    "mkt_propose": "🔄 Proposer",
    "mkt_this_card": "cette carte",
    "mkt_give_get": "Tu donnes <strong>{give}</strong> → Tu reçois <strong>{get}</strong>",
    "mkt_level": "📈 Niveau",
    "mkt_baratto_label": "😼 <strong>Monsieur Troc</strong> :",
    "mkt_loading_cmp": "Chargement de la comparaison…",
    "mkt_cmp_title": "🔄 Comparaison d'échange",
    "mkt_accept_trade": "✅ Accepter l'échange",
    "mkt_close": "↩️ Fermer",
    "mkt_err_cmp": "Erreur au chargement de la comparaison.",
    "mkt_close2": "Fermer",
    "mkt_trade_h": "🔄 Échange",
    "mkt_need_card": "Pour échanger il te faut au moins UNE de tes cartes publiée et active dans le Monde (et pas au repos).",
    "mkt_closeX": "✖ Fermer",
    "mkt_propose_h": "🔄 Proposer un échange",
    "mkt_want": "Tu veux <strong>{name}</strong>{owner}.",
    "mkt_tap_offer": "Touche TA carte à offrir :",
    "mkt_do_trade": "🔄 Échanger",
    "mkt_cancelX": "✖ Annuler",
    "mkt_pick_offer": "Touche d'abord une de tes cartes à offrir.",
    "mkt_notactive2": "⚠️ Le Marché n'est pas encore actif sur le serveur : une étape de configuration manque (SQL de l'étape 2).",
    "mkt_trade_fail": "Échange non proposé : {t}",
    "mkt_sent_ok": "🔄 Offre envoyée ! En attente de réponse.",
    "mkt_neterr2": "Erreur réseau : {m}",
    "mkt_op_fail": "Opération échouée : {t}",
    "mkt_trade_done": "✅ Échange fait ! Les cartes ont changé de propriétaire.",
    "mkt_rejected": "Offre refusée.",
    "mkt_cancelled": "↩️ Offre annulée.",
    "mkt_received": "🎁 Tu as reçu {name} dans l'échange !",
    "mkt_login_first": "Connecte-toi d'abord (onglet 🌍 Monde).",
    "mkt_auc_h": "🔨 Enchère",
    "mkt_need_free": "Il te faut une carte publiée et libre (pas déjà au marché) à mettre aux enchères.",
    "mkt_put_auc_h": "🔨 Mettre aux enchères",
    "mkt_tap_sell": "Touche la carte à vendre :",
    "mkt_min_price": "Prix minimum (points)",
    "mkt_duration": "Durée",
    "mkt_h1": "1 heure",
    "mkt_h6": "6 heures",
    "mkt_h24": "24 heures",
    "mkt_d2": "2 jours",
    "mkt_hold_auc": "🔨 Lancer l'enchère",
    "mkt_pick_card": "Touche d'abord une carte.",
    "mkt_auc_notactive": "⚠️ Les enchères ne sont pas encore actives sur le serveur (SQL manquant).",
    "mkt_auc_fail": "Enchère non créée : {t}",
    "mkt_auc_ok": "🔨 Enchère lancée ! Ta carte est maintenant au marché.",
    "mkt_auc_notactive2": "⚠️ Enchères pas encore actives sur le serveur (étape SQL manquante).",
    "mkt_err": "Erreur {code}.",
    "mkt_no_auc": "Aucune enchère en cours. Lances-en une !",
    "mkt_curbid": "💰 {n} pts de {owner}",
    "mkt_nobid": "aucune offre",
    "mkt_your_auc": "🔨 ton enchère",
    "mkt_withdraw": "↩️ Retirer",
    "mkt_bid_btn": "💰 Surenchérir",
    "mkt_base": "Base {n} pts",
    "mkt_history": "📜 Historique des offres",
    "mkt_min_bid": "Tu dois offrir au moins {n} points.",
    "mkt_no_points": "Tu n'as pas assez de points (tu en as {p}).",
    "mkt_bid_fail": "Offre refusée : {t}",
    "mkt_no_bids": "Encore aucune offre.",
    "mkt_bid_line": "💰 {n} pts — {owner} · {when}",
    "mkt_err2": "Erreur.",
    "mkt_confirm_withdraw": "Retirer la carte de l'enchère ?",
    "mkt_withdraw_fail": "Non retirée : {t}",
    "mkt_withdrawn": "↩️ Enchère retirée."
  },
  "sent": {
    "sent_title": "🗺️ Le Sentier des Neuf Vies",
    "sent_desc": "Un long voyage par étapes pour chacune de tes cartes : affronte les chats du sentier l'un après l'autre. Chaque victoire débloque l'étape suivante et t'offre la vignette de ce chat pour l'Album. Se joue hors ligne, sans paris ni repos : si tu perds, tu recommences.",
    "sent_pick": "Qui marche sur le sentier",
    "pick_card": "👆 Choisis une carte ci-dessus pour commencer le voyage.",
    "no_card": "Crée d'abord une carte, puis en route sur le sentier.",
    "progress": "<strong>{name}</strong> — étape {done}/{tot} franchies.",
    "more_soon": "🚧 Les prochaines zones du sentier arrivent bientôt…",
    "stage": "Étape",
    "zone_done": "🎉 Zone terminée ! +{pts} points et une nouvelle page d'Album.",
    "got_fig": "📒 Nouvelle vignette : {name} !",
    "album_sum": "📒 Album — <strong>{done}/{tot}</strong> vignettes <span class=\"count\">{open}</span>",
    "z_1": "Les Ruelles",
    "z_2": "Les Jardins",
    "z_3": "La Forêt",
    "z_4": "La Montagne",
    "z_5": "La Ville",
    "z_6": "Le Désert",
    "z_7": "La Mer",
    "z_8": "Les Terres de Glace",
    "z_9": "Le Volcan",
    "z_10": "Le Cosmos",
    "bn_s01": "Minou",
    "bk_s01": "Le Bleu",
    "bl_s01": "Le premier chat que tu rencontres : curieux, maladroit, mais plein de cœur.",
    "bn_s02": "Farfouille",
    "bk_s02": "Le Roi des Poubelles",
    "bl_s02": "Connaît chaque poubelle du quartier et ce qu'il y a dedans.",
    "bn_s03": "Chaussette",
    "bk_s03": "Le Dormeur",
    "bl_s03": "Noir et blanc, toujours sur le capot le plus chaud de la ruelle.",
    "bn_s04": "Cartonou",
    "bk_s04": "L'Embuscade en Carton",
    "bl_s04": "Vit dans une boîte et surgit quand tu t'y attends le moins.",
    "bn_s05": "Minuit",
    "bk_s05": "L'Ombre de la Ruelle",
    "bl_s05": "Noir comme la nuit, tu ne le vois qu'à ses yeux brillants.",
    "bn_s06": "Crème",
    "bk_s06": "Le Gourmand",
    "bl_s06": "A toujours une moustache de lait et un sourire satisfait.",
    "bn_s07": "Corde",
    "bk_s07": "Le Musicien",
    "bl_s07": "Joue de sa guitare désaccordée sous les lampadaires pour quelques friandises.",
    "bn_s08": "Sardine",
    "bk_s08": "Le Poissonnier",
    "bl_s08": "Ne lâche jamais son poisson : il faudra le mériter.",
    "bn_s09": "Éclair",
    "bk_s09": "La Foudre de la Ruelle",
    "bl_s09": "Rebondit d'un mur à l'autre : attrape-le si tu peux.",
    "bn_s10": "Œil-Unique",
    "bk_s10": "Le Roi des Ruelles",
    "bl_s10": "Un seul œil et mille cicatrices : il commande les errants. Le premier vrai obstacle.",
    "bn_s11": "Papillon",
    "bk_s11": "Le Chasse-Papillons",
    "bl_s11": "Poursuit les papillons toute la journée, n'en attrape jamais un.",
    "bn_s12": "Tournesol",
    "bk_s12": "Le Dormeur au Soleil",
    "bl_s12": "Dort là où frappe le soleil et se déplace avec lui.",
    "bn_s13": "Bourdon",
    "bk_s13": "Le Dard",
    "bl_s13": "A appris à ses dépens que les abeilles piquent. Il réessaie encore.",
    "bn_s14": "Cui-cui",
    "bk_s14": "L'Épie-Oiseaux",
    "bl_s14": "Observe les oiseaux depuis la fenêtre pendant des heures, immobile.",
    "bn_s15": "Ptit-Crapaud",
    "bk_s15": "L'Effraie-Grenouilles",
    "bl_s15": "Saute dans la mare et fait fuir toutes les grenouilles.",
    "bn_s16": "Épine",
    "bk_s16": "Le Blessé des Roses",
    "bl_s16": "Mille griffures dans les ronces, mais la roseraie est à lui.",
    "bn_s17": "Escargot",
    "bk_s17": "Le Patient",
    "bl_s17": "Observe les escargots. Il est la seule chose plus lente qu'eux.",
    "bn_s18": "Éclabousse",
    "bk_s18": "L'Arrose-Fontaine",
    "bl_s18": "Joue avec l'eau de la fontaine et revient toujours trempé.",
    "bn_s19": "Piquant",
    "bk_s19": "L'Ami Épineux",
    "bl_s19": "S'est lié d'amitié avec un hérisson. Ne demande pas comment.",
    "bn_s20": "Vieux Saule",
    "bk_s20": "Le Seigneur du Jardin",
    "bl_s20": "Le chat le plus âgé du jardin : sage, calme et intouchable.",
    "bn_s21": "Champi",
    "bk_s21": "Le Cueilleur",
    "bl_s21": "Flaire les meilleurs champignons du bois et évite les mauvais.",
    "bn_s22": "Plumenuit",
    "bk_s22": "Le Rival du Hibou",
    "bl_s22": "Défie le hibou chaque nuit à qui reste éveillé le plus longtemps.",
    "bn_s23": "Gland",
    "bk_s23": "L'Amasseur",
    "bl_s23": "Vole les glands aux écureuils et les cache partout.",
    "bn_s24": "Futé",
    "bk_s24": "Le Rusé",
    "bl_s24": "Marche comme un renard et pense comme un renard.",
    "bn_s25": "Défense",
    "bk_s25": "Le Gardien du Territoire",
    "bl_s25": "Défend sa clairière contre tous, sangliers compris.",
    "bn_s26": "Toile",
    "bk_s26": "L'Empêtré",
    "bl_s26": "Finit toujours dans les toiles d'araignée, mais n'abandonne jamais.",
    "bn_s27": "Pomme de Pin",
    "bk_s27": "Le Grimpeur de Pins",
    "bl_s27": "Grimpe les pins les plus hauts juste pour regarder en bas.",
    "bn_s28": "Faon",
    "bk_s28": "Le Chasseur Silencieux",
    "bl_s28": "Suit les cerfs dans les bois sans un bruit.",
    "bn_s29": "Louveteau",
    "bk_s29": "Le Petit Sauvage",
    "bl_s29": "Élevé parmi les loups, il a appris leur hurlement.",
    "bn_s30": "Gros Ours",
    "bk_s30": "La Bête de la Forêt",
    "bl_s30": "Gros comme un ours : le roi incontesté des bois.",
    "bn_s31": "Godillot",
    "bk_s31": "Le Suit-Randonneurs",
    "bl_s31": "Suit les randonneurs au sommet en espérant un sandwich.",
    "bn_s32": "Saute-Chèvre",
    "bk_s32": "L'Effraie-Chèvres",
    "bl_s32": "Fait sursauter les chèvres sur les falaises, juste pour rire.",
    "bn_s33": "Caillou",
    "bk_s33": "L'Équilibriste",
    "bl_s33": "Tient en équilibre sur les rochers les plus inconfortables.",
    "bn_s34": "Aiglon",
    "bk_s34": "Le Rival de l'Aigle",
    "bl_s34": "Dispute à l'aigle les plus hauts sommets, sans ailes.",
    "bn_s35": "Toile de Tente",
    "bk_s35": "Le Voleur du Campement",
    "bl_s35": "Dévalise les tentes des campeurs la nuit.",
    "bn_s36": "Cime",
    "bk_s36": "L'Habitant des Sommets",
    "bl_s36": "Vit là où l'air est rare et où aucun autre chat n'ose.",
    "bn_s37": "Bourrasque",
    "bk_s37": "L'Ébouriffé",
    "bl_s37": "Le vent de la montagne lui a hérissé le poil pour toujours.",
    "bn_s38": "Grappin",
    "bk_s38": "Le Grimpeur",
    "bl_s38": "Escalade des parois où même les chèvres ne vont pas.",
    "bn_s39": "Clochette",
    "bk_s39": "Le Montagnard",
    "bl_s39": "Porte une clochette au cou : tu l'entends avant de le voir.",
    "bn_s40": "Corneblanche",
    "bk_s40": "Le Roi de la Montagne",
    "bl_s40": "Cornes de bélier et pattes de fer : il domine chaque cime.",
    "bn_s41": "Taxi",
    "bk_s41": "L'Esquive-Voitures",
    "bl_s41": "Traverse la circulation la plus folle sans une égratignure.",
    "bn_s42": "Tuile",
    "bk_s42": "Le Rôdeur des Toits",
    "bl_s42": "Règne sur les toits de la grande ville, de tuile en tuile.",
    "bn_s43": "Margherita",
    "bk_s43": "Le Pilleur de Pizzas",
    "bl_s43": "Aucune boîte de pizza n'est en sécurité quand il rôde.",
    "bn_s44": "Feu Rouge",
    "bk_s44": "Le Guette-Circulation",
    "bl_s44": "Attend toujours le vert. Un chat très civilisé.",
    "bn_s45": "Parkour",
    "bk_s45": "L'Acrobate des Toits",
    "bl_s45": "Bondit d'un immeuble à l'autre comme au cinéma.",
    "bn_s46": "Néon",
    "bk_s46": "Le Paresseux au Néon",
    "bl_s46": "Dort sous les enseignes lumineuses, dans la chaleur de la ville.",
    "bn_s47": "Métro",
    "bk_s47": "Le Chat du Métro",
    "bl_s47": "Connaît chaque tunnel et chaque quai sous terre.",
    "bn_s48": "Jazz",
    "bk_s48": "Le Chat de la Ruelle",
    "bl_s48": "Miaule au rythme du jazz derrière les clubs, la nuit.",
    "bn_s49": "Gratte-ciel",
    "bk_s49": "Le Grimpeur de Tours",
    "bl_s49": "A gravi le plus haut immeuble juste pour la vue.",
    "bn_s50": "Nocturne",
    "bk_s50": "Le Boss de la Ville",
    "bl_s50": "Il commande chaque ruelle après le coucher du soleil. La ville est à lui.",
    "bn_s51": "Cactou",
    "bk_s51": "L'Esquive-Cactus",
    "bl_s51": "Court entre les cactus sans jamais se piquer. Presque.",
    "bn_s52": "Crochet",
    "bk_s52": "Le Méfiant",
    "bl_s52": "Surveille chaque scorpion : il a déjà été piqué une fois.",
    "bn_s53": "Dune",
    "bk_s53": "Le Coureur des Dunes",
    "bl_s53": "Monte et descend les dunes comme des coussins.",
    "bn_s54": "Palmier",
    "bk_s54": "Le Paresseux de l'Oasis",
    "bl_s54": "A trouvé la seule ombre du désert et ne la lâche pas.",
    "bn_s55": "Sifflement",
    "bk_s55": "Le Charmeur de Serpents",
    "bl_s55": "Fixe les serpents jusqu'à ce qu'ils abandonnent.",
    "bn_s56": "Canicule",
    "bk_s56": "Le Brûlé par le Soleil",
    "bl_s56": "Le soleil du désert lui a réchauffé le caractère.",
    "bn_s57": "Amphore",
    "bk_s57": "Le Chat des Ruines",
    "bl_s57": "Vit parmi les ruines antiques, gardien de secrets de sable.",
    "bn_s58": "Bosse",
    "bk_s58": "Le Suit-Chameaux",
    "bl_s58": "Suit les caravanes pour les miettes des voyageurs.",
    "bn_s59": "Tourbillon",
    "bk_s59": "Le Survivant des Tempêtes",
    "bl_s59": "Il a traversé mille tempêtes de sable. Il est toujours là.",
    "bn_s60": "Léonin",
    "bk_s60": "Le Sphinx du Désert",
    "bl_s60": "Immobile comme une statue, ancien comme le sable. Parle par énigmes.",
    "bn_s61": "Pince",
    "bk_s61": "L'Attrape-Crabes",
    "bl_s61": "Poursuit les crabes sur le rivage, y perd toujours une moustache.",
    "bn_s62": "Coquillage",
    "bk_s62": "Le Collectionneur",
    "bl_s62": "Ramasse les coquillages et les cache dans le sable.",
    "bn_s63": "Vague",
    "bk_s63": "L'Esquive-Vagues",
    "bl_s63": "Défie les vagues et s'enfuit juste avant d'être mouillé.",
    "bn_s64": "Hameçon",
    "bk_s64": "Le Pêcheur",
    "bl_s64": "Pêche de la patte mieux que bien des pêcheurs.",
    "bn_s65": "Mouette",
    "bk_s65": "Le Rival de la Mouette",
    "bl_s65": "Dispute aux mouettes chaque miette du quai.",
    "bn_s66": "Voile",
    "bk_s66": "Le Clandestin",
    "bl_s66": "S'embarque en douce et personne ne s'en aperçoit.",
    "bn_s67": "Abordage",
    "bk_s67": "Le Chat Pirate",
    "bl_s67": "Un bandeau sur l'œil et une patte toujours prête à l'assaut.",
    "bn_s68": "Tentacule",
    "bk_s68": "Le Dompteur de Poulpes",
    "bl_s68": "Le seul qui joue avec les poulpes et en sort vainqueur.",
    "bn_s69": "Phoque",
    "bk_s69": "L'Ami de la Mer",
    "bl_s69": "Nage avec les phoques comme s'il était né parmi eux.",
    "bn_s70": "Léviathan",
    "bk_s70": "Le Roi de la Mer",
    "bl_s70": "Grand comme une baleine : il commande chaque vague de l'océan.",
    "sent_fight": "⚔️ Combattre",
    "sent_back": "↩️ Retour",
    "sent_replay": "⚔️ Rejouer",
    "bn_s71": "Poudrerie",
    "bk_s71": "L'Attrape-Flocons",
    "bl_s71": "Essaie d'attraper les flocons de neige avec ses pattes, un par un.",
    "bn_s72": "Bonhomme",
    "bk_s72": "Le Bâtisseur de Neige",
    "bl_s72": "Construit des bonshommes de neige puis les démolit pour rire.",
    "bn_s73": "Glaçon",
    "bk_s73": "Le Glisseur",
    "bl_s73": "Glisse sur la glace sans jamais vraiment s'arrêter.",
    "bn_s74": "Pingouin",
    "bk_s74": "Le Rival du Pingouin",
    "bl_s74": "Défie les pingouins à qui glisse le plus loin sur le ventre.",
    "bn_s75": "Skieur",
    "bk_s75": "Le Descendeur",
    "bl_s75": "Dévale les pentes enneigées plus vite qu'une luge.",
    "bn_s76": "Ourson",
    "bk_s76": "L'Ami de l'Ours Blanc",
    "bl_s76": "A adopté un ourson polaire. Ou est-ce l'inverse ?",
    "bn_s77": "Blizzard",
    "bk_s77": "Le Marcheur des Tempêtes",
    "bl_s77": "Traverse les tempêtes de neige comme une brise.",
    "bn_s78": "Curleur",
    "bk_s78": "Le Lanceur de Glace",
    "bl_s78": "Fait glisser des pierres sur la glace avec une visée parfaite.",
    "bn_s79": "Cristal",
    "bk_s79": "L'Admire-Cristaux",
    "bl_s79": "Passe des heures à fixer les cristaux de glace scintillants.",
    "bn_s80": "Roi Gel",
    "bk_s80": "Le Souverain de la Glace",
    "bl_s80": "Son souffle gèle les lacs. Personne ne soutient son regard de glace.",
    "bn_s81": "Braise",
    "bk_s81": "Le Tison",
    "bl_s81": "Marche sur les charbons ardents sans se brûler les pattes.",
    "bn_s82": "Cratère",
    "bk_s82": "L'Habitant du Cratère",
    "bl_s82": "Vit au bord du volcan, où il fait une chaleur infernale.",
    "bn_s83": "Obsidienne",
    "bk_s83": "Le Chat de Pierre Noire",
    "bl_s83": "Dur et brillant comme du verre volcanique.",
    "bn_s84": "Fracas",
    "bk_s84": "L'Explosif",
    "bl_s84": "Quand il se fâche, toute la montagne tremble.",
    "bn_s85": "Pétard",
    "bk_s85": "La Mèche Courte",
    "bl_s85": "S'enflamme pour un rien et part à l'assaut.",
    "bn_s86": "Source",
    "bk_s86": "Le Paresseux des Thermes",
    "bl_s86": "Somnole dans les bassins chauds près de la lave.",
    "bn_s87": "Fournaise",
    "bk_s87": "Le Brûlant",
    "bl_s87": "À son passage, l'air tremble de chaleur.",
    "bn_s88": "Flammèche",
    "bk_s88": "Le Gardien du Feu",
    "bl_s88": "Maintient vivante l'antique flamme du volcan.",
    "bn_s89": "Lanterne",
    "bk_s89": "La Flamme Éternelle",
    "bl_s89": "Brûle depuis mille ans et ne s'éteint jamais.",
    "bn_s90": "Dragonneau",
    "bk_s90": "Le Dragon du Volcan",
    "bl_s90": "Crache des étincelles et commande la lave. Le roi du feu.",
    "bn_s91": "Lunette",
    "bk_s91": "Le Chat de la Lune",
    "bl_s91": "Saute de cratère en cratère sur la lune, léger comme une plume.",
    "bn_s92": "Étoilette",
    "bk_s92": "Le Cueilleur d'Étoiles",
    "bl_s92": "Collectionne les étoiles filantes dans un bocal (dit-il).",
    "bn_s93": "Anneau",
    "bk_s93": "Le Seigneur des Anneaux",
    "bl_s93": "Vit sur les anneaux de Saturne, en équilibre parfait.",
    "bn_s94": "Comète",
    "bk_s94": "Le Voyageur",
    "bl_s94": "File dans l'espace en laissant une traînée lumineuse.",
    "bn_s95": "Fusée",
    "bk_s95": "L'Astronaute",
    "bl_s95": "Est monté sur une fusée pour rire et n'est jamais redescendu.",
    "bn_s96": "Soucoupe",
    "bk_s96": "L'Ami des Aliens",
    "bl_s96": "S'est lié d'amitié avec des créatures d'autres mondes.",
    "bn_s97": "Météore",
    "bk_s97": "Le Vœu",
    "bl_s97": "Passe si vite qu'il faut faire un vœu.",
    "bn_s98": "Vide",
    "bk_s98": "Le Trou Noir",
    "bl_s98": "Engloutit tout ce qui s'approche, même la lumière.",
    "bn_s99": "Poussière",
    "bk_s99": "Le Manteau d'Étoiles",
    "bl_s99": "Son pelage est fait de poussière de galaxies.",
    "bn_s100": "Souverain Cosmique",
    "bk_s100": "Le Seigneur des Neuf Vies",
    "bl_s100": "Le dernier adversaire du Sentier. Ancien comme l'univers, invincible comme une légende."
  },
  "msg": {
    "del_card_confirm": "Supprimer la carte de {name} ? Ses statistiques de combat seront aussi supprimées.",
    "nick_set": "🥊 {name} est désormais « {nick} »",
    "retire_login": "Pour retirer une carte du monde tu dois d'abord te connecter (onglet 🌍 Monde).",
    "retire_confirm": "Retirer {name} de l'Arène Mondiale ? Elle reste au classement avec son bilan comme « retirée », mais personne ne peut plus la défier. (La republier la réactive.)",
    "err_http": "Erreur : HTTP {code}",
    "card_not_pub": "Cette carte n'est pas publiée (ou n'est pas à toi).",
    "retired_ok": "🚪 {name} s'est retirée du monde avec honneur. Son bilan reste au classement.",
    "err_net": "Erreur réseau : {m}",
    "code_copied": "Code copié ! Envoie-le à un ami (ex. sur WhatsApp) : il le colle dans son appli pour défier {name}. Note : le code est long car il contient aussi la photo.",
    "audio_quota": "⛔ Quota quotidien Gemini épuisé.\n\nLes clips déjà faits sont sauvegardés. Reprends demain (le quota se réinitialise) et il complétera seulement les manquants.",
    "audio_err": "🎙️ Erreur audio ({lang}) : {err}",
    "same_cat": "Un chat ne peut pas se battre contre lui-même ! Choisis deux cartes différentes.",
    "backup_confirm": "Importer la sauvegarde ? Elle remplacera ta collection, tes rivaux et tes stats actuels ({n} cartes dans la sauvegarde).",
    "backup_invalid": "Fichier de sauvegarde invalide.",
    "share_unsupported": "Le partage direct n'est pas pris en charge par ce navigateur : utilise « Télécharger » et joins l'image.",
    "card_gone_local": "Cette carte n'est plus dans ta collection locale.",
    "news_beaten": "💥 {loser} a été battue par {winner} {by} {owner} — se repose maintenant 😴",
    "world_login": "Connecte-toi d'abord (en haut de l'onglet Monde) pour défier en ligne.",
    "out_of_range": "🔒 Hors de portée : {name} est #{ro}, tu es #{rm}. Tu ne peux défier qu'entre 5 places au-dessus et 5 en dessous : grimpe au classement !",
    "opp_trading": "🔄 {name} est prise dans un échange : impossible de la défier maintenant.",
    "opp_resting": "😴 {name} vient d'aller se reposer : réessaie dans {min} minutes.",
    "need_pub_card": "Pour défier en ligne il te faut UNE de tes cartes publiée et active : publies-en une depuis « Choisir les cartes à publier ».",
    "catnip_have": "Avantage déjà acheté : il vaut pour ton prochain combat.",
    "catnip_need": "Il faut 50 points (tu en as {pts}). Gagne des paris et des médailles !",
    "catnip_confirm": "Dépenser 50 points ? Ta carte commencera le prochain combat avec l'herbe à chat (premier coup doublé).",
    "catnip_ready": "🌿 Avantage prêt : il vaut pour ton prochain combat !",
    "regen_cost": "Redessiner coûte 30 points (tu en as {pts}).",
    "regen_confirm": "Dépenser 30 points pour un nouveau dessin IA ?",
    "frame_have": "{name} arbore déjà le Cadre d'Or !",
    "frame_cost": "Le Cadre d'Or coûte 100 points (tu en as {pts}).",
    "frame_confirm": "Dépenser 100 points pour le Cadre d'Or de {name} ? Il reste pour toujours.",
    "food_need": "💰 Il faut {cost} points (tu en as {pts}) : gagne-les dans le monde !",
    "train_cancel": "↩️ Entraînement annulé : {cost} points remboursés.",
    "pick_champ": "Choisis d'abord ton champion dans le menu ci-dessus.",
    "qr_gen_fail": "Générateur QR non chargé : recharge la page avec internet.",
    "qr_read_fail": "Lecteur QR non chargé : internet requis.",
    "cam_fail": "Caméra indisponible : {m}",
    "qr_invalid": "QR invalide.",
    "qr_self": "Tu as scanné ta propre carte !"
  },
  "moves": {
    "ma_0": "Griffure",
    "ma_1": "Embuscade",
    "ma_2": "Regard",
    "ma_3": "Bond",
    "ma_4": "Coup de patte",
    "ma_5": "Miaulement",
    "ma_6": "Assaut",
    "ma_7": "Ronron",
    "mb_0": "Foudroyant",
    "mb_1": "du Canapé",
    "mb_2": "de Mépris",
    "mb_3": "Cosmique",
    "mb_4": "Sauvage",
    "mb_5": "Nocturne",
    "mb_6": "de 4h du Matin",
    "mb_7": "Hypnotique"
  },
  "instr": {
    "i_pianoforte": "piano",
    "i_tromba": "trompette",
    "i_chitarra": "guitare",
    "i_archi": "cordes",
    "i_organo": "orgue",
    "i_marimba": "marimba",
    "theme_line": "{stile} en {ton}, {instr}"
  },
  "breeds": {
    "b_soriano": "Tigré",
    "b_tigrato": "Tigré",
    "b_europeo": "Européen",
    "b_comune": "Chat de gouttière",
    "b_certosino": "Chartreux",
    "b_siamese": "Siamois",
    "b_persiano": "Persan",
    "b_mainecoon": "Maine Coon",
    "b_ragdoll": "Ragdoll",
    "b_sphynx": "Sphynx",
    "b_bengala": "Bengal",
    "b_british": "British Shorthair",
    "b_norvegese": "Norvégien",
    "b_angora": "Angora",
    "b_birmano": "Birman",
    "b_abissino": "Abyssin",
    "b_esotico": "Exotic",
    "b_siberiano": "Sibérien",
    "b_scottish": "Scottish Fold",
    "b_rex": "Rex",
    "b_blurusso": "Bleu Russe",
    "b_orientale": "Oriental",
    "b_turco": "Turc de Van",
    "b_savana": "Savannah",
    "b_bombay": "Bombay",
    "c_bianco": "blanc",
    "c_nero": "noir",
    "c_grigio": "gris",
    "c_blu": "bleu",
    "c_rosso": "roux",
    "c_crema": "crème",
    "c_marrone": "brun",
    "c_fulvo": "fauve",
    "c_tartarugato": "écaille",
    "c_tricolore": "tricolore",
    "c_bicolore": "bicolore",
    "c_maculato": "tacheté",
    "c_striato": "rayé",
    "c_pointed": "colorpoint",
    "coat_lungo": "à poil long",
    "coat_corto": "à poil court"
  },
  "award": {
    "title": "🏆 Les Awards du Samedi Soir",
    "host": "Michou Ronron",
    "subtitle": "Chaque samedi soir, le grand gala : prix, points et gloire pour les meilleurs chats de la semaine.",
    "promo_when": "SAMEDI, 21H00",
    "promo_line": "🎬 Prochain épisode avec {host}",
    "promo_cd": "dans {d}j {h}h {m}m",
    "promo_soon": "dans {h}h {m}m",
    "promo_live": "🔴 C’est l’heure ! La cérémonie va commencer…",
    "noms_title": "✨ Les nominations de la semaine",
    "noms_sub": "Qui est en tête maintenant — en direct",
    "noms_empty": "Aucun combat cette semaine. Combats dans le Monde pour entrer au classement !",
    "past_title": "📼 Épisodes précédents",
    "past_empty": "La première soirée de gala est ce samedi. Reviens voir les gagnants !",
    "hall_title": "🏛️ Hall of Fame — records de tous les temps",
    "hall_empty": "Aucun record encore : quelqu’un sera le premier.",
    "by": "de",
    "pts": "+{p} pts",
    "week_of": "Soirée du {d}",
    "aw_mvp": "MVP — Chat de la Semaine",
    "aw_instancabile": "Infatigable",
    "aw_cecchino": "Tireur d’élite",
    "aw_dominatore": "Dominateur",
    "d_mvp": "plus de victoires",
    "d_instancabile": "plus de combats",
    "d_cecchino": "meilleur pourcentage",
    "d_dominatore": "plus longue série",
    "hof_striscia": "Série Légendaire",
    "hof_veterano": "Vétéran",
    "hof_recordman": "Recordman de Victoires",
    "hof_winrate": "Meilleur Pourcentage",
    "val_mvp": "{n} victoires",
    "val_instancabile": "{n} combats",
    "val_cecchino": "{n}%",
    "val_dominatore": "série de {n}",
    "val_striscia": "{n} d’affilée",
    "val_veterano": "{n} combats",
    "val_recordman": "{n} victoires",
    "val_winrate": "{n}%",
    "cer_title": "GRAND GALA DU SAMEDI SOIR",
    "cer_open": "🎩 Mesdames et messieurs… bienvenue au Gala ! Je suis {host}, et ce soir on récompense les meilleurs chats de la semaine !",
    "cer_drumroll": "🥁 Roulement de ronrons…",
    "cer_gold": "🥇 La patte d’or revient à… {name}, de {owner} !",
    "cer_silver": "🥈 Argent pour {name}, de {owner}.",
    "cer_bronze": "🥉 Bronze pour {name}, de {owner}.",
    "cer_pts": "✨ +{p} points !",
    "cer_q_mvp": "Le plus victorieux de tous !",
    "cer_q_instancabile": "Ne s’est jamais arrêté !",
    "cer_q_cecchino": "Précis comme un sniper !",
    "cer_q_dominatore": "Quelle série !",
    "cer_mvp_finale": "🌟 Et maintenant le prix le plus convoité… le Chat de la Semaine !",
    "cer_close": "🎉 C’est tout pour ce soir ! Une patte d’applaudissements pour nos champions. À samedi prochain !",
    "cer_none": "Aucun prix cette semaine : trop peu de combats ! Retournez vous battre.",
    "btn_replay": "🎬 Revoir la soirée",
    "btn_skip": "Passer ▶▶",
    "cer_preview": "APERÇU — classement en cours",
    "pl_1": "La soirée où les chats deviennent légendes.",
    "pl_2": "Smoking, projecteurs et ronrons — c’est parti !",
    "pl_3": "Neuf vies, une seule scène.",
    "pl_4": "Qui remporte la patte d’or ?",
    "pl_5": "Croquettes rouges et tapis… rouge aussi.",
    "pl_6": "Applaudissements, confettis et quelques griffures.",
    "pl_7": "Le samedi le plus chic du quartier.",
    "pl_8": "Seuls les chats les plus coriaces montent sur scène.",
    "pl_9": "Lumière, caméra… miaou !",
    "pl_10": "Ce soir on récompense qui a griffé le plus fort.",
    "place_1": "Première place · Or",
    "place_2": "Deuxième place · Argent",
    "place_3": "Troisième place · Bronze",
    "full_mvp": "Le chat avec le plus de victoires mondiales cette semaine. Tout simplement le meilleur.",
    "full_instancabile": "A disputé le plus de combats : jamais à l’arrêt, toujours sur le ring.",
    "full_cecchino": "Le meilleur pourcentage de victoires (au moins 5 combats) : précision, pas chance.",
    "full_dominatore": "La plus longue série de victoires consécutives de la semaine.",
    "react_1": "Quel coup de patte !",
    "react_2": "Applaudissements ! 👏",
    "react_3": "Frissons garantis !",
    "react_4": "Un vrai phénomène !",
    "react_5": "Quelle classe !",
    "react_6": "Le public est en délire !",
    "cer_podium": "🏆 Et maintenant… le podium !",
    "cer_suspense": "🥁 …et le gagnant est…",
    "cer_hall_intro": "🏛️ Et maintenant… les Records de Tous les Temps !",
    "cer_hall_hold": "Ce record tient bon. Quel champion !",
    "cer_record_broken": "Nouveau record ! {name} entre dans la légende !",
    "rec_new": "NOUVEAU RECORD !",
    "aw_inlizza": "en lice",
    "cont_title": "Les poursuivants",
    "cer_contenders": "Et attention à eux : à une moustache du podium !",
    "notif_win": "🏆 Tu as gagné {list} ! +{pts} points ajoutés.",
    "notif_more": "et {n} de plus",
    "aw_ammazza": "Tueur de géants",
    "d_ammazza": "le plus gros exploit",
    "full_ammazza": "A battu un adversaire bien mieux classé : l’exploit de la semaine.",
    "cer_q_ammazza": "David contre Goliath !",
    "val_ammazza": "{n} Elo d’écart",
    "aw_beniamino": "Chouchou",
    "d_beniamino": "le plus défié",
    "full_beniamino": "Le chat que les autres ont le plus défié : une vraie star.",
    "cer_q_beniamino": "Tout le monde veut le défier !",
    "val_beniamino": "{n} défis reçus",
    "aw_debuttante": "Révélation",
    "d_debuttante": "meilleure recrue",
    "full_debuttante": "La meilleure carte créée cette semaine, en victoires.",
    "cer_q_debuttante": "Né pour se battre !",
    "val_debuttante": "{n} victoires",
    "aw_astro": "Étoile montante",
    "d_astro": "plus grande montée Elo",
    "full_astro": "Celui qui a gagné le plus d’Elo cette semaine : en pleine ascension.",
    "cer_q_astro": "Ascension irrésistible !",
    "val_astro": "+{n} Elo",
    "aw_pantofolaio": "Pantouflard",
    "d_pantofolaio": "a le moins combattu",
    "full_pantofolaio": "Le prix pour rire : parmi ceux qui ont combattu, le moins actif.",
    "cer_q_pantofolaio": "Le canapé l’appelle !",
    "val_pantofolaio": "seulement {n} combats",
    "hof_piccoelo": "Pic d’Elo",
    "val_piccoelo": "{n} Elo",
    "hof_regno": "Plus long règne",
    "val_regno": "{n} jours",
    "hof_muro": "Le Mur",
    "val_muro": "{n} défenses",
    "hof_pluricampione": "Multi-champion",
    "val_pluricampione": "{n} titres",
    "hof_novevite": "Les Neuf Vies",
    "val_novevite": "Sentier terminé"
  },
  "gang": {
    "login": "Connecte-toi pour utiliser les clans.",
    "none_title": "🛡️ Les Clans",
    "none_sub": "Rejoins un clan ou crée le tien. Ensemble, on combat en équipe.",
    "create": "Crée ton clan",
    "name_ph": "Nom du clan",
    "emblem": "Emblème",
    "create_btn": "🛡️ Créer le clan",
    "board": "📋 Tableau — clans existants",
    "board_empty": "Aucun clan pour l’instant. Sois le premier !",
    "members_n": "{n} membres",
    "cards_n": "{n} cartes",
    "apply": "Demander",
    "applied": "✅ Demande envoyée",
    "full": "Complet",
    "invites": "✉️ Tes invitations",
    "invited_by": "invitation de {who}",
    "accept": "Accepter",
    "decline": "Refuser",
    "members": "👥 Membres",
    "leader": "👑 chef",
    "roster": "🃏 Effectif",
    "roster_empty": "Effectif vide. Ajoute tes cartes !",
    "add_card": "➕ Ajouter",
    "add_none": "Aucune carte à ajouter",
    "remove": "Retirer",
    "apps": "📥 Demandes d’adhésion",
    "apps_empty": "Aucune demande.",
    "approve": "Accepter",
    "reject": "Refuser",
    "leave": "🚪 Quitter le clan",
    "disband": "💥 Dissoudre le clan",
    "leave_confirm": "Quitter le clan ?",
    "disband_confirm": "Tu es le chef : partir dissout le clan. Confirmer ?",
    "created": "🛡️ Clan créé !",
    "order_hint": "(le chef peut réordonner avec ▲▼)",
    "inv_title": "✉️ Inviter des joueurs",
    "inv_browse": "🔎 Parcourir les joueurs",
    "invite_btn": "Inviter",
    "invited_lbl": "✅ Invité",
    "no_free": "Aucun joueur libre à inviter.",
    "search_ph": "Chercher un clan…",
    "more": "Charger plus",
    "open_lbl": "Ouvert",
    "closed_lbl": "🔒 Fermé",
    "browse_others": "📋 Parcourir les autres clans",
    "set_open": "🔓 Ouvrir le clan",
    "set_closed": "🔒 Fermer le clan",
    "search_player": "Chercher un joueur…",
    "see_cards": "Voir les cartes",
    "back": "Retour",
    "no_cards": "Aucune carte publiée.",
    "invite_sent": "✉️ Invitation envoyée !",
    "kick": "Exclure",
    "kick_confirm": "Exclure ce membre du clan ?",
    "joined_msg": "🛡️ Tu as rejoint un clan !",
    "kicked_msg": "🚪 Tu ne fais plus partie du clan.",
    "changed_msg": "Ton clan a changé.",
    "attack": "⚔️ Attaquer",
    "war_won": "🏆 Guerre gagnée ! +30 points de clan",
    "war_lost": "💥 Guerre perdue. +5 de consolation",
    "no_fresh": "Aucune carte fraîche à aligner (elles se reposent).",
    "enemy_empty": "Le clan adverse n’a aucune carte.",
    "pts": "pts",
    "war_confirm": "Attaquer {name} ? Tes cartes se reposeront ensuite une heure.",
    "pick_title": "Choisis ta formation",
    "pick_desc": "Touche les cartes dans l’ordre (min {min}, max {n}). Le gagnant reste en jeu.",
    "pick_go": "⚔️ Attaquer ({n})",
    "def_hint": "Les cartes défendent dans l’ordre du roster : elles répondent au même nombre que l’attaquant (3–5).",
    "def_size_lbl": "Défenseurs :",
    "warlog_title": "Journal des guerres",
    "warlog_empty": "Aucune guerre pour l’instant.",
    "wl_attacked": "Tu as attaqué {name}",
    "wl_defended": "{name} t’a attaqué",
    "wl_win": "Victoire",
    "wl_lose": "Défaite",
    "mycards_title": "Mes cartes dans les clans",
    "mycards_pull": "Retirer",
    "map_btn": "🗺️ Carte des territoires",
    "map_title": "Quartier des Chats",
    "map_legend": "Qui commande",
    "map_empty": "La carte n’a pas encore été créée.",
    "map_nobody": "Aucun clan ne contrôle encore de territoire.",
    "you": "toi",
    "zone_count": "{n} zones",
    "zone_free": "Territoire libre",
    "zone_yours": "Tu la contrôles",
    "zone_owner": "Tenue par {name}",
    "zone_defends": "Tes cartes la défendent. Rapporte {n} points/jour.",
    "zone_free_note": "Personne ne la tient — conquiers-la. Rapporte {n} points/jour.",
    "zone_enemy_note": "Zone ennemie. Rapporte {n} points/jour à son détenteur.",
    "zone_mine_def": "Ta défense garde cette zone",
    "zone_noclan": "Rejoins un clan pour jouer la carte.",
    "zone_leader_only": "Seul le chef peut attaquer.",
    "zone_noadj": "Ne borde pas tes zones",
    "zone_beachhead": "Pars d’une zone libre",
    "zone_attack": "Attaquer la zone",
    "zone_confirm": "Attaquer {name} ?",
    "zone_won": "🏆 Zone conquise !",
    "zone_lost": "💥 Attaque repoussée",
    "wl_took": "a conquis",
    "wl_failed": "n’a pas pris",
    "zone_porto": "Port aux Poissons",
    "zone_tetti": "Toits Chauds",
    "zone_giardino": "Jardin",
    "zone_vicolo": "Ruelle",
    "zone_piazza": "Grande Place",
    "zone_mercato": "Marché",
    "zone_parco": "Parc",
    "zone_fontana": "Fontaine",
    "zone_molo": "Quai",
    "pick_min": "Choisis-en au moins {n}",
    "scout_title": "Reconnaissance",
    "scout_enemy": "Ils défendent",
    "scout_yours": "Tu alignes (min {n})",
    "scout_go": "⚔️ Attaquer ({n})",
    "scout_pickmin": "Choisis-en au moins {n}",
    "scout_wait": [
      "Montre-moi ces champions ! Qui monte au front ? 👀",
      "Sors l’équipe, je dois jauger l’ennemi !",
      "Choisis tes combattants, allez ! J’ai pas que ça à faire !"
    ],
    "sfregio_name": "Griffe",
    "sfregio_pct": "~{p}% — parole de matou ! 🐾",
    "sfregio_hi": [
      "Pfff, ils vont les balayer ! J’y mets mes moustaches ! 💥",
      "Fastoche, minou ! Ces boules de poils s’évanouissent d’un feulement !",
      "Victoire dans la poche ! Je sors déjà les confettis ! 🎉",
      "Une promenade, mon gars. Ramène une médaille, hein !"
    ],
    "sfregio_mid": [
      "Bon, c’est du 50-50… mais on est des chatons ? Fonce !",
      "Pile ou face, l’ami. Croise les pattes et prie !",
      "Ça peut basculer. Garde les griffes affûtées !",
      "Égalité. Je miserais bien un peu… mais chut !"
    ],
    "sfregio_low": [
      "Ouh là, risqué, minou. Mais quel panache ! J’essaierais… peut-être.",
      "Aïe, ça sent le roussi. Prends un pansement, au cas où.",
      "Coup de poker, l’ami. Mais les héros adorent le risque… ou la sieste.",
      "J’aime pas ça. M’enfin, la chance sourit aux moustachus… parfois."
    ],
    "sfregio_bad": [
      "T’es sérieux ? Ces monstres vont te croquer ! 🙀",
      "Suicide pur, mon gars. Reviens quand t’auras grandi.",
      "Non non non. Ils vont te réduire en pâtée !",
      "T’es fou ? Ce sont des lions déguisés ! …c’est ton enterrement."
    ],
    "need3": "Il te faut au moins 3 cartes fraîches pour attaquer (3v3).",
    "zone_take_free": "Occuper {name} ? Elle est libre : tu la prends sans combattre."
  }
};
