(window.LANG_DB=window.LANG_DB||{})["es"] = {
  "ui": {
    "tagline": "Fotografía a tu gato y conviértelo en una carta coleccionable",
    "tab_crea": "📸 Crear",
    "tab_carte": "📚 Cartas",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Mundo",
    "tab_mercato": "🔁 Mercado",
    "tab_boss": "🤖 Jefes",
    "tab_pal": "🏋️ Gimnasio",
    "tab_med": "🏅 Medallas",
    "tab_reg": "📖 Reglas",
    "drop_title": "Toca para hacer o subir una foto",
    "drop_sub": "JPG o PNG — mejor si el gato se ve bien",
    "cat_name": "Nombre del gato (opcional)",
    "gen_btn": "✨ Generar la carta",
    "dl_card": "⬇️ Descargar la carta (PNG)",
    "regen_btn": "🔁 Regenerar el dibujo (30 puntos)",
    "new_card": "🔄 Nueva carta",
    "coll_title": "📚 Tu colección",
    "dojo_title": "🥋 Dojo",
    "your_card": "Tu carta",
    "opponent": "Oponente",
    "fight_btn": "⚔️ ¡Pelea!",
    "tourn4": "🏆 Torneo de 4",
    "tourn8": "🏆 Torneo de 8",
    "albo": "📊 Palmarés",
    "pub_sum": "🗂️ Elige qué cartas publicar en el Mundo",
    "player_name": "Tu nombre de jugador (obligatorio, mín 3 letras)",
    "pub_btn": "📤 Publicar las cartas elegidas",
    "duel_title": "⚡ Reta a un amigo",
    "duel_champ": "Tu campeón para el duelo",
    "qr_show": "📱 Mostrar mi QR",
    "qr_scan": "📷 Escanear el suyo",
    "world_title": "🌍 Arena Mundial",
    "my_world": "🐱 Tus cartas en el mundo",
    "my_online": "Tu carta para los retos online",
    "find_btn": "🔄 Buscar rivales en el mundo",
    "leader_title": "🏅 Clasificación mundial",
    "leader_more": "⬇️ Mostrar más posiciones",
    "market_title": "🔁 Mercado",
    "trade_title": "🔄 Intercambio (trueque)",
    "trade_browse": "🔍 Ver cartas para intercambiar",
    "trader_ask": "💰 Pedir consejo al Mercader",
    "auc_title": "⚖️ Subastas",
    "auc_create": "🔨 Subastar una carta",
    "auc_refresh": "🔄 Actualizar subastas",
    "boss_title": "🤖 Jefes de la Arena",
    "boss_chall": "Tu retador (cartas publicadas)",
    "gym_title": "🏋️ Gimnasio",
    "gym_student": "El alumno de hoy",
    "gym_pantry": "🍽️ Despensa — compra y gánatelo jugando",
    "coach_ask": "🎓 Pedir consejo al Coach",
    "mis_title": "📅 Misiones de hoy",
    "med_title": "🏅 Medallero",
    "reg_title": "📖 Las reglas de CatCards",
    "opt_title": "⚙️ Opciones",
    "locked_title": "Se requiere acceso",
    "locked_txt": "Puntos, Mercado, retos y entrenamientos viven en tu cuenta: inicia sesión para usar Dojo, Mundo, Mercado, Jefes y Gimnasio.",
    "login_google": "🔵 Entrar con Google",
    "login_hint": "Inicia sesión: puntos, Mercado y retos viven en tu cuenta",
    "logout": "Salir",
    "close": "✖ Cerrar",
    "skip_intro": "⏭️ Saltar la presentación",
    "bet_title": "🥊 El rincón del Tío Rocco",
    "bet_sub": "🎲 Pronóstico",
    "bet_skip": "Sin apuesta, ¡al combate!",
    "bet_back": "↩️ Volver (cancelar el combate)",
    "points_lbl": "💰 Tus puntos:",
    "dl_short": "⬇️ Descargar",
    "nick_btn": "✏️ Cambiar apodo",
    "theme_btn": "▶️ Escuchar el tema",
    "retire_btn": "🚪 Retirar del mundo",
    "frame_btn": "🎨 Marco de Oro (100 puntos)",
    "del_btn": "🗑️ Eliminar"
  },
  "stat": {
    "Forza": "Fuerza",
    "Intelligenza": "Inteligencia",
    "Destrezza": "Destreza",
    "Velocità": "Velocidad",
    "Fascino": "Encanto",
    "Indifferenza": "Indiferencia"
  },
  "rarity": {
    "Comune": "Común",
    "Rara": "Rara",
    "Epica": "Épica",
    "Leggendaria": "Legendaria"
  },
  "ann": {
    "red": "Desde la esquina roja... {n}... «{k}»!",
    "blue": "Desde la esquina azul... {n}... «{k}»!"
  },
  "nicks": {
    "n01": "El Sócrates de la Lata",
    "n02": "El Barón Colmillo Torcido",
    "n03": "El Coloso de las Brasas",
    "n04": "El Gladiador del Asfalto",
    "n05": "El Quesito Durmiente",
    "n06": "El Monolito de Felpa",
    "n07": "El Maestro Lamedor Zen",
    "n08": "El Imperturbable Zen",
    "n09": "La Fortaleza Blanda Inamovible",
    "n10": "El Radar del Más Allá del Sofá",
    "n11": "El Radar de los Males",
    "n12": "Su Suavidad Hipnótica",
    "n13": "El Veterano del Ronroneo",
    "n14": "El Triste Hipnotista Felino",
    "n15": "El Panzer de Seda",
    "n16": "El Escape en Llamas",
    "n17": "El Ovillo Hipnótico",
    "n18": "La Garra de Jengibre",
    "n19": "El Dirigible de Mesa",
    "n20": "El Bastión de Pelo",
    "n21": "El Mejilla de Acero",
    "n22": "El Fantasma del Sofá",
    "n23": "La Furia del Trastero",
    "n24": "El Tornado de Pelo",
    "n25": "La Sombra de la Despensa",
    "n26": "El Ninja del Alféizar",
    "n27": "La Avalancha Rojiza",
    "n28": "El Sicario de las Cortinas",
    "n29": "El Terror de los Ovillos",
    "n30": "La Locomotora Perezosa",
    "n31": "El Filósofo del Radiador",
    "n32": "El Huracán en Pantuflas",
    "n33": "El Guepardo de Salón",
    "n34": "La Esfinge del Frigorífico",
    "n35": "El Relámpago Socarrón",
    "n36": "El Cojín Asesino",
    "n37": "La Bestia del Balcón",
    "n38": "El General Zarpazo",
    "n39": "El Acróbata de Medianoche",
    "n40": "El Sultán de la Siesta",
    "n41": "El Tigre de la Moqueta",
    "n42": "El Fantasma de la Escalera",
    "n43": "El Destructor de Sofás",
    "n44": "La Pantera del Rellano",
    "n45": "El Barón de los Bocaditos",
    "n46": "El Emperador de la Cesta",
    "n47": "El Pirata del Pescado Fresco",
    "n48": "El Rayo de Peluche",
    "n49": "El Campeón de las Croquetas",
    "n50": "El Estratega del Desván",
    "n51": "El Monstruo de las Zapatillas",
    "n52": "La Duquesa con Garras",
    "n53": "El Vikingo Aterciopelado",
    "n54": "El Enigma Bigotudo",
    "n55": "El Ciclón Silencioso",
    "n56": "La Zarpa del Destino",
    "n57": "El Rey del Cartón",
    "n58": "La Emboscada Permanente",
    "n59": "El Meteorito Blando",
    "n60": "La Leyenda del Patio",
    "n61": "El Guardián del Cuenco",
    "n62": "El Ojo de la Noche",
    "n63": "El Samurái Despeluchado",
    "n64": "La Furia Tricolor",
    "n65": "El Profesor de Emboscadas",
    "n66": "El Almirante de los Tejados",
    "n67": "La Apisonadora",
    "n68": "La Peste Elegante",
    "n69": "El Volcán Somnoliento",
    "n70": "La Garra de Terciopelo",
    "n71": "El Bandido de la Cocina",
    "n72": "El Centinela del Frigo",
    "n73": "El Dragón del Cojín",
    "n74": "El Eco del Maullido",
    "n75": "El Maestro del Ronroneo",
    "n76": "La Tormenta de Bolsillo",
    "n77": "El Gigante Amable",
    "n78": "El Último Callejero",
    "n79": "El Cazador de Lagartijas",
    "n80": "La Novena Vida"
  },
  "descrs": {
    "d01": "Duerme 20 horas al día y las otras 4 entrena para dormir mejor.",
    "d02": "Nunca ha perdido una batalla contra un calcetín.",
    "d03": "Cree que el frigorífico le debe explicaciones.",
    "d04": "Maestro en el arte de ocupar justo donde querías sentarte.",
    "d05": "Ha tirado tres jarrones. Todos culpables.",
    "d06": "Habla tres idiomas: ronroneo, maullido y desprecio.",
    "d07": "Corre a las 4 de la mañana por razones que no nos incumben.",
    "d08": "Un guerrero nato, siempre que el sofá esté a menos de dos metros.",
    "d09": "Su cuenco está medio vacío. Siempre. Incluso lleno.",
    "d10": "Mira fijamente la pared porque la pared empezó primero.",
    "d11": "Ex callejero, ahora alto ejecutivo de la siesta.",
    "d12": "Ronronea como un tractor y araña como una navaja.",
    "d13": "El veterinario aún lo recuerda en sus pesadillas.",
    "d14": "No persigue ratones: envía avisos de desahucio.",
    "d15": "Sabe abrir tres tipos de puertas y finge que no.",
    "d16": "La caja vale más que el regalo. Siempre.",
    "d17": "Doctorado en miradas de juicio.",
    "d18": "Lucha contra el crimen. El crimen es la aspiradora.",
    "d19": "Cada silla de la casa es suya. También la tuya.",
    "d20": "Entrena en las cortinas cuando nadie mira.",
    "d21": "Pasatiempo favorito: tirar cosas de las mesas con elegancia.",
    "d22": "Maúlla en do menor cuando el cuenco está vacío.",
    "d23": "Nadie lo ha visto llegar. Solo irse con la cena.",
    "d24": "Pesa justo lo necesario para inmovilizarte las piernas.",
    "d25": "Las lagartijas del barrio han puesto precio a su cabeza.",
    "d26": "Duerme en posturas que desafían la física y el sentido común.",
    "d27": "Entendió el láser. Finge que no, por lástima.",
    "d28": "Un cruce entre un cojín y un cepo.",
    "d29": "Vigila el barrio desde la ventana como un jefe de estado.",
    "d30": "Su ronroneo cura el estrés. Sus uñas lo causan.",
    "d31": "Come como un lobo, duerme como una piedra, reina como un rey.",
    "d32": "El único gato que ganó una discusión con un pepino.",
    "d33": "Se ofende si lo miras. Se ofende si no lo miras.",
    "d34": "Tiene tres escondites secretos. El mejor: en medio del pasillo.",
    "d35": "De pequeño cayó en un cuenco de nata. Nunca se recuperó.",
    "d36": "Enseña yoga a los gatos del barrio. Primera lección: ignorar a todos.",
    "d37": "El cartero pidió el traslado.",
    "d38": "Colecciona gomas de pelo. Nadie sabe dónde las esconde.",
    "d39": "Cuando hay tormenta, protege la casa. Desde debajo de la cama.",
    "d40": "Su mirada ha espantado a dos perros y un fontanero.",
    "d41": "Vive para tres cosas: comer, dormir y juzgarte.",
    "d42": "Una vez vio un ratón. Ambos aún lo cuentan.",
    "d43": "Elegantísimo hasta que se cae del alféizar.",
    "d44": "Adoptó a una familia de humanos. Los está adiestrando bien.",
    "d45": "No se sube a la mesa. La mesa baja a su nivel.",
    "d46": "Sabe exactamente cuándo abres el atún. Incluso a una manzana.",
    "d47": "El ovillo ya estaba así cuando llegó.",
    "d48": "Mitad gato, mitad sirena de alarma de las 5 a.m.",
    "d49": "Pelea con honor, gana con estilo, duerme sin vergüenza.",
    "d50": "Lo último que ven las alfombras antes del final."
  },
  "battle": {
    "skip": "⏭️ Presentación saltada: ¡al grano!",
    "open": "🎤 SEÑORAS Y SEÑOREEES… ¡bienvenidos a la Arena CatCards!",
    "red": "🔴 Esquina roja: {NAME}, «{nick}»! {rec}",
    "blue": "🔵 Esquina azul: {NAME}, «{nick}»! {rec}",
    "debut": "¡En su debut en la arena!",
    "theme": "🎵 Suena el tema de entrada de {name}…",
    "ding": "🔔 ¡DING DING DING!",
    "first_fast": "⚡ ¡{name} es más rápido y ataca primero!",
    "first_surprise": "😼 ¡{name} sorprende a todos y empieza!",
    "round_end": "🔔 ¡Fin del asalto {round}! Los gatos vuelven a su esquina a lamerse…",
    "charmed_skip": "😍 ¡{name} está embelesado y pierde el turno!",
    "chant": "🎺 Desde las gradas: «{NAME}! {NAME}!»",
    "pu_yarn": "🧶 ¡Un ovillo rueda a la arena! {name} juega y recupera {hp} PV",
    "pu_catnip": "🌿 ¡Hierba gatera! {name} está eufórico: próximo golpe DOBLE (pero algo mareado…)",
    "pu_box": "📦 ¡Una caja de cartón! {name} no se resiste: pierde el turno pero es INTOCABLE!",
    "pu_fish": "🐟 ¡Un pez fresco vuela a la arena! {name} rebosa energía: +agilidad por 3 turnos",
    "purr_heal": "💗 {name} ronronea y recupera {hp} PV",
    "double_paw": "🐾 ¡Doble Zarpazo! ¡{name} ataca otra vez!",
    "box_dodge": "📦 {opp} está escondido en la caja: ¡el golpe de {name} falla!",
    "dodge": "💨 {name} intenta {move} pero {opp} esquiva!",
    "final_blow": "⏱️ El tiempo se ralentiza… ¡GOLPE FINAL!",
    "hit": "{icon} {name} usa {move}!{crit}{catnip}  −{dmg} PV",
    "crit_tag": " 💥 ¡CRÍTICO!",
    "catnip_tag": " 🌿 ¡POTENCIADO!",
    "dev1": "😱 ¡Golpe devastador!",
    "dev2": "🎙️ ¡El público enloquece!",
    "dev3": "💢 ¡Qué potencia impresionante!",
    "on_fire": "🔥 ¡{name} está ON FIRE! ¡Tres golpes seguidos!",
    "on_ropes": "🎙️ ¡{opp} está contra las cuerdas! El público contiene la respiración…",
    "clever": "✨ ¡Jugada astuta! {opp} queda confuso y perderá un turno!",
    "nine_lives": "🐈 ¡{opp} usa una de sus Nueve Vidas y aguanta con 1 PV!",
    "charm_hit": "✨ ¡{opp} queda embelesado por el encanto de {name}!",
    "replay": "📹 REPETICIÓN del golpe final…",
    "winner": "🏆 ¡{name} gana el combate!",
    "win_points": "💰 ¡+10 puntos por la victoria!",
    "boss_points": "💰 ¡+10 puntos: has domado a un Jefe de la Arena!",
    "boss_noprize": "🎖️ Jefe ya vencido hoy: gloria sí, premio mañana.",
    "boss_survives": "🤖 El Jefe sigue en pie... el intento de hoy se fue: hasta mañana (quizá con hierba gatera 🌿).",
    "tourn_champ": "👑 ¡{name} es el CAMPEÓN del torneo!",
    "world_ok": "🌍 ¡Resultado registrado en la Arena Mundial!",
    "bet_win": "🎲 ¡Acertaste! Apostaste {stake} a {name}: +{gain} puntos (total: {total})",
    "bet_lose": "🎲 Fallaste: −{stake} puntos (total: {total}). ¡La próxima irá mejor!",
    "stake": "🎁 En juego — victoria: {win} · derrota: +{lose} XP",
    "stake_pts": "+{pt} puntos y +{xp} XP",
    "stake_nopts": "+{xp} XP (sin puntos en local)",
    "boss_stake_note": " — puntos solo en la 1ª victoria del día",
    "entry_catnip": "🌿 ¡{name} entra en la arena ya cargado de hierba gatera!"
  },
  "chars": {
    "rocco_warn": "Ojo con su {stat}: ahí te come.",
    "rocco_70": "Chaval, a este lo tumbas antes del gong. No te confíes y ciérralo rápido.",
    "rocco_55": "Eres el favorito, pero los favoritos que se duermen acaban en la lona. Pega primero.",
    "rocco_50": "Cincuenta-cincuenta, chaval: gana el que tenga más hambre. Si tienes 50 puntos, la hierba gatera los vale.",
    "rocco_35": "No te miento: es más grande que tú. Sin hierba gatera yo no haría este combate.",
    "rocco_lose": "Hazle caso al viejo Rocco: este te rompe. Vuelve al gimnasio, sube un nivel y LUEGO hablamos. Si insistes, al menos la hierba gatera.",
    "baratto_great": "🤑 ¡Un chollo! Recibes mucho más de lo que das — ciérralo rápido.",
    "baratto_good": "👍 Buen trato: sales ganando. El Mercader aprueba.",
    "baratto_even": "⚖️ Intercambio parejo: decide con el corazón, no con la cartera.",
    "baratto_bad": "😾 Pierdes algo... ¿seguro? El Mercader tuerce los bigotes.",
    "baratto_terrible": "🙀 ¡Pésimo trato! Das mucho más de lo que recibes. Olvídalo.",
    "baratto_empty": "¡No tienes cartas para trocar! Crea algunas y vuelve: el bazar es para negocios, no caridad.",
    "inc_100a": "¡CIEN PUNTOS! ¡Qué locura magnífica! 😼",
    "inc_100b": "¡Una oferta de reyes! ¿Y quién se atreve a subir?",
    "inc_50a": "¡Cincuenta! ¡El público tiembla, señores!",
    "inc_50b": "¡Buena cifra! ¡La subasta se calienta!",
    "inc_bata": "¡Y sube otra vez! ¡No paran!",
    "inc_batb": "¡Batalla hasta el último punto, qué espectáculo!",
    "inc_starta": "¡Primera puja en la mesa! ¿Quién da más?",
    "inc_startb": "¡Empezamos! ¡Adjudicado al que no se rinda!",
    "baffo_open": [
      "¡Miau, recluta! ",
      "Escucha al viejo Baffo: ",
      "Suelta la croqueta y escucha: ",
      "En mis tiempos no había cojines blandos. ",
      "Bigotes tiesos y orejas alerta: "
    ],
    "baffo_empty": "¡El gimnasio está vacío! Tráeme un alumno desde la pestaña 📸 Crear.",
    "baffo_indiff_afford": "El punto débil de {name} es {stat} ({val}): entrénala con el combo {combo} (60 puntos), puedes permitírtelo.",
    "baffo_indiff_save": "El punto débil de {name} es {stat} ({val}), pero solo se entrena con el combo {combo} (60 puntos): te faltan {miss}, ve ahorrando.",
    "baffo_indiff_alt": " O mientras tanto refuerza {stat2} ({val2}) con {food} (25 puntos).",
    "baffo_weak": "El punto más débil de {name} es {stat} ({val}): dale {food}.",
    "baffo_combo": "Tienes {pts} puntos: el combo {combo} ({tgt}) sube dos cosas en un solo descanso — caro pero útil si tienes prisa.",
    "baffo_record_bad": "Con {w} victorias y {l} derrotas hace falta garra, no mimos.",
    "baffo_unbeaten": "Está invicto: cuidado no se le suba a la cabeza.",
    "baffo_margin": "Margen de entrenamiento agotado: solo las victorias en el Mundo desbloquean más progreso.",
    "baffo_broke": "Y las arcas lloran ({pts} puntos): gana alguna apuesta mundial.",
    "baffo_fit": "{name} está en plena forma. Que pelee, que el banquillo ablanda los músculos.",
    "felini_open": [
      "Escucha al Mánager: ",
      "He olido el negocio: ",
      "El ring es un tablero de ajedrez: ",
      "Hablan los números, chaval: "
    ],
    "felini_checking": "Un momento, consulto los registros…",
    "felini_noauth": "Primero inicia sesión, chaval: los negocios se hacen con un nombre en el contrato.",
    "felini_nocard": "No tienes un campeón publicado. Publica una carta y hablamos de negocios.",
    "felini_resting": "😴 {name} se está recuperando: vuelve cuando esté listo otra vez y hablamos de estrategia.",
    "felini_norank": "Tu campeón no aparece en el ranking: republícalo y vuelve a verme.",
    "felini_loss_streak": "{name} ha perdido {n} seguidas (🧊): sácalo del circuito un tiempo, llévalo con el Coach, y que vuelva hambriento.",
    "felini_champ": "{name} es el CAMPEÓN 👑: defiende la corona{chaser}.",
    "felini_chaser": ", y ojo con {name} (#2, {elo} pt) que está al acecho",
    "felini_target": "el próximo combate ideal para {name} (#{rk}) es {tname} de {owner} (#{trk}, {elo} pt): {verdict}",
    "felini_v_risky": "arriesgado, pero si lo ganas das el pelotazo en la clasificación.",
    "felini_v_beatable": "sobre el papel es vencible: una victoria de gestión.",
    "felini_v_even": "un combate parejo, de los que le gustan al público.",
    "felini_prob_low": "Pero hablemos claro: Tío Rocco estima solo un {p}% de victoria. Yo esperaría — gimnasio, un nivel más, Y ENTONCES se firma el contrato.",
    "felini_prob_mid": "Las probabilidades dicen {p}%: combate abierto, deciden los nervios (y quizá la hierba gatera 🌿).",
    "felini_prob_high": "Tío Rocco estima un {p}% de victoria: a tu alcance. Ve y cierra el combate.",
    "felini_belt": "Y recuérdalo: ese tiene el CINTURÓN 👑 — la clasificación no cuenta nada, lo ganas y el campeón eres TÚ.",
    "felini_hot": "Ojo eso sí: es un rival duro, viene de una racha de {n} victorias 🔥.",
    "felini_cold": "Y te digo: está en plena crisis (🧊 {n} derrotas seguidas) — el momento perfecto para golpear.",
    "felini_catnip_need": "Mi consejo desde la esquina: invierte 50 puntos en hierba gatera 🌿 antes del combate — contra uno así hace falta el turbo.",
    "felini_catnip_broke": "Haría falta hierba gatera 🌿, pero las arcas lloran ({pts} puntos): o encuentras puntos, o eliges un objetivo más blando.",
    "felini_catnip_opt": "¿Hierba gatera 🌿? Opcional: combate parejo, decidirán los nervios.",
    "felini_catnip_no": "Nada de hierba gatera: se las apaña con sus propias patas, ahorra los puntos.",
    "felini_notarget": "ningún objetivo de otros dueños por encima de ti ahora mismo (o descansan todos): defiende la posición, o vuelve más tarde.",
    "felini_margin": "Y aún le quedan {n} puntos de margen en el gimnasio: una buena comida antes del combate nunca mató a nadie.",
    "trader_open": [
      "Psst, amigo: ",
      "¡Negocios, negocios! ",
      "El Mercader lo sabe todo: ",
      "Entre nosotros que entendemos: "
    ],
    "trader_best": "agarra fuerte a {name}, esa vale oro: no la cedas por cuatro perras.",
    "trader_worst": "si de verdad tienes que dar algo, empieza por {name} — tienes cosas mejores en mano.",
    "trader_commons": "Tienes un montón de {rar} ({n}): cambia un par por algo más raro, fíate.",
    "trader_gem": "Y ojo: hay una {rar} de {owner} en el escaparate — si tienes un buen repetido, intenta el cambio antes de que la pille otro.",
    "trader_browse": "Pulsa «Explorar cartas para intercambiar» y enséñame qué hay: yo te digo si hay negocio."
  },
  "titles": {
    "world": "DESAFÍO MUNDIAL",
    "live": "DUELO EN VIVO",
    "boss": "BOSS DE LA ARENA",
    "quarti": "CUARTOS DE FINAL",
    "semi": "SEMIFINAL",
    "finale": "FINAL"
  },
  "gym": {
    "lbl_allena": "Entrena:",
    "lbl_start": "▶️ ¡Empieza el entrenamiento!",
    "fn_croc": "Pienso",
    "fn_pollo": "Pollo",
    "fn_topo": "Ratoncito",
    "fn_erba": "Hierba gatera",
    "fn_pesce": "Pescado",
    "fn_chicche": "Golosinas",
    "fn_bistecca": "Filete del Guerrero",
    "fn_scarica": "Descarga Felina",
    "fn_fascino": "Encanto Fatal",
    "fn_trono": "Trono de Plumas",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Fuerza",
    "ft_topo": "🧠 Inteligencia",
    "ft_erba": "🎯 Destreza",
    "ft_pesce": "⚡ Velocidad",
    "ft_chicche": "✨ Encanto",
    "ft_bistecca": "💪 Fuerza + ❤️ HP",
    "ft_scarica": "⚡ Velocidad + 🎯 Destreza",
    "ft_fascino": "✨ Encanto + 🧠 Inteligencia",
    "ft_trono": "😼 Indiferencia + ❤️ HP",
    "gn_gomitolo": "Atrapa el ovillo",
    "gn_topo": "Caza del ratón",
    "gn_piuma": "Sigue la pluma",
    "gn_corda": "Tira y afloja",
    "gn_porta": "Derriba la puerta",
    "gn_laser": "Caza del láser",
    "gn_memory": "Memoria de las latas",
    "gn_pesca": "Pesca al vuelo",
    "gn_scatto": "Arranque felino",
    "gn_scalata": "Escalada de la estantería",
    "gn_fusa": "Ritmo del ronroneo",
    "gn_sfilata": "El Desfile",
    "gn_zen": "Zen del gato",
    "gn_sguardi": "Concurso de miradas",
    "ga_gomitolo": "Agilidad — 🌿 hierba gatera (Destreza) y 🐟 pescado (Velocidad)",
    "ga_topo": "Físico — 🍗 pollo (Fuerza) y 🥫 pienso (HP)",
    "ga_piuma": "Mente — 🐁 ratoncito (Inteligencia) y 🧀 golosinas (Encanto)",
    "ga_corda": "Fuerza — 🍗 pollo (Fuerza)",
    "ga_porta": "Fuerza — 🍗 pollo (Fuerza)",
    "ga_laser": "Destreza — 🌿 hierba gatera (Destreza)",
    "ga_memory": "Inteligencia — 🐁 ratoncito (Inteligencia)",
    "ga_pesca": "Velocidad — 🐟 pescado (Velocidad)",
    "ga_scatto": "Velocidad — 🐟 pescado (Velocidad)",
    "ga_scalata": "HP — 🥫 pienso (HP)",
    "ga_fusa": "Encanto — 🧀 golosinas (Encanto)",
    "ga_sfilata": "Encanto — 🧀 golosinas (Encanto)",
    "ga_zen": "Indiferencia — 🛋️ cojín real (Indiferencia)",
    "ga_sguardi": "Indiferencia — 🛋️ cojín real (Indiferencia)",
    "gd_gomitolo": "El ovillo se dispara por el recuadro y acelera con cada toque: tócalo cuantas más veces puedas en <strong>10 segundos</strong>.<br>🚫 Menos de 5 tomas: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_topo": "Los ratones asoman de sus madrigueras y desaparecen enseguida: golpéalos en cuanto aparezcan, durante <strong>15 segundos</strong>.<br>🚫 Menos de 5 golpes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_piuma": "Las plumas de colores parpadean en secuencia: repítela tocándolas en el mismo orden. Cada ronda la secuencia se alarga; un error termina el entrenamiento.<br>🚫 Menos de 3 rondas: comida desperdiciada · ✅ 3-4: bono ×1 · 🌟 5+: bono ×2",
    "gd_corda": "Machaca el botón <strong>TIRA</strong> para arrastrar al perrazo más allá de la línea: él tira hacia atrás sin parar, no sueltes durante <strong>10 segundos</strong>.<br>🚫 Menos de 8 tirones: comida desperdiciada · ✅ 8-15: bono ×1 · 🌟 16+: bono ×2",
    "gd_porta": "La barra de potencia va y viene disparada: toca cuando esté en la <strong>zona verde</strong> para cargar el zarpazo. Golpea lo más fuerte que puedas en <strong>12 segundos</strong>.<br>🚫 Menos de 5 buenos golpes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_laser": "El punto rojo aparece y desaparece cada vez más rápido: tócalo antes de que se esfume, durante <strong>12 segundos</strong>.<br>🚫 Menos de 6 tomas: comida desperdiciada · ✅ 6-11: bono ×1 · 🌟 12+: bono ×2",
    "gd_memory": "Descubre las cartas de dos en dos y empareja las parejas iguales de memoria, en <strong>30 segundos</strong>.<br>🚫 Menos de 3 parejas: comida desperdiciada · ✅ 3-4: bono ×1 · 🌟 5+: bono ×2",
    "gd_pesca": "El pez se escurre bajo el agua y aflora solo un instante: tócalo <strong>justo cuando salta</strong>. Las ventanas se acortan. Tienes <strong>14 segundos</strong>.<br>🚫 Menos de 5 tomas: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_scatto": "Espera el <strong>verde</strong> y toca lo más rápido posible: mide tu reflejo. 5 rondas — salir antes de tiempo pierde la ronda.<br>🚫 Menos de 2 buenos arranques: comida desperdiciada · ✅ 2-3: bono ×1 · 🌟 4+: bono ×2",
    "gd_scalata": "El gato salta de estante en estante: toca <strong>cuando la plataforma esté alineada</strong> para saltar encima. Un salto errado y caes. Sube lo más alto que puedas.<br>🚫 Menos de 5 estantes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_fusa": "El círculo se cierra a compás: toca <strong>cuando llegue al objetivo</strong>, al ritmo del ronroneo. Cuanto más preciso seas, más acelera el ritmo.<br>🚫 Menos de 5 toques a tiempo: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_sfilata": "En la pasarela aparece una flecha: <strong>desliza (swipe) en su dirección</strong> para hacer la pose. Las flechas llegan cada vez más rápido, tienes <strong>16 segundos</strong>.<br>🚫 Menos de 6 poses: comida desperdiciada · 🌟 12+: bono ×2",
    "gd_zen": "La disciplina de la indiferencia: <strong>ignora cada distracción</strong> (🐭 ratón, 🪶 pluma, 🔴 láser) y toca <strong>solo el cojín 🛋️</strong> cuando aparezca. Tocar una distracción te hace perder la ronda. Tienes <strong>14 segundos</strong>.<br>🚫 Menos de 5 cojines: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_sguardi": "<strong>Mantén pulsado</strong> y no te muevas: quien queda impasible gana. Pero si aparece un 😹 cosquilleo debes <strong>soltar enseguida</strong>, luego volver a pulsar. Resiste lo más que puedas.<br>🚫 Menos de 8 segundos de impasibilidad: comida desperdiciada · ✅ 8-13: bono ×1 · 🌟 14+: bono ×2",
    "tr_wasted_h": "🙀 ¡Comida desperdiciada!",
    "tr_wasted_b": "Puntuación: <strong>{score}</strong> — por debajo del umbral mínimo.<br><br>{ic} El {food} se perdió y {name} ahora descansa una hora.<br><br>😼 <em>«En mis tiempos se entrenaba hasta con los ojos vendados.»</em>",
    "tr_coach_wasted": "🙀 ¿¡Solo {score} puntos!? Comida desperdiciada.",
    "tr_perfect_h": "🌟 ¡Entrenamiento perfecto!",
    "tr_ok_h": "✅ ¡Entrenamiento logrado!",
    "tr_bonus2": " — ¡bono duplicado!",
    "tr_online": "🌍 Carta actualizada también en la Arena Mundial.<br>",
    "tr_body": "Puntuación: <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> para {name}</span><br><br>{online}😴 Ahora una hora de descanso: los músculos crecen durmiendo.",
    "tr_coach_perfect": "😼 ¡{score} puntos! {name} tiene madera de campeón.",
    "tr_coach_ok": "👍 {score} puntos, trabajo honesto. {name} crece."
  },
  "powers": {
    "pn_0": "Nueve Vidas",
    "pn_1": "Emboscada Perfecta",
    "pn_2": "Ronroneo Regenerador",
    "pn_3": "Doble Zarpazo",
    "pn_4": "Modo Líquido",
    "pn_5": "Mirada Hipnótica",
    "pn_6": "Armadura de Pereza",
    "pn_7": "Caos Felino",
    "pd_0": "la primera vez que cae KO se queda con 1 HP",
    "pd_1": "su primer ataque siempre es crítico",
    "pd_2": "recupera HP en cada uno de sus turnos",
    "pd_3": "25% de probabilidad de atacar dos veces",
    "pd_4": "esquiva mucho más a menudo",
    "pd_5": "hechiza con el doble de probabilidad",
    "pd_6": "recibe un 20% menos de daño",
    "pd_7": "su daño es impredecible (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Gana 1 desafío mundial",
    "m_world2": "Gana 2 desafíos mundiales",
    "m_fight3": "Combate 3 encuentros (los locales también cuentan)",
    "m_tourn": "Gana un torneo (de 4 u 8)",
    "m_upset": "La Hazaña: vence en el mundo a un rival con más Elo que el tuyo",
    "m_train1": "Completa un entrenamiento logrado",
    "m_gom10": "Haz 10+ en Atrapa el ovillo",
    "m_topo10": "Haz 10+ en Caza del ratón",
    "m_piuma5": "Llega a 5 rondas en Sigue la pluma",
    "m_boss": "Doma un Boss de la Arena",
    "m_bet": "Gana una apuesta",
    "m_catnip": "Gana un combate empezando con hierba gatera",
    "m_card": "Crea una carta nueva",
    "m_qr": "Juega un duelo en vivo (QR)",
    "a_prima_carta_nm": "Primera carta",
    "a_prima_carta_ds": "Crea tu primera carta",
    "a_coll5_nm": "Coleccionista",
    "a_coll5_ds": "5 cartas en la colección",
    "a_coll10_nm": "Gatero en serie",
    "a_coll10_ds": "10 cartas en la colección",
    "a_epica_nm": "¡Qué rareza!",
    "a_epica_ds": "Consigue una carta Épica",
    "a_legg_nm": "¡Legendaria!",
    "a_legg_ds": "Consigue una Legendaria",
    "a_win1_nm": "Primera victoria",
    "a_win1_ds": "Gana un desafío mundial",
    "a_win10_nm": "Veterano",
    "a_win10_ds": "Gana 10 desafíos mundiales",
    "a_win50_nm": "Leyenda",
    "a_win50_ds": "Gana 50 desafíos mundiales",
    "a_t4_nm": "Campeón",
    "a_t4_ds": "Gana un torneo de 4",
    "a_t8_nm": "Dominador",
    "a_t8_ds": "Gana un torneo de 8",
    "a_pub_nm": "En el mundo",
    "a_pub_ds": "Publica una carta",
    "a_wwin_nm": "Triplete",
    "a_wwin_ds": "Gana 3 desafíos mundiales seguidos",
    "a_bet_nm": "Corredor de apuestas",
    "a_bet_ds": "Gana una apuesta",
    "a_ricco_nm": "Ricachón",
    "a_ricco_ds": "Posee 150 puntos",
    "a_onore_nm": "Retiro con honor",
    "a_onore_ds": "Retira una carta con récord positivo",
    "a_disfatta_nm": "Debacle",
    "a_disfatta_ds": "Pierde 10 desafíos mundiales seguidos",
    "bm_ds": "Derrota a {name} (Div. {tier})",
    "bmall_nm": "Mataboss",
    "bmall_ds": "Derrota a los 64 Boss de la Arena",
    "cx_rar4": "El póker: una carta por cada rareza",
    "cx_razze3": "Descubre 3 razas diferentes",
    "cx_razze5": "Descubre 5 razas diferentes",
    "cx_razze10": "Descubre 10 razas diferentes",
    "cx_pot4": "Colecciona 4 poderes especiales distintos",
    "cx_pot8": "Colecciona los 8 poderes especiales",
    "cx_lv5": "Lleva un gato al nivel 5",
    "cx_hp100": "Una carta con 100+ HP",
    "cx_oro": "Una carta con el Marco de Oro",
    "p_done": "hecho",
    "p_won": "✓ conseguida",
    "p_towin": "🔒 por conseguir",
    "p_howto": "Cómo se consigue:",
    "p_reward": "Premio:",
    "p_unlocked": "Desbloqueada el",
    "cx_open": "(toca para abrir)",
    "cx_h_rar": "💎 Rareza",
    "cx_h_pow": "🌟 Poderes especiales",
    "cx_h_breeds": "🐱 Razas descubiertas",
    "cx_nobreeds": "Ninguna aún: la raza llega con el análisis IA de la foto.",
    "cx_h_objs": "🎯 Objetivos",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> objetivos <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex: {ic} {txt}! +{pt} puntos",
    "mis_tris_line": "🎉 Trío completado: +10 puntos de bono cobrados. ¡Hasta mañana!",
    "mis_toast_tris": "🎉 ¡TRÍO! Misión «{txt}» y día completo: ¡+5 y +10 de bono!",
    "mis_toast_done": "📅 Misión completada: {ic} {txt}! +5 puntos",
    "med_toast": "🏅 Medalla desbloqueada: {ic} {nm}! +{pt} puntos",
    "bm_sum": "🤖 Boss domados — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>"
  },
  "reg": {
    "r_h_cards": "🎴 Las cartas",
    "r_p_cards": "Fotografía un gato y se convierte en carta: la IA lo redibuja en cartoon y analiza su aspecto y carácter para generar <strong>estadísticas</strong> (un gatazo robusto tendrá más Fuerza), <strong>raza</strong>, <strong>descripción</strong>, <strong>poder especial</strong> y <strong>3 movimientos</strong> (💥 potente pero impreciso, ⚡ rápido y casi infalible, ✨ astuto que puede confundir). La <strong>rareza</strong> se sortea a partir de la huella de la foto: 55% Común, 28% Rara, 13% Épica, 4% Legendaria (las Épicas y Legendarias brillan y tienen estadísticas con bonus). La misma foto da siempre la misma carta.",
    "r_h_xp": "⭐ Experiencia y niveles",
    "r_p_xp": "Las cartas crecen combatiendo: <strong>desafíos mundiales y en vivo: 25 XP por victoria, 10 por derrota</strong> · <strong>arena local y torneos: 5 y 2</strong>. Cada 100 XP: +1 nivel = <strong>+4 HP, +3% de ataque y +3 de margen de gimnasio</strong>. Los espejos (carta contra sí misma) no cuentan.",
    "r_h_pts": "💰 Los puntos (la moneda)",
    "r_p_pts": "Se ganan con: <strong>+10 por cada victoria mundial o en vivo</strong>, +10 por cada Boss domado, 📅 misiones diarias (5 cada una, +10 el trío: máx 25 al día), apuestas ganadas, medallas (10-100 puntos cada una) y 🎁 códigos de regalo. Las victorias locales: cero puntos. Se <strong>gastan</strong> en: apuestas (10-100), comida en el gimnasio (20-25), 🌿 ventaja mundial (50), 🎨 Marco de Oro (100), 🔁 regeneración del dibujo (30). Perder un combate no cuesta puntos: solo las apuestas erradas.",
    "r_h_bet": "🎲 Las apuestas",
    "r_p_bet": "En los <strong>desafíos mundiales y en vivo</strong>: antes del combate eliges la apuesta y a quién apostar (⭐ favorito a cuota baja, 🐾 perdedor a cuota alta). Ganas la apuesta × (cuota − 1); si te equivocas pierdes la apuesta. Nada de apuestas en local ni en torneos.",
    "r_h_rest": "😴 El descanso",
    "r_p_rest": "Tras cada combate real (local 1v1, mundial, en vivo) y cada entrenamiento, los gatos implicados descansan <strong>1 hora</strong>: no pueden combatir ni comer. El descanso lo ven todos, también en línea. Los torneos son exhibiciones y no cansan.",
    "r_h_gym": "🏋️ El gimnasio",
    "r_p_gym": "Cada nivel desbloquea <strong>+3 puntos de margen de entrenamiento</strong>. Compras un alimento (🥫 HP · 🍗 Fuerza · 🐁 Inteligencia · 🌿 Destreza · 🐟 Velocidad · 🧀 Encanto) y el gato se lo gana con el ejercicio asociado: 🧶 ovillo (agilidad), 🐭 caza del ratón (físico), 🪶 sigue la pluma (mente). Umbrales: <strong>por debajo de 5 puntos comida desperdiciada, 5-9 bono ×1, 10+ bono ×2</strong> (para la pluma: 3 y 5 rondas). Las cartas publicadas se actualizan en línea solas. El Coach da consejos gratis.",
    "r_h_world": "🌍 La Arena Mundial",
    "r_p_world": "Inicia sesión con Google (o email), elige tu nombre de jugador (uno por cuenta, renombrable en todas partes de golpe) y <strong>publica las cartas que quieras</strong>: solo las publicadas y activas pueden desafiar en línea. Desafías las cartas de otros, el resultado va al registro y a la clasificación (ordenada por % de victorias). Puedes <strong>🚪 retirar</strong> una carta: queda en la clasificación como \"retirada\" pero nadie puede desafiarla más. El punto rojo en Mundo te avisa cuando tus cartas han combatido en tu ausencia.",
    "r_h_rank": "📊 La clasificación (estilo UFC)",
    "r_p_rank1": "Cada carta publicada tiene una puntuación <strong>Elo</strong>, que parte de <strong>1000</strong>. En cada combate el ganador <strong>toma</strong> puntos y el perdedor <strong>cede los mismos puntos</strong> — y la cantidad depende de la diferencia de fuerza: vencer a un rival <strong>más fuerte</strong> vale hasta <strong>~32 puntos</strong>, vencer a uno mucho más débil vale el mínimo, <strong>8</strong> (ganar fácil rinde poco, la hazaña rinde mucho). Ninguna carta baja nunca de 100. El cálculo lo hace el servidor, igual para todos.",
    "r_p_rank2": "La clasificación oficial es por Elo, pero el cinturón es otra cosa: <strong>campeón se llega SOLO venciendo al campeón vigente 👑</strong> en un desafío mundial o en vivo. Puedes superarlo en puntos cuanto quieras: sigues siendo primer aspirante hasta que lo tumbes en el ring. El campeón está siempre en lo alto de la clasificación, y quien ha sido campeón conserva para siempre el 🏆. Solo puedes desafiar a quien esté <strong>de 5 posiciones por encima a 5 por debajo</strong> de la tuya: para el título hay que escalar (en el top 5 el campeón está a tiro). La clasificación muestra las rachas — 🔥 victorias seguidas, 🧊 derrotas seguidas, y la mejor racha de siempre. El <strong>🎩 Mánager</strong> estudia los números y te aconseja el próximo combate adecuado, si conviene la hierba gatera 🌿, y cuándo es mejor retirarse un poco al gimnasio.",
    "r_h_cat": "🃏 El Catdex",
    "r_p_cat": "El álbum de la colección, al final de la pestaña 📚 Cartas: lleva la cuenta de las <strong>rarezas, razas y poderes especiales</strong> que has descubierto (las casillas que faltan quedan ❓) y premia los hitos con puntos <strong>únicos</strong> — del póker de rarezas (+25) a las 10 razas distintas (+25) hasta los 8 poderes (+30). La raza la escribe la IA cuando creas la carta: nombres parecidos (p. ej. \"atigrado\" y \"europeo atigrado\") cuentan como una sola familia. Para completarlo hace falta solo una cosa: fotografiar gatos nuevos.",
    "r_h_mis": "📅 Las misiones diarias",
    "r_p_mis": "Cada medianoche llegan <strong>3 misiones</strong>, iguales para todo el mundo: una de combate, una de gimnasio, una sorpresa (boss, apuestas, QR…). Cada una paga <strong>5 puntos</strong>, el trío completo otros <strong>10 de bono</strong>. Las encuentras arriba del 🏅 Medallero, con el ✅ en las ya hechas. Máximo 25 puntos al día: lo justo para un entrenamiento, o poco más.",
    "r_h_boss": "🤖 Los Boss de la Arena",
    "r_p_boss": "<strong>64 leyendas en 8 divisiones</strong> de dificultad creciente: desde los Callejeros del Barrio (fáciles) hasta los Boss Finales como el 🌑 Gatto Mammone o 🤖 MIAO-9000, monstruosos. Cada día hay <strong>2 activos, iguales para todo el mundo</strong> (los decide la fecha). Vencer a uno paga <strong>+10 puntos y 25 XP</strong>. Cuidado: tienes <strong>UN solo intento al día por boss</strong> — ganado, perdido o abandonado, se vuelve mañana. Elige bien el gato antes de bajar a la arena. Perder cuesta solo 2 XP de consolación. Tras el combate el gato <strong>descansa una hora</strong> como en cualquier combate real, y la hierba gatera 🌿 comprada antes vale también aquí. Contra los Boss bajan al campo <strong>solo las cartas publicadas en el Mundo</strong>, y los boss <strong>no tocan la clasificación Elo</strong>. Cada boss tiene su medalla (sección «🤖 Boss domados» en el 🏅 Medallero, premios más ricos para las divisiones altas), más el 🏆 Mataboss para quien los dome a los 64.",
    "r_h_qr": "⚡ El duelo en vivo (QR)",
    "r_p_qr": "Dos teléfonos: uno muestra el QR de su carta (🥋 Dojo → 📱), el otro lo escanea (📷) y el duelo se juega en su pantalla. <strong>Cuenta como un desafío mundial</strong>: puntos, XP completos, medallas, descanso, apuestas y resultado registrado si las cartas están publicadas.",
    "r_h_tourn": "🏆 Torneos y medallero",
    "r_p_tourn": "Torneos de 4 u 8 entre tus cartas y los rivales: exhibiciones automáticas con cuadro (XP reducidos, sin descanso, sin puntos). El <strong>🏅 Medallero</strong> tiene 25 medallas con premios en puntos (9 son de Boss) — toca una medalla para descubrir cómo se consigue. Ojo con la 💀 Debacle…",
    "r_h_fight": "⚔️ El combate",
    "r_p_fight": "Automático por turnos: la Velocidad decide quién empieza (normalmente), la Fuerza el daño, la Destreza las esquivas, la Inteligencia los críticos (×1.6), el Encanto hechiza, la Indiferencia reduce el daño. Ningún golpe quita más del 38% de los HP. Poderes especiales, potenciadores aleatorios (🧶🌿📦🐟), golpe final a cámara lenta y repetición. La presentación se puede saltar (⏭️ o desde Opciones)."
  }
};
