(window.LANG_DB=window.LANG_DB||{})["es"] = {
  "ui": {
    "tagline": "Fotografía a tu gato y conviértelo en una carta coleccionable",
    "tab_crea": "📸 Crear",
    "tab_carte": "📚 Cartas",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Mundo",
    "tab_mercato": "🔁 Mercado",
    "tab_boss": "🤖 Jefes",
    "tab_pal": "🏋️ Gimnasio",
    "tab_med": "🏅 Medallas",
    "tab_reg": "📖 Reglas",
    "drop_title": "Toca para hacer o subir una foto",
    "drop_sub": "JPG o PNG — mejor si el gato se ve bien",
    "cat_name": "Nombre del gato (opcional)",
    "gen_btn": "✨ Generar la carta",
    "dl_card": "⬇️ Descargar la carta (PNG)",
    "regen_btn": "🔁 Regenerar el dibujo (30 puntos)",
    "new_card": "🔄 Nueva carta",
    "coll_title": "📚 Tu colección",
    "dojo_title": "🥋 Dojo",
    "your_card": "Tu carta",
    "opponent": "Oponente",
    "fight_btn": "⚔️ ¡Pelea!",
    "tourn4": "🏆 Torneo de 4",
    "tourn8": "🏆 Torneo de 8",
    "albo": "📊 Palmarés",
    "pub_sum": "🗂️ Elige qué cartas publicar en el Mundo",
    "player_name": "Tu nombre de jugador (obligatorio, mín 3 letras)",
    "pub_btn": "📤 Publicar las cartas elegidas",
    "duel_title": "⚡ Reta a un amigo",
    "duel_champ": "Tu campeón para el duelo",
    "qr_show": "📱 Mostrar mi QR",
    "qr_scan": "📷 Escanear el suyo",
    "world_title": "🌍 Arena Mundial",
    "my_world": "🐱 Tus cartas en el mundo",
    "my_online": "Tu carta para los retos online",
    "find_btn": "🔄 Buscar rivales en el mundo",
    "leader_title": "🏅 Clasificación mundial",
    "leader_more": "⬇️ Mostrar más posiciones",
    "market_title": "🔁 Mercado",
    "trade_title": "🔄 Intercambio (trueque)",
    "trade_browse": "🔍 Ver cartas para intercambiar",
    "trader_ask": "💰 Pedir consejo al Mercader",
    "auc_title": "⚖️ Subastas",
    "auc_create": "🔨 Subastar una carta",
    "auc_refresh": "🔄 Actualizar subastas",
    "boss_title": "🤖 Jefes de la Arena",
    "boss_chall": "Tu retador (cartas publicadas)",
    "gym_title": "🏋️ Gimnasio",
    "gym_student": "El alumno de hoy",
    "gym_pantry": "🍽️ Despensa — compra y gánatelo jugando",
    "coach_ask": "🎓 Pedir consejo al Coach",
    "mis_title": "📅 Misiones de hoy",
    "med_title": "🏅 Medallero",
    "reg_title": "📖 Las reglas de CatCards",
    "opt_title": "⚙️ Opciones",
    "locked_title": "Se requiere acceso",
    "locked_txt": "Puntos, Mercado, retos y entrenamientos viven en tu cuenta: inicia sesión para usar Dojo, Mundo, Mercado, Jefes y Gimnasio.",
    "login_google": "🔵 Entrar con Google",
    "login_hint": "Inicia sesión: puntos, Mercado y retos viven en tu cuenta",
    "logout": "Salir",
    "close": "✖ Cerrar",
    "skip_intro": "⏭️ Saltar la presentación",
    "bet_title": "🥊 El rincón del Tío Rocco",
    "bet_sub": "🎲 Pronóstico",
    "bet_skip": "Sin apuesta, ¡al combate!",
    "bet_back": "↩️ Volver (cancelar el combate)",
    "points_lbl": "💰 Tus puntos:",
    "dl_short": "⬇️ Descargar",
    "nick_btn": "✏️ Cambiar apodo",
    "theme_btn": "▶️ Escuchar el tema",
    "retire_btn": "🚪 Retirar del mundo",
    "frame_btn": "🎨 Marco de Oro (100 puntos)",
    "del_btn": "🗑️ Eliminar",
    "coach_greet": "Miau, recluta. Elige un alumno y pongámonos a trabajar.",
    "gym_combo": "🌟 Combo Premium — dos estadísticas, un solo descanso",
    "bet_choose": "Elige la apuesta y a quién apostar. Si te equivocas, pierdes la apuesta.",
    "bet_insufficient": "Puntos insuficientes para apostar (mínimo 10).",
    "tab_sent": "🗺️ Sendero",
    "opt_ai_sum": "🤖 Ajustes de IA",
    "opt_key_label": "Clave API Gemini",
    "opt_test_key": "🧪 Probar la clave",
    "opt_backup_label": "Copia de la colección",
    "opt_export": "💾 Exportar copia",
    "opt_import": "📂 Importar copia",
    "opt_gift_label": "🎁 Código de regalo",
    "opt_redeem": "Canjear puntos",
    "opt_av_label": "Audio y presentaciones",
    "snd_on": "🔊 Sonido: ON",
    "snd_off": "🔇 Sonido: OFF",
    "pres_on": "🎬 Presentaciones: ON",
    "pres_skip": "⏭️ Presentaciones: SALTADAS",
    "bt_bracket": "📋 Cuadro",
    "qr_desc1": "Duelo en vivo, teléfono contra teléfono: cuenta para puntos, medallas y apuestas como un desafío mundial.",
    "qr_desc2": "Uno muestra el QR, el otro lo escanea: el duelo se juega en el teléfono de quien escanea.",
    "coll_one": "1 carta guardada",
    "coll_many": "{n} cartas guardadas",
    "coll_none": "Aún no hay cartas: crea una en la pestaña 📸 Crear, o importa una copia desde ⚙️ Opciones.",
    "xp_line": "📈 Nivel {lvl} — {inLvl}/100 XP (≈ {w} victorias mundiales para el Nv.{next})",
    "opt_ai_desc": "Sin clave API uso un filtro cartoon integrado y gratuito. Con una clave <strong>Google Gemini</strong> el cartoon lo genera la IA (calidad muy superior). Créala gratis en <strong>aistudio.google.com</strong> → «Get API key».",
    "tab_award": "🏆 Premios",
    "publish_btn": "🌍 Publicar en el Mundo",
    "pub_moved": "Para publicar o retirar una carta, tócala en la pestaña 📚 Cartas.",
    "ask_name_title": "¿Cómo te llamas?",
    "ask_name_desc": "El nombre que verán los rivales (mín 3 letras).",
    "ask_name_ok": "Guardar y publicar",
    "ask_name_cancel": "Cancelar",
    "hub_fight": "Combatir",
    "hub_cards": "Cartas",
    "hub_glory": "Gloria",
    "hub_social": "Social",
    "tab_opz": "⚙️ Opciones",
    "tab_gang": "🛡️ Gang"
  },
  "stat": {
    "Forza": "Fuerza",
    "Intelligenza": "Inteligencia",
    "Destrezza": "Destreza",
    "Velocità": "Velocidad",
    "Fascino": "Encanto",
    "Indifferenza": "Indiferencia"
  },
  "rarity": {
    "Comune": "Común",
    "Rara": "Rara",
    "Epica": "Épica",
    "Leggendaria": "Legendaria"
  },
  "ann": {
    "red": "Desde la esquina roja... {n}... «{k}»!",
    "blue": "Desde la esquina azul... {n}... «{k}»!"
  },
  "nicks": {
    "n01": "El Sócrates de la Lata",
    "n02": "El Barón Colmillo Torcido",
    "n03": "El Coloso de las Brasas",
    "n04": "El Gladiador del Asfalto",
    "n05": "El Quesito Durmiente",
    "n06": "El Monolito de Felpa",
    "n07": "El Maestro Lamedor Zen",
    "n08": "El Imperturbable Zen",
    "n09": "La Fortaleza Blanda Inamovible",
    "n10": "El Radar del Más Allá del Sofá",
    "n11": "El Radar de los Males",
    "n12": "Su Suavidad Hipnótica",
    "n13": "El Veterano del Ronroneo",
    "n14": "El Triste Hipnotista Felino",
    "n15": "El Panzer de Seda",
    "n16": "El Escape en Llamas",
    "n17": "El Ovillo Hipnótico",
    "n18": "La Garra de Jengibre",
    "n19": "El Dirigible de Mesa",
    "n20": "El Bastión de Pelo",
    "n21": "El Mejilla de Acero",
    "n22": "El Fantasma del Sofá",
    "n23": "La Furia del Trastero",
    "n24": "El Tornado de Pelo",
    "n25": "La Sombra de la Despensa",
    "n26": "El Ninja del Alféizar",
    "n27": "La Avalancha Rojiza",
    "n28": "El Sicario de las Cortinas",
    "n29": "El Terror de los Ovillos",
    "n30": "La Locomotora Perezosa",
    "n31": "El Filósofo del Radiador",
    "n32": "El Huracán en Pantuflas",
    "n33": "El Guepardo de Salón",
    "n34": "La Esfinge del Frigorífico",
    "n35": "El Relámpago Socarrón",
    "n36": "El Cojín Asesino",
    "n37": "La Bestia del Balcón",
    "n38": "El General Zarpazo",
    "n39": "El Acróbata de Medianoche",
    "n40": "El Sultán de la Siesta",
    "n41": "El Tigre de la Moqueta",
    "n42": "El Fantasma de la Escalera",
    "n43": "El Destructor de Sofás",
    "n44": "La Pantera del Rellano",
    "n45": "El Barón de los Bocaditos",
    "n46": "El Emperador de la Cesta",
    "n47": "El Pirata del Pescado Fresco",
    "n48": "El Rayo de Peluche",
    "n49": "El Campeón de las Croquetas",
    "n50": "El Estratega del Desván",
    "n51": "El Monstruo de las Zapatillas",
    "n52": "La Duquesa con Garras",
    "n53": "El Vikingo Aterciopelado",
    "n54": "El Enigma Bigotudo",
    "n55": "El Ciclón Silencioso",
    "n56": "La Zarpa del Destino",
    "n57": "El Rey del Cartón",
    "n58": "La Emboscada Permanente",
    "n59": "El Meteorito Blando",
    "n60": "La Leyenda del Patio",
    "n61": "El Guardián del Cuenco",
    "n62": "El Ojo de la Noche",
    "n63": "El Samurái Despeluchado",
    "n64": "La Furia Tricolor",
    "n65": "El Profesor de Emboscadas",
    "n66": "El Almirante de los Tejados",
    "n67": "La Apisonadora",
    "n68": "La Peste Elegante",
    "n69": "El Volcán Somnoliento",
    "n70": "La Garra de Terciopelo",
    "n71": "El Bandido de la Cocina",
    "n72": "El Centinela del Frigo",
    "n73": "El Dragón del Cojín",
    "n74": "El Eco del Maullido",
    "n75": "El Maestro del Ronroneo",
    "n76": "La Tormenta de Bolsillo",
    "n77": "El Gigante Amable",
    "n78": "El Último Callejero",
    "n79": "El Cazador de Lagartijas",
    "n80": "La Novena Vida"
  },
  "descrs": {
    "d01": "Duerme 20 horas al día y las otras 4 entrena para dormir mejor.",
    "d02": "Nunca ha perdido una batalla contra un calcetín.",
    "d03": "Cree que el frigorífico le debe explicaciones.",
    "d04": "Maestro en el arte de ocupar justo donde querías sentarte.",
    "d05": "Ha tirado tres jarrones. Todos culpables.",
    "d06": "Habla tres idiomas: ronroneo, maullido y desprecio.",
    "d07": "Corre a las 4 de la mañana por razones que no nos incumben.",
    "d08": "Un guerrero nato, siempre que el sofá esté a menos de dos metros.",
    "d09": "Su cuenco está medio vacío. Siempre. Incluso lleno.",
    "d10": "Mira fijamente la pared porque la pared empezó primero.",
    "d11": "Ex callejero, ahora alto ejecutivo de la siesta.",
    "d12": "Ronronea como un tractor y araña como una navaja.",
    "d13": "El veterinario aún lo recuerda en sus pesadillas.",
    "d14": "No persigue ratones: envía avisos de desahucio.",
    "d15": "Sabe abrir tres tipos de puertas y finge que no.",
    "d16": "La caja vale más que el regalo. Siempre.",
    "d17": "Doctorado en miradas de juicio.",
    "d18": "Lucha contra el crimen. El crimen es la aspiradora.",
    "d19": "Cada silla de la casa es suya. También la tuya.",
    "d20": "Entrena en las cortinas cuando nadie mira.",
    "d21": "Pasatiempo favorito: tirar cosas de las mesas con elegancia.",
    "d22": "Maúlla en do menor cuando el cuenco está vacío.",
    "d23": "Nadie lo ha visto llegar. Solo irse con la cena.",
    "d24": "Pesa justo lo necesario para inmovilizarte las piernas.",
    "d25": "Las lagartijas del barrio han puesto precio a su cabeza.",
    "d26": "Duerme en posturas que desafían la física y el sentido común.",
    "d27": "Entendió el láser. Finge que no, por lástima.",
    "d28": "Un cruce entre un cojín y un cepo.",
    "d29": "Vigila el barrio desde la ventana como un jefe de estado.",
    "d30": "Su ronroneo cura el estrés. Sus uñas lo causan.",
    "d31": "Come como un lobo, duerme como una piedra, reina como un rey.",
    "d32": "El único gato que ganó una discusión con un pepino.",
    "d33": "Se ofende si lo miras. Se ofende si no lo miras.",
    "d34": "Tiene tres escondites secretos. El mejor: en medio del pasillo.",
    "d35": "De pequeño cayó en un cuenco de nata. Nunca se recuperó.",
    "d36": "Enseña yoga a los gatos del barrio. Primera lección: ignorar a todos.",
    "d37": "El cartero pidió el traslado.",
    "d38": "Colecciona gomas de pelo. Nadie sabe dónde las esconde.",
    "d39": "Cuando hay tormenta, protege la casa. Desde debajo de la cama.",
    "d40": "Su mirada ha espantado a dos perros y un fontanero.",
    "d41": "Vive para tres cosas: comer, dormir y juzgarte.",
    "d42": "Una vez vio un ratón. Ambos aún lo cuentan.",
    "d43": "Elegantísimo hasta que se cae del alféizar.",
    "d44": "Adoptó a una familia de humanos. Los está adiestrando bien.",
    "d45": "No se sube a la mesa. La mesa baja a su nivel.",
    "d46": "Sabe exactamente cuándo abres el atún. Incluso a una manzana.",
    "d47": "El ovillo ya estaba así cuando llegó.",
    "d48": "Mitad gato, mitad sirena de alarma de las 5 a.m.",
    "d49": "Pelea con honor, gana con estilo, duerme sin vergüenza.",
    "d50": "Lo último que ven las alfombras antes del final."
  },
  "battle": {
    "skip": "⏭️ Presentación saltada: ¡al grano!",
    "open": "🎤 SEÑORAS Y SEÑOREEES… ¡bienvenidos a la Arena CatCards!",
    "red": "🔴 Esquina roja: {NAME}, «{nick}»! {rec}",
    "blue": "🔵 Esquina azul: {NAME}, «{nick}»! {rec}",
    "debut": "¡En su debut en la arena!",
    "theme": "🎵 Suena el tema de entrada de {name}…",
    "ding": "🔔 ¡DING DING DING!",
    "first_fast": "⚡ ¡{name} es más rápido y ataca primero!",
    "first_surprise": "😼 ¡{name} sorprende a todos y empieza!",
    "round_end": "🔔 ¡Fin del asalto {round}! Los gatos vuelven a su esquina a lamerse…",
    "charmed_skip": "😍 ¡{name} está embelesado y pierde el turno!",
    "chant": "🎺 Desde las gradas: «{NAME}! {NAME}!»",
    "pu_yarn": "🧶 ¡Un ovillo rueda a la arena! {name} juega y recupera {hp} PV",
    "pu_catnip": "🌿 ¡Hierba gatera! {name} está eufórico: próximo golpe DOBLE (pero algo mareado…)",
    "pu_box": "📦 ¡Una caja de cartón! {name} no se resiste: pierde el turno pero es INTOCABLE!",
    "pu_fish": "🐟 ¡Un pez fresco vuela a la arena! {name} rebosa energía: +agilidad por 3 turnos",
    "purr_heal": "💗 {name} ronronea y recupera {hp} PV",
    "double_paw": "🐾 ¡Doble Zarpazo! ¡{name} ataca otra vez!",
    "box_dodge": "📦 {opp} está escondido en la caja: ¡el golpe de {name} falla!",
    "dodge": "💨 {name} intenta {move} pero {opp} esquiva!",
    "final_blow": "⏱️ El tiempo se ralentiza… ¡GOLPE FINAL!",
    "hit": "{icon} {name} usa {move}!{crit}{catnip}  −{dmg} PV",
    "crit_tag": " 💥 ¡CRÍTICO!",
    "catnip_tag": " 🌿 ¡POTENCIADO!",
    "dev1": "😱 ¡Golpe devastador!",
    "dev2": "🎙️ ¡El público enloquece!",
    "dev3": "💢 ¡Qué potencia impresionante!",
    "on_fire": "🔥 ¡{name} está ON FIRE! ¡Tres golpes seguidos!",
    "on_ropes": "🎙️ ¡{opp} está contra las cuerdas! El público contiene la respiración…",
    "clever": "✨ ¡Jugada astuta! {opp} queda confuso y perderá un turno!",
    "nine_lives": "🐈 ¡{opp} usa una de sus Nueve Vidas y aguanta con 1 PV!",
    "charm_hit": "✨ ¡{opp} queda embelesado por el encanto de {name}!",
    "replay": "📹 REPETICIÓN del golpe final…",
    "winner": "🏆 ¡{name} gana el combate!",
    "win_points": "💰 ¡+10 puntos por la victoria!",
    "boss_points": "💰 ¡+10 puntos: has domado a un Jefe de la Arena!",
    "boss_noprize": "🎖️ Jefe ya vencido hoy: gloria sí, premio mañana.",
    "boss_survives": "🤖 El Jefe sigue en pie... el intento de hoy se fue: hasta mañana (quizá con hierba gatera 🌿).",
    "tourn_champ": "👑 ¡{name} es el CAMPEÓN del torneo!",
    "world_ok": "🌍 ¡Resultado registrado en la Arena Mundial!",
    "bet_win": "🎲 ¡Acertaste! Apostaste {stake} a {name}: +{gain} puntos (total: {total})",
    "bet_lose": "🎲 Fallaste: −{stake} puntos (total: {total}). ¡La próxima irá mejor!",
    "stake": "🎁 En juego — victoria: {win} · derrota: +{lose} XP",
    "stake_pts": "+{pt} puntos y +{xp} XP",
    "stake_nopts": "+{xp} XP (sin puntos en local)",
    "boss_stake_note": " — puntos solo en la 1ª victoria del día",
    "entry_catnip": "🌿 ¡{name} entra en la arena ya cargado de hierba gatera!"
  },
  "chars": {
    "rocco_warn": "Ojo con su {stat}: ahí te come.",
    "rocco_70": "Chaval, a este lo tumbas antes del gong. No te confíes y ciérralo rápido.",
    "rocco_55": "Eres el favorito, pero los favoritos que se duermen acaban en la lona. Pega primero.",
    "rocco_50": "Cincuenta-cincuenta, chaval: gana el que tenga más hambre. Si tienes 50 puntos, la hierba gatera los vale.",
    "rocco_35": "No te miento: es más grande que tú. Sin hierba gatera yo no haría este combate.",
    "rocco_lose": "Hazle caso al viejo Rocco: este te rompe. Vuelve al gimnasio, sube un nivel y LUEGO hablamos. Si insistes, al menos la hierba gatera.",
    "baratto_great": "🤑 ¡Un chollo! Recibes mucho más de lo que das — ciérralo rápido.",
    "baratto_good": "👍 Buen trato: sales ganando. El Mercader aprueba.",
    "baratto_even": "⚖️ Intercambio parejo: decide con el corazón, no con la cartera.",
    "baratto_bad": "😾 Pierdes algo... ¿seguro? El Mercader tuerce los bigotes.",
    "baratto_terrible": "🙀 ¡Pésimo trato! Das mucho más de lo que recibes. Olvídalo.",
    "baratto_empty": "¡No tienes cartas para trocar! Crea algunas y vuelve: el bazar es para negocios, no caridad.",
    "inc_100a": "¡CIEN PUNTOS! ¡Qué locura magnífica! 😼",
    "inc_100b": "¡Una oferta de reyes! ¿Y quién se atreve a subir?",
    "inc_50a": "¡Cincuenta! ¡El público tiembla, señores!",
    "inc_50b": "¡Buena cifra! ¡La subasta se calienta!",
    "inc_bata": "¡Y sube otra vez! ¡No paran!",
    "inc_batb": "¡Batalla hasta el último punto, qué espectáculo!",
    "inc_starta": "¡Primera puja en la mesa! ¿Quién da más?",
    "inc_startb": "¡Empezamos! ¡Adjudicado al que no se rinda!",
    "baffo_open": [
      "¡Miau, recluta! ",
      "Escucha al viejo Baffo: ",
      "Suelta la croqueta y escucha: ",
      "En mis tiempos no había cojines blandos. ",
      "Bigotes tiesos y orejas alerta: "
    ],
    "baffo_empty": "¡El gimnasio está vacío! Tráeme un alumno desde la pestaña 📸 Crear.",
    "baffo_indiff_afford": "El punto débil de {name} es {stat} ({val}): entrénala con el combo {combo} (60 puntos), puedes permitírtelo.",
    "baffo_indiff_save": "El punto débil de {name} es {stat} ({val}), pero solo se entrena con el combo {combo} (60 puntos): te faltan {miss}, ve ahorrando.",
    "baffo_indiff_alt": " O mientras tanto refuerza {stat2} ({val2}) con {food} (25 puntos).",
    "baffo_weak": "El punto más débil de {name} es {stat} ({val}): dale {food}.",
    "baffo_combo": "Tienes {pts} puntos: el combo {combo} ({tgt}) sube dos cosas en un solo descanso — caro pero útil si tienes prisa.",
    "baffo_record_bad": "Con {w} victorias y {l} derrotas hace falta garra, no mimos.",
    "baffo_unbeaten": "Está invicto: cuidado no se le suba a la cabeza.",
    "baffo_margin": "Margen de entrenamiento agotado: solo las victorias en el Mundo desbloquean más progreso.",
    "baffo_broke": "Y las arcas lloran ({pts} puntos): gana alguna apuesta mundial.",
    "baffo_fit": "{name} está en plena forma. Que pelee, que el banquillo ablanda los músculos.",
    "felini_open": [
      "Escucha al Mánager: ",
      "He olido el negocio: ",
      "El ring es un tablero de ajedrez: ",
      "Hablan los números, chaval: "
    ],
    "felini_checking": "Un momento, consulto los registros…",
    "felini_noauth": "Primero inicia sesión, chaval: los negocios se hacen con un nombre en el contrato.",
    "felini_nocard": "No tienes un campeón publicado. Publica una carta y hablamos de negocios.",
    "felini_resting": "😴 {name} se está recuperando: vuelve cuando esté listo otra vez y hablamos de estrategia.",
    "felini_norank": "Tu campeón no aparece en el ranking: republícalo y vuelve a verme.",
    "felini_loss_streak": "{name} ha perdido {n} seguidas (🧊): sácalo del circuito un tiempo, llévalo con el Coach, y que vuelva hambriento.",
    "felini_champ": "{name} es el CAMPEÓN 👑: defiende la corona{chaser}.",
    "felini_chaser": ", y ojo con {name} (#2, {elo} pt) que está al acecho",
    "felini_target": "el próximo combate ideal para {name} (#{rk}) es {tname} de {owner} (#{trk}, {elo} pt): {verdict}",
    "felini_v_risky": "arriesgado, pero si lo ganas das el pelotazo en la clasificación.",
    "felini_v_beatable": "sobre el papel es vencible: una victoria de gestión.",
    "felini_v_even": "un combate parejo, de los que le gustan al público.",
    "felini_prob_low": "Pero hablemos claro: Tío Rocco estima solo un {p}% de victoria. Yo esperaría — gimnasio, un nivel más, Y ENTONCES se firma el contrato.",
    "felini_prob_mid": "Las probabilidades dicen {p}%: combate abierto, deciden los nervios (y quizá la hierba gatera 🌿).",
    "felini_prob_high": "Tío Rocco estima un {p}% de victoria: a tu alcance. Ve y cierra el combate.",
    "felini_belt": "Y recuérdalo: ese tiene el CINTURÓN 👑 — la clasificación no cuenta nada, lo ganas y el campeón eres TÚ.",
    "felini_hot": "Ojo eso sí: es un rival duro, viene de una racha de {n} victorias 🔥.",
    "felini_cold": "Y te digo: está en plena crisis (🧊 {n} derrotas seguidas) — el momento perfecto para golpear.",
    "felini_catnip_need": "Mi consejo desde la esquina: invierte 50 puntos en hierba gatera 🌿 antes del combate — contra uno así hace falta el turbo.",
    "felini_catnip_broke": "Haría falta hierba gatera 🌿, pero las arcas lloran ({pts} puntos): o encuentras puntos, o eliges un objetivo más blando.",
    "felini_catnip_opt": "¿Hierba gatera 🌿? Opcional: combate parejo, decidirán los nervios.",
    "felini_catnip_no": "Nada de hierba gatera: se las apaña con sus propias patas, ahorra los puntos.",
    "felini_notarget": "ningún objetivo de otros dueños por encima de ti ahora mismo (o descansan todos): defiende la posición, o vuelve más tarde.",
    "felini_margin": "Y aún le quedan {n} puntos de margen en el gimnasio: una buena comida antes del combate nunca mató a nadie.",
    "trader_open": [
      "Psst, amigo: ",
      "¡Negocios, negocios! ",
      "El Mercader lo sabe todo: ",
      "Entre nosotros que entendemos: "
    ],
    "trader_best": "agarra fuerte a {name}, esa vale oro: no la cedas por cuatro perras.",
    "trader_worst": "si de verdad tienes que dar algo, empieza por {name} — tienes cosas mejores en mano.",
    "trader_commons": "Tienes un montón de {rar} ({n}): cambia un par por algo más raro, fíate.",
    "trader_gem": "Y ojo: hay una {rar} de {owner} en el escaparate — si tienes un buen repetido, intenta el cambio antes de que la pille otro.",
    "trader_browse": "Pulsa «Explorar cartas para intercambiar» y enséñame qué hay: yo te digo si hay negocio.",
    "rocco_catnip": "🌿 Bravo chaval. Ahora entra ahí y hazte valer: el primer golpe será un tren.",
    "baffo_all_rest": "😴 Todos tus alumnos están descansando: vuelve cuando uno esté listo y nos ponemos a trabajar."
  },
  "titles": {
    "world": "DESAFÍO MUNDIAL",
    "live": "DUELO EN VIVO",
    "boss": "BOSS DE LA ARENA",
    "quarti": "CUARTOS DE FINAL",
    "semi": "SEMIFINAL",
    "finale": "FINAL",
    "sentiero": "EL SENDERO"
  },
  "gym": {
    "lbl_allena": "Entrena:",
    "lbl_start": "▶️ ¡Empieza el entrenamiento!",
    "fn_croc": "Pienso",
    "fn_pollo": "Pollo",
    "fn_topo": "Ratoncito",
    "fn_erba": "Hierba gatera",
    "fn_pesce": "Pescado",
    "fn_chicche": "Golosinas",
    "fn_bistecca": "Filete del Guerrero",
    "fn_scarica": "Descarga Felina",
    "fn_fascino": "Encanto Fatal",
    "fn_trono": "Trono de Plumas",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Fuerza",
    "ft_topo": "🧠 Inteligencia",
    "ft_erba": "🎯 Destreza",
    "ft_pesce": "⚡ Velocidad",
    "ft_chicche": "✨ Encanto",
    "ft_bistecca": "💪 Fuerza + ❤️ HP",
    "ft_scarica": "⚡ Velocidad + 🎯 Destreza",
    "ft_fascino": "✨ Encanto + 🧠 Inteligencia",
    "ft_trono": "😼 Indiferencia + ❤️ HP",
    "gn_gomitolo": "Atrapa el ovillo",
    "gn_topo": "Caza del ratón",
    "gn_piuma": "Sigue la pluma",
    "gn_corda": "Tira y afloja",
    "gn_porta": "Derriba la puerta",
    "gn_laser": "Caza del láser",
    "gn_memory": "Memoria de las latas",
    "gn_pesca": "Pesca al vuelo",
    "gn_scatto": "Arranque felino",
    "gn_scalata": "Escalada de la estantería",
    "gn_fusa": "Ritmo del ronroneo",
    "gn_sfilata": "El Desfile",
    "gn_zen": "Zen del gato",
    "gn_sguardi": "Concurso de miradas",
    "ga_gomitolo": "Agilidad — 🌿 hierba gatera (Destreza) y 🐟 pescado (Velocidad)",
    "ga_topo": "Físico — 🍗 pollo (Fuerza) y 🥫 pienso (HP)",
    "ga_piuma": "Mente — 🐁 ratoncito (Inteligencia) y 🧀 golosinas (Encanto)",
    "ga_corda": "Fuerza — 🍗 pollo (Fuerza)",
    "ga_porta": "Fuerza — 🍗 pollo (Fuerza)",
    "ga_laser": "Destreza — 🌿 hierba gatera (Destreza)",
    "ga_memory": "Inteligencia — 🐁 ratoncito (Inteligencia)",
    "ga_pesca": "Velocidad — 🐟 pescado (Velocidad)",
    "ga_scatto": "Velocidad — 🐟 pescado (Velocidad)",
    "ga_scalata": "HP — 🥫 pienso (HP)",
    "ga_fusa": "Encanto — 🧀 golosinas (Encanto)",
    "ga_sfilata": "Encanto — 🧀 golosinas (Encanto)",
    "ga_zen": "Indiferencia — 🛋️ cojín real (Indiferencia)",
    "ga_sguardi": "Indiferencia — 🛋️ cojín real (Indiferencia)",
    "gd_gomitolo": "El ovillo se dispara por el recuadro y acelera con cada toque: tócalo cuantas más veces puedas en <strong>10 segundos</strong>.<br>🚫 Menos de 5 tomas: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_topo": "Los ratones asoman de sus madrigueras y desaparecen enseguida: golpéalos en cuanto aparezcan, durante <strong>15 segundos</strong>.<br>🚫 Menos de 5 golpes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_piuma": "Las plumas de colores parpadean en secuencia: repítela tocándolas en el mismo orden. Cada ronda la secuencia se alarga; un error termina el entrenamiento.<br>🚫 Menos de 3 rondas: comida desperdiciada · ✅ 3-4: bono ×1 · 🌟 5+: bono ×2",
    "gd_corda": "Machaca el botón <strong>TIRA</strong> para arrastrar al perrazo más allá de la línea: él tira hacia atrás sin parar, no sueltes durante <strong>10 segundos</strong>.<br>🚫 Menos de 8 tirones: comida desperdiciada · ✅ 8-15: bono ×1 · 🌟 16+: bono ×2",
    "gd_porta": "La barra de potencia va y viene disparada: toca cuando esté en la <strong>zona verde</strong> para cargar el zarpazo. Golpea lo más fuerte que puedas en <strong>12 segundos</strong>.<br>🚫 Menos de 5 buenos golpes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_laser": "El punto rojo aparece y desaparece cada vez más rápido: tócalo antes de que se esfume, durante <strong>12 segundos</strong>.<br>🚫 Menos de 6 tomas: comida desperdiciada · ✅ 6-11: bono ×1 · 🌟 12+: bono ×2",
    "gd_memory": "Descubre las cartas de dos en dos y empareja las parejas iguales de memoria, en <strong>30 segundos</strong>.<br>🚫 Menos de 3 parejas: comida desperdiciada · ✅ 3-4: bono ×1 · 🌟 5+: bono ×2",
    "gd_pesca": "El pez se escurre bajo el agua y aflora solo un instante: tócalo <strong>justo cuando salta</strong>. Las ventanas se acortan. Tienes <strong>14 segundos</strong>.<br>🚫 Menos de 5 tomas: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_scatto": "Espera el <strong>verde</strong> y toca lo más rápido posible: mide tu reflejo. 5 rondas — salir antes de tiempo pierde la ronda.<br>🚫 Menos de 2 buenos arranques: comida desperdiciada · ✅ 2-3: bono ×1 · 🌟 4+: bono ×2",
    "gd_scalata": "El gato salta de estante en estante: toca <strong>cuando la plataforma esté alineada</strong> para saltar encima. Un salto errado y caes. Sube lo más alto que puedas.<br>🚫 Menos de 5 estantes: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_fusa": "El círculo se cierra a compás: toca <strong>cuando llegue al objetivo</strong>, al ritmo del ronroneo. Cuanto más preciso seas, más acelera el ritmo.<br>🚫 Menos de 5 toques a tiempo: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_sfilata": "En la pasarela aparece una flecha: <strong>desliza (swipe) en su dirección</strong> para hacer la pose. Las flechas llegan cada vez más rápido, tienes <strong>16 segundos</strong>.<br>🚫 Menos de 6 poses: comida desperdiciada · 🌟 12+: bono ×2",
    "gd_zen": "La disciplina de la indiferencia: <strong>ignora cada distracción</strong> (🐭 ratón, 🪶 pluma, 🔴 láser) y toca <strong>solo el cojín 🛋️</strong> cuando aparezca. Tocar una distracción te hace perder la ronda. Tienes <strong>14 segundos</strong>.<br>🚫 Menos de 5 cojines: comida desperdiciada · ✅ 5-9: bono ×1 · 🌟 10+: bono ×2",
    "gd_sguardi": "<strong>Mantén pulsado</strong> y no te muevas: quien queda impasible gana. Pero si aparece un 😹 cosquilleo debes <strong>soltar enseguida</strong>, luego volver a pulsar. Resiste lo más que puedas.<br>🚫 Menos de 8 segundos de impasibilidad: comida desperdiciada · ✅ 8-13: bono ×1 · 🌟 14+: bono ×2",
    "tr_wasted_h": "🙀 ¡Comida desperdiciada!",
    "tr_wasted_b": "Puntuación: <strong>{score}</strong> — por debajo del umbral mínimo.<br><br>{ic} El {food} se perdió y {name} ahora descansa una hora.<br><br>😼 <em>«En mis tiempos se entrenaba hasta con los ojos vendados.»</em>",
    "tr_coach_wasted": "🙀 ¿¡Solo {score} puntos!? Comida desperdiciada.",
    "tr_perfect_h": "🌟 ¡Entrenamiento perfecto!",
    "tr_ok_h": "✅ ¡Entrenamiento logrado!",
    "tr_bonus2": " — ¡bono duplicado!",
    "tr_online": "🌍 Carta actualizada también en la Arena Mundial.<br>",
    "tr_body": "Puntuación: <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> para {name}</span><br><br>{online}😴 Ahora una hora de descanso: los músculos crecen durmiendo.",
    "tr_coach_perfect": "😼 ¡{score} puntos! {name} tiene madera de campeón.",
    "tr_coach_ok": "👍 {score} puntos, trabajo honesto. {name} crece.",
    "gi_none": "Sin alumno: crea primero una carta.",
    "gi_info": "Nv.{lv} · margen de entrenamiento: <strong>{used}/{cap}</strong> usado <span style=\"color:var(--muted)\">(+3 por nivel: se sube ganando en el mundo)</span>",
    "gi_resting": "<br>😴 Está descansando: vuelve en {min} minutos",
    "gi_ready": "<br>✅ ¡Listo para entrenar!",
    "gi_nofood": "😼 El Coach: «Nada de comida para {name}: margen de entrenamiento agotado. Gana combates para subir de nivel (+3 de margen por nivel), y luego se vuelve a la mesa.»",
    "gi_pick_opt": "— elige un alumno —",
    "gi_pick": "👉 Elige un alumno arriba para empezar.",
    "gi_pick_alert": "Elige primero un alumno del menú de arriba."
  },
  "powers": {
    "pn_0": "Nueve Vidas",
    "pn_1": "Emboscada Perfecta",
    "pn_2": "Ronroneo Regenerador",
    "pn_3": "Doble Zarpazo",
    "pn_4": "Modo Líquido",
    "pn_5": "Mirada Hipnótica",
    "pn_6": "Armadura de Pereza",
    "pn_7": "Caos Felino",
    "pd_0": "la primera vez que cae KO se queda con 1 HP",
    "pd_1": "su primer ataque siempre es crítico",
    "pd_2": "recupera HP en cada uno de sus turnos",
    "pd_3": "25% de probabilidad de atacar dos veces",
    "pd_4": "esquiva mucho más a menudo",
    "pd_5": "hechiza con el doble de probabilidad",
    "pd_6": "recibe un 20% menos de daño",
    "pd_7": "su daño es impredecible (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Gana 1 desafío mundial",
    "m_world2": "Gana 2 desafíos mundiales",
    "m_fight3": "Combate 3 encuentros (los locales también cuentan)",
    "m_tourn": "Gana un torneo (de 4 u 8)",
    "m_upset": "La Hazaña: vence en el mundo a un rival con más Elo que el tuyo",
    "m_train1": "Completa un entrenamiento logrado",
    "m_gom10": "Haz 10+ en Atrapa el ovillo",
    "m_topo10": "Haz 10+ en Caza del ratón",
    "m_piuma5": "Llega a 5 rondas en Sigue la pluma",
    "m_boss": "Doma un Boss de la Arena",
    "m_bet": "Gana una apuesta",
    "m_catnip": "Gana un combate empezando con hierba gatera",
    "m_card": "Crea una carta nueva",
    "m_qr": "Juega un duelo en vivo (QR)",
    "a_prima_carta_nm": "Primera carta",
    "a_prima_carta_ds": "Crea tu primera carta",
    "a_coll5_nm": "Coleccionista",
    "a_coll5_ds": "5 cartas en la colección",
    "a_coll10_nm": "Gatero en serie",
    "a_coll10_ds": "10 cartas en la colección",
    "a_epica_nm": "¡Qué rareza!",
    "a_epica_ds": "Consigue una carta Épica",
    "a_legg_nm": "¡Legendaria!",
    "a_legg_ds": "Consigue una Legendaria",
    "a_win1_nm": "Primera victoria",
    "a_win1_ds": "Gana un desafío mundial",
    "a_win10_nm": "Veterano",
    "a_win10_ds": "Gana 10 desafíos mundiales",
    "a_win50_nm": "Leyenda",
    "a_win50_ds": "Gana 50 desafíos mundiales",
    "a_t4_nm": "Campeón",
    "a_t4_ds": "Gana un torneo de 4",
    "a_t8_nm": "Dominador",
    "a_t8_ds": "Gana un torneo de 8",
    "a_pub_nm": "En el mundo",
    "a_pub_ds": "Publica una carta",
    "a_wwin_nm": "Triplete",
    "a_wwin_ds": "Gana 3 desafíos mundiales seguidos",
    "a_bet_nm": "Corredor de apuestas",
    "a_bet_ds": "Gana una apuesta",
    "a_ricco_nm": "Ricachón",
    "a_ricco_ds": "Posee 150 puntos",
    "a_onore_nm": "Retiro con honor",
    "a_onore_ds": "Retira una carta con récord positivo",
    "a_disfatta_nm": "Debacle",
    "a_disfatta_ds": "Pierde 10 desafíos mundiales seguidos",
    "bm_ds": "Derrota a {name} (Div. {tier})",
    "bmall_nm": "Mataboss",
    "bmall_ds": "Derrota a los 64 Boss de la Arena",
    "cx_rar4": "El póker: una carta por cada rareza",
    "cx_razze3": "Descubre 3 razas diferentes",
    "cx_razze5": "Descubre 5 razas diferentes",
    "cx_razze10": "Descubre 10 razas diferentes",
    "cx_pot4": "Colecciona 4 poderes especiales distintos",
    "cx_pot8": "Colecciona los 8 poderes especiales",
    "cx_lv5": "Lleva un gato al nivel 5",
    "cx_hp100": "Una carta con 100+ HP",
    "cx_oro": "Una carta con el Marco de Oro",
    "p_done": "hecho",
    "p_won": "✓ conseguida",
    "p_towin": "🔒 por conseguir",
    "p_howto": "Cómo se consigue:",
    "p_reward": "Premio:",
    "p_unlocked": "Desbloqueada el",
    "cx_open": "(toca para abrir)",
    "cx_h_rar": "💎 Rareza",
    "cx_h_pow": "🌟 Poderes especiales",
    "cx_h_breeds": "🐱 Razas descubiertas",
    "cx_nobreeds": "Ninguna aún: la raza llega con el análisis IA de la foto.",
    "cx_h_objs": "🎯 Objetivos",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> objetivos <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex: {ic} {txt}! +{pt} puntos",
    "mis_tris_line": "🎉 Trío completado: +10 puntos de bono cobrados. ¡Hasta mañana!",
    "mis_toast_tris": "🎉 ¡TRÍO! Misión «{txt}» y día completo: ¡+5 y +10 de bono!",
    "mis_toast_done": "📅 Misión completada: {ic} {txt}! +5 puntos",
    "med_toast": "🏅 Medalla desbloqueada: {ic} {nm}! +{pt} puntos",
    "bm_sum": "🤖 Boss domados — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>",
    "a_sentiero_done_nm": "Caminante de las Nueve Vidas",
    "a_sentiero_done_ds": "Completa todo el Sendero (100 etapas)"
  },
  "reg": {
    "r_h_cards": "🎴 Las cartas",
    "r_p_cards": "Fotografía un gato y se convierte en carta: la IA lo redibuja en cartoon y analiza su aspecto y carácter para generar <strong>estadísticas</strong> (un gatazo robusto tendrá más Fuerza), <strong>raza</strong>, <strong>descripción</strong>, <strong>poder especial</strong> y <strong>3 movimientos</strong> (💥 potente pero impreciso, ⚡ rápido y casi infalible, ✨ astuto que puede confundir). La <strong>rareza</strong> se sortea a partir de la huella de la foto: 55% Común, 28% Rara, 13% Épica, 4% Legendaria (las Épicas y Legendarias brillan y tienen estadísticas con bonus). La misma foto da siempre la misma carta.",
    "r_h_xp": "⭐ Experiencia y niveles",
    "r_p_xp": "Las cartas crecen combatiendo: <strong>desafíos mundiales y en vivo: 25 XP por victoria, 10 por derrota</strong> · <strong>arena local y torneos: 5 y 2</strong>. Cada 100 XP: +1 nivel = <strong>+4 HP, +3% de ataque y +3 de margen de gimnasio</strong>. Los espejos (carta contra sí misma) no cuentan.",
    "r_h_pts": "💰 Los puntos (la moneda)",
    "r_p_pts": "Se ganan con: <strong>+10 por cada victoria mundial o en vivo</strong>, +10 por cada Boss domado, 📅 misiones diarias (5 cada una, +10 el trío: máx 25 al día), apuestas ganadas, medallas (10-100 puntos cada una) y 🎁 códigos de regalo. Las victorias locales: cero puntos. Se <strong>gastan</strong> en: apuestas (10-100), comida en el gimnasio (20-25), 🌿 ventaja mundial (50), 🎨 Marco de Oro (100), 🔁 regeneración del dibujo (30). Perder un combate no cuesta puntos: solo las apuestas erradas.",
    "r_h_bet": "🎲 Las apuestas",
    "r_p_bet": "En los <strong>desafíos mundiales y en vivo</strong>: antes del combate eliges la apuesta y a quién apostar (⭐ favorito a cuota baja, 🐾 perdedor a cuota alta). Ganas la apuesta × (cuota − 1); si te equivocas pierdes la apuesta. Nada de apuestas en local ni en torneos.",
    "r_h_rest": "😴 El descanso",
    "r_p_rest": "Tras cada combate real (local 1v1, mundial, en vivo) y cada entrenamiento, los gatos implicados descansan <strong>1 hora</strong>: no pueden combatir ni comer. El descanso lo ven todos, también en línea. Los torneos son exhibiciones y no cansan.",
    "r_h_gym": "🏋️ El gimnasio",
    "r_p_gym": "Cada nivel desbloquea <strong>+3 puntos de margen de entrenamiento</strong>. Compras un alimento (🥫 HP · 🍗 Fuerza · 🐁 Inteligencia · 🌿 Destreza · 🐟 Velocidad · 🧀 Encanto) y el gato se lo gana con el ejercicio asociado: 🧶 ovillo (agilidad), 🐭 caza del ratón (físico), 🪶 sigue la pluma (mente). Umbrales: <strong>por debajo de 5 puntos comida desperdiciada, 5-9 bono ×1, 10+ bono ×2</strong> (para la pluma: 3 y 5 rondas). Las cartas publicadas se actualizan en línea solas. El Coach da consejos gratis.",
    "r_h_world": "🌍 La Arena Mundial",
    "r_p_world": "Inicia sesión con Google (o email), elige tu nombre de jugador (uno por cuenta, renombrable en todas partes de golpe) y <strong>publica las cartas que quieras</strong>: solo las publicadas y activas pueden desafiar en línea. Desafías las cartas de otros, el resultado va al registro y a la clasificación (ordenada por % de victorias). Puedes <strong>🚪 retirar</strong> una carta: queda en la clasificación como \"retirada\" pero nadie puede desafiarla más. El punto rojo en Mundo te avisa cuando tus cartas han combatido en tu ausencia.",
    "r_h_rank": "📊 La clasificación (estilo UFC)",
    "r_p_rank1": "Cada carta publicada tiene una puntuación <strong>Elo</strong>, que parte de <strong>1000</strong>. En cada combate el ganador <strong>toma</strong> puntos y el perdedor <strong>cede los mismos puntos</strong> — y la cantidad depende de la diferencia de fuerza: vencer a un rival <strong>más fuerte</strong> vale hasta <strong>~32 puntos</strong>, vencer a uno mucho más débil vale el mínimo, <strong>8</strong> (ganar fácil rinde poco, la hazaña rinde mucho). Ninguna carta baja nunca de 100. El cálculo lo hace el servidor, igual para todos.",
    "r_p_rank2": "La clasificación oficial es por Elo, pero el cinturón es otra cosa: <strong>campeón se llega SOLO venciendo al campeón vigente 👑</strong> en un desafío mundial o en vivo. Puedes superarlo en puntos cuanto quieras: sigues siendo primer aspirante hasta que lo tumbes en el ring. El campeón está siempre en lo alto de la clasificación, y quien ha sido campeón conserva para siempre el 🏆. Solo puedes desafiar a quien esté <strong>de 5 posiciones por encima a 5 por debajo</strong> de la tuya: para el título hay que escalar (en el top 5 el campeón está a tiro). La clasificación muestra las rachas — 🔥 victorias seguidas, 🧊 derrotas seguidas, y la mejor racha de siempre. El <strong>🎩 Mánager</strong> estudia los números y te aconseja el próximo combate adecuado, si conviene la hierba gatera 🌿, y cuándo es mejor retirarse un poco al gimnasio.",
    "r_h_cat": "🃏 El Catdex",
    "r_p_cat": "El álbum de la colección, al final de la pestaña 📚 Cartas: lleva la cuenta de las <strong>rarezas, razas y poderes especiales</strong> que has descubierto (las casillas que faltan quedan ❓) y premia los hitos con puntos <strong>únicos</strong> — del póker de rarezas (+25) a las 10 razas distintas (+25) hasta los 8 poderes (+30). La raza la escribe la IA cuando creas la carta: nombres parecidos (p. ej. \"atigrado\" y \"europeo atigrado\") cuentan como una sola familia. Para completarlo hace falta solo una cosa: fotografiar gatos nuevos.",
    "r_h_mis": "📅 Las misiones diarias",
    "r_p_mis": "Cada medianoche llegan <strong>3 misiones</strong>, iguales para todo el mundo: una de combate, una de gimnasio, una sorpresa (boss, apuestas, QR…). Cada una paga <strong>5 puntos</strong>, el trío completo otros <strong>10 de bono</strong>. Las encuentras arriba del 🏅 Medallero, con el ✅ en las ya hechas. Máximo 25 puntos al día: lo justo para un entrenamiento, o poco más.",
    "r_h_boss": "🤖 Los Boss de la Arena",
    "r_p_boss": "<strong>64 leyendas en 8 divisiones</strong> de dificultad creciente: desde los Callejeros del Barrio (fáciles) hasta los Boss Finales como el 🌑 Gatto Mammone o 🤖 MIAO-9000, monstruosos. Cada día hay <strong>2 activos, iguales para todo el mundo</strong> (los decide la fecha). Vencer a uno paga <strong>+10 puntos y 25 XP</strong>. Cuidado: tienes <strong>UN solo intento al día por boss</strong> — ganado, perdido o abandonado, se vuelve mañana. Elige bien el gato antes de bajar a la arena. Perder cuesta solo 2 XP de consolación. Tras el combate el gato <strong>descansa una hora</strong> como en cualquier combate real, y la hierba gatera 🌿 comprada antes vale también aquí. Contra los Boss bajan al campo <strong>solo las cartas publicadas en el Mundo</strong>, y los boss <strong>no tocan la clasificación Elo</strong>. Cada boss tiene su medalla (sección «🤖 Boss domados» en el 🏅 Medallero, premios más ricos para las divisiones altas), más el 🏆 Mataboss para quien los dome a los 64.",
    "r_h_qr": "⚡ El duelo en vivo (QR)",
    "r_p_qr": "Dos teléfonos: uno muestra el QR de su carta (🥋 Dojo → 📱), el otro lo escanea (📷) y el duelo se juega en su pantalla. <strong>Cuenta como un desafío mundial</strong>: puntos, XP completos, medallas, descanso, apuestas y resultado registrado si las cartas están publicadas.",
    "r_h_tourn": "🏆 Torneos y medallero",
    "r_p_tourn": "Torneos de 4 u 8 entre tus cartas y los rivales: exhibiciones automáticas con cuadro (XP reducidos, sin descanso, sin puntos). El <strong>🏅 Medallero</strong> tiene 25 medallas con premios en puntos (9 son de Boss) — toca una medalla para descubrir cómo se consigue. Ojo con la 💀 Debacle…",
    "r_h_fight": "⚔️ El combate",
    "r_p_fight": "Automático por turnos: la Velocidad decide quién empieza (normalmente), la Fuerza el daño, la Destreza las esquivas, la Inteligencia los críticos (×1.6), el Encanto hechiza, la Indiferencia reduce el daño. Ningún golpe quita más del 38% de los HP. Poderes especiales, potenciadores aleatorios (🧶🌿📦🐟), golpe final a cámara lenta y repetición. La presentación se puede saltar (⏭️ o desde Opciones).",
    "mgr_greet": "El ring es un tablero de ajedrez, chaval. Elige tu campeón y te digo la próxima jugada.",
    "mis_desc": "Tres encargos nuevos cada medianoche, iguales para todo el mundo: <strong>5 puntos</strong> cada uno, <strong>+10 de bono</strong> si completas el trío.",
    "med_desc": "Las medallas premian con puntos: gástalos en apuestas, ventaja mundial, Marco de Oro, regeneraciones y en la despensa del Gimnasio.",
    "boss_intro": "64 leyendas en 8 divisiones: cada día aparecen 2, iguales para todo el mundo. Vencerlas paga <strong>+10 puntos</strong>, XP completos y una medalla dedicada. <strong>Un intento al día por boss</strong>, ganado o perdido; los boss no tocan la clasificación Elo. Solo combaten las cartas <strong>publicadas en el Mundo</strong>."
  },
  "boss": {
    "div_1": "Callejeros del Barrio",
    "div_2": "Domésticos Rebeldes",
    "div_3": "Nobles y Aristogatos",
    "div_4": "Bestias Salvajes",
    "div_5": "Mitos y Leyendas",
    "div_6": "Espectros y lo Sobrenatural",
    "div_7": "Divinidades Felinas",
    "div_8": "Boss Finales",
    "di_1": "Desde los callejones del barrio",
    "di_2": "Desde los salones alborotados",
    "di_3": "Desde los salones de la nobleza",
    "di_4": "Desde las tierras salvajes",
    "di_5": "Desde las antiguas leyendas",
    "di_6": "Desde el más allá felino",
    "di_7": "Desde los tronos celestes",
    "di_8": "Desde el fin de todo",
    "bu_already_beaten": "✅ ya domado",
    "bu_beaten_today": "🎖️ Domado hoy: premio cobrado.",
    "bu_failed_today": "💥 Intento de hoy fallido.",
    "bu_one_try": "Un solo intento al día por boss: vuelve mañana.",
    "bu_btn_beaten": "✅ Batido hoy",
    "bu_btn_tomorrow": "⏳ Vuelve mañana",
    "bu_btn_fight": "⚔️ Desafía a {name}",
    "bu_bestiary_sum": "📖 Bestiario — <strong>{done}/{tot}</strong> domados <span class=\"count\">{open}</span>",
    "bu_stats_unknown": "Estadísticas desconocidas: enfréntate a {name} para revelarlas.",
    "bu_beaten_tag": "✅ domado",
    "bu_never_tag": "🔒 nunca enfrentado",
    "bu_mystery_desc": "Un boss de la división «{div}» aún envuelto en misterio. Aparece por rotación: vencelo para añadirlo al Bestiario.",
    "bu_close": "✖ Cerrar",
    "bu_already_today": "⏳ Ya has desafiado a {name} hoy: un solo intento al día por boss, ganado o perdido. ¡Vuelve mañana!",
    "bu_only_world": "Contra los Boss solo combaten las cartas publicadas en el Mundo: publica una desde la pestaña 🌍.",
    "bu_resting": "😴 {name} está descansando: vuelve en {min} minutos.",
    "bu_pub_first": "— publica primero una carta en el Mundo —",
    "bn_latta": "El Minino de Lata",
    "bk_latta": "La Lata Viviente",
    "bl_latta": "Convencido de ser una lata. Duro fuera, atún dentro.",
    "bn_b02": "Medio Bigote",
    "bk_b02": "El Ladrón del Mercado",
    "bl_b02": "Roba en el mercado y desaparece antes de que digas «miau».",
    "bn_b03": "Patasucia",
    "bk_b03": "El Señor de los Cubos",
    "bl_b03": "Reina sobre los cubos de basura del barrio, inmune a todo asco.",
    "bn_b04": "La Bola de Pelo",
    "bk_b04": "La Apisonadora",
    "bl_b04": "Rueda sobre ti y no se detiene. Simple, pero eficaz.",
    "bn_b05": "Panza Blanda",
    "bk_b05": "El Perezoso",
    "bl_b05": "Demasiado perezoso para esquivar, demasiado gordo para caer.",
    "bn_b06": "Olfato",
    "bk_b06": "El Sabueso Felino",
    "bl_b06": "Sigue el olor de la comida hasta el fin del mundo.",
    "bn_b07": "Media Cola",
    "bk_b07": "El Furioso",
    "bl_b07": "Perdió media cola, ganó el doble de rabia.",
    "bn_b08": "El Gato del Panadero",
    "bk_b08": "El Horno Viviente",
    "bl_b08": "Huele a pan, muerde a brasa.",
    "bn_b09": "Sofá Destrozado",
    "bk_b09": "La Garra de Cuero",
    "bl_b09": "Sus uñas cortan el cuero como mantequilla.",
    "bn_b10": "El Rey del Frigo",
    "bk_b10": "Su Majestad Hambrienta",
    "bl_b10": "Abre las puertas con la sola fuerza del hambre.",
    "bn_b11": "Gatita Mimada",
    "bk_b11": "El Ángel con Garras",
    "bl_b11": "Lazo rosa, garras de acero.",
    "bn_b12": "Bola de Lana",
    "bk_b12": "La Trampa Suave",
    "bl_b12": "Parece tierno. Es una trampa.",
    "bn_b13": "El Despertador de las 4",
    "bk_b13": "La Pesadilla Nocturna",
    "bl_b13": "Te ataca cuando menos lo esperas: las 4 de la madrugada.",
    "bn_b14": "El Gato del Teclado",
    "bk_b14": "El Saboteador",
    "bl_b14": "Camina sobre los nervios. Y sobre las teclas.",
    "bn_b15": "Cortina Rasgada",
    "bk_b15": "El Escalador",
    "bl_b15": "Se sube donde no debería. Siempre.",
    "bn_b16": "Jarrón Roto",
    "bk_b16": "El Inocente Destructor",
    "bl_b16": "Deja destrucción y una mirada angelical.",
    "bn_barone": "El Barón von Bigoten",
    "bk_barone": "La Garra Aristocrática",
    "bl_barone": "Se bate según la vieja etiqueta: primero la reverencia, luego el doble zarpazo.",
    "bn_b18": "Condesa Terciopelo",
    "bk_b18": "La Mirada que Aturde",
    "bl_b18": "Un pelaje tan suave que aturde al rival.",
    "bn_b19": "Sir Zarpazo III",
    "bk_b19": "El Duelista",
    "bl_b19": "Espadachín legendario, nunca perdió un duelo al alba.",
    "bn_b20": "Madame Persia",
    "bk_b20": "La Reina del Cojín",
    "bl_b20": "Reina desde su cojín de seda y no se levanta por nadie.",
    "bn_b21": "El Duque Cartujo",
    "bk_b21": "El Acero Gris",
    "bl_b21": "Gris como el acero, frío como el hierro.",
    "bn_b22": "Lady Siam",
    "bk_b22": "El Golpe de Hielo",
    "bl_b22": "Ojos de zafiro, golpe que hiela la sangre.",
    "bn_b23": "Don Gatazo",
    "bk_b23": "El Padrino",
    "bl_b23": "El padrino del callejón: ofertas que no puedes rechazar.",
    "bn_b24": "El Mayordomo Esmoquin",
    "bk_b24": "La Sombra Elegante",
    "bl_b24": "Blanco y negro, impecable y letal.",
    "bn_sfinge": "La Esfinge del Patio",
    "bk_sfinge": "El Enigma Peludo",
    "bl_sfinge": "Te mira fijamente hasta que confiesas. Solo habla con acertijos.",
    "bn_b26": "Colmillo de Lince",
    "bk_b26": "La Emboscada",
    "bl_b26": "No lo oyes llegar. Solo lo sientes después.",
    "bn_b27": "El Gato Salvaje",
    "bk_b27": "El Indómito",
    "bl_b27": "Nunca fue domesticado. Nunca lo será.",
    "bn_b28": "Sombra de la Jungla",
    "bk_b28": "El Silencio Negro",
    "bl_b28": "Negro como la noche, silencioso como la muerte.",
    "bn_b29": "Rugido",
    "bk_b29": "La Gran Voz",
    "bl_b29": "Pequeño de tamaño, enorme de voz.",
    "bn_b30": "Garra de las Nieves",
    "bk_b30": "El Golpe Gélido",
    "bl_b30": "Baja de las cumbres con un golpe que congela.",
    "bn_b31": "El Tigre de Cartón",
    "bk_b31": "El Engaño a Rayas",
    "bl_b31": "Parece falso hasta que te muerde.",
    "bn_b32": "El Puma de los Tejados",
    "bk_b32": "El Saltador",
    "bl_b32": "Salta de un edificio a otro sin rozar el suelo.",
    "bn_nonna": "La Abuela de los Callejones",
    "bk_nonna": "Siete Vidas y Media",
    "bl_nonna": "Sus ronroneos curan, sus zarpazos educan.",
    "bn_pescatore": "El Pescador Fantasma",
    "bk_pescatore": "La Red del Destino",
    "bl_pescatore": "Aparece en las noches de niebla, olor a sardinas y venganza.",
    "bn_b35": "El Gato con Botas",
    "bk_b35": "La Hoja Legendaria",
    "bl_b35": "El espadachín de los cuentos, en carne, pelo y botas.",
    "bn_b36": "Bastet Menor",
    "bk_b36": "La Sacerdotisa",
    "bl_b36": "Sacerdotisa de los nueve anillos, guardiana de los ritos.",
    "bn_b37": "El Gato Guardián",
    "bk_b37": "El Custodio del Umbral",
    "bl_b37": "Custodia el umbral del granero sagrado desde hace siglos.",
    "bn_b38": "Cola de Zorro",
    "bk_b38": "Los Nueve Engaños",
    "bl_b38": "Nueve colas, nueve engaños, ninguna piedad.",
    "bn_b39": "El Callejero Inmortal",
    "bk_b39": "Ocho Vidas Gastadas",
    "bl_b39": "Dicen que ya ha gastado ocho vidas. Queda una.",
    "bn_b40": "Maneki el Amuleto",
    "bk_b40": "La Pata del Destino",
    "bl_b40": "La pata alzada que sella los destinos ajenos.",
    "bn_spettro": "El Espectro de los Tejados",
    "bk_spettro": "La Sombra de Medianoche",
    "bl_spettro": "Nadie lo vio llegar jamás. Muchos vieron irse su cena.",
    "bn_b42": "El Gato Negro del Viernes",
    "bk_b42": "La Mala Suerte con Pelo",
    "bl_b42": "Trae mala suerte a quien ose desafiarlo.",
    "bn_b43": "Ojos en la Oscuridad",
    "bk_b43": "El Depredador Invisible",
    "bl_b43": "Solo lo ves cuando ya es demasiado tarde.",
    "bn_b44": "El Segador Bigotudo",
    "bk_b44": "El Señor de la Novena Vida",
    "bl_b44": "Viene a cobrar tu novena vida.",
    "bn_b45": "Fantasma de la Chimenea",
    "bk_b45": "La Ceniza Viviente",
    "bl_b45": "Vive en la ceniza caliente de la chimenea.",
    "bn_b46": "La Gata Bruja",
    "bk_b46": "La Hechicera",
    "bl_b46": "Convierte a los ratones en tormentas con un maullido.",
    "bn_b47": "El Vampiro Persa",
    "bk_b47": "El Chupa-Velocidad",
    "bl_b47": "Absorbe la Velocidad de los rivales y la hace suya.",
    "bn_b48": "Ectoplasma Felino",
    "bk_b48": "El Intocable",
    "bl_b48": "No puedes golpear lo que no es sólido.",
    "bn_imperatore": "El Emperador Atigrado",
    "bk_imperatore": "El Trono de Cojines",
    "bl_imperatore": "Reina desde el cojín más alto. Su caos dicta las reglas.",
    "bn_b50": "Bastet la Diosa",
    "bk_b50": "La Antigua Protectora",
    "bl_b50": "La antigua diosa protectora de todos los gatos.",
    "bn_b51": "El Gato de Schrödinger",
    "bk_b51": "Vivo y Muerto",
    "bl_b51": "Vivo y muerto a la vez, hasta que lo atacas.",
    "bn_b52": "Ra-Miau el Sol",
    "bk_b52": "El Cegador",
    "bl_b52": "Cegador: quema a quien osa mirarlo.",
    "bn_b53": "Sekhmet Felina",
    "bk_b53": "La Furia Divina",
    "bl_b53": "La furia divina hecha garras.",
    "bn_b54": "El Guardián de las Pirámides",
    "bk_b54": "Mil Dinastías",
    "bl_b54": "Viejo de mil dinastías, inmóvil como la piedra.",
    "bn_b55": "Luna Creciente",
    "bk_b55": "La Diosa de la Noche",
    "bl_b55": "La diosa de la noche: en la oscuridad es invencible.",
    "bn_b56": "El Gato de las Estrellas",
    "bk_b56": "El Manto Cósmico",
    "bl_b56": "Su manto es un cielo de constelaciones.",
    "bn_mammone": "El Gatto Mammone",
    "bk_mammone": "La Leyenda de las Leyendas",
    "bl_mammone": "El monstruo de los cuentos. Enorme, antiguo y susceptible.",
    "bn_b58": "Behemot",
    "bk_b58": "El Coloso del Abismo",
    "bl_b58": "El coloso que duerme bajo los volcanes.",
    "bn_b59": "El Primer Gato",
    "bk_b59": "El Ancestro",
    "bl_b59": "Aquel del que descienden todos los mininos del mundo.",
    "bn_b60": "Devorador de Nueve Soles",
    "bk_b60": "El Mito Cósmico",
    "bl_b60": "El mito que engulle soles, uno tras otro.",
    "bn_b61": "El Señor de los Callejeros",
    "bk_b61": "El Rey de Todos",
    "bl_b61": "Comanda a cada gato callejero del mundo.",
    "bn_b62": "Chronos Felino",
    "bk_b62": "El Devorador de Tiempo",
    "bl_b62": "Come el tiempo y envejece a los rivales.",
    "bn_b63": "El Gato Vacío",
    "bk_b63": "La Ausencia Hecha Felino",
    "bl_b63": "La ausencia hecha felino. La nada que maúlla.",
    "bn_b64": "MIAO-9000",
    "bk_b64": "El Gato-Máquina Definitivo",
    "bl_b64": "El gato-máquina definitivo. Error: piedad no encontrada."
  },
  "world": {
    "w_recent": "📜 Los últimos 5 combates de tus cartas",
    "w_open": "(toca para abrir)",
    "w_beat": "{w} de {wo} venció a {l} de {lo}",
    "w_rank_champ": "👑 #1",
    "w_rank_n": "#{rk} en la clasificación",
    "w_retired": "🚪 retirada",
    "w_record": "{w} V / {l} D",
    "w_none_pub": "Ninguna de tus cartas está publicada aún.",
    "w_reactivate": "↩️ Reactivar",
    "w_retire": "🚪 Retirar",
    "w_rank_suffix": "en la clasificación",
    "w_by": "de",
    "w_anon": "anónimo",
    "w_wc_champ": "👑 CAMPEÓN DEL MUNDO",
    "w_wc_rank": "#{rk} en la clasificación",
    "w_elo": "pts Elo",
    "w_exchamp": "🏆 excampeón",
    "w_beststreak": "mejor racha 🔥{n}",
    "w_sw": "🔥 {n} seguidas",
    "w_sl": "🧊 {n} KO seguidos",
    "w_resting": "😴 Está descansando: vuelve en {min} minutos",
    "w_not_ranked": "⏳ {name} aún no está en la clasificación (¿recién publicada? reintenta pronto con 🔄).",
    "w_no_challengers": "📊 {name} es #{rk}, pero no hay retadores en ±5 ahora mismo. ¡Invita a alguien a publicar!",
    "w_you_rank": "📊 {name} es #{rk} en la clasificación. Estos puede desafiar (de 5 posiciones por encima a 5 por debajo):",
    "w_rests_short": "😴 descansa ({min}m)",
    "w_btn_fight": "⚔️ Desafiar",
    "w_ldr_champ": "CAMPEÓN",
    "w_ex": "ex",
    "w_maxstreak": "máx 🔥{n}",
    "w_none_rank": "Ninguna carta en la clasificación: ¡publica una!",
    "w_record_c": "{w}V/{l}D",
    "w_selrest": "😴 descansa",
    "w_selmarket": "🔒 en el mercado",
    "w_fav": "⭐ favorito",
    "w_underdog": "🐾 no favorito",
    "w_quota": "cuota",
    "w_ifwin": "si gana: +{n} puntos",
    "prize_line": "🎁 <strong>En juego:</strong> victoria +10 puntos y +25 XP · derrota +10 XP",
    "w_catnip_ready": "🌿 Hierba gatera LISTA para este combate ✔",
    "w_catnip_btn": "🌿 Dale hierba gatera — primer golpe duplicado (50 puntos)",
    "w_catnip_need": "Hacen falta 50 puntos (tienes {pts}).",
    "w_pick_champ_opt": "— elige un campeón —",
    "w_all_resting": "😴 todos tus gatos descansan — vuelve más tarde",
    "w_pub_first_opt": "— publica primero una carta —",
    "w_loading": "Cargando la clasificación…"
  },
  "mkt": {
    "mkt_desc": "Intercambia o vende tus cartas con otros jugadores. La carta cambia de dueño con todo (Elo, victorias, nivel); mientras está en negociación queda congelada y no combate. Hay que estar conectado y tener cartas publicadas en el Mundo.",
    "trd_greet": "¡Bienvenido al bazar, amigo! Soy Míster Trueque: pregunta, que yo sé cómo se hacen los buenos negocios.",
    "inc_greet": "¡Señoras y señores, se abre la subasta! ¿Quién ofrece? ¿Quién puja?",
    "mkt_browse_btn": "🔍 Explorar cartas para intercambiar",
    "mkt_filter_ph": "Filtrar por dueño (p. ej. Lu…)",
    "mkt_notactive": "⚠️ El Mercado aún no está activo en el servidor (falta un paso de configuración). Las demás funciones de la app funcionan con normalidad.",
    "mkt_recv_h": "📥 Ofertas recibidas",
    "mkt_offers": "{owner} te ofrece <strong>{from}</strong> a cambio de tu <strong>{to}</strong>",
    "mkt_compare_btn": "🔍 Comparar",
    "mkt_accept": "✅ Aceptar",
    "mkt_reject": "✖ Rechazar",
    "mkt_none_recv": "Ninguna oferta recibida.",
    "mkt_sent_h": "📤 Ofertas enviadas",
    "mkt_sent": "Ofreciste <strong>{from}</strong> por <strong>{to}</strong> de {owner}",
    "mkt_cancel": "↩️ Cancelar",
    "mkt_login": "Inicia sesión para intercambiar.",
    "mkt_loading": "Cargando…",
    "mkt_err_load": "❌ Error {code} al cargar las cartas.",
    "mkt_none_avail": "Ninguna carta disponible para intercambiar.",
    "mkt_neterr": "Error de red.",
    "mkt_none_of": "Ninguna carta de «{q}».",
    "mkt_propose": "🔄 Proponer",
    "mkt_this_card": "esta carta",
    "mkt_give_get": "Das <strong>{give}</strong> → Recibes <strong>{get}</strong>",
    "mkt_level": "📈 Nivel",
    "mkt_baratto_label": "😼 <strong>Míster Trueque</strong>:",
    "mkt_loading_cmp": "Cargando la comparación…",
    "mkt_cmp_title": "🔄 Comparación de intercambio",
    "mkt_accept_trade": "✅ Aceptar el intercambio",
    "mkt_close": "↩️ Cerrar",
    "mkt_err_cmp": "Error al cargar la comparación.",
    "mkt_close2": "Cerrar",
    "mkt_trade_h": "🔄 Intercambio",
    "mkt_need_card": "Para intercambiar necesitas al menos UNA carta TUYA publicada y activa en el Mundo (y no en reposo).",
    "mkt_closeX": "✖ Cerrar",
    "mkt_propose_h": "🔄 Proponer intercambio",
    "mkt_want": "Quieres <strong>{name}</strong>{owner}.",
    "mkt_tap_offer": "Toca TU carta para ofrecer:",
    "mkt_do_trade": "🔄 Intercambiar",
    "mkt_cancelX": "✖ Cancelar",
    "mkt_pick_offer": "Toca primero una carta tuya para ofrecer.",
    "mkt_notactive2": "⚠️ El Mercado aún no está activo en el servidor: falta un paso de configuración (SQL de la etapa 2).",
    "mkt_trade_fail": "Intercambio no propuesto: {t}",
    "mkt_sent_ok": "🔄 ¡Oferta enviada! Esperando respuesta.",
    "mkt_neterr2": "Error de red: {m}",
    "mkt_op_fail": "Operación fallida: {t}",
    "mkt_trade_done": "✅ ¡Intercambio hecho! Las cartas cambiaron de dueño.",
    "mkt_rejected": "Oferta rechazada.",
    "mkt_cancelled": "↩️ Oferta cancelada.",
    "mkt_received": "🎁 ¡Recibiste {name} en el intercambio!",
    "mkt_login_first": "Inicia sesión primero (pestaña 🌍 Mundo).",
    "mkt_auc_h": "🔨 Subasta",
    "mkt_need_free": "Necesitas una carta publicada y libre (no ya en el mercado) para subastar.",
    "mkt_put_auc_h": "🔨 Poner en subasta",
    "mkt_tap_sell": "Toca la carta a vender:",
    "mkt_min_price": "Precio mínimo (puntos)",
    "mkt_duration": "Duración",
    "mkt_h1": "1 hora",
    "mkt_h6": "6 horas",
    "mkt_h24": "24 horas",
    "mkt_d2": "2 días",
    "mkt_hold_auc": "🔨 Iniciar la subasta",
    "mkt_pick_card": "Toca primero una carta.",
    "mkt_auc_notactive": "⚠️ Las subastas aún no están activas en el servidor (falta el SQL).",
    "mkt_auc_fail": "Subasta no creada: {t}",
    "mkt_auc_ok": "🔨 ¡Subasta iniciada! Tu carta está ahora en el mercado.",
    "mkt_auc_notactive2": "⚠️ Subastas aún no activas en el servidor (falta el paso SQL).",
    "mkt_err": "Error {code}.",
    "mkt_no_auc": "Ninguna subasta en curso. ¡Inicia una!",
    "mkt_curbid": "💰 {n} pt de {owner}",
    "mkt_nobid": "sin ofertas",
    "mkt_your_auc": "🔨 tu subasta",
    "mkt_withdraw": "↩️ Retirar",
    "mkt_bid_btn": "💰 Pujar",
    "mkt_base": "Base {n} pt",
    "mkt_history": "📜 Historial de ofertas",
    "mkt_min_bid": "Debes ofrecer al menos {n} puntos.",
    "mkt_no_points": "No tienes suficientes puntos (tienes {p}).",
    "mkt_bid_fail": "Oferta rechazada: {t}",
    "mkt_no_bids": "Aún ninguna oferta.",
    "mkt_bid_line": "💰 {n} pt — {owner} · {when}",
    "mkt_err2": "Error.",
    "mkt_confirm_withdraw": "¿Retirar la carta de la subasta?",
    "mkt_withdraw_fail": "No retirada: {t}",
    "mkt_withdrawn": "↩️ Subasta retirada."
  },
  "sent": {
    "sent_title": "🗺️ El Sendero de las Nueve Vidas",
    "sent_desc": "Un largo viaje por etapas para cada una de tus cartas: enfréntate a los gatos del sendero uno tras otro. Cada victoria desbloquea la siguiente etapa y te da el cromo de ese gato para el Álbum. Se juega sin conexión, sin apuestas ni descanso: si pierdes, reintenta.",
    "sent_pick": "Quién recorre el sendero",
    "pick_card": "👆 Elige una carta arriba para empezar el viaje.",
    "no_card": "Crea primero una carta, y luego al sendero.",
    "progress": "<strong>{name}</strong> — etapa {done}/{tot} superadas.",
    "more_soon": "🚧 Las próximas zonas del sendero llegan pronto…",
    "stage": "Etapa",
    "zone_done": "🎉 ¡Zona completada! +{pts} puntos y una nueva página del Álbum.",
    "got_fig": "📒 ¡Nuevo cromo: {name}!",
    "album_sum": "📒 Álbum — <strong>{done}/{tot}</strong> cromos <span class=\"count\">{open}</span>",
    "z_1": "Los Callejones",
    "z_2": "Los Jardines",
    "z_3": "El Bosque",
    "z_4": "La Montaña",
    "z_5": "La Ciudad",
    "z_6": "El Desierto",
    "z_7": "El Mar",
    "z_8": "Las Tierras de Hielo",
    "z_9": "El Volcán",
    "z_10": "El Cosmos",
    "bn_s01": "Gatito",
    "bk_s01": "El Novato",
    "bl_s01": "El primer gato que encuentras: curioso, torpe, pero con mucho corazón.",
    "bn_s02": "Hurga",
    "bk_s02": "El Rey de la Basura",
    "bl_s02": "Conoce cada contenedor del barrio y lo que hay dentro.",
    "bn_s03": "Calcetín",
    "bk_s03": "El Dormilón",
    "bl_s03": "Blanco y negro, siempre en el capó más caliente del callejón.",
    "bn_s04": "Cajita",
    "bk_s04": "La Emboscada de Cartón",
    "bl_s04": "Vive en una caja y salta cuando menos lo esperas.",
    "bn_s05": "Medianoche",
    "bk_s05": "La Sombra del Callejón",
    "bl_s05": "Negro como la noche, solo lo ves por sus ojos brillantes.",
    "bn_s06": "Nata",
    "bk_s06": "El Goloso",
    "bl_s06": "Siempre con bigotes de leche y una sonrisa satisfecha.",
    "bn_s07": "Cuerda",
    "bk_s07": "El Músico",
    "bl_s07": "Toca su guitarra desafinada bajo las farolas por unas golosinas.",
    "bn_s08": "Sardina",
    "bk_s08": "El Pescadero",
    "bl_s08": "Nunca suelta su pescado: tendrás que ganártelo.",
    "bn_s09": "Rayo",
    "bk_s09": "El Relámpago del Callejón",
    "bl_s09": "Rebota de pared en pared: atrápalo si puedes.",
    "bn_s10": "Tuerto",
    "bk_s10": "El Rey de los Callejones",
    "bl_s10": "Un solo ojo y mil cicatrices: manda sobre los callejeros. El primer obstáculo de verdad.",
    "bn_s11": "Aleteo",
    "bk_s11": "El Cazamariposas",
    "bl_s11": "Persigue mariposas todo el día, nunca atrapa una.",
    "bn_s12": "Girasol",
    "bk_s12": "El Dormilón al Sol",
    "bl_s12": "Duerme donde da el sol y se mueve con él.",
    "bn_s13": "Zumbido",
    "bk_s13": "El Aguijón",
    "bl_s13": "Aprendió por las malas que las abejas pican. Sigue intentándolo.",
    "bn_s14": "Pío",
    "bk_s14": "El Espía-pájaros",
    "bl_s14": "Observa a los pajaritos desde la ventana durante horas, inmóvil.",
    "bn_s15": "Ranita",
    "bk_s15": "El Espanta-ranas",
    "bl_s15": "Salta al estanque y hace huir a todas las ranas.",
    "bn_s16": "Espina",
    "bk_s16": "El Herido de Rosas",
    "bl_s16": "Mil arañazos entre las zarzas, pero el rosal es suyo.",
    "bn_s17": "Caracol",
    "bk_s17": "El Paciente",
    "bl_s17": "Observa moverse a los caracoles. Es lo único más lento que ellos.",
    "bn_s18": "Chapoteo",
    "bk_s18": "El Salpica-fuentes",
    "bl_s18": "Juega con el agua de la fuente y vuelve siempre empapado.",
    "bn_s19": "Púa",
    "bk_s19": "El Amigo Espinoso",
    "bl_s19": "Se hizo amigo de un erizo. No preguntes cómo.",
    "bn_s20": "Viejo Sauce",
    "bk_s20": "El Señor del Jardín",
    "bl_s20": "El gato más viejo del jardín: sabio, calmo e intocable.",
    "bn_s21": "Hongo",
    "bk_s21": "El Recolector",
    "bl_s21": "Olfatea las mejores setas del bosque y esquiva las malas.",
    "bn_s22": "Plumanoche",
    "bk_s22": "El Rival del Búho",
    "bl_s22": "Reta al búho cada noche a ver quién aguanta más despierto.",
    "bn_s23": "Bellota",
    "bk_s23": "El Acaparador",
    "bl_s23": "Roba bellotas a las ardillas y las esconde por todas partes.",
    "bn_s24": "Astuto",
    "bk_s24": "El Ladino",
    "bl_s24": "Camina como un zorro y piensa como un zorro.",
    "bn_s25": "Colmillo",
    "bk_s25": "El Guardián del Territorio",
    "bl_s25": "Defiende su claro de cualquiera, jabalíes incluidos.",
    "bn_s26": "Telaraña",
    "bk_s26": "El Enredado",
    "bl_s26": "Siempre acaba en las telarañas, pero nunca se rinde.",
    "bn_s27": "Piña",
    "bk_s27": "El Trepapinos",
    "bl_s27": "Trepa los pinos más altos solo para mirar hacia abajo.",
    "bn_s28": "Cervato",
    "bk_s28": "El Cazador Silencioso",
    "bl_s28": "Sigue a los ciervos por el bosque sin hacer ruido.",
    "bn_s29": "Lobezno",
    "bk_s29": "El Cachorro Salvaje",
    "bl_s29": "Criado entre lobos, aprendió su aullido.",
    "bn_s30": "Osote",
    "bk_s30": "La Bestia del Bosque",
    "bl_s30": "Grande como un oso: el rey indiscutible del bosque.",
    "bn_s31": "Botita",
    "bk_s31": "El Sigue-Excursionistas",
    "bl_s31": "Sigue a los excursionistas a la cima esperando un bocadillo.",
    "bn_s32": "Saltacabras",
    "bk_s32": "El Espanta-cabras",
    "bl_s32": "Hace saltar a las cabras en los riscos solo por diversión.",
    "bn_s33": "Piedrita",
    "bk_s33": "El Equilibrista",
    "bl_s33": "Se equilibra sobre las rocas más incómodas de la montaña.",
    "bn_s34": "Aguilucho",
    "bk_s34": "El Rival del Águila",
    "bl_s34": "Le disputa al águila las cumbres más altas, sin alas.",
    "bn_s35": "Toldillo",
    "bk_s35": "El Ladrón del Campamento",
    "bl_s35": "Saquea las tiendas de los campistas por la noche.",
    "bn_s36": "Cima",
    "bk_s36": "El Habitante de las Cumbres",
    "bl_s36": "Vive donde el aire es fino y ningún otro gato se atreve.",
    "bn_s37": "Ventarrón",
    "bk_s37": "El Despeinado",
    "bl_s37": "El viento de la montaña le erizó el pelo para siempre.",
    "bn_s38": "Garfio",
    "bk_s38": "El Escalador",
    "bl_s38": "Trepa paredes donde ni las cabras van.",
    "bn_s39": "Campanilla",
    "bk_s39": "El Montañés",
    "bl_s39": "Lleva un cascabel al cuello: lo oyes antes de verlo.",
    "bn_s40": "Cuernoblanco",
    "bk_s40": "El Rey de la Montaña",
    "bl_s40": "Cuernos de carnero y patas de hierro: domina cada cumbre.",
    "bn_s41": "Taxi",
    "bk_s41": "El Esquiva-coches",
    "bl_s41": "Cruza el tráfico más caótico sin un rasguño.",
    "bn_s42": "Teja",
    "bk_s42": "El Merodeador de Tejados",
    "bl_s42": "Reina sobre los tejados de la gran ciudad, teja a teja.",
    "bn_s43": "Margarita",
    "bk_s43": "El Saqueador de Pizzas",
    "bl_s43": "Ninguna caja de pizza está a salvo con él cerca.",
    "bn_s44": "Semáforo",
    "bk_s44": "El Vigila-tráfico",
    "bl_s44": "Siempre espera el verde. Un gato muy cívico.",
    "bn_s45": "Parkour",
    "bk_s45": "El Acróbata de Tejados",
    "bl_s45": "Salta de un edificio a otro como en las películas.",
    "bn_s46": "Neón",
    "bk_s46": "El Holgazán de Neón",
    "bl_s46": "Duerme bajo los letreros luminosos, al calor de la ciudad.",
    "bn_s47": "Metro",
    "bk_s47": "El Gato del Metro",
    "bl_s47": "Conoce cada túnel y cada andén bajo tierra.",
    "bn_s48": "Jazz",
    "bk_s48": "El Gato del Callejón",
    "bl_s48": "Maúlla a ritmo de jazz detrás de los locales, de noche.",
    "bn_s49": "Rascacielos",
    "bk_s49": "El Trepa-torres",
    "bl_s49": "Escaló el edificio más alto solo por las vistas.",
    "bn_s50": "Nocturno",
    "bk_s50": "El Boss de la Ciudad",
    "bl_s50": "Manda en cada callejón tras el atardecer. La ciudad es suya.",
    "bn_s51": "Cactín",
    "bk_s51": "El Esquiva-cactus",
    "bl_s51": "Corre entre los cactus sin pincharse nunca. Casi.",
    "bn_s52": "Garfio-cola",
    "bk_s52": "El Desconfiado",
    "bl_s52": "Vigila a cada escorpión: ya lo picaron una vez.",
    "bn_s53": "Duna",
    "bk_s53": "El Corredor de Dunas",
    "bl_s53": "Sube y baja las dunas como si fueran cojines.",
    "bn_s54": "Palmera",
    "bk_s54": "El Holgazán del Oasis",
    "bl_s54": "Encontró la única sombra del desierto y no la suelta.",
    "bn_s55": "Siseo",
    "bk_s55": "El Encantador de Serpientes",
    "bl_s55": "Mira fijo a las serpientes hasta que se rinden.",
    "bn_s56": "Solazo",
    "bk_s56": "El Quemado por el Sol",
    "bl_s56": "El sol del desierto le caldeó el carácter.",
    "bn_s57": "Ánfora",
    "bk_s57": "El Gato de las Ruinas",
    "bl_s57": "Vive entre las ruinas antiguas, guardián de secretos de arena.",
    "bn_s58": "Joroba",
    "bk_s58": "El Sigue-camellos",
    "bl_s58": "Sigue las caravanas por las migas de los viajeros.",
    "bn_s59": "Torbellino",
    "bk_s59": "El Superviviente de Tormentas",
    "bl_s59": "Ha pasado mil tormentas de arena. Sigue aquí.",
    "bn_s60": "Leonino",
    "bk_s60": "La Esfinge del Desierto",
    "bl_s60": "Inmóvil como una estatua, antiguo como la arena. Habla con acertijos.",
    "bn_s61": "Pinza",
    "bk_s61": "El Atrapa-cangrejos",
    "bl_s61": "Persigue cangrejos en la orilla, siempre pierde un bigote.",
    "bn_s62": "Concha",
    "bk_s62": "El Coleccionista",
    "bl_s62": "Recoge conchas y las esconde en la arena.",
    "bn_s63": "Ola",
    "bk_s63": "El Esquiva-olas",
    "bl_s63": "Reta a las olas y huye justo antes de mojarse.",
    "bn_s64": "Anzuelo",
    "bk_s64": "El Pescador",
    "bl_s64": "Pesca con la pata mejor que muchos pescadores.",
    "bn_s65": "Gaviota",
    "bk_s65": "El Rival de la Gaviota",
    "bl_s65": "Les disputa a las gaviotas cada miga del muelle.",
    "bn_s66": "Vela",
    "bk_s66": "El Polizón",
    "bl_s66": "Se embarca a escondidas y nadie se da cuenta.",
    "bn_s67": "Abordaje",
    "bk_s67": "El Gato Pirata",
    "bl_s67": "Un parche en el ojo y una pata siempre lista para el asalto.",
    "bn_s68": "Tentáculo",
    "bk_s68": "El Domador de Pulpos",
    "bl_s68": "El único que juega con los pulpos y sale vencedor.",
    "bn_s69": "Foca",
    "bk_s69": "El Amigo del Mar",
    "bl_s69": "Nada con las focas como si hubiera nacido entre ellas.",
    "bn_s70": "Leviatán",
    "bk_s70": "El Rey del Mar",
    "bl_s70": "Grande como una ballena: comanda cada ola del océano.",
    "sent_fight": "⚔️ Combatir",
    "sent_back": "↩️ Atrás",
    "sent_replay": "⚔️ Rejugar",
    "bn_s71": "Nevisca",
    "bk_s71": "El Atrapa-copos",
    "bl_s71": "Intenta atrapar los copos de nieve con las patas, uno a uno.",
    "bn_s72": "Muñeco",
    "bk_s72": "El Constructor de Nieve",
    "bl_s72": "Construye muñecos de nieve y luego los derriba por diversión.",
    "bn_s73": "Carámbano",
    "bk_s73": "El Resbalón",
    "bl_s73": "Se desliza sobre el hielo sin detenerse nunca de verdad.",
    "bn_s74": "Pingüino",
    "bk_s74": "El Rival del Pingüino",
    "bl_s74": "Reta a los pingüinos a ver quién resbala más lejos sobre la barriga.",
    "bn_s75": "Esquiador",
    "bk_s75": "El Descensista",
    "bl_s75": "Baja las laderas nevadas más rápido que un trineo.",
    "bn_s76": "Osito",
    "bk_s76": "El Amigo del Oso Blanco",
    "bl_s76": "Adoptó a un cachorro de oso polar. ¿O fue al revés?",
    "bn_s77": "Ventisca",
    "bk_s77": "El Caminante de Tormentas",
    "bl_s77": "Atraviesa las tormentas de nieve como si fueran una brisa.",
    "bn_s78": "Curler",
    "bk_s78": "El Lanzador de Hielo",
    "bl_s78": "Desliza piedras sobre el hielo con puntería perfecta.",
    "bn_s79": "Cristal",
    "bk_s79": "El Admira-cristales",
    "bl_s79": "Pasa horas mirando los cristales de hielo que brillan.",
    "bn_s80": "Rey Hielo",
    "bk_s80": "El Soberano del Hielo",
    "bl_s80": "Su aliento congela los lagos. Nadie aguanta su mirada de hielo.",
    "bn_s81": "Brasa",
    "bk_s81": "El Tizón",
    "bl_s81": "Camina sobre carbones ardientes sin quemarse las patas.",
    "bn_s82": "Cráter",
    "bk_s82": "El Habitante del Cráter",
    "bl_s82": "Vive al borde del volcán, donde hace un calor infernal.",
    "bn_s83": "Obsidiana",
    "bk_s83": "El Gato de Piedra Negra",
    "bl_s83": "Duro y brillante como el vidrio volcánico.",
    "bn_s84": "Estruendo",
    "bk_s84": "El Explosivo",
    "bl_s84": "Cuando se enfada, toda la montaña tiembla.",
    "bn_s85": "Petardo",
    "bk_s85": "La Mecha Corta",
    "bl_s85": "Se enciende por nada y sale al ataque.",
    "bn_s86": "Manantial",
    "bk_s86": "El Holgazán de las Termas",
    "bl_s86": "Dormita en las pozas calientes junto a la lava.",
    "bn_s87": "Bochorno",
    "bk_s87": "El Candente",
    "bl_s87": "A su paso, el aire tiembla de calor.",
    "bn_s88": "Llamita",
    "bk_s88": "El Guardián del Fuego",
    "bl_s88": "Mantiene viva la antigua llama del volcán.",
    "bn_s89": "Farol",
    "bk_s89": "La Llama Eterna",
    "bl_s89": "Arde desde hace mil años y nunca se apaga.",
    "bn_s90": "Dragoncito",
    "bk_s90": "El Dragón del Volcán",
    "bl_s90": "Escupe chispas y comanda la lava. El rey del fuego.",
    "bn_s91": "Lunita",
    "bk_s91": "El Gato de la Luna",
    "bl_s91": "Salta de cráter en cráter en la luna, ligero como una pluma.",
    "bn_s92": "Estrellita",
    "bk_s92": "El Recoge-estrellas",
    "bl_s92": "Colecciona estrellas fugaces en un frasco (según él).",
    "bn_s93": "Anillo",
    "bk_s93": "El Señor de los Anillos",
    "bl_s93": "Vive en los anillos de Saturno, en equilibrio perfecto.",
    "bn_s94": "Cometa",
    "bk_s94": "El Viajero",
    "bl_s94": "Surca el espacio dejando una estela luminosa.",
    "bn_s95": "Cohete",
    "bk_s95": "El Astronauta",
    "bl_s95": "Se subió a un cohete por juego y no volvió a bajar.",
    "bn_s96": "Platillo",
    "bk_s96": "El Amigo de los Aliens",
    "bl_s96": "Se hizo amigo de criaturas de otros mundos.",
    "bn_s97": "Meteoro",
    "bk_s97": "El Deseo",
    "bl_s97": "Pasa tan rápido que hay que pedir un deseo.",
    "bn_s98": "Vacío",
    "bk_s98": "El Agujero Negro",
    "bl_s98": "Engulle todo lo que se acerca, incluso la luz.",
    "bn_s99": "Polvo",
    "bk_s99": "El Manto de Estrellas",
    "bl_s99": "Su pelaje está hecho de polvo de galaxias.",
    "bn_s100": "Soberano Cósmico",
    "bk_s100": "El Señor de las Nueve Vidas",
    "bl_s100": "El último rival del Sendero. Antiguo como el universo, invencible como una leyenda."
  },
  "msg": {
    "del_card_confirm": "¿Eliminar la carta de {name}? También se borrarán sus estadísticas de combate.",
    "nick_set": "🥊 {name} ahora es «{nick}»",
    "retire_login": "Para retirar una carta del mundo primero debes iniciar sesión (pestaña 🌍 Mundo).",
    "retire_confirm": "¿Retirar a {name} de la Arena Mundial? Se queda en la clasificación con su récord como \"retirada\", pero nadie podrá desafiarla más. (Republicarla la reactiva.)",
    "err_http": "Error: HTTP {code}",
    "card_not_pub": "Esta carta no está publicada (o no es tuya).",
    "retired_ok": "🚪 {name} se retiró del mundo con honor. Su récord queda en la clasificación.",
    "err_net": "Error de red: {m}",
    "code_copied": "¡Código copiado! Envíalo a un amigo (p. ej. por WhatsApp): lo pega en su app para desafiar a {name}. Nota: el código es largo porque también contiene la foto.",
    "audio_quota": "⛔ Cuota diaria de Gemini agotada.\n\nLos clips ya hechos están guardados. Retoma mañana (la cuota se reinicia) y completará solo los que falten.",
    "audio_err": "🎙️ Error de audio ({lang}): {err}",
    "same_cat": "¡Un gato no puede luchar contra sí mismo! Elige dos cartas distintas.",
    "backup_confirm": "¿Importar la copia? Reemplazará tu colección, rivales y estadísticas actuales ({n} cartas en la copia).",
    "backup_invalid": "Archivo de copia no válido.",
    "share_unsupported": "Este navegador no admite compartir directamente: usa «Descargar» y adjunta la imagen.",
    "card_gone_local": "Esta carta ya no está en tu colección local.",
    "news_beaten": "💥 {loser} fue vencida por {winner} {by} {owner} — ahora descansa 😴",
    "world_login": "Inicia sesión primero (arriba en la pestaña Mundo) para desafiar en línea.",
    "out_of_range": "🔒 Fuera de alcance: {name} es #{ro}, tú eres #{rm}. Solo puedes desafiar entre 5 posiciones por encima y 5 por debajo: ¡escala la clasificación!",
    "opp_trading": "🔄 {name} está en un intercambio: no se puede desafiar ahora.",
    "opp_resting": "😴 {name} acaba de ir a descansar: reintenta en {min} minutos.",
    "need_pub_card": "Para desafiar en línea necesitas UNA carta tuya publicada y activa: publica una desde «Elige qué cartas publicar».",
    "catnip_have": "Ventaja ya comprada: vale para tu próximo combate.",
    "catnip_need": "Hacen falta 50 puntos (tienes {pts}). ¡Gana apuestas y medallas!",
    "catnip_confirm": "¿Gastar 50 puntos? Tu carta empezará el próximo combate con hierba gatera (primer golpe duplicado).",
    "catnip_ready": "🌿 ¡Ventaja lista: vale para tu próximo combate!",
    "regen_cost": "Redibujar cuesta 30 puntos (tienes {pts}).",
    "regen_confirm": "¿Gastar 30 puntos por un nuevo dibujo IA?",
    "frame_have": "¡{name} ya luce el Marco de Oro!",
    "frame_cost": "El Marco de Oro cuesta 100 puntos (tienes {pts}).",
    "frame_confirm": "¿Gastar 100 puntos por el Marco de Oro de {name}? Se queda para siempre.",
    "food_need": "💰 Hacen falta {cost} puntos (tienes {pts}): ¡gánalos en el mundo!",
    "train_cancel": "↩️ Entrenamiento cancelado: {cost} puntos devueltos.",
    "pick_champ": "Elige primero tu campeón en el menú de arriba.",
    "qr_gen_fail": "Generador QR no cargado: recarga la página con internet.",
    "qr_read_fail": "Lector QR no cargado: hace falta internet.",
    "cam_fail": "Cámara no disponible: {m}",
    "qr_invalid": "QR no válido.",
    "qr_self": "¡Has escaneado tu propia carta!"
  },
  "moves": {
    "ma_0": "Arañazo",
    "ma_1": "Emboscada",
    "ma_2": "Mirada",
    "ma_3": "Salto",
    "ma_4": "Zarpazo",
    "ma_5": "Maullido",
    "ma_6": "Asalto",
    "ma_7": "Ronroneo",
    "mb_0": "Fulminante",
    "mb_1": "del Sofá",
    "mb_2": "de Desdén",
    "mb_3": "Cósmico",
    "mb_4": "Salvaje",
    "mb_5": "Nocturno",
    "mb_6": "de las 4 de la Mañana",
    "mb_7": "Hipnótico"
  },
  "instr": {
    "i_pianoforte": "piano",
    "i_tromba": "trompeta",
    "i_chitarra": "guitarra",
    "i_archi": "cuerdas",
    "i_organo": "órgano",
    "i_marimba": "marimba",
    "theme_line": "{stile} en {ton}, {instr}"
  },
  "breeds": {
    "b_soriano": "Atigrado",
    "b_tigrato": "Atigrado",
    "b_europeo": "Europeo",
    "b_comune": "Gato común",
    "b_certosino": "Cartujo",
    "b_siamese": "Siamés",
    "b_persiano": "Persa",
    "b_mainecoon": "Maine Coon",
    "b_ragdoll": "Ragdoll",
    "b_sphynx": "Sphynx",
    "b_bengala": "Bengalí",
    "b_british": "British Shorthair",
    "b_norvegese": "Bosque de Noruega",
    "b_angora": "Angora",
    "b_birmano": "Birmano",
    "b_abissino": "Abisinio",
    "b_esotico": "Exótico",
    "b_siberiano": "Siberiano",
    "b_scottish": "Scottish Fold",
    "b_rex": "Rex",
    "b_blurusso": "Azul Ruso",
    "b_orientale": "Oriental",
    "b_turco": "Van Turco",
    "b_savana": "Savannah",
    "b_bombay": "Bombay",
    "c_bianco": "blanco",
    "c_nero": "negro",
    "c_grigio": "gris",
    "c_blu": "azul",
    "c_rosso": "rojo",
    "c_crema": "crema",
    "c_marrone": "marrón",
    "c_fulvo": "leonado",
    "c_tartarugato": "carey",
    "c_tricolore": "tricolor",
    "c_bicolore": "bicolor",
    "c_maculato": "manchado",
    "c_striato": "rayado",
    "c_pointed": "colorpoint",
    "coat_lungo": "de pelo largo",
    "coat_corto": "de pelo corto"
  },
  "award": {
    "title": "🏆 Los Premios del Sábado Noche",
    "host": "Julio Miaulesias",
    "subtitle": "Cada sábado por la noche, la gran gala: premios, puntos y gloria para los mejores gatos de la semana.",
    "promo_when": "SÁBADO, 21:00",
    "promo_line": "🎬 Próximo episodio con {host}",
    "promo_cd": "en {d}d {h}h {m}m",
    "promo_soon": "en {h}h {m}m",
    "promo_live": "🔴 ¡Es la hora! La ceremonia está por empezar…",
    "noms_title": "✨ Las nominaciones de esta semana",
    "noms_sub": "Quién va en cabeza ahora — en directo",
    "noms_empty": "Aún no hay combates esta semana. ¡Lucha en el Mundo para entrar en la clasificación!",
    "past_title": "📼 Episodios anteriores",
    "past_empty": "La primera gala es este sábado. ¡Vuelve para ver a los ganadores!",
    "hall_title": "🏛️ Hall of Fame — récords de siempre",
    "hall_empty": "Aún no hay récords: alguien será el primero.",
    "by": "de",
    "pts": "+{p} pts",
    "week_of": "Gala del {d}",
    "aw_mvp": "MVP — Gato de la Semana",
    "aw_instancabile": "Incansable",
    "aw_cecchino": "Francotirador",
    "aw_dominatore": "Dominador",
    "d_mvp": "más victorias",
    "d_instancabile": "más combates",
    "d_cecchino": "mejor porcentaje",
    "d_dominatore": "racha más larga",
    "hof_striscia": "Racha Legendaria",
    "hof_veterano": "Veterano",
    "hof_recordman": "Récord de Victorias",
    "hof_winrate": "Mejor Porcentaje",
    "val_mvp": "{n} victorias",
    "val_instancabile": "{n} combates",
    "val_cecchino": "{n}%",
    "val_dominatore": "racha de {n}",
    "val_striscia": "{n} seguidas",
    "val_veterano": "{n} combates",
    "val_recordman": "{n} victorias",
    "val_winrate": "{n}%",
    "cer_title": "GRAN GALA DEL SÁBADO NOCHE",
    "cer_open": "🎩 Damas y caballeros… ¡bienvenidos a la Gala! Soy {host}, ¡y esta noche premiamos a los mejores gatos de la semana!",
    "cer_drumroll": "🥁 Redoble de ronroneos…",
    "cer_gold": "🥇 ¡La zarpa de oro es para… {name}, de {owner}!",
    "cer_silver": "🥈 Plata para {name}, de {owner}.",
    "cer_bronze": "🥉 Bronce para {name}, de {owner}.",
    "cer_pts": "✨ ¡+{p} puntos!",
    "cer_q_mvp": "¡El más ganador de todos!",
    "cer_q_instancabile": "¡No paró ni un momento!",
    "cer_q_cecchino": "¡Preciso como un francotirador!",
    "cer_q_dominatore": "¡Vaya racha!",
    "cer_mvp_finale": "🌟 Y ahora el premio más deseado… ¡el Gato de la Semana!",
    "cer_close": "🎉 ¡Eso es todo por esta noche! Un aplauso para nuestros campeones. ¡Hasta el sábado que viene!",
    "cer_none": "Esta semana no hay premios: ¡pocas peleas! Volved al combate.",
    "btn_replay": "🎬 Volver a ver la gala",
    "btn_skip": "Saltar ▶▶",
    "cer_preview": "ANTICIPO — clasificación en curso",
    "pl_1": "La noche en que los gatos se hacen leyenda.",
    "pl_2": "Esmoquin, focos y ronroneos: ¡empezamos!",
    "pl_3": "Nueve vidas, un solo escenario.",
    "pl_4": "¿Quién se lleva la zarpa de oro?",
    "pl_5": "Pienso rojo y alfombra… también roja.",
    "pl_6": "Aplausos, confeti y algún arañazo.",
    "pl_7": "El sábado más elegante del barrio.",
    "pl_8": "Solo los gatos más duros suben al escenario.",
    "pl_9": "Luces, cámara… ¡miau!",
    "pl_10": "Esta noche premiamos a quien arañó más fuerte.",
    "place_1": "Primer puesto · Oro",
    "place_2": "Segundo puesto · Plata",
    "place_3": "Tercer puesto · Bronce",
    "full_mvp": "El gato con más victorias mundiales de la semana. Simplemente el mejor.",
    "full_instancabile": "Disputó más combates que nadie: nunca para, siempre en el ring.",
    "full_cecchino": "El mejor porcentaje de victorias (al menos 5 combates): precisión, no suerte.",
    "full_dominatore": "La racha de victorias consecutivas más larga de la semana.",
    "react_1": "¡Vaya zarpazo!",
    "react_2": "¡Un aplauso! 👏",
    "react_3": "¡Piel de gallina!",
    "react_4": "¡Todo un fenómeno!",
    "react_5": "¡Qué clase!",
    "react_6": "¡El público enloquece!",
    "cer_podium": "🏆 Y ahora… ¡el podio!",
    "cer_suspense": "🥁 …y el ganador es…",
    "cer_hall_intro": "🏛️ Y ahora… ¡los Récords de Siempre!",
    "cer_hall_hold": "Este récord sigue en pie. ¡Qué campeón!",
    "cer_record_broken": "¡Nuevo récord! ¡{name} entra en la leyenda!",
    "rec_new": "¡NUEVO RÉCORD!",
    "aw_inlizza": "en liza",
    "cont_title": "Los perseguidores",
    "cer_contenders": "Y ojo con estos: ¡a un bigote del podio!",
    "notif_win": "🏆 ¡Ganaste {list}! +{pts} puntos añadidos.",
    "notif_more": "y {n} más",
    "aw_ammazza": "Matagigantes",
    "d_ammazza": "la mayor sorpresa",
    "full_ammazza": "Venció a un rival muy superior en Elo: la sorpresa de la semana.",
    "cer_q_ammazza": "¡David contra Goliat!",
    "val_ammazza": "{n} de Elo de diferencia",
    "aw_beniamino": "El Favorito",
    "d_beniamino": "el más retado",
    "full_beniamino": "El gato al que más retaron los demás: toda una estrella.",
    "cer_q_beniamino": "¡Todos quieren retarlo!",
    "val_beniamino": "{n} retos recibidos",
    "aw_debuttante": "Novato de la Semana",
    "d_debuttante": "mejor carta nueva",
    "full_debuttante": "La mejor carta creada esta semana, por victorias.",
    "cer_q_debuttante": "¡Nacido para luchar!",
    "val_debuttante": "{n} victorias",
    "aw_astro": "Estrella emergente",
    "d_astro": "mayor subida de Elo",
    "full_astro": "Quien más Elo ganó esta semana: en ascenso.",
    "cer_q_astro": "¡Ascenso imparable!",
    "val_astro": "+{n} Elo",
    "aw_pantofolaio": "Perezoso",
    "d_pantofolaio": "el que menos luchó",
    "full_pantofolaio": "El premio en broma: entre los que lucharon, el menos activo.",
    "cer_q_pantofolaio": "¡El sofá lo llama!",
    "val_pantofolaio": "solo {n} combates",
    "hof_piccoelo": "Pico de Elo",
    "val_piccoelo": "{n} Elo",
    "hof_regno": "Reinado más largo",
    "val_regno": "{n} días",
    "hof_muro": "El Muro",
    "val_muro": "{n} defensas",
    "hof_pluricampione": "Multicampeón",
    "val_pluricampione": "{n} títulos",
    "hof_novevite": "Las Nueve Vidas",
    "val_novevite": "Sendero completo"
  },
  "gang": {
    "login": "Inicia sesión para usar los clanes.",
    "none_title": "🛡️ Los Clanes",
    "none_sub": "Únete a un clan o crea el tuyo. Juntos se lucha en equipo.",
    "create": "Crea tu clan",
    "name_ph": "Nombre del clan",
    "emblem": "Emblema",
    "create_btn": "🛡️ Crear clan",
    "board": "📋 Tablón — clanes existentes",
    "board_empty": "Aún no hay clanes. ¡Sé el primero!",
    "members_n": "{n} miembros",
    "cards_n": "{n} cartas",
    "apply": "Solicitar",
    "applied": "✅ Solicitud enviada",
    "full": "Lleno",
    "invites": "✉️ Tus invitaciones",
    "invited_by": "invitación de {who}",
    "accept": "Aceptar",
    "decline": "Rechazar",
    "members": "👥 Miembros",
    "leader": "👑 jefe",
    "roster": "🃏 Plantilla",
    "roster_empty": "Plantilla vacía. ¡Añade tus cartas!",
    "add_card": "➕ Añadir",
    "add_none": "No hay cartas para añadir",
    "remove": "Quitar",
    "apps": "📥 Solicitudes de ingreso",
    "apps_empty": "Sin solicitudes.",
    "approve": "Aceptar",
    "reject": "Rechazar",
    "leave": "🚪 Salir del clan",
    "disband": "💥 Disolver el clan",
    "leave_confirm": "¿Salir del clan?",
    "disband_confirm": "Eres el jefe: al salir el clan se disuelve. ¿Confirmas?",
    "created": "🛡️ ¡Clan creado!",
    "order_hint": "(el jefe puede reordenar con ▲▼)",
    "inv_title": "✉️ Invitar jugadores",
    "inv_browse": "🔎 Explorar jugadores",
    "invite_btn": "Invitar",
    "invited_lbl": "✅ Invitado",
    "no_free": "No hay jugadores libres para invitar.",
    "search_ph": "Buscar un clan…",
    "more": "Cargar más",
    "open_lbl": "Abierto",
    "closed_lbl": "🔒 Cerrado",
    "browse_others": "📋 Explorar otros clanes",
    "set_open": "🔓 Abrir el clan",
    "set_closed": "🔒 Cerrar el clan",
    "search_player": "Buscar un jugador…",
    "see_cards": "Ver cartas",
    "back": "Atrás",
    "no_cards": "Sin cartas publicadas.",
    "invite_sent": "✉️ ¡Invitación enviada!",
    "kick": "Expulsar",
    "kick_confirm": "¿Expulsar a este miembro del clan?",
    "joined_msg": "🛡️ ¡Te uniste a un clan!",
    "kicked_msg": "🚪 Ya no estás en el clan.",
    "changed_msg": "Tu clan ha cambiado.",
    "attack": "⚔️ Atacar",
    "war_won": "🏆 ¡Guerra ganada! +30 puntos de clan",
    "war_lost": "💥 Guerra perdida. +5 de consolación",
    "no_fresh": "No hay cartas frescas para alinear (están descansando).",
    "enemy_empty": "El clan rival no tiene cartas.",
    "pts": "pts",
    "war_confirm": "¿Atacar a {name}? Tus cartas descansarán una hora.",
    "pick_title": "Elige tu formación",
    "pick_desc": "Toca las cartas en orden (máx {n}). El ganador se queda.",
    "pick_go": "⚔️ Atacar ({n})",
    "def_hint": "Las primeras {n} cartas defienden el clan cuando te atacan.",
    "def_size_lbl": "Defensores:",
    "warlog_title": "Registro de guerras",
    "warlog_empty": "Aún no hay guerras.",
    "wl_attacked": "Atacaste a {name}",
    "wl_defended": "{name} te atacó",
    "wl_win": "Victoria",
    "wl_lose": "Derrota"
  }
};
