(window.LANG_DB=window.LANG_DB||{})["en"] = {
  "ui": {
    "tagline": "Snap your cat and turn it into a collectible card",
    "tab_crea": "📸 Create",
    "tab_carte": "📚 Cards",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 World",
    "tab_mercato": "🔁 Market",
    "tab_boss": "🤖 Bosses",
    "tab_pal": "🏋️ Gym",
    "tab_med": "🏅 Medals",
    "tab_reg": "📖 Rules",
    "drop_title": "Tap to take or upload a photo",
    "drop_sub": "JPG or PNG — best if the cat is clearly visible",
    "cat_name": "Cat's name (optional)",
    "gen_btn": "✨ Create the card",
    "dl_card": "⬇️ Download the card (PNG)",
    "regen_btn": "🔁 Redraw the art (30 points)",
    "new_card": "🔄 New card",
    "coll_title": "📚 Your collection",
    "dojo_title": "🥋 Dojo",
    "your_card": "Your card",
    "opponent": "Opponent",
    "fight_btn": "⚔️ Fight!",
    "tourn4": "🏆 4-cat tourney",
    "tourn8": "🏆 8-cat tourney",
    "albo": "📊 Hall of fame",
    "pub_sum": "🗂️ Choose which cards to publish to the World",
    "player_name": "Your player name (required, min 3 letters)",
    "pub_btn": "📤 Publish selected cards",
    "duel_title": "⚡ Challenge a friend",
    "duel_champ": "Your champion for the duel",
    "qr_show": "📱 Show my QR",
    "qr_scan": "📷 Scan theirs",
    "world_title": "🌍 World Arena",
    "my_world": "🐱 Your cards in the world",
    "my_online": "Your card for online matches",
    "find_btn": "🔄 Find challengers worldwide",
    "leader_title": "🏅 World ranking",
    "leader_more": "⬇️ Show more ranks",
    "market_title": "🔁 Market",
    "trade_title": "🔄 Trade (barter)",
    "trade_browse": "🔍 Browse cards to trade",
    "trader_ask": "💰 Ask the Merchant for advice",
    "auc_title": "⚖️ Auctions",
    "auc_create": "🔨 Put a card up for auction",
    "auc_refresh": "🔄 Refresh auctions",
    "boss_title": "🤖 Arena Bosses",
    "boss_chall": "Your challenger (published cards)",
    "gym_title": "🏋️ Gym",
    "gym_student": "Today's student",
    "gym_pantry": "🍽️ Pantry — buy, then earn it in the minigame",
    "coach_ask": "🎓 Ask the Coach for advice",
    "mis_title": "📅 Today's missions",
    "med_title": "🏅 Medal collection",
    "reg_title": "📖 CatCards rules",
    "opt_title": "⚙️ Options",
    "locked_title": "Sign-in required",
    "locked_txt": "Points, Market, matches and training live on your account: sign in to use Dojo, World, Market, Bosses and Gym.",
    "login_google": "🔵 Sign in with Google",
    "login_hint": "Sign in: points, Market and matches live on your account",
    "logout": "Sign out",
    "close": "✖ Close",
    "skip_intro": "⏭️ Skip the intro",
    "bet_title": "🥊 Uncle Rocco's corner",
    "bet_sub": "🎲 Betting",
    "bet_skip": "No bet, on with the match!",
    "bet_back": "↩️ Go back (cancel the match)",
    "points_lbl": "💰 Your points:",
    "dl_short": "⬇️ Download",
    "nick_btn": "✏️ Change nickname",
    "theme_btn": "▶️ Play theme song",
    "retire_btn": "🚪 Retire from the world",
    "frame_btn": "🎨 Golden Frame (100 points)",
    "del_btn": "🗑️ Delete",
    "coach_greet": "Meow, recruit. Pick a trainee and let's get to work.",
    "gym_combo": "🌟 Premium Combo — two stats, a single rest",
    "bet_choose": "Choose your stake and who to bet on. If you're wrong, you lose the stake.",
    "bet_insufficient": "Not enough points to bet (minimum 10).",
    "tab_sent": "🗺️ Path",
    "opt_ai_sum": "🤖 AI settings",
    "opt_key_label": "Gemini API key",
    "opt_test_key": "🧪 Test the key",
    "opt_backup_label": "Collection backup",
    "opt_export": "💾 Export backup",
    "opt_import": "📂 Import backup",
    "opt_gift_label": "🎁 Gift code",
    "opt_redeem": "Redeem points",
    "opt_av_label": "Audio and intros",
    "snd_on": "🔊 Sound: ON",
    "snd_off": "🔇 Sound: OFF",
    "pres_on": "🎬 Intros: ON",
    "pres_skip": "⏭️ Intros: SKIPPED",
    "bt_bracket": "📋 Bracket",
    "qr_desc1": "Live duel, phone against phone: it counts for points, medals and bets like a world match.",
    "qr_desc2": "One shows the QR, the other scans it: the duel plays out on the scanner's phone.",
    "coll_one": "1 saved card",
    "coll_many": "{n} saved cards",
    "coll_none": "No cards yet: create one in the 📸 Create tab, or import a backup from ⚙️ Options.",
    "xp_line": "📈 Level {lvl} — {inLvl}/100 XP (≈ {w} world wins to Lv.{next})",
    "opt_ai_desc": "Without an API key I use a built-in free cartoon filter. With a <strong>Google Gemini</strong> key the cartoon is AI-generated (much higher quality). Create one free at <strong>aistudio.google.com</strong> → «Get API key».",
    "tab_award": "🏆 Awards",
    "publish_btn": "🌍 Publish to the World",
    "pub_moved": "To publish or retire a card, tap it in the 📚 Cards tab.",
    "ask_name_title": "What’s your name?",
    "ask_name_desc": "The name challengers will see (min 3 letters).",
    "ask_name_ok": "Save & publish",
    "ask_name_cancel": "Cancel",
    "hub_fight": "Fight",
    "hub_cards": "Cards",
    "hub_glory": "Glory",
    "hub_social": "Social",
    "tab_opz": "⚙️ Settings",
    "tab_gang": "🛡️ Gang",
    "in_clan": "In {name}",
    "withdraw_clan": "Withdraw",
    "withdraw_confirm": "Withdraw this card from the clan?",
    "withdraw_done": "Card withdrawn from the clan.",
    "tab_terr": "🗺️ Territory"
  },
  "stat": {
    "Forza": "Strength",
    "Intelligenza": "Intelligence",
    "Destrezza": "Agility",
    "Velocità": "Speed",
    "Fascino": "Charm",
    "Indifferenza": "Aloofness"
  },
  "rarity": {
    "Comune": "Common",
    "Rara": "Rare",
    "Epica": "Epic",
    "Leggendaria": "Legendary"
  },
  "ann": {
    "red": "From the red corner... {n}... \"{k}\"!",
    "blue": "From the blue corner... {n}... \"{k}\"!"
  },
  "nicks": {
    "n01": "The Tin-Can Socrates",
    "n02": "Baron Crookfang",
    "n03": "The Ember Colossus",
    "n04": "The Asphalt Gladiator",
    "n05": "The Sleeping Softcheese",
    "n06": "The Fleece Monolith",
    "n07": "The Zen Master Licker",
    "n08": "The Unshakable Zen",
    "n09": "The Immovable Soft Fortress",
    "n10": "The Beyond-the-Couch Radar",
    "n11": "The Mischief Radar",
    "n12": "His Hypnotic Softness",
    "n13": "The Purring Veteran",
    "n14": "The Sad Feline Hypnotist",
    "n15": "The Silk Panzer",
    "n16": "The Flaming Muffler",
    "n17": "The Hypnotic Puffball",
    "n18": "The Ginger Claw",
    "n19": "The Centerpiece Blimp",
    "n20": "The Bastion of Fur",
    "n21": "The Steel Cheek",
    "n22": "The Couch Phantom",
    "n23": "The Understairs Fury",
    "n24": "The Fur Tornado",
    "n25": "The Pantry Shadow",
    "n26": "The Windowsill Ninja",
    "n27": "The Tawny Avalanche",
    "n28": "The Curtain Assassin",
    "n29": "The Terror of Yarn Balls",
    "n30": "The Lazy Locomotive",
    "n31": "The Radiator Philosopher",
    "n32": "The Hurricane in Slippers",
    "n33": "The Living-Room Cheetah",
    "n34": "The Refrigerator Sphinx",
    "n35": "The Sly Lightning",
    "n36": "The Killer Pillow",
    "n37": "The Balcony Beast",
    "n38": "General Scratch",
    "n39": "The Midnight Acrobat",
    "n40": "The Sultan of Naps",
    "n41": "The Carpet Tiger",
    "n42": "The Staircase Ghost",
    "n43": "The Couch Destroyer",
    "n44": "The Landing Panther",
    "n45": "The Baron of Morsels",
    "n46": "The Emperor of the Basket",
    "n47": "The Fresh-Fish Pirate",
    "n48": "The Plush Thunderbolt",
    "n49": "The Kibble Champion",
    "n50": "The Attic Strategist",
    "n51": "The Slipper Monster",
    "n52": "The Clawed Duchess",
    "n53": "The Velvet Viking",
    "n54": "The Whiskered Enigma",
    "n55": "The Silent Cyclone",
    "n56": "The Paw of Destiny",
    "n57": "The Cardboard King",
    "n58": "The Permanent Ambush",
    "n59": "The Soft Meteorite",
    "n60": "The Courtyard Legend",
    "n61": "The Bowl Guardian",
    "n62": "The Eye of the Night",
    "n63": "The Scruffy Samurai",
    "n64": "The Tricolor Fury",
    "n65": "The Professor of Ambushes",
    "n66": "The Admiral of the Rooftops",
    "n67": "The Steamroller",
    "n68": "The Elegant Pest",
    "n69": "The Sleepy Volcano",
    "n70": "The Velvet Claw",
    "n71": "The Kitchen Bandit",
    "n72": "The Fridge Sentinel",
    "n73": "The Cushion Dragon",
    "n74": "The Echo of the Meow",
    "n75": "The Master of Purrs",
    "n76": "The Pocket Tempest",
    "n77": "The Gentle Giant",
    "n78": "The Last Stray",
    "n79": "The Lizard Hunter",
    "n80": "The Ninth Life"
  },
  "descrs": {
    "d01": "Sleeps 20 hours a day and spends the other 4 training to sleep better.",
    "d02": "Has never lost a battle against a sock.",
    "d03": "Believes the refrigerator owes him an explanation.",
    "d04": "Master of the art of occupying exactly where you wanted to sit.",
    "d05": "Knocked over three vases. All of them guilty.",
    "d06": "Speaks three languages: purr, meow and contempt.",
    "d07": "Runs at 4 a.m. for reasons beyond our understanding.",
    "d08": "A born warrior, as long as the couch is within two meters.",
    "d09": "His bowl is half empty. Always. Even when full.",
    "d10": "Stares at the wall because the wall started it.",
    "d11": "Former stray, now a senior executive of napping.",
    "d12": "Purrs like a tractor and scratches like a razor.",
    "d13": "The vet still remembers him in his nightmares.",
    "d14": "Doesn't chase mice: serves eviction notices.",
    "d15": "Can open three kinds of doors and pretends he can't.",
    "d16": "The box is worth more than the gift. Always.",
    "d17": "Holds a PhD in judgmental stares.",
    "d18": "Fights crime. The crime is the vacuum cleaner.",
    "d19": "Every chair in the house is his. Including yours.",
    "d20": "Trains on the curtains when nobody's watching.",
    "d21": "Favorite hobby: elegantly knocking things off tables.",
    "d22": "Meows in C minor when the bowl is empty.",
    "d23": "No one ever sees him coming. Only leaving with dinner.",
    "d24": "Weighs exactly enough to pin your legs down.",
    "d25": "The neighborhood lizards have put a bounty on him.",
    "d26": "Sleeps in positions that defy physics and common sense.",
    "d27": "Figured out the laser pointer. Pretends otherwise out of pity.",
    "d28": "A cross between a pillow and a bear trap.",
    "d29": "Surveys the neighborhood from the window like a head of state.",
    "d30": "His purrs cure stress. His claws cause it.",
    "d31": "Eats like a wolf, sleeps like a rock, reigns like a king.",
    "d32": "The only cat who ever won an argument with a cucumber.",
    "d33": "Gets offended if you look at him. Gets offended if you don't.",
    "d34": "Has three secret hideouts. The best one: the middle of the hallway.",
    "d35": "Fell into a bowl of cream as a kitten. Never recovered.",
    "d36": "Teaches yoga to neighborhood cats. Lesson one: ignore everyone.",
    "d37": "The mailman requested a transfer.",
    "d38": "Collects hair ties. Nobody knows where he hides them.",
    "d39": "When a storm hits, he protects the house. From under the bed.",
    "d40": "His stare has scared off two dogs and a plumber.",
    "d41": "Lives for three things: eating, sleeping and judging you.",
    "d42": "Once saw a mouse. They both still talk about it.",
    "d43": "Extremely elegant until he falls off the windowsill.",
    "d44": "Adopted a family of humans. Training them well.",
    "d45": "He doesn't climb on the table. The table lowers itself to him.",
    "d46": "Knows exactly when you open the tuna. Even from a block away.",
    "d47": "The yarn ball was already like that when he got there.",
    "d48": "Half cat, half 5 a.m. alarm siren.",
    "d49": "Fights with honor, wins with style, sleeps without shame.",
    "d50": "The last thing carpets see before the end."
  },
  "battle": {
    "skip": "⏭️ Intro skipped: straight to the action!",
    "open": "🎤 LADIES AND GENTLEMEEEN… welcome to the CatCards Arena!",
    "red": "🔴 Red corner: {NAME}, «{nick}»! {rec}",
    "blue": "🔵 Blue corner: {NAME}, «{nick}»! {rec}",
    "debut": "Making an arena debut!",
    "theme": "🎵 {name}'s entrance theme plays…",
    "ding": "🔔 DING DING DING!",
    "first_fast": "⚡ {name} is faster and strikes first!",
    "first_surprise": "😼 {name} surprises everyone and goes first!",
    "round_end": "🔔 End of round {round}! The cats return to their corners to lick their fur…",
    "charmed_skip": "😍 {name} is charmed and loses the turn!",
    "chant": "🎺 From the stands: «{NAME}! {NAME}!»",
    "pu_yarn": "🧶 A ball of yarn rolls into the arena! {name} plays with it and recovers {hp} HP",
    "pu_catnip": "🌿 Catnip in the arena! {name} is buzzing: next hit DOUBLED (but a bit woozy…)",
    "pu_box": "📦 A cardboard box! {name} can't resist and climbs in: skips the turn but is UNTOUCHABLE!",
    "pu_fish": "🐟 A fresh fish flies into the arena! {name} darts with energy: +agility for 3 turns",
    "purr_heal": "💗 {name} purrs and recovers {hp} HP",
    "double_paw": "🐾 Double Paw Strike! {name} attacks again!",
    "box_dodge": "📦 {opp} is hidden in the box: {name}'s hit misses!",
    "dodge": "💨 {name} tries {move} but {opp} dodges!",
    "final_blow": "⏱️ Time slows down… FINAL BLOW!",
    "hit": "{icon} {name} uses {move}!{crit}{catnip}  −{dmg} HP",
    "crit_tag": " 💥 CRITICAL!",
    "catnip_tag": " 🌿 BOOSTED!",
    "dev1": "😱 Devastating hit!",
    "dev2": "🎙️ The crowd goes wild!",
    "dev3": "💢 What crushing power!",
    "on_fire": "🔥 {name} is ON FIRE! Three hits in a row!",
    "on_ropes": "🎙️ {opp} is on the ropes! The crowd holds its breath…",
    "clever": "✨ Clever move! {opp} is confused and will lose a turn!",
    "nine_lives": "🐈 {opp} uses one of its Nine Lives and stays up with 1 HP!",
    "charm_hit": "✨ {opp} is charmed by {name}'s charm!",
    "replay": "📹 REPLAY of the final blow…",
    "winner": "🏆 {name} wins the fight!",
    "win_points": "💰 +10 points for the win!",
    "boss_points": "💰 +10 points: you tamed an Arena Boss!",
    "boss_noprize": "🎖️ Boss already beaten today: glory yes, prize tomorrow.",
    "boss_survives": "🤖 The Boss stays standing... today's attempt is gone: see you tomorrow (maybe with catnip 🌿).",
    "tourn_champ": "👑 {name} is the tournament CHAMPION!",
    "world_ok": "🌍 Result recorded in the World Arena!",
    "bet_win": "🎲 Right call! You bet {stake} on {name}: +{gain} points (total: {total})",
    "bet_lose": "🎲 Wrong call: −{stake} points (total: {total}). Better luck next time!",
    "stake": "🎁 At stake — win: {win} · loss: +{lose} XP",
    "stake_pts": "+{pt} points and +{xp} XP",
    "stake_nopts": "+{xp} XP (no points locally)",
    "boss_stake_note": " — points only on the first win of the day",
    "entry_catnip": "🌿 {name} enters the arena already loaded with catnip!"
  },
  "chars": {
    "rocco_warn": "Watch his {stat}: that's where he eats you alive.",
    "rocco_70": "Kid, you'll drop this one before the bell. Don't get cocky — finish it fast.",
    "rocco_55": "You're the favorite, but favorites who sleep hit the canvas. Strike first.",
    "rocco_50": "Fifty-fifty, kid: this goes to whoever's hungrier. If you've got 50 points, the catnip's worth every one.",
    "rocco_35": "I won't lie: he's bigger than you. Without catnip I wouldn't take this fight.",
    "rocco_lose": "Listen to old Rocco: this one breaks you. Back to the gym, gain a level, THEN we talk. If you must fight, at least take the catnip.",
    "baratto_great": "🤑 Steal of a deal! You get way more than you give — close it fast.",
    "baratto_good": "👍 Good deal: you come out ahead. The Merchant approves.",
    "baratto_even": "⚖️ Even trade: decide with your heart, not your wallet.",
    "baratto_bad": "😾 You lose a little... sure about this? The Merchant twitches his whiskers.",
    "baratto_terrible": "🙀 Terrible deal! You give far more than you get. Forget it.",
    "baratto_empty": "No cards to barter! Make some and come back: the bazaar's for deals, not charity.",
    "inc_100a": "A HUNDRED POINTS! Magnificent madness! 😼",
    "inc_100b": "A kingly bid! And who dares raise it now?",
    "inc_50a": "Fifty! The crowd is trembling, ladies and gentlemen!",
    "inc_50b": "Fine sum! The auction's heating up!",
    "inc_bata": "And another raise! They just won't stop!",
    "inc_batb": "A battle to the last point — what a show!",
    "inc_starta": "First bid on the block! Who gives more?",
    "inc_startb": "Here we go! Sold to whoever won't quit!",
    "baffo_open": [
      "Meow, recruit! ",
      "Listen to old Baffo: ",
      "Spit out that kibble and listen: ",
      "In my day, no soft cushions. ",
      "Whiskers straight, ears up: "
    ],
    "baffo_empty": "The gym is empty! Bring me a student from the 📸 Create tab.",
    "baffo_indiff_afford": "{name}'s weak spot is {stat} ({val}): train it with the {combo} combo (60 points) — you can afford it.",
    "baffo_indiff_save": "{name}'s weak spot is {stat} ({val}), but it only trains with the {combo} combo (60 points): you're {miss} short — save up.",
    "baffo_indiff_alt": " Or meanwhile boost {stat2} ({val2}) with {food} (25 points).",
    "baffo_weak": "{name}'s weakest stat is {stat} ({val}): give it {food}.",
    "baffo_combo": "You have {pts} points: the {combo} combo ({tgt}) grows two things in a single rest — pricey but handy if you're in a hurry.",
    "baffo_record_bad": "With {w} wins and {l} losses, he needs grit, not cuddles.",
    "baffo_unbeaten": "He's unbeaten: just don't let him get a big head.",
    "baffo_margin": "Training margin used up: only World wins unlock more progress.",
    "baffo_broke": "And the coffers are dry ({pts} points): win a few World bets.",
    "baffo_fit": "{name} is in top shape. Send him to fight — the bench softens the muscles.",
    "felini_open": [
      "Listen to the Manager: ",
      "I smell a deal: ",
      "The ring is a chessboard: ",
      "The numbers talk, kid: "
    ],
    "felini_checking": "One moment, let me check the records…",
    "felini_noauth": "Sign in first, kid: business needs a name on the contract.",
    "felini_nocard": "You haven’t got a champion in the ring. Publish a card and let’s talk business.",
    "felini_resting": "😴 {name} is recovering: come back when it’s ready again and we’ll talk strategy.",
    "felini_norank": "Your champion isn’t in the rankings: republish it and come back to me.",
    "felini_loss_streak": "{name} has lost {n} in a row (🧊): pull it off the circuit for a while, take it to the Coach, and bring it back hungry.",
    "felini_champ": "{name} is the CHAMPION 👑: defend the crown{chaser}.",
    "felini_chaser": ", and watch out for {name} (#2, {elo} pts) who’s champing at the bit",
    "felini_target": "the right next bout for {name} (#{rk}) is {tname} owned by {owner} (#{trk}, {elo} pts): {verdict}",
    "felini_v_risky": "risky, but beat it and you make a killing in the standings.",
    "felini_v_beatable": "on paper it’s beatable: a manager’s win.",
    "felini_v_even": "an even bout, the kind the crowd loves.",
    "felini_prob_low": "But let’s be clear: Uncle Rocco puts your win odds at just {p}%. I’d wait — gym, one more level, THEN we sign the contract.",
    "felini_prob_mid": "The odds say {p}%: an open match, nerves will decide it (and maybe some catnip 🌿).",
    "felini_prob_high": "Uncle Rocco reckons a {p}% win chance: within reach. Go and close the match.",
    "felini_belt": "And remember: that one holds the BELT 👑 — the ranking means nothing, beat it and YOU’re the champion.",
    "felini_hot": "Careful though: it’s a tough opponent, riding a streak of {n} wins 🔥.",
    "felini_cold": "And I’ll tell you: it’s in a deep slump (🧊 {n} losses in a row) — the perfect moment to strike.",
    "felini_catnip_need": "My ringside advice: invest 50 points in catnip 🌿 before the match — against one like that you need the turbo.",
    "felini_catnip_broke": "You’d want catnip 🌿, but the coffers are crying ({pts} points): either find points, or pick a softer target.",
    "felini_catnip_opt": "Catnip 🌿? Optional: an even match, nerves will decide.",
    "felini_catnip_no": "No catnip: it’ll manage on its own paws, save your points.",
    "felini_notarget": "no target from other owners above you right now (or they’re all resting): defend your position, or check back later.",
    "felini_margin": "And it still has {n} points of gym margin left: a good meal before the match never hurt anyone.",
    "trader_open": [
      "Psst, friend: ",
      "Deals, deals! ",
      "The Merchant knows all: ",
      "Between us who know our stuff: "
    ],
    "trader_best": "hold on tight to {name}, that one’s worth gold: don’t give it up for pennies.",
    "trader_worst": "if you really must trade something, start with {name} — you’ve got better in hand.",
    "trader_commons": "You’ve got a pile of {rar} cards ({n}): trade a couple for something rarer, trust me.",
    "trader_gem": "And watch out: there’s a {rar} from {owner} on the shelf — if you’ve got a good spare, try the trade before someone else grabs it.",
    "trader_browse": "Hit «Browse cards to trade» and show me what’s around: I’ll tell you if there’s a deal.",
    "rocco_catnip": "🌿 Good lad. Now get in there and show them: the first hit will be a freight train.",
    "baffo_all_rest": "😴 All your trainees are resting: come back when one is ready and we'll get to work."
  },
  "titles": {
    "world": "WORLD MATCH",
    "live": "LIVE DUEL",
    "boss": "ARENA BOSS",
    "quarti": "QUARTERFINALS",
    "semi": "SEMIFINAL",
    "finale": "FINAL",
    "sentiero": "THE PATH"
  },
  "gym": {
    "lbl_allena": "Trains:",
    "lbl_start": "▶️ Start the workout!",
    "fn_croc": "Kibble",
    "fn_pollo": "Chicken",
    "fn_topo": "Little Mouse",
    "fn_erba": "Catnip",
    "fn_pesce": "Fish",
    "fn_chicche": "Treats",
    "fn_bistecca": "Warrior's Steak",
    "fn_scarica": "Feline Surge",
    "fn_fascino": "Fatal Charm",
    "fn_trono": "Feather Throne",
    "ft_croc": "❤️ HP",
    "ft_pollo": "💪 Strength",
    "ft_topo": "🧠 Intelligence",
    "ft_erba": "🎯 Agility",
    "ft_pesce": "⚡ Speed",
    "ft_chicche": "✨ Charm",
    "ft_bistecca": "💪 Strength + ❤️ HP",
    "ft_scarica": "⚡ Speed + 🎯 Agility",
    "ft_fascino": "✨ Charm + 🧠 Intelligence",
    "ft_trono": "😼 Aloofness + ❤️ HP",
    "gn_gomitolo": "Catch the Yarn Ball",
    "gn_topo": "Mouse Hunt",
    "gn_piuma": "Follow the Feather",
    "gn_corda": "Tug of War",
    "gn_porta": "Break the Door",
    "gn_laser": "Laser Chase",
    "gn_memory": "Can Memory",
    "gn_pesca": "Quick Fishing",
    "gn_scatto": "Feline Sprint",
    "gn_scalata": "Bookshelf Climb",
    "gn_fusa": "Purr Rhythm",
    "gn_sfilata": "The Catwalk",
    "gn_zen": "Cat Zen",
    "gn_sguardi": "Staring Contest",
    "ga_gomitolo": "Agility — 🌿 catnip (Agility) and 🐟 fish (Speed)",
    "ga_topo": "Physique — 🍗 chicken (Strength) and 🥫 kibble (HP)",
    "ga_piuma": "Mind — 🐁 little mouse (Intelligence) and 🧀 treats (Charm)",
    "ga_corda": "Strength — 🍗 chicken (Strength)",
    "ga_porta": "Strength — 🍗 chicken (Strength)",
    "ga_laser": "Agility — 🌿 catnip (Agility)",
    "ga_memory": "Intelligence — 🐁 little mouse (Intelligence)",
    "ga_pesca": "Speed — 🐟 fish (Speed)",
    "ga_scatto": "Speed — 🐟 fish (Speed)",
    "ga_scalata": "HP — 🥫 kibble (HP)",
    "ga_fusa": "Charm — 🧀 treats (Charm)",
    "ga_sfilata": "Charm — 🧀 treats (Charm)",
    "ga_zen": "Aloofness — 🛋️ royal cushion (Aloofness)",
    "ga_sguardi": "Aloofness — 🛋️ royal cushion (Aloofness)",
    "gd_gomitolo": "The yarn ball darts around the box and speeds up with every catch: tap it as many times as you can in <strong>10 seconds</strong>.<br>🚫 Fewer than 5 catches: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_topo": "Mice pop out of their holes and vanish at once: hit them the moment they appear, for <strong>15 seconds</strong>.<br>🚫 Fewer than 5 hits: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_piuma": "The colored feathers flash in sequence: repeat it by tapping them in the same order. Each round the sequence gets longer; one mistake ends the workout.<br>🚫 Fewer than 3 rounds: food wasted · ✅ 3-4: bonus ×1 · 🌟 5+: bonus ×2",
    "gd_corda": "Hammer the <strong>PULL</strong> button to drag the big dog past the line: he keeps tugging back, don't let go for <strong>10 seconds</strong>.<br>🚫 Fewer than 8 tugs: food wasted · ✅ 8-15: bonus ×1 · 🌟 16+: bonus ×2",
    "gd_porta": "The power bar zips back and forth: tap when it's in the <strong>green zone</strong> to charge the paw strike. Hit as hard as you can in <strong>12 seconds</strong>.<br>🚫 Fewer than 5 good hits: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_laser": "The red dot appears and vanishes ever faster: tap it before it fades, for <strong>12 seconds</strong>.<br>🚫 Fewer than 6 catches: food wasted · ✅ 6-11: bonus ×1 · 🌟 12+: bonus ×2",
    "gd_memory": "Flip the cards two at a time and match the identical pairs from memory, in <strong>30 seconds</strong>.<br>🚫 Fewer than 3 pairs: food wasted · ✅ 3-4: bonus ×1 · 🌟 5+: bonus ×2",
    "gd_pesca": "The fish darts underwater and surfaces only for an instant: tap it <strong>right when it jumps out</strong>. The windows get shorter. You have <strong>14 seconds</strong>.<br>🚫 Fewer than 5 catches: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_scatto": "Wait for <strong>green</strong> and tap as fast as you can: it measures your reflex. 5 rounds — jump the gun and you lose the round.<br>🚫 Fewer than 2 good sprints: food wasted · ✅ 2-3: bonus ×1 · 🌟 4+: bonus ×2",
    "gd_scalata": "The cat leaps from shelf to shelf: tap <strong>when the platform is aligned</strong> to jump onto it. One wrong jump and you fall. Climb as high as you can.<br>🚫 Fewer than 5 shelves: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_fusa": "The ring shrinks in time: tap <strong>when it reaches the target</strong>, to the rhythm of the purr. The more precise you are, the faster the beat.<br>🚫 Fewer than 5 on-beat taps: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_sfilata": "An arrow appears on the runway: <strong>swipe in its direction</strong> to strike the pose. The arrows come faster and faster, you have <strong>16 seconds</strong>.<br>🚫 Fewer than 6 poses: food wasted · 🌟 12+: bonus ×2",
    "gd_zen": "The discipline of aloofness: <strong>ignore every distraction</strong> (🐭 mouse, 🪶 feather, 🔴 laser) and tap <strong>only the cushion 🛋️</strong> when it appears. Touching a distraction loses you the round. You have <strong>14 seconds</strong>.<br>🚫 Fewer than 5 cushions: food wasted · ✅ 5-9: bonus ×1 · 🌟 10+: bonus ×2",
    "gd_sguardi": "<strong>Hold down</strong> and don't move: whoever stays impassive wins. But if a 😹 tickle appears you must <strong>let go at once</strong>, then press again. Hold out as long as you can.<br>🚫 Fewer than 8 seconds of composure: food wasted · ✅ 8-13: bonus ×1 · 🌟 14+: bonus ×2",
    "tr_wasted_h": "🙀 Food wasted!",
    "tr_wasted_b": "Score: <strong>{score}</strong> — below the minimum threshold.<br><br>{ic} The {food} went to waste and {name} now rests for an hour.<br><br>😼 <em>«In my day we trained blindfolded.»</em>",
    "tr_coach_wasted": "🙀 Only {score} points?! Food wasted.",
    "tr_perfect_h": "🌟 Perfect workout!",
    "tr_ok_h": "✅ Workout complete!",
    "tr_bonus2": " — bonus doubled!",
    "tr_online": "🌍 Card also updated in the World Arena.<br>",
    "tr_body": "Score: <strong>{score}</strong>{bonus}<br><br><span style=\"font-size:1.3rem;\">{ic} <strong>{gain}</strong> for {name}</span><br><br>{online}😴 Now an hour of rest: muscles grow while sleeping.",
    "tr_coach_perfect": "😼 {score} points! {name} has the makings of a champion.",
    "tr_coach_ok": "👍 {score} points, honest work. {name} is growing.",
    "gi_none": "No trainee: create a card first.",
    "gi_info": "Lv.{lv} · training margin: <strong>{used}/{cap}</strong> used <span style=\"color:var(--muted)\">(+3 per level: you level up by winning in the world)</span>",
    "gi_resting": "<br>😴 Resting: come back in {min} minutes",
    "gi_ready": "<br>✅ Ready to train!",
    "gi_nofood": "😼 The Coach: «No food for {name}: training margin used up. Win matches to level up (+3 margin per level), then it's back to the table.»",
    "gi_pick_opt": "— pick a trainee —",
    "gi_pick": "👉 Pick a trainee above to get started.",
    "gi_pick_alert": "Pick a trainee from the menu above first."
  },
  "powers": {
    "pn_0": "Nine Lives",
    "pn_1": "Perfect Ambush",
    "pn_2": "Regenerating Purrs",
    "pn_3": "Double Paw",
    "pn_4": "Liquid Mode",
    "pn_5": "Hypnotic Gaze",
    "pn_6": "Armor of Laziness",
    "pn_7": "Feline Chaos",
    "pd_0": "the first time it's knocked out it stays at 1 HP",
    "pd_1": "its first attack is always a critical",
    "pd_2": "recovers HP on each of its turns",
    "pd_3": "25% chance to attack twice",
    "pd_4": "dodges far more often",
    "pd_5": "charms with double the chance",
    "pd_6": "takes 20% less damage",
    "pd_7": "its damage is unpredictable (x0.5–x2)"
  },
  "prog": {
    "m_world1": "Win 1 world match",
    "m_world2": "Win 2 world matches",
    "m_fight3": "Fight 3 bouts (local ones count too)",
    "m_tourn": "Win a tournament (4 or 8)",
    "m_upset": "The Upset: beat an opponent with higher Elo than yours in the world",
    "m_train1": "Complete a successful workout",
    "m_gom10": "Score 10+ in Catch the Yarn Ball",
    "m_topo10": "Score 10+ in Mouse Hunt",
    "m_piuma5": "Reach 5 rounds in Follow the Feather",
    "m_boss": "Tame an Arena Boss",
    "m_bet": "Win a bet",
    "m_catnip": "Win a match starting with catnip",
    "m_card": "Create a new card",
    "m_qr": "Play a live duel (QR)",
    "a_prima_carta_nm": "First card",
    "a_prima_carta_ds": "Create your first card",
    "a_coll5_nm": "Collector",
    "a_coll5_ds": "5 cards in your collection",
    "a_coll10_nm": "Serial Cat Lover",
    "a_coll10_ds": "10 cards in your collection",
    "a_epica_nm": "What rarity!",
    "a_epica_ds": "Get an Epic card",
    "a_legg_nm": "Legendary!",
    "a_legg_ds": "Get a Legendary",
    "a_win1_nm": "First win",
    "a_win1_ds": "Win a world match",
    "a_win10_nm": "Veteran",
    "a_win10_ds": "Win 10 world matches",
    "a_win50_nm": "Legend",
    "a_win50_ds": "Win 50 world matches",
    "a_t4_nm": "Champion",
    "a_t4_ds": "Win a 4-cat tournament",
    "a_t8_nm": "Dominator",
    "a_t8_ds": "Win an 8-cat tournament",
    "a_pub_nm": "In the world",
    "a_pub_ds": "Publish a card",
    "a_wwin_nm": "Hat-trick",
    "a_wwin_ds": "Win 3 world matches in a row",
    "a_bet_nm": "Bookmaker",
    "a_bet_ds": "Win a bet",
    "a_ricco_nm": "Rich",
    "a_ricco_ds": "Own 150 points",
    "a_onore_nm": "Honorable retirement",
    "a_onore_ds": "Retire a card with a winning record",
    "a_disfatta_nm": "Rout",
    "a_disfatta_ds": "Lose 10 world matches in a row",
    "bm_ds": "Defeat {name} (Div. {tier})",
    "bmall_nm": "Boss Slayer",
    "bmall_ds": "Defeat all 64 Arena Bosses",
    "cx_rar4": "The full house: one card for each rarity",
    "cx_razze3": "Discover 3 different breeds",
    "cx_razze5": "Discover 5 different breeds",
    "cx_razze10": "Discover 10 different breeds",
    "cx_pot4": "Collect 4 different special powers",
    "cx_pot8": "Collect all 8 special powers",
    "cx_lv5": "Take a cat to level 5",
    "cx_hp100": "A card with 100+ HP",
    "cx_oro": "A card with the Gold Frame",
    "p_done": "done",
    "p_won": "✓ earned",
    "p_towin": "🔒 to earn",
    "p_howto": "How to get it:",
    "p_reward": "Reward:",
    "p_unlocked": "Unlocked on",
    "cx_open": "(tap to open)",
    "cx_h_rar": "💎 Rarity",
    "cx_h_pow": "🌟 Special powers",
    "cx_h_breeds": "🐱 Breeds discovered",
    "cx_nobreeds": "None yet: the breed comes from the AI photo analysis.",
    "cx_h_objs": "🎯 Objectives",
    "cx_sum": "🃏 Catdex — <strong>{done}/{tot}</strong> objectives <span class=\"count\">{open}</span>",
    "cx_toast": "🃏 Catdex: {ic} {txt}! +{pt} points",
    "mis_tris_line": "🎉 Trio done: +10 bonus points collected. See you tomorrow!",
    "mis_toast_tris": "🎉 TRIO! Mission «{txt}» and full day: +5 and +10 bonus!",
    "mis_toast_done": "📅 Mission complete: {ic} {txt}! +5 points",
    "med_toast": "🏅 Medal unlocked: {ic} {nm}! +{pt} points",
    "bm_sum": "🤖 Bosses tamed — <strong>{done}/{tot}</strong> <span class=\"count\">{open}</span>",
    "a_sentiero_done_nm": "Wayfarer of the Nine Lives",
    "a_sentiero_done_ds": "Complete the whole Path (100 stages)"
  },
  "reg": {
    "r_h_cards": "🎴 The cards",
    "r_p_cards": "Photograph a cat and it becomes a card: the AI redraws it as a cartoon and analyzes its look and character to generate <strong>stats</strong> (a sturdy tomcat will have more Strength), <strong>breed</strong>, <strong>description</strong>, <strong>special power</strong> and <strong>3 moves</strong> (💥 powerful but inaccurate, ⚡ fast and almost unfailing, ✨ cunning and can confuse). The <strong>rarity</strong> is drawn from the photo's fingerprint: 55% Common, 28% Rare, 13% Epic, 4% Legendary (Epics and Legendaries shine and have bonus stats). The same photo always gives the same card.",
    "r_h_xp": "⭐ Experience and levels",
    "r_p_xp": "Cards grow by fighting: <strong>world and live matches: 25 XP for a win, 10 for a loss</strong> · <strong>local arena and tournaments: 5 and 2</strong>. Every 100 XP: +1 level = <strong>+4 HP, +3% attack and +3 gym margin</strong>. Mirror matches (a card against itself) don't count.",
    "r_h_pts": "💰 Points (the currency)",
    "r_p_pts": "You earn them with: <strong>+10 for each world or live win</strong>, +10 for each Boss tamed, 📅 daily missions (5 each, +10 for the trio: max 25 a day), won bets, medals (10-100 points each) and 🎁 gift codes. Local wins: zero points. You <strong>spend</strong> them on: bets (stake 10-100), gym food (20-25), 🌿 world edge (50), 🎨 Gold Frame (100), 🔁 redrawing the art (30). Losing a match costs no points: only wrong bets do.",
    "r_h_bet": "🎲 Betting",
    "r_p_bet": "In <strong>world and live matches</strong>: before the match you choose the stake and who to back (⭐ favorite at low odds, 🐾 underdog at high odds). You win the stake × (odds − 1); if you're wrong you lose the stake. No betting in local matches or tournaments.",
    "r_h_rest": "😴 Rest",
    "r_p_rest": "After every real match (local 1v1, world, live) and every workout, the cats involved rest for <strong>1 hour</strong>: they can't fight or eat. Rest is visible to everyone, even online. Tournaments are exhibitions and don't tire cats out.",
    "r_h_gym": "🏋️ The gym",
    "r_p_gym": "Each level unlocks <strong>+3 points of training margin</strong>. You buy a food (🥫 HP · 🍗 Strength · 🐁 Intelligence · 🌿 Agility · 🐟 Speed · 🧀 Charm) and the cat earns it through the matching exercise: 🧶 yarn ball (agility), 🐭 mouse hunt (physique), 🪶 follow the feather (mind). Thresholds: <strong>under 5 points food wasted, 5-9 bonus ×1, 10+ bonus ×2</strong> (for the feather: 3 and 5 rounds). Published cards update online by themselves. The Coach gives free advice.",
    "r_h_world": "🌍 The World Arena",
    "r_p_world": "Sign in with Google (or email), choose your player name (one per account, renamable everywhere at once) and <strong>publish the cards you want</strong>: only published, active cards can challenge online. You challenge other players' cards, the result goes into the log and the ranking (sorted by win %). You can <strong>🚪 retire</strong> a card: it stays in the ranking as \"retired\" but no one can challenge it anymore. The red dot on World tells you when your cards fought while you were away.",
    "r_h_rank": "📊 The ranking (UFC style)",
    "r_p_rank1": "Every published card has an <strong>Elo</strong> score, starting at <strong>1000</strong>. In each match the winner <strong>takes</strong> points and the loser <strong>gives up the same points</strong> — and the amount depends on the strength gap: beating a <strong>stronger</strong> opponent is worth up to <strong>~32 points</strong>, beating a much weaker one is worth the minimum, <strong>8</strong> (easy wins pay little, upsets pay a lot). No card ever drops below 100. The server does the math, the same for everyone.",
    "r_p_rank2": "The official standings are by Elo, but the belt is another matter: <strong>you become champion ONLY by beating the reigning champion 👑</strong> in a world or live match. You can pass them in points as much as you like: you stay first contender until you knock them out in the ring. The champion always sits at the top of the ranking, and anyone who has been champion keeps the 🏆 forever. You can only challenge cats <strong>from 5 places above to 5 below</strong> yours: for the title you have to climb (in the top 5 the champion is within reach). The ranking shows streaks — 🔥 wins in a row, 🧊 losses in a row, and the best streak ever. The <strong>🎩 Manager</strong> studies the numbers and advises you on the right next match, whether catnip 🌿 is worth it, and when it's better to pull back into the gym for a while.",
    "r_h_cat": "🃏 The Catdex",
    "r_p_cat": "The collection album, at the bottom of the 📚 Cards tab: it keeps track of the <strong>rarities, breeds and special powers</strong> you've discovered (missing slots stay ❓) and rewards milestones with <strong>one-off</strong> points — from the rarity full house (+25) to 10 different breeds (+25) up to all 8 powers (+30). The AI writes the breed when you create the card: similar names (e.g. \"tabby\" and \"European tabby\") count as a single family. To complete it you need only one thing: photograph new cats.",
    "r_h_mis": "📅 Daily missions",
    "r_p_mis": "Every midnight <strong>3 missions</strong> arrive, the same for the whole world: one combat, one gym, one surprise (boss, bets, QR…). Each pays <strong>5 points</strong>, the full trio another <strong>10 bonus</strong>. You'll find them at the top of the 🏅 Medals, with a ✅ on the ones already done. Maximum 25 points a day: just enough for a workout, or a little more.",
    "r_h_boss": "🤖 The Arena Bosses",
    "r_p_boss": "<strong>64 legends in 8 divisions</strong> of rising difficulty: from the Neighborhood Strays (easy) to Final Bosses like the 🌑 Gatto Mammone or 🤖 MIAO-9000, monstrous. Each day <strong>2 are active, the same for the whole world</strong> (the date decides them). Beating one pays <strong>+10 points and 25 XP</strong>. Careful: you have <strong>only ONE attempt per boss per day</strong> — won, lost or abandoned, you come back tomorrow. Choose your cat well before entering the arena. Losing costs only 2 consolation XP. After the match the cat <strong>rests for an hour</strong> as in any real match, and catnip 🌿 bought beforehand counts here too. Against Bosses <strong>only cards published in the World</strong> take the field, and bosses <strong>don't touch the Elo ranking</strong>. Each boss has its own medal (the «🤖 Bosses tamed» section in the 🏅 Medals, richer rewards for higher divisions), plus the 🏆 Boss Slayer for whoever tames all 64.",
    "r_h_qr": "⚡ The live duel (QR)",
    "r_p_qr": "Two phones: one shows its card's QR (🥋 Dojo → 📱), the other scans it (📷) and the duel plays out on its screen. <strong>It counts as a world match</strong>: points, full XP, medals, rest, bets and a recorded result if the cards are published.",
    "r_h_tourn": "🏆 Tournaments and medals",
    "r_p_tourn": "Tournaments of 4 or 8 between your cards and rivals: automatic exhibitions with a bracket (reduced XP, no rest, no points). The <strong>🏅 Medals</strong> case has 25 medals with point rewards (9 are Boss ones) — tap a medal to find out how to earn it. Watch out for the 💀 Rout…",
    "r_h_fight": "⚔️ Combat",
    "r_p_fight": "Automatic and turn-based: Speed decides who starts (usually), Strength the damage, Agility the dodges, Intelligence the criticals (×1.6), Charm bewitches, Aloofness reduces damage. No hit removes more than 38% of HP. Special powers, random power-ups (🧶🌿📦🐟), a slow-motion final blow and replay. The presentation can be skipped (⏭️ or from Options).",
    "mgr_greet": "The ring is a chessboard, kid. Pick your champion and I'll tell you the next move.",
    "mis_desc": "Three new tasks every midnight, the same for the whole world: <strong>5 points</strong> each, <strong>+10 bonus</strong> if you complete the trio.",
    "med_desc": "Medals reward you with points: spend them on bets, the world edge, the Gold Frame, redraws and in the Gym pantry.",
    "boss_intro": "64 legends across 8 divisions: 2 appear each day, the same for the whole world. Beating them pays <strong>+10 points</strong>, full XP and a dedicated medal. <strong>One attempt per boss per day</strong>, won or lost; bosses don't affect the Elo ranking. Only cards <strong>published in the World</strong> can fight."
  },
  "boss": {
    "div_1": "Neighborhood Strays",
    "div_2": "Rebel House Cats",
    "div_3": "Nobles and Aristocats",
    "div_4": "Wild Beasts",
    "div_5": "Myths and Legends",
    "div_6": "Spirits and the Supernatural",
    "div_7": "Feline Deities",
    "div_8": "Final Bosses",
    "di_1": "From the neighborhood alleys",
    "di_2": "From living rooms in uproar",
    "di_3": "From the halls of nobility",
    "di_4": "From the wild lands",
    "di_5": "From the ancient legends",
    "di_6": "From the feline afterlife",
    "di_7": "From the celestial thrones",
    "di_8": "From the end of all things",
    "bu_already_beaten": "✅ already tamed",
    "bu_beaten_today": "🎖️ Tamed today: reward collected.",
    "bu_failed_today": "💥 Today's attempt failed.",
    "bu_one_try": "Only one attempt per boss per day: come back tomorrow.",
    "bu_btn_beaten": "✅ Beaten today",
    "bu_btn_tomorrow": "⏳ Come back tomorrow",
    "bu_btn_fight": "⚔️ Challenge {name}",
    "bu_bestiary_sum": "📖 Bestiary — <strong>{done}/{tot}</strong> tamed <span class=\"count\">{open}</span>",
    "bu_stats_unknown": "Stats unknown: face {name} to reveal them.",
    "bu_beaten_tag": "✅ tamed",
    "bu_never_tag": "🔒 never faced",
    "bu_mystery_desc": "A boss from the «{div}» division still shrouded in mystery. It appears on rotation: beat it to add it to the Bestiary.",
    "bu_close": "✖ Close",
    "bu_already_today": "⏳ You've already challenged {name} today: only one attempt per boss per day, won or lost. Come back tomorrow!",
    "bu_only_world": "Against Bosses only cards published in the World fight: publish one from the 🌍 tab.",
    "bu_resting": "😴 {name} is resting: come back in {min} minutes.",
    "bu_pub_first": "— publish a card in the World first —",
    "bn_latta": "The Tin Kitty",
    "bk_latta": "The Living Can",
    "bl_latta": "Convinced he's a can of food. Tough outside, tuna inside.",
    "bn_b02": "Half-Whisker",
    "bk_b02": "The Market Thief",
    "bl_b02": "Steals from the market and vanishes before you can say «meow».",
    "bn_b03": "Dirtypaw",
    "bk_b03": "Lord of the Bins",
    "bl_b03": "Rules the neighborhood trash cans, immune to all disgust.",
    "bn_b04": "The Furball",
    "bk_b04": "The Steamroller",
    "bl_b04": "Rolls right over you and never stops. Simple, but effective.",
    "bn_b05": "Soft Belly",
    "bk_b05": "The Lazybones",
    "bl_b05": "Too lazy to dodge, too fat to fall.",
    "bn_b06": "Sniffer",
    "bk_b06": "The Feline Hound",
    "bl_b06": "Follows the scent of food to the ends of the earth.",
    "bn_b07": "Half-Tail",
    "bk_b07": "The Furious",
    "bl_b07": "Lost half his tail, gained twice the rage.",
    "bn_b08": "The Baker's Cat",
    "bk_b08": "The Living Oven",
    "bl_b08": "Smells of bread, bites of embers.",
    "bn_b09": "Wrecked Couch",
    "bk_b09": "The Leather Claw",
    "bl_b09": "His nails cut leather like butter.",
    "bn_b10": "The Fridge King",
    "bk_b10": "His Hungry Majesty",
    "bl_b10": "Opens the doors with the sheer force of hunger.",
    "bn_b11": "Spoiled Kitty",
    "bk_b11": "The Angel with Claws",
    "bl_b11": "Pink bow, steel claws.",
    "bn_b12": "Ball of Wool",
    "bk_b12": "The Soft Trap",
    "bl_b12": "Looks tender. It's a trap.",
    "bn_b13": "The 4 AM Alarm",
    "bk_b13": "The Nightmare",
    "bl_b13": "Attacks when you least expect it: 4 in the morning.",
    "bn_b14": "The Keyboard Cat",
    "bk_b14": "The Saboteur",
    "bl_b14": "Walks on your nerves. And on the keys.",
    "bn_b15": "Torn Curtain",
    "bk_b15": "The Climber",
    "bl_b15": "Climbs where it shouldn't. Always.",
    "bn_b16": "Broken Vase",
    "bk_b16": "The Innocent Destroyer",
    "bl_b16": "Leaves destruction and an angelic look.",
    "bn_barone": "Baron von Whisken",
    "bk_barone": "The Aristocratic Claw",
    "bl_barone": "Duels by the old etiquette: first the bow, then the double paw.",
    "bn_b18": "Countess Velvet",
    "bk_b18": "The Stunning Gaze",
    "bl_b18": "A coat so soft it stuns the opponent.",
    "bn_b19": "Sir Scratch III",
    "bk_b19": "The Duelist",
    "bl_b19": "Legendary swordsman, never lost a duel at dawn.",
    "bn_b20": "Madame Persia",
    "bk_b20": "The Cushion Queen",
    "bl_b20": "Reigns from her silk cushion and rises for no one.",
    "bn_b21": "The Chartreux Duke",
    "bk_b21": "The Grey Steel",
    "bl_b21": "Grey as steel, cold as iron.",
    "bn_b22": "Lady Siam",
    "bk_b22": "The Ice Strike",
    "bl_b22": "Sapphire eyes, a blow that freezes the blood.",
    "bn_b23": "Don Bigcat",
    "bk_b23": "The Godfather",
    "bl_b23": "The alley's godfather: offers you can't refuse.",
    "bn_b24": "The Tuxedo Butler",
    "bk_b24": "The Elegant Shadow",
    "bl_b24": "Black and white, impeccable and lethal.",
    "bn_sfinge": "The Courtyard Sphinx",
    "bk_sfinge": "The Furry Riddle",
    "bl_sfinge": "Stares at you until you confess. Speaks only in riddles.",
    "bn_b26": "Lynx Fang",
    "bk_b26": "The Ambush",
    "bl_b26": "You don't hear it coming. You only feel it after.",
    "bn_b27": "The Wildcat",
    "bk_b27": "The Untamed",
    "bl_b27": "Never been tamed. Never will be.",
    "bn_b28": "Jungle Shadow",
    "bk_b28": "The Black Silence",
    "bl_b28": "Black as night, silent as death.",
    "bn_b29": "Roar",
    "bk_b29": "The Great Voice",
    "bl_b29": "Small in size, huge in voice.",
    "bn_b30": "Snow Claw",
    "bk_b30": "The Icy Blow",
    "bl_b30": "Descends from the peaks with a freezing strike.",
    "bn_b31": "The Cardboard Tiger",
    "bk_b31": "The Striped Trick",
    "bl_b31": "Looks fake until it bites you.",
    "bn_b32": "The Rooftop Puma",
    "bk_b32": "The Leaper",
    "bl_b32": "Jumps from building to building without touching the ground.",
    "bn_nonna": "The Alley Granny",
    "bk_nonna": "Seven Lives and a Half",
    "bl_nonna": "Her purrs heal, her smacks teach.",
    "bn_pescatore": "The Ghost Fisherman",
    "bk_pescatore": "The Net of Fate",
    "bl_pescatore": "Appears on foggy nights, smelling of sardines and revenge.",
    "bn_b35": "Puss in Boots",
    "bk_b35": "The Legendary Blade",
    "bl_b35": "The swordsman of fairy tales, in flesh, fur and boots.",
    "bn_b36": "Lesser Bastet",
    "bk_b36": "The Priestess",
    "bl_b36": "Priestess of the nine rings, guardian of the rites.",
    "bn_b37": "The Guardian Cat",
    "bk_b37": "The Keeper of the Threshold",
    "bl_b37": "Has guarded the sacred granary's threshold for centuries.",
    "bn_b38": "Foxtail",
    "bk_b38": "The Nine Tricks",
    "bl_b38": "Nine tails, nine tricks, no mercy.",
    "bn_b39": "The Immortal Stray",
    "bk_b39": "Eight Lives Spent",
    "bl_b39": "They say he's already spent eight lives. One remains.",
    "bn_b40": "Maneki the Lucky",
    "bk_b40": "The Paw of Fate",
    "bl_b40": "The raised paw that seals others' fates.",
    "bn_spettro": "The Rooftop Specter",
    "bk_spettro": "The Midnight Shadow",
    "bl_spettro": "No one ever saw it arrive. Many saw their dinner leave.",
    "bn_b42": "The Friday Black Cat",
    "bk_b42": "Bad Luck in Fur",
    "bl_b42": "Brings bad luck to anyone who dares challenge it.",
    "bn_b43": "Eyes in the Dark",
    "bk_b43": "The Invisible Predator",
    "bl_b43": "You see it only when it's already too late.",
    "bn_b44": "The Whiskered Reaper",
    "bk_b44": "Lord of the Ninth Life",
    "bl_b44": "Comes to collect your ninth life.",
    "bn_b45": "Chimney Ghost",
    "bk_b45": "The Living Ash",
    "bl_b45": "Lives in the warm ash of the fireplace.",
    "bn_b46": "The Witch Cat",
    "bk_b46": "The Enchantress",
    "bl_b46": "Turns mice into storms with a single meow.",
    "bn_b47": "The Persian Vampire",
    "bk_b47": "The Speed-Sucker",
    "bl_b47": "Sucks the opponents' Speed and makes it his own.",
    "bn_b48": "Feline Ectoplasm",
    "bk_b48": "The Untouchable",
    "bl_b48": "You can't hit what isn't solid.",
    "bn_imperatore": "The Tabby Emperor",
    "bk_imperatore": "The Throne of Cushions",
    "bl_imperatore": "Reigns from the highest cushion. His chaos sets the rules.",
    "bn_b50": "Bastet the Goddess",
    "bk_b50": "The Ancient Protector",
    "bl_b50": "The ancient goddess who protects all cats.",
    "bn_b51": "Schrödinger's Cat",
    "bk_b51": "Alive and Dead",
    "bl_b51": "Alive and dead at once, until you attack it.",
    "bn_b52": "Ra-Meow the Sun",
    "bk_b52": "The Blinding One",
    "bl_b52": "Blinding: he burns whoever dares to look at him.",
    "bn_b53": "Feline Sekhmet",
    "bk_b53": "The Divine Fury",
    "bl_b53": "Divine fury made of claws.",
    "bn_b54": "The Guardian of the Pyramids",
    "bk_b54": "A Thousand Dynasties",
    "bl_b54": "Old as a thousand dynasties, still as stone.",
    "bn_b55": "Crescent Moon",
    "bk_b55": "The Goddess of Night",
    "bl_b55": "The goddess of night: in the dark she is invincible.",
    "bn_b56": "The Cat of Stars",
    "bk_b56": "The Cosmic Coat",
    "bl_b56": "His coat is a sky full of constellations.",
    "bn_mammone": "The Gatto Mammone",
    "bk_mammone": "The Legend of Legends",
    "bl_mammone": "The monster of fairy tales. Huge, ancient and touchy.",
    "bn_b58": "Behemoth",
    "bk_b58": "The Colossus of the Abyss",
    "bl_b58": "The colossus that sleeps beneath the volcanoes.",
    "bn_b59": "The First Cat",
    "bk_b59": "The Ancestor",
    "bl_b59": "The one all the world's cats descend from.",
    "bn_b60": "Devourer of Nine Suns",
    "bk_b60": "The Cosmic Myth",
    "bl_b60": "The myth that swallows suns, one after another.",
    "bn_b61": "The Lord of Strays",
    "bk_b61": "The King of All",
    "bl_b61": "Commands every stray cat in the world.",
    "bn_b62": "Feline Chronos",
    "bk_b62": "The Time Eater",
    "bl_b62": "Eats time and ages his opponents.",
    "bn_b63": "The Void Cat",
    "bk_b63": "Absence Made Feline",
    "bl_b63": "Absence made feline. The nothing that meows.",
    "bn_b64": "MIAO-9000",
    "bk_b64": "The Ultimate Machine-Cat",
    "bl_b64": "The ultimate machine-cat. Error: mercy not found."
  },
  "world": {
    "w_recent": "📜 Your cards' last 5 matches",
    "w_open": "(tap to open)",
    "w_beat": "{w} by {wo} beat {l} by {lo}",
    "w_rank_champ": "👑 #1",
    "w_rank_n": "#{rk} in the ranking",
    "w_retired": "🚪 retired",
    "w_record": "{w} W / {l} L",
    "w_none_pub": "None of your cards is published yet.",
    "w_reactivate": "↩️ Reactivate",
    "w_retire": "🚪 Retire",
    "w_rank_suffix": "in the ranking",
    "w_by": "by",
    "w_anon": "anonymous",
    "w_wc_champ": "👑 WORLD CHAMPION",
    "w_wc_rank": "#{rk} in the ranking",
    "w_elo": "Elo pts",
    "w_exchamp": "🏆 former champion",
    "w_beststreak": "best streak 🔥{n}",
    "w_sw": "🔥 {n} in a row",
    "w_sl": "🧊 {n} KOs in a row",
    "w_resting": "😴 Resting: come back in {min} minutes",
    "w_not_ranked": "⏳ {name} isn't in the ranking yet (just published? try again shortly with 🔄).",
    "w_no_challengers": "📊 {name} is #{rk}, but no challengers within ±5 right now. Invite someone to publish!",
    "w_you_rank": "📊 {name} is #{rk} in the ranking. Here's who it can challenge (5 places above to 5 below):",
    "w_rests_short": "😴 resting ({min}m)",
    "w_btn_fight": "⚔️ Challenge",
    "w_ldr_champ": "CHAMPION",
    "w_ex": "ex",
    "w_maxstreak": "max 🔥{n}",
    "w_none_rank": "No cards in the ranking: publish one!",
    "w_record_c": "{w}W/{l}L",
    "w_selrest": "😴 resting",
    "w_selmarket": "🔒 on the market",
    "w_fav": "⭐ favorite",
    "w_underdog": "🐾 underdog",
    "w_quota": "odds",
    "w_ifwin": "if it wins: +{n} points",
    "prize_line": "🎁 <strong>At stake:</strong> win +10 points and +25 XP · loss +10 XP",
    "w_catnip_ready": "🌿 Catnip READY for this match ✔",
    "w_catnip_btn": "🌿 Give it catnip — first hit doubled (50 points)",
    "w_catnip_need": "You need 50 points (you have {pts}).",
    "w_pick_champ_opt": "— pick a champion —",
    "w_all_resting": "😴 all your cats are resting — come back later",
    "w_pub_first_opt": "— publish a card first —",
    "w_loading": "Loading the ranking…"
  },
  "mkt": {
    "mkt_desc": "Trade or sell your cards with other players. The card changes owner with everything (Elo, wins, level); while in negotiation it stays frozen and can't fight. You need to be signed in and have cards published in the World.",
    "trd_greet": "Welcome to the bazaar, friend! I'm Mister Barter: just ask, I know how good deals are made.",
    "inc_greet": "Ladies and gentlemen, the auction opens! Who bids? Who raises?",
    "mkt_browse_btn": "🔍 Browse cards to trade",
    "mkt_filter_ph": "Filter by owner (e.g. Lu…)",
    "mkt_notactive": "⚠️ The Market isn't active on the server yet (a setup step is missing). The other app features work normally.",
    "mkt_recv_h": "📥 Offers received",
    "mkt_offers": "{owner} offers you <strong>{from}</strong> in exchange for your <strong>{to}</strong>",
    "mkt_compare_btn": "🔍 Compare",
    "mkt_accept": "✅ Accept",
    "mkt_reject": "✖ Reject",
    "mkt_none_recv": "No offers received.",
    "mkt_sent_h": "📤 Offers sent",
    "mkt_sent": "You offered <strong>{from}</strong> for <strong>{to}</strong> by {owner}",
    "mkt_cancel": "↩️ Cancel",
    "mkt_login": "Sign in to trade.",
    "mkt_loading": "Loading…",
    "mkt_err_load": "❌ Error {code} loading the cards.",
    "mkt_none_avail": "No cards available for trade.",
    "mkt_neterr": "Network error.",
    "mkt_none_of": "No cards from «{q}».",
    "mkt_propose": "🔄 Propose",
    "mkt_this_card": "this card",
    "mkt_give_get": "You give <strong>{give}</strong> → You get <strong>{get}</strong>",
    "mkt_level": "📈 Level",
    "mkt_baratto_label": "😼 <strong>Mister Barter</strong>:",
    "mkt_loading_cmp": "Loading the comparison…",
    "mkt_cmp_title": "🔄 Trade comparison",
    "mkt_accept_trade": "✅ Accept the trade",
    "mkt_close": "↩️ Close",
    "mkt_err_cmp": "Error loading the comparison.",
    "mkt_close2": "Close",
    "mkt_trade_h": "🔄 Trade",
    "mkt_need_card": "To trade you need at least one of YOUR cards published and active in the World (and not resting).",
    "mkt_closeX": "✖ Close",
    "mkt_propose_h": "🔄 Propose a trade",
    "mkt_want": "You want <strong>{name}</strong>{owner}.",
    "mkt_tap_offer": "Tap YOUR card to offer:",
    "mkt_do_trade": "🔄 Trade",
    "mkt_cancelX": "✖ Cancel",
    "mkt_pick_offer": "Tap one of your cards to offer first.",
    "mkt_notactive2": "⚠️ The Market isn't active on the server yet: a setup step is missing (stage 2 SQL).",
    "mkt_trade_fail": "Trade not proposed: {t}",
    "mkt_sent_ok": "🔄 Offer sent! Awaiting a reply.",
    "mkt_neterr2": "Network error: {m}",
    "mkt_op_fail": "Operation failed: {t}",
    "mkt_trade_done": "✅ Trade done! The cards changed owner.",
    "mkt_rejected": "Offer rejected.",
    "mkt_cancelled": "↩️ Offer cancelled.",
    "mkt_received": "🎁 You received {name} in the trade!",
    "mkt_login_first": "Sign in first (🌍 World tab).",
    "mkt_auc_h": "🔨 Auction",
    "mkt_need_free": "You need a published, free card (not already on the market) to put up for auction.",
    "mkt_put_auc_h": "🔨 Put up for auction",
    "mkt_tap_sell": "Tap the card to sell:",
    "mkt_min_price": "Minimum price (points)",
    "mkt_duration": "Duration",
    "mkt_h1": "1 hour",
    "mkt_h6": "6 hours",
    "mkt_h24": "24 hours",
    "mkt_d2": "2 days",
    "mkt_hold_auc": "🔨 Start the auction",
    "mkt_pick_card": "Tap a card first.",
    "mkt_auc_notactive": "⚠️ Auctions aren't active on the server yet (SQL missing).",
    "mkt_auc_fail": "Auction not created: {t}",
    "mkt_auc_ok": "🔨 Auction started! Your card is now on the market.",
    "mkt_auc_notactive2": "⚠️ Auctions not active on the server yet (SQL step missing).",
    "mkt_err": "Error {code}.",
    "mkt_no_auc": "No auctions running. Start one!",
    "mkt_curbid": "💰 {n} pts by {owner}",
    "mkt_nobid": "no bids",
    "mkt_your_auc": "🔨 your auction",
    "mkt_withdraw": "↩️ Withdraw",
    "mkt_bid_btn": "💰 Bid",
    "mkt_base": "Base {n} pts",
    "mkt_history": "📜 Bid history",
    "mkt_min_bid": "You must bid at least {n} points.",
    "mkt_no_points": "You don't have enough points (you have {p}).",
    "mkt_bid_fail": "Bid rejected: {t}",
    "mkt_no_bids": "No bids yet.",
    "mkt_bid_line": "💰 {n} pts — {owner} · {when}",
    "mkt_err2": "Error.",
    "mkt_confirm_withdraw": "Withdraw the card from the auction?",
    "mkt_withdraw_fail": "Not withdrawn: {t}",
    "mkt_withdrawn": "↩️ Auction withdrawn."
  },
  "sent": {
    "sent_title": "🗺️ The Path of Nine Lives",
    "sent_desc": "A long journey in stages for each of your cards: face the path cats one after another. Each win unlocks the next stage and gives you that cat's sticker for the Album. Plays offline, no bets or rest: if you lose, try again.",
    "sent_pick": "Who walks the path",
    "pick_card": "👆 Pick a card above to begin the journey.",
    "no_card": "Create a card first, then set off on the path.",
    "progress": "<strong>{name}</strong> — stage {done}/{tot} cleared.",
    "more_soon": "🚧 The next zones of the path are coming soon…",
    "stage": "Stage",
    "zone_done": "🎉 Zone complete! +{pts} points and a new Album page.",
    "got_fig": "📒 New sticker: {name}!",
    "album_sum": "📒 Album — <strong>{done}/{tot}</strong> stickers <span class=\"count\">{open}</span>",
    "z_1": "The Alleys",
    "z_2": "The Gardens",
    "z_3": "The Forest",
    "z_4": "The Mountain",
    "z_5": "The City",
    "z_6": "The Desert",
    "z_7": "The Sea",
    "z_8": "The Ice Lands",
    "z_9": "The Volcano",
    "z_10": "The Cosmos",
    "bn_s01": "Kitty",
    "bk_s01": "The Rookie",
    "bl_s01": "The first cat you meet: curious, clumsy, but full of heart.",
    "bn_s02": "Rummage",
    "bk_s02": "The Trash King",
    "bl_s02": "Knows every bin in the neighborhood and what's inside.",
    "bn_s03": "Socks",
    "bk_s03": "The Sleepyhead",
    "bl_s03": "Black and white, always on the warmest car hood in the alley.",
    "bn_s04": "Boxie",
    "bk_s04": "The Cardboard Ambush",
    "bl_s04": "Lives in a box and pops out when you least expect it.",
    "bn_s05": "Midnight",
    "bk_s05": "The Alley Shadow",
    "bl_s05": "Black as night, you only spot him by his glowing eyes.",
    "bn_s06": "Cream",
    "bk_s06": "The Glutton",
    "bl_s06": "Always has a milk moustache and a satisfied grin.",
    "bn_s07": "String",
    "bk_s07": "The Busker",
    "bl_s07": "Plays his out-of-tune guitar under the streetlights for a few treats.",
    "bn_s08": "Sardine",
    "bk_s08": "The Fishmonger",
    "bl_s08": "Never lets go of his fish: you'll have to earn it.",
    "bn_s09": "Bolt",
    "bk_s09": "The Alley Lightning",
    "bl_s09": "Bounces from wall to wall: catch him if you can.",
    "bn_s10": "One-Eye",
    "bk_s10": "King of the Alleys",
    "bl_s10": "One eye and a thousand scars: he rules the strays. The first real obstacle.",
    "bn_s11": "Flutter",
    "bk_s11": "The Butterfly Chaser",
    "bl_s11": "Chases butterflies all day, never catches one.",
    "bn_s12": "Sunflower",
    "bk_s12": "The Sun Napper",
    "bl_s12": "Sleeps where the sun hits and moves along with it.",
    "bn_s13": "Buzz",
    "bk_s13": "The Stinger",
    "bl_s13": "Learned the hard way that bees sting. Still tries.",
    "bn_s14": "Chirp",
    "bk_s14": "The Bird-Watcher",
    "bl_s14": "Watches the little birds from the window for hours, motionless.",
    "bn_s15": "Froggo",
    "bk_s15": "The Frog-Startler",
    "bl_s15": "Jumps in the pond and scatters all the frogs.",
    "bn_s16": "Thorn",
    "bk_s16": "The Rose-Scarred",
    "bl_s16": "A thousand scratches in the brambles, but the rose bed is his.",
    "bn_s17": "Snail",
    "bk_s17": "The Patient One",
    "bl_s17": "Watches snails move. He's the only thing slower than them.",
    "bn_s18": "Splash",
    "bk_s18": "The Fountain-Splasher",
    "bl_s18": "Plays with the fountain water and always comes back soaked.",
    "bn_s19": "Prickle",
    "bk_s19": "The Spiky Friend",
    "bl_s19": "Made friends with a hedgehog. Don't ask how.",
    "bn_s20": "Old Willow",
    "bk_s20": "Lord of the Garden",
    "bl_s20": "The oldest cat in the garden: wise, calm and untouchable.",
    "bn_s21": "Shroom",
    "bk_s21": "The Forager",
    "bl_s21": "Sniffs out the forest's best mushrooms and dodges the bad ones.",
    "bn_s22": "Nightfeather",
    "bk_s22": "The Owl's Rival",
    "bl_s22": "Challenges the owl every night to see who stays awake longer.",
    "bn_s23": "Acorn",
    "bk_s23": "The Hoarder",
    "bl_s23": "Steals acorns from the squirrels and hides them everywhere.",
    "bn_s24": "Sly",
    "bk_s24": "The Cunning One",
    "bl_s24": "Walks like a fox and thinks like a fox.",
    "bn_s25": "Tusk",
    "bk_s25": "The Territory Keeper",
    "bl_s25": "Defends his clearing from anyone, boars included.",
    "bn_s26": "Cobweb",
    "bk_s26": "The Tangled",
    "bl_s26": "Always ends up in spiderwebs, but never gives up.",
    "bn_s27": "Pinecone",
    "bk_s27": "The Pine-Climber",
    "bl_s27": "Climbs the tallest pines just to look down.",
    "bn_s28": "Fawn",
    "bk_s28": "The Silent Hunter",
    "bl_s28": "Follows the deer through the woods without a sound.",
    "bn_s29": "Wolfling",
    "bk_s29": "The Wild Cub",
    "bl_s29": "Raised among wolves, he learned their howl.",
    "bn_s30": "Big Bear",
    "bk_s30": "The Forest Beast",
    "bl_s30": "Big as a bear: the undisputed king of the woods.",
    "bn_s31": "Bootie",
    "bk_s31": "The Hiker-Follower",
    "bl_s31": "Follows hikers to the summit hoping for a sandwich.",
    "bn_s32": "Goatleap",
    "bk_s32": "The Goat-Startler",
    "bl_s32": "Makes the goats jump on the cliffs just for fun.",
    "bn_s33": "Pebble",
    "bk_s33": "The Balancer",
    "bl_s33": "Balances on the most awkward boulders of the mountain.",
    "bn_s34": "Eaglet",
    "bk_s34": "The Eagle's Rival",
    "bl_s34": "Fights the eagle for the highest peaks, with no wings.",
    "bn_s35": "Tentflap",
    "bk_s35": "The Camp Thief",
    "bl_s35": "Raids the campers' tents in the night.",
    "bn_s36": "Summit",
    "bk_s36": "The Peak-Dweller",
    "bl_s36": "Lives where the air is thin and no other cat dares.",
    "bn_s37": "Gale",
    "bk_s37": "The Windswept",
    "bl_s37": "The mountain wind ruffled his fur forever.",
    "bn_s38": "Grapple",
    "bk_s38": "The Climber",
    "bl_s38": "Scales walls where even goats won't go.",
    "bn_s39": "Jingle",
    "bk_s39": "The Highlander",
    "bl_s39": "Wears a bell on his collar: you hear him before you see him.",
    "bn_s40": "Whitehorn",
    "bk_s40": "King of the Mountain",
    "bl_s40": "Ram's horns and iron paws: he rules every peak.",
    "bn_s41": "Taxi",
    "bk_s41": "The Car-Dodger",
    "bl_s41": "Crosses the wildest traffic without a scratch.",
    "bn_s42": "Shingle",
    "bk_s42": "The Rooftop Prowler",
    "bl_s42": "Rules the big city's roofs, tile by tile.",
    "bn_s43": "Margherita",
    "bk_s43": "The Pizza Raider",
    "bl_s43": "No pizza box is safe with him around.",
    "bn_s44": "Traffic Light",
    "bk_s44": "The Traffic-Watcher",
    "bl_s44": "Always waits for the green. A very civil cat.",
    "bn_s45": "Parkour",
    "bk_s45": "The Rooftop Acrobat",
    "bl_s45": "Leaps from building to building like in the movies.",
    "bn_s46": "Neon",
    "bk_s46": "The Neon Lounger",
    "bl_s46": "Sleeps under the bright signs, in the city's warmth.",
    "bn_s47": "Metro",
    "bk_s47": "The Subway Cat",
    "bl_s47": "Knows every tunnel and platform underground.",
    "bn_s48": "Jazz",
    "bk_s48": "The Alley Cat",
    "bl_s48": "Meows in jazz time behind the clubs at night.",
    "bn_s49": "Skyscraper",
    "bk_s49": "The Tower-Climber",
    "bl_s49": "Climbed the tallest building just for the view.",
    "bn_s50": "Nocturne",
    "bk_s50": "The City Boss",
    "bl_s50": "Rules every alley after sunset. The city is his.",
    "bn_s51": "Cactino",
    "bk_s51": "The Cactus-Dodger",
    "bl_s51": "Runs among the cacti without ever getting pricked. Almost.",
    "bn_s52": "Hooktail",
    "bk_s52": "The Wary One",
    "bl_s52": "Keeps an eye on every scorpion: he's been stung once already.",
    "bn_s53": "Dune",
    "bk_s53": "The Dune-Runner",
    "bl_s53": "Runs up and down the dunes like they were cushions.",
    "bn_s54": "Palm",
    "bk_s54": "The Oasis Lounger",
    "bl_s54": "Found the desert's only shade and won't give it up.",
    "bn_s55": "Hiss",
    "bk_s55": "The Snake-Charmer",
    "bl_s55": "Stares snakes down until they give up.",
    "bn_s56": "Scorcher",
    "bk_s56": "The Sun-Baked",
    "bl_s56": "The desert sun warmed up his temper.",
    "bn_s57": "Amphora",
    "bk_s57": "The Ruins Cat",
    "bl_s57": "Lives among the ancient ruins, keeper of secrets of sand.",
    "bn_s58": "Hump",
    "bk_s58": "The Camel-Follower",
    "bl_s58": "Follows the caravans for the travelers' crumbs.",
    "bn_s59": "Whirl",
    "bk_s59": "The Storm Survivor",
    "bl_s59": "He's been through a thousand sandstorms. Still here.",
    "bn_s60": "Leonino",
    "bk_s60": "The Desert Sphinx",
    "bl_s60": "Still as a statue, ancient as the sand. Speaks in riddles.",
    "bn_s61": "Pincer",
    "bk_s61": "The Crab-Catcher",
    "bl_s61": "Chases crabs on the shoreline, always loses a whisker.",
    "bn_s62": "Seashell",
    "bk_s62": "The Collector",
    "bl_s62": "Gathers shells and buries them in the sand.",
    "bn_s63": "Wave",
    "bk_s63": "The Wave-Dodger",
    "bl_s63": "Dares the waves and flees just before getting wet.",
    "bn_s64": "Hook",
    "bk_s64": "The Fisher",
    "bl_s64": "Fishes with his paw better than many fishermen.",
    "bn_s65": "Seagull",
    "bk_s65": "The Gull's Rival",
    "bl_s65": "Fights the seagulls for every crumb on the pier.",
    "bn_s66": "Sail",
    "bk_s66": "The Stowaway",
    "bl_s66": "Sneaks aboard and no one ever notices.",
    "bn_s67": "Boarding",
    "bk_s67": "The Pirate Cat",
    "bl_s67": "An eyepatch and a paw always ready for a raid.",
    "bn_s68": "Tentacle",
    "bk_s68": "The Octopus Wrangler",
    "bl_s68": "The only one who plays with octopuses and wins.",
    "bn_s69": "Seal",
    "bk_s69": "The Sea's Friend",
    "bl_s69": "Swims with the seals as if born among them.",
    "bn_s70": "Leviathan",
    "bk_s70": "King of the Sea",
    "bl_s70": "Big as a whale: he commands every wave of the ocean.",
    "sent_fight": "⚔️ Fight",
    "sent_back": "↩️ Back",
    "sent_replay": "⚔️ Replay",
    "bn_s71": "Flurry",
    "bk_s71": "The Flake-Catcher",
    "bl_s71": "Tries to catch snowflakes with his paws, one by one.",
    "bn_s72": "Snowman",
    "bk_s72": "The Snow-Builder",
    "bl_s72": "Builds snowmen and then knocks them down for fun.",
    "bn_s73": "Icicle",
    "bk_s73": "The Slider",
    "bl_s73": "Slides on the ice and never really stops.",
    "bn_s74": "Penguin",
    "bk_s74": "The Penguin's Rival",
    "bl_s74": "Challenges the penguins to a belly-slide contest.",
    "bn_s75": "Skier",
    "bk_s75": "The Downhiller",
    "bl_s75": "Speeds down the snowy slopes faster than a sled.",
    "bn_s76": "Cubby",
    "bk_s76": "The Polar Bear's Friend",
    "bl_s76": "Adopted a polar bear cub. Or was it the other way around?",
    "bn_s77": "Blizzard",
    "bk_s77": "The Storm-Walker",
    "bl_s77": "Walks through snowstorms like they were a breeze.",
    "bn_s78": "Curler",
    "bk_s78": "The Ice-Slinger",
    "bl_s78": "Slides stones across the ice with perfect aim.",
    "bn_s79": "Crystal",
    "bk_s79": "The Crystal-Gazer",
    "bl_s79": "Spends hours staring at the glittering ice crystals.",
    "bn_s80": "Frost King",
    "bk_s80": "The Ice Sovereign",
    "bl_s80": "His breath freezes the lakes. No one meets his icy gaze.",
    "bn_s81": "Ember",
    "bk_s81": "The Firebrand",
    "bl_s81": "Walks on burning coals without scorching his paws.",
    "bn_s82": "Crater",
    "bk_s82": "The Crater-Dweller",
    "bl_s82": "Lives on the volcano's rim, where it's infernally hot.",
    "bn_s83": "Obsidian",
    "bk_s83": "The Black-Stone Cat",
    "bl_s83": "Hard and shiny as volcanic glass.",
    "bn_s84": "Blast",
    "bk_s84": "The Explosive",
    "bl_s84": "When he gets angry, the whole mountain shakes.",
    "bn_s85": "Firecracker",
    "bk_s85": "The Short Fuse",
    "bl_s85": "Goes off at the slightest thing and charges in.",
    "bn_s86": "Hot Spring",
    "bk_s86": "The Spa Lounger",
    "bl_s86": "Naps in the hot pools near the lava.",
    "bn_s87": "Scorch",
    "bk_s87": "The Red-Hot",
    "bl_s87": "As he passes, the air shimmers with heat.",
    "bn_s88": "Flamelet",
    "bk_s88": "The Fire-Keeper",
    "bl_s88": "Keeps the volcano's ancient flame alive.",
    "bn_s89": "Lantern",
    "bk_s89": "The Eternal Flame",
    "bl_s89": "Has burned for a thousand years and never goes out.",
    "bn_s90": "Dragonling",
    "bk_s90": "The Volcano Dragon",
    "bl_s90": "Spits sparks and commands the lava. King of fire.",
    "bn_s91": "Moonlet",
    "bk_s91": "The Moon Cat",
    "bl_s91": "Hops from crater to crater on the moon, light as a feather.",
    "bn_s92": "Starlet",
    "bk_s92": "The Star-Gatherer",
    "bl_s92": "Collects shooting stars in a jar (so he says).",
    "bn_s93": "Ring",
    "bk_s93": "Lord of the Rings",
    "bl_s93": "Lives on Saturn's rings in perfect balance.",
    "bn_s94": "Comet",
    "bk_s94": "The Traveler",
    "bl_s94": "Streaks through space leaving a glowing trail.",
    "bn_s95": "Rocket",
    "bk_s95": "The Astronaut",
    "bl_s95": "Climbed onto a rocket for fun and never came down.",
    "bn_s96": "Saucer",
    "bk_s96": "The Aliens' Friend",
    "bl_s96": "Made friends with creatures from other worlds.",
    "bn_s97": "Meteor",
    "bk_s97": "The Wish",
    "bl_s97": "Passes so fast you have to make a wish.",
    "bn_s98": "Void",
    "bk_s98": "The Black Hole",
    "bl_s98": "Swallows everything that comes near, even light.",
    "bn_s99": "Stardust",
    "bk_s99": "The Star-Cloak",
    "bl_s99": "His fur is made of galaxy dust.",
    "bn_s100": "Cosmic Sovereign",
    "bk_s100": "Lord of the Nine Lives",
    "bl_s100": "The Path's final foe. Ancient as the universe, invincible as a legend."
  },
  "msg": {
    "del_card_confirm": "Delete {name}'s card? Its battle stats will be deleted too.",
    "nick_set": "🥊 {name} is now «{nick}»",
    "retire_login": "To retire a card from the world you must sign in first (🌍 World tab).",
    "retire_confirm": "Retire {name} from the World Arena? It stays in the ranking with its record as \"retired\", but no one can challenge it anymore. (Republishing brings it back.)",
    "err_http": "Error: HTTP {code}",
    "card_not_pub": "This card isn't published (or isn't yours).",
    "retired_ok": "🚪 {name} retired from the world with honor. Its record stays in the ranking.",
    "err_net": "Network error: {m}",
    "code_copied": "Code copied! Send it to a friend (e.g. on WhatsApp): they paste it into their app to challenge {name}. Note: the code is long because it also contains the photo.",
    "audio_quota": "⛔ Gemini daily quota exhausted.\n\nThe clips already made are saved. Resume tomorrow (the quota resets) and it will complete only the missing ones.",
    "audio_err": "🎙️ Audio error ({lang}): {err}",
    "same_cat": "A cat can't fight itself! Pick two different cards.",
    "backup_confirm": "Import the backup? It will replace your current collection, rivals and stats ({n} cards in the backup).",
    "backup_invalid": "Invalid backup file.",
    "share_unsupported": "Direct sharing isn't supported by this browser: use «Download» and attach the image.",
    "card_gone_local": "This card is no longer in your local collection.",
    "news_beaten": "💥 {loser} was beaten by {winner} {by} {owner} — now resting 😴",
    "world_login": "Sign in first (top of the World tab) to challenge online.",
    "out_of_range": "🔒 Out of range: {name} is #{ro}, you are #{rm}. You can only challenge within 5 places above and 5 below: climb the ranking!",
    "opp_trading": "🔄 {name} is busy in a trade: it can't be challenged right now.",
    "opp_resting": "😴 {name} just went to rest: try again in {min} minutes.",
    "need_pub_card": "To challenge online you need one of YOUR cards published and active: publish one from «Choose which cards to publish».",
    "catnip_have": "Edge already bought: it applies to your next match.",
    "catnip_need": "You need 50 points (you have {pts}). Win bets and medals!",
    "catnip_confirm": "Spend 50 points? Your card will start the next match with catnip (first hit doubled).",
    "catnip_ready": "🌿 Edge ready: it applies to your next match!",
    "regen_cost": "Redrawing the art costs 30 points (you have {pts}).",
    "regen_confirm": "Spend 30 points for a new AI drawing?",
    "frame_have": "{name} already sports the Gold Frame!",
    "frame_cost": "The Gold Frame costs 100 points (you have {pts}).",
    "frame_confirm": "Spend 100 points for {name}'s Gold Frame? It stays forever.",
    "food_need": "💰 You need {cost} points (you have {pts}): win them in the world!",
    "train_cancel": "↩️ Workout cancelled: {cost} points refunded.",
    "pick_champ": "Pick your champion in the menu above first.",
    "qr_gen_fail": "QR generator not loaded: reload the page with internet on.",
    "qr_read_fail": "QR reader not loaded: internet needed.",
    "cam_fail": "Camera not available: {m}",
    "qr_invalid": "Invalid QR.",
    "qr_self": "You scanned your own card!"
  },
  "moves": {
    "ma_0": "Scratch",
    "ma_1": "Ambush",
    "ma_2": "Glare",
    "ma_3": "Pounce",
    "ma_4": "Paw-swipe",
    "ma_5": "Meow",
    "ma_6": "Assault",
    "ma_7": "Purr",
    "mb_0": "Lightning",
    "mb_1": "Couch",
    "mb_2": "Scornful",
    "mb_3": "Cosmic",
    "mb_4": "Wild",
    "mb_5": "Nocturnal",
    "mb_6": "4 AM",
    "mb_7": "Hypnotic"
  },
  "instr": {
    "i_pianoforte": "piano",
    "i_tromba": "trumpet",
    "i_chitarra": "guitar",
    "i_archi": "strings",
    "i_organo": "organ",
    "i_marimba": "marimba",
    "theme_line": "{stile} in {ton}, {instr}"
  },
  "breeds": {
    "b_soriano": "Tabby",
    "b_tigrato": "Tabby",
    "b_europeo": "European",
    "b_comune": "Domestic cat",
    "b_certosino": "Chartreux",
    "b_siamese": "Siamese",
    "b_persiano": "Persian",
    "b_mainecoon": "Maine Coon",
    "b_ragdoll": "Ragdoll",
    "b_sphynx": "Sphynx",
    "b_bengala": "Bengal",
    "b_british": "British",
    "b_norvegese": "Norwegian Forest",
    "b_angora": "Angora",
    "b_birmano": "Birman",
    "b_abissino": "Abyssinian",
    "b_esotico": "Exotic",
    "b_siberiano": "Siberian",
    "b_scottish": "Scottish Fold",
    "b_rex": "Rex",
    "b_blurusso": "Russian Blue",
    "b_orientale": "Oriental",
    "b_turco": "Turkish Van",
    "b_savana": "Savannah",
    "b_bombay": "Bombay",
    "c_bianco": "white",
    "c_nero": "black",
    "c_grigio": "grey",
    "c_blu": "blue",
    "c_rosso": "red",
    "c_crema": "cream",
    "c_marrone": "brown",
    "c_fulvo": "tawny",
    "c_tartarugato": "tortoiseshell",
    "c_tricolore": "calico",
    "c_bicolore": "bicolour",
    "c_maculato": "spotted",
    "c_striato": "striped",
    "c_pointed": "colourpoint",
    "coat_lungo": "longhair",
    "coat_corto": "shorthair"
  },
  "award": {
    "title": "🏆 Saturday Night Awards",
    "host": "Meow Sinatra",
    "subtitle": "Every Saturday night, the big gala: prizes, points and glory for the week’s best cats.",
    "promo_when": "SATURDAY, 9:00 PM",
    "promo_line": "🎬 Next episode with {host}",
    "promo_cd": "in {d}d {h}h {m}m",
    "promo_soon": "in {h}h {m}m",
    "promo_live": "🔴 It’s time! The ceremony is about to begin…",
    "noms_title": "✨ This week’s nominations",
    "noms_sub": "Who’s leading right now — updated live",
    "noms_empty": "No matches yet this week. Fight in the World to make the ranking!",
    "past_title": "📼 Previous episodes",
    "past_empty": "The first gala night is this Saturday. Come back to see the winners!",
    "hall_title": "🏛️ Hall of Fame — all-time records",
    "hall_empty": "No records yet: someone will be the first.",
    "by": "by",
    "pts": "+{p} pts",
    "week_of": "Night of {d}",
    "aw_mvp": "MVP — Cat of the Week",
    "aw_instancabile": "Tireless",
    "aw_cecchino": "Sharpshooter",
    "aw_dominatore": "Dominator",
    "d_mvp": "most wins",
    "d_instancabile": "most matches",
    "d_cecchino": "best win rate",
    "d_dominatore": "longest streak",
    "hof_striscia": "Legendary Streak",
    "hof_veterano": "Veteran",
    "hof_recordman": "Win Record Holder",
    "hof_winrate": "Best Win Rate",
    "val_mvp": "{n} wins",
    "val_instancabile": "{n} matches",
    "val_cecchino": "{n}%",
    "val_dominatore": "{n}-win streak",
    "val_striscia": "{n} in a row",
    "val_veterano": "{n} matches",
    "val_recordman": "{n} wins",
    "val_winrate": "{n}%",
    "cer_title": "SATURDAY NIGHT GALA",
    "cer_open": "🎩 Ladies and gentlemen… welcome to the Gala! I’m {host}, and tonight we honor the week’s finest cats!",
    "cer_drumroll": "🥁 Purr-roll please…",
    "cer_gold": "🥇 The golden paw goes to… {name}, owned by {owner}!",
    "cer_silver": "🥈 Silver for {name}, owned by {owner}.",
    "cer_bronze": "🥉 Bronze for {name}, owned by {owner}.",
    "cer_pts": "✨ +{p} points!",
    "cer_q_mvp": "The winningest of them all!",
    "cer_q_instancabile": "Never stopped for a second!",
    "cer_q_cecchino": "Sharp as a sniper!",
    "cer_q_dominatore": "What a streak!",
    "cer_mvp_finale": "🌟 And now the most coveted prize of the night… Cat of the Week!",
    "cer_close": "🎉 That’s all for tonight! A big paw for our champions. See you next Saturday!",
    "cer_none": "No awards this week: not enough fights! Get back in the ring.",
    "btn_replay": "🎬 Replay the gala",
    "btn_skip": "Skip ▶▶",
    "cer_preview": "PREVIEW — standings in progress",
    "pl_1": "The night cats become legends.",
    "pl_2": "Tuxedo, spotlights and purrs — let’s go!",
    "pl_3": "Nine lives, one stage.",
    "pl_4": "Who takes home the golden paw?",
    "pl_5": "Red kibble and a red carpet too.",
    "pl_6": "Applause, confetti and a few scratches.",
    "pl_7": "The classiest Saturday in the neighborhood.",
    "pl_8": "Only the toughest cats hit the stage.",
    "pl_9": "Lights, camera… meow!",
    "pl_10": "Tonight we crown who scratched hardest.",
    "place_1": "First place · Gold",
    "place_2": "Second place · Silver",
    "place_3": "Third place · Bronze",
    "full_mvp": "The cat with the most world wins this week. Simply the best.",
    "full_instancabile": "Fought more matches than anyone: never stops, always in the ring.",
    "full_cecchino": "The best win rate (at least 5 matches): precision, not luck.",
    "full_dominatore": "The longest streak of consecutive wins this week.",
    "react_1": "What a paw!",
    "react_2": "Applause, please! 👏",
    "react_3": "Goosebumps!",
    "react_4": "A true phenomenon!",
    "react_5": "What class!",
    "react_6": "The crowd goes wild!",
    "cer_podium": "🏆 And now… the podium!",
    "cer_suspense": "🥁 …and the winner is…",
    "cer_hall_intro": "🏛️ And now… the All-Time Records!",
    "cer_hall_hold": "This record still stands. What a champion!",
    "cer_record_broken": "New record! {name} enters legend!",
    "rec_new": "NEW RECORD!",
    "aw_inlizza": "in the running",
    "cont_title": "The chasers",
    "cer_contenders": "And watch these: a whisker from the podium!",
    "notif_win": "🏆 You won {list}! +{pts} points added.",
    "notif_more": "and {n} more",
    "aw_ammazza": "Giant-Slayer",
    "d_ammazza": "the biggest upset",
    "full_ammazza": "Beat an opponent rated far higher: the week's upset.",
    "cer_q_ammazza": "David beats Goliath!",
    "val_ammazza": "{n} Elo gap",
    "aw_beniamino": "Crowd Favorite",
    "d_beniamino": "the most challenged",
    "full_beniamino": "The cat others challenged the most: a real star.",
    "cer_q_beniamino": "Everyone wants a shot!",
    "val_beniamino": "{n} challenges received",
    "aw_debuttante": "Rookie of the Week",
    "d_debuttante": "best newcomer",
    "full_debuttante": "The best card created this week, by number of wins.",
    "cer_q_debuttante": "Born to fight!",
    "val_debuttante": "{n} wins",
    "aw_astro": "Rising Star",
    "d_astro": "biggest Elo climb",
    "full_astro": "Who gained the most Elo this week: on the rise.",
    "cer_q_astro": "Unstoppable rise!",
    "val_astro": "+{n} Elo",
    "aw_pantofolaio": "Couch Potato",
    "d_pantofolaio": "fought the least",
    "full_pantofolaio": "The joke prize: among those who fought, did the least.",
    "cer_q_pantofolaio": "The couch is calling!",
    "val_pantofolaio": "only {n} matches",
    "hof_piccoelo": "Elo Peak",
    "val_piccoelo": "{n} Elo",
    "hof_regno": "Longest Reign",
    "val_regno": "{n} days",
    "hof_muro": "The Wall",
    "val_muro": "{n} defenses",
    "hof_pluricampione": "Multi-Champion",
    "val_pluricampione": "{n} titles",
    "hof_novevite": "The Nine Lives",
    "val_novevite": "Path complete"
  },
  "gang": {
    "login": "Sign in to use clans.",
    "none_title": "🛡️ Clans",
    "none_sub": "Join a clan or create your own. Together you fight as a team.",
    "create": "Create your clan",
    "name_ph": "Clan name",
    "emblem": "Emblem",
    "create_btn": "🛡️ Create clan",
    "board": "📋 Board — existing clans",
    "board_empty": "No clans yet. Be the first to create one!",
    "members_n": "{n} members",
    "cards_n": "{n} cards",
    "apply": "Apply",
    "applied": "✅ Request sent",
    "full": "Full",
    "invites": "✉️ Your invites",
    "invited_by": "invite from {who}",
    "accept": "Accept",
    "decline": "Decline",
    "members": "👥 Members",
    "leader": "👑 leader",
    "roster": "🃏 Roster",
    "roster_empty": "Empty roster. Add your cards!",
    "add_card": "➕ Add",
    "add_none": "No cards to add",
    "remove": "Remove",
    "apps": "📥 Join requests",
    "apps_empty": "No requests.",
    "approve": "Accept",
    "reject": "Reject",
    "leave": "🚪 Leave clan",
    "disband": "💥 Disband clan",
    "leave_confirm": "Leave the clan?",
    "disband_confirm": "You are the leader: leaving disbands the clan. Confirm?",
    "created": "🛡️ Clan created!",
    "order_hint": "(the leader can reorder with ▲▼)",
    "inv_title": "✉️ Invite players",
    "inv_browse": "🔎 Browse players",
    "invite_btn": "Invite",
    "invited_lbl": "✅ Invited",
    "no_free": "No free players to invite.",
    "search_ph": "Search a clan…",
    "more": "Load more",
    "open_lbl": "Open",
    "closed_lbl": "🔒 Closed",
    "browse_others": "📋 Browse other clans",
    "set_open": "🔓 Open the clan",
    "set_closed": "🔒 Close the clan",
    "search_player": "Search a player…",
    "see_cards": "See cards",
    "back": "Back",
    "no_cards": "No published cards.",
    "invite_sent": "✉️ Invite sent!",
    "kick": "Kick",
    "kick_confirm": "Kick this member from the clan?",
    "joined_msg": "🛡️ You joined a clan!",
    "kicked_msg": "🚪 You are no longer in the clan.",
    "changed_msg": "Your clan changed.",
    "attack": "⚔️ Attack",
    "war_won": "🏆 War won! +30 clan points",
    "war_lost": "💥 War lost. +5 consolation",
    "no_fresh": "No fresh cards to field (they are resting).",
    "enemy_empty": "The enemy clan has no cards in the roster.",
    "pts": "pts",
    "war_confirm": "Attack {name}? Your cards will then rest for an hour.",
    "pick_title": "Choose your lineup",
    "pick_desc": "Tap cards in order (min {min}, max {n}). The winner stays on.",
    "pick_go": "⚔️ Attack ({n})",
    "def_hint": "Cards defend in roster order: they field as many as the attacker brings (3–5).",
    "def_size_lbl": "Defenders:",
    "warlog_title": "War log",
    "warlog_empty": "No wars yet.",
    "wl_attacked": "You attacked {name}",
    "wl_defended": "{name} attacked you",
    "wl_win": "Win",
    "wl_lose": "Loss",
    "mycards_title": "My cards in clans",
    "mycards_pull": "Withdraw",
    "map_btn": "🗺️ Territory map",
    "map_title": "Cats’ Quarter",
    "map_legend": "Who rules",
    "map_empty": "The map hasn’t been created yet.",
    "map_nobody": "No clan controls a territory yet.",
    "you": "you",
    "zone_count": "{n} zones",
    "zone_free": "Free territory",
    "zone_yours": "You control it",
    "zone_owner": "Held by {name}",
    "zone_defends": "Your cards defend it. Yields {n} points/day.",
    "zone_free_note": "No one holds it — conquer it. Yields {n} points/day.",
    "zone_enemy_note": "Enemy zone. Yields {n} points/day to its holder.",
    "zone_mine_def": "Your defense guards this zone",
    "zone_noclan": "Join a clan to play the map.",
    "zone_leader_only": "Only the leader can attack.",
    "zone_noadj": "Not adjacent to your zones",
    "zone_beachhead": "Start from a free zone",
    "zone_attack": "Attack the zone",
    "zone_confirm": "Attack {name}?",
    "zone_won": "🏆 Zone conquered!",
    "zone_lost": "💥 Attack repelled",
    "wl_took": "conquered",
    "wl_failed": "failed to take",
    "zone_porto": "Fish Harbor",
    "zone_tetti": "Warm Roofs",
    "zone_giardino": "Garden",
    "zone_vicolo": "Alley",
    "zone_piazza": "Grand Square",
    "zone_mercato": "Market",
    "zone_parco": "Park",
    "zone_fontana": "Fountain",
    "zone_molo": "Pier",
    "pick_min": "Pick at least {n}",
    "scout_title": "Recon",
    "scout_enemy": "They defend",
    "scout_yours": "You field (min {n})",
    "scout_go": "⚔️ Attack ({n})",
    "scout_pickmin": "Pick at least {n}",
    "scout_wait": [
      "Lemme see them champs! Who’s goin’ in? 👀",
      "Show me the lineup, I gotta size up the enemy!",
      "Pick your fighters, pick ’em! I ain’t got all day!"
    ],
    "sfregio_name": "Scratch",
    "sfregio_pct": "~{p}% — trust me, pal! 🐾",
    "sfregio_hi": [
      "Pfft, they’ll mop the floor with ’em! Bet my whiskers on it! 💥",
      "Easy peasy, kitty! These fluffballs faint at a hiss!",
      "Victory’s in the bag! I’m already fetchin’ the confetti! 🎉",
      "A walk in the park, pal. Bring back a medal, will ya?"
    ],
    "sfregio_mid": [
      "Eh, it’s a coin toss… but what are we, kittens? Go for it!",
      "Fifty-fifty, buddy. Cross your paws and pray!",
      "Could go either way. Keep them claws sharp!",
      "Even odds. I’d place a tiny bet… but don’t tell ’em I said so!"
    ],
    "sfregio_low": [
      "Ooh, risky, kitty. Risky but juicy! I’d maybe try it…",
      "Yikes, this looks rough. Pack a bandage, just in case.",
      "Long shot, pal. But heroes love a gamble… or a nap.",
      "Don’t love it. Still, fortune favors the furry… sometimes."
    ],
    "sfregio_bad": [
      "You kiddin’ me? These beasts’ll eat ya alive! 🙀",
      "Pure suicide, buddy. Come back when you’ve bulked up.",
      "Nope nope nope. They’ll make mincemeat outta ya!",
      "Are you nuts? Those are lions in disguise! …your funeral."
    ],
    "need3": "You need at least 3 fresh cards to attack (3v3).",
    "zone_take_free": "Take {name}? It’s free: you grab it without a fight.",
    "rendita_line": "💰 Your {c} cards here earn ~{x} points/day.",
    "rendita_none": "💰 Conquer zones on the map: your cards will start earning points every day.",
    "card_of": "by {name}",
    "apply_nocards": "You have no cards to offer.",
    "apply_allused": "All your cards are already in a clan.",
    "apply_pick": "Which card do you apply with?",
    "applied_ok": "✉️ Request sent!"
  }
};
