(window.LANG_DB=window.LANG_DB||{})["fr"] = {
  "ui": {
    "tagline": "Photographie ton chat et transforme-le en carte à collectionner",
    "tab_crea": "📸 Créer",
    "tab_carte": "📚 Cartes",
    "tab_dojo": "🥋 Dojo",
    "tab_mondo": "🌍 Monde",
    "tab_mercato": "🔁 Marché",
    "tab_boss": "🤖 Boss",
    "tab_pal": "🏋️ Salle",
    "tab_med": "🏅 Médailles",
    "tab_reg": "📖 Règles",
    "drop_title": "Touche pour prendre ou charger une photo",
    "drop_sub": "JPG ou PNG — l'idéal : un chat bien visible",
    "cat_name": "Nom du chat (facultatif)",
    "gen_btn": "✨ Générer la carte",
    "dl_card": "⬇️ Télécharger la carte (PNG)",
    "regen_btn": "🔁 Regénérer le dessin (30 points)",
    "new_card": "🔄 Nouvelle carte",
    "coll_title": "📚 Ta collection",
    "dojo_title": "🥋 Dojo",
    "your_card": "Ta carte",
    "opponent": "Adversaire",
    "fight_btn": "⚔️ Combat !",
    "tourn4": "🏆 Tournoi à 4",
    "tourn8": "🏆 Tournoi à 8",
    "albo": "📊 Palmarès",
    "pub_sum": "🗂️ Choisis les cartes à publier dans le Monde",
    "player_name": "Ton pseudo (obligatoire, 3 lettres min)",
    "pub_btn": "📤 Publier les cartes choisies",
    "duel_title": "⚡ Défie un ami",
    "duel_champ": "Ton champion pour le duel",
    "qr_show": "📱 Montrer mon QR",
    "qr_scan": "📷 Scanner le sien",
    "world_title": "🌍 Arène Mondiale",
    "my_world": "🐱 Tes cartes dans le monde",
    "my_online": "Ta carte pour les défis en ligne",
    "find_btn": "🔄 Chercher des adversaires",
    "leader_title": "🏅 Classement mondial",
    "leader_more": "⬇️ Voir plus de positions",
    "market_title": "🔁 Marché",
    "trade_title": "🔄 Échange (troc)",
    "trade_browse": "🔍 Parcourir les cartes",
    "trader_ask": "💰 Demander conseil au Marchand",
    "auc_title": "⚖️ Enchères",
    "auc_create": "🔨 Mettre une carte aux enchères",
    "auc_refresh": "🔄 Actualiser les enchères",
    "boss_title": "🤖 Boss de l'Arène",
    "boss_chall": "Ton challenger (cartes publiées)",
    "gym_title": "🏋️ Salle de sport",
    "gym_student": "L'élève du jour",
    "gym_pantry": "🍽️ Garde-manger — achète, puis mérite-le en jouant",
    "coach_ask": "🎓 Demander conseil au Coach",
    "mis_title": "📅 Missions du jour",
    "med_title": "🏅 Médailler",
    "reg_title": "📖 Les règles de CatCards",
    "opt_title": "⚙️ Options",
    "locked_title": "Connexion requise",
    "locked_txt": "Points, Marché, défis et entraînements vivent sur ton compte : connecte-toi pour utiliser Dojo, Monde, Marché, Boss et Salle.",
    "login_google": "🔵 Connexion avec Google",
    "login_hint": "Connecte-toi : points, Marché et défis vivent sur ton compte",
    "logout": "Déconnexion",
    "close": "✖ Fermer",
    "skip_intro": "⏭️ Passer la présentation",
    "bet_title": "🥊 Le coin de Tonton Rocco",
    "bet_sub": "🎲 Pronostic",
    "bet_skip": "Pas de pari, place au match !",
    "bet_back": "↩️ Retour (annuler le match)",
    "points_lbl": "💰 Tes points:",
    "dl_short": "⬇️ Télécharger",
    "nick_btn": "✏️ Changer le surnom",
    "theme_btn": "▶️ Écouter le thème",
    "retire_btn": "🚪 Retirer du monde",
    "frame_btn": "🎨 Cadre d'Or (100 points)",
    "del_btn": "🗑️ Supprimer"
  },
  "stat": {},
  "rarity": {},
  "ann": {
    "red": "Dans le coin rouge... {n}... «{k}»!",
    "blue": "Dans le coin bleu... {n}... «{k}»!"
  },
  "nicks": {
    "n01": "Le Socrate de la Boîte",
    "n02": "Le Baron Croc-Tordu",
    "n03": "Le Colosse de la Braise",
    "n04": "Le Gladiateur de l'Asphalte",
    "n05": "Le Fromage Dormant",
    "n06": "Le Monolithe de Peluche",
    "n07": "Le Maître Lécheur Zen",
    "n08": "L'Imperturbable Zen",
    "n09": "La Forteresse Douce Inamovible",
    "n10": "Le Radar de l'Outre-Canapé",
    "n11": "Le Radar des Ennuis",
    "n12": "Sa Douceur Hypnotique",
    "n13": "Le Vétéran du Ronron",
    "n14": "Le Triste Hypnotiseur Félin",
    "n15": "Le Panzer de Soie",
    "n16": "Le Pot d'Échappement Enflammé",
    "n17": "La Boule Hypnotique",
    "n18": "La Griffe au Gingembre",
    "n19": "Le Dirigeable de Table",
    "n20": "Le Bastion de Poils",
    "n21": "La Joue d'Acier",
    "n22": "Le Fantôme du Canapé",
    "n23": "La Furie du Sous-Escalier",
    "n24": "La Tornade de Poils",
    "n25": "L'Ombre du Garde-Manger",
    "n26": "Le Ninja du Rebord",
    "n27": "L'Avalanche Fauve",
    "n28": "Le Tueur de Rideaux",
    "n29": "La Terreur des Pelotes",
    "n30": "La Locomotive Paresseuse",
    "n31": "Le Philosophe du Radiateur",
    "n32": "L'Ouragan en Pantoufles",
    "n33": "Le Guépard de Salon",
    "n34": "Le Sphinx du Frigo",
    "n35": "L'Éclair Sournois",
    "n36": "Le Coussin Tueur",
    "n37": "La Bête du Balcon",
    "n38": "Le Général Griffe",
    "n39": "L'Acrobate de Minuit",
    "n40": "Le Sultan de la Sieste",
    "n41": "Le Tigre de la Moquette",
    "n42": "Le Fantôme de l'Escalier",
    "n43": "Le Destructeur de Canapés",
    "n44": "La Panthère du Palier",
    "n45": "Le Baron des Bouchées",
    "n46": "L'Empereur du Panier",
    "n47": "Le Pirate du Poisson Frais",
    "n48": "L'Éclair en Peluche",
    "n49": "Le Champion des Croquettes",
    "n50": "Le Stratège du Grenier",
    "n51": "Le Monstre des Pantoufles",
    "n52": "La Duchesse Griffue",
    "n53": "Le Viking Velouté",
    "n54": "L'Énigme à Moustaches",
    "n55": "Le Cyclone Silencieux",
    "n56": "La Patte du Destin",
    "n57": "Le Roi du Carton",
    "n58": "L'Embuscade Permanente",
    "n59": "La Météorite Moelleuse",
    "n60": "La Légende de la Cour",
    "n61": "Le Gardien de la Gamelle",
    "n62": "L'Œil de la Nuit",
    "n63": "Le Samouraï Pelé",
    "n64": "La Furie Tricolore",
    "n65": "Le Professeur d'Embuscades",
    "n66": "L'Amiral des Toits",
    "n67": "Le Rouleau Compresseur",
    "n68": "La Peste Élégante",
    "n69": "Le Volcan Somnolent",
    "n70": "La Griffe de Velours",
    "n71": "Le Bandit de la Cuisine",
    "n72": "La Sentinelle du Frigo",
    "n73": "Le Dragon du Coussin",
    "n74": "L'Écho du Miaulement",
    "n75": "Le Maître du Ronronnement",
    "n76": "La Tempête de Poche",
    "n77": "Le Doux Géant",
    "n78": "Le Dernier Errant",
    "n79": "Le Chasseur de Lézards",
    "n80": "La Neuvième Vie"
  },
  "descrs": {
    "d01": "Dort 20 heures par jour et s'entraîne à mieux dormir les 4 autres.",
    "d02": "N'a jamais perdu une bataille contre une chaussette.",
    "d03": "Pense que le frigo lui doit des explications.",
    "d04": "Maître dans l'art d'occuper exactement la place où tu voulais t'asseoir.",
    "d05": "A renversé trois vases. Tous coupables.",
    "d06": "Parle trois langues : ronron, miaou et mépris.",
    "d07": "Court à 4h du matin pour des raisons qui nous dépassent.",
    "d08": "Un guerrier né, tant que le canapé est à moins de deux mètres.",
    "d09": "Sa gamelle est à moitié vide. Toujours. Même pleine.",
    "d10": "Fixe le mur parce que le mur a commencé.",
    "d11": "Ancien errant, désormais cadre supérieur de la sieste.",
    "d12": "Ronronne comme un tracteur et griffe comme un rasoir.",
    "d13": "Le vétérinaire le revoit encore dans ses cauchemars.",
    "d14": "Ne chasse pas les souris : envoie des avis d'expulsion.",
    "d15": "Sait ouvrir trois types de portes et fait semblant de ne pas savoir.",
    "d16": "La boîte vaut plus que le cadeau. Toujours.",
    "d17": "Docteur en regards de jugement.",
    "d18": "Combat le crime. Le crime, c'est l'aspirateur.",
    "d19": "Chaque chaise de la maison est à lui. Même la tienne.",
    "d20": "S'entraîne sur les rideaux quand personne ne regarde.",
    "d21": "Passe-temps favori : faire tomber des objets avec élégance.",
    "d22": "Miaule en do mineur quand la gamelle est vide.",
    "d23": "Personne ne l'a vu arriver. Seulement repartir avec le dîner.",
    "d24": "Pèse juste ce qu'il faut pour bloquer tes jambes.",
    "d25": "Les lézards du quartier ont mis sa tête à prix.",
    "d26": "Dort dans des positions qui défient la physique et le bon sens.",
    "d27": "A compris le laser. Fait semblant par pitié.",
    "d28": "Un croisement entre un coussin et un piège à loup.",
    "d29": "Surveille le quartier depuis la fenêtre comme un chef d'État.",
    "d30": "Son ronron soigne le stress. Ses griffes le provoquent.",
    "d31": "Mange comme un loup, dort comme une pierre, règne comme un roi.",
    "d32": "Le seul chat à avoir gagné un débat contre un concombre.",
    "d33": "Se vexe si tu le regardes. Se vexe si tu ne le regardes pas.",
    "d34": "A trois cachettes secrètes. La meilleure : le milieu du couloir.",
    "d35": "Tombé dans un bol de crème étant petit. Ne s'en est jamais remis.",
    "d36": "Enseigne le yoga aux chats du quartier. Leçon un : ignorer tout le monde.",
    "d37": "Le facteur a demandé sa mutation.",
    "d38": "Collectionne les élastiques. Personne ne sait où il les cache.",
    "d39": "Quand l'orage gronde, il protège la maison. De sous le lit.",
    "d40": "Son regard a fait fuir deux chiens et un plombier.",
    "d41": "Vit pour trois choses : manger, dormir et te juger.",
    "d42": "A vu une souris un jour. Ils en parlent encore tous les deux.",
    "d43": "Très élégant jusqu'à ce qu'il tombe du rebord.",
    "d44": "A adopté une famille d'humains. Il les dresse bien.",
    "d45": "Il ne monte pas sur la table. La table descend à son niveau.",
    "d46": "Sait exactement quand tu ouvres le thon. Même à un pâté de maisons.",
    "d47": "La pelote était déjà comme ça à son arrivée.",
    "d48": "Moitié chat, moitié sirène d'alarme de 5h du matin.",
    "d49": "Se bat avec honneur, gagne avec style, dort sans honte.",
    "d50": "La dernière chose que voient les tapis avant la fin."
  },
  "battle": {
    "skip": "⏭️ Présentation zappée : droit au but !",
    "open": "🎤 MESDAMES ET MESSIEUUURS… bienvenue dans l'Arène CatCards !",
    "red": "🔴 Coin rouge : {NAME}, «{nick}» ! {rec}",
    "blue": "🔵 Coin bleu : {NAME}, «{nick}» ! {rec}",
    "debut": "Pour ses débuts dans l'arène !",
    "theme": "🎵 Le thème d'entrée de {name} retentit…",
    "ding": "🔔 DING DING DING !",
    "first_fast": "⚡ {name} est plus rapide et frappe en premier !",
    "first_surprise": "😼 {name} surprend tout le monde et commence !",
    "round_end": "🔔 Fin du round {round} ! Les chats regagnent leur coin pour se lécher…",
    "charmed_skip": "😍 {name} est envoûté et perd son tour !",
    "chant": "🎺 Des tribunes : «{NAME} ! {NAME} !»",
    "pu_yarn": "🧶 Une pelote roule dans l'arène ! {name} joue et récupère {hp} PV",
    "pu_catnip": "🌿 Herbe à chat ! {name} est excité : prochain coup DOUBLÉ (mais un peu dans les vapes…)",
    "pu_box": "📦 Un carton ! {name} ne résiste pas : passe son tour mais devient INTOUCHABLE !",
    "pu_fish": "🐟 Un poisson frais vole dans l'arène ! {name} pétille d'énergie : +agilité pour 3 tours",
    "purr_heal": "💗 {name} ronronne et récupère {hp} PV",
    "double_paw": "🐾 Double Coup de Patte ! {name} attaque encore !",
    "box_dodge": "📦 {opp} est planqué dans le carton : le coup de {name} rate !",
    "dodge": "💨 {name} tente {move} mais {opp} esquive !",
    "final_blow": "⏱️ Le temps ralentit… COUP FINAL !",
    "hit": "{icon} {name} utilise {move} !{crit}{catnip}  −{dmg} PV",
    "crit_tag": " 💥 CRITIQUE !",
    "catnip_tag": " 🌿 BOOSTÉ !",
    "dev1": "😱 Coup dévastateur !",
    "dev2": "🎙️ Le public est en délire !",
    "dev3": "💢 Quelle puissance !",
    "on_fire": "🔥 {name} est EN FEU ! Trois coups d'affilée !",
    "on_ropes": "🎙️ {opp} est dans les cordes ! Le public retient son souffle…",
    "clever": "✨ Ruse ! {opp} est confus et perdra un tour !",
    "nine_lives": "🐈 {opp} utilise une de ses Neuf Vies et reste debout avec 1 PV !",
    "charm_hit": "✨ {opp} est envoûté par le charme de {name} !",
    "replay": "📹 REPLAY du coup final…",
    "winner": "🏆 {name} remporte le combat !",
    "win_points": "💰 +10 points pour la victoire !",
    "boss_points": "💰 +10 points : tu as dompté un Boss de l'Arène !",
    "boss_noprize": "🎖️ Boss déjà battu aujourd'hui : la gloire oui, la récompense demain.",
    "boss_survives": "🤖 Le Boss reste debout... l'essai du jour est perdu : à demain (avec de l'herbe à chat 🌿, peut-être).",
    "tourn_champ": "👑 {name} est le CHAMPION du tournoi !",
    "world_ok": "🌍 Résultat enregistré dans l'Arène Mondiale !",
    "bet_win": "🎲 Bien vu ! Tu avais misé {stake} sur {name} : +{gain} points (total : {total})",
    "bet_lose": "🎲 Mauvais pronostic : −{stake} points (total : {total}). La prochaine fois !",
    "stake": "🎁 En jeu — victoire : {win} · défaite : +{lose} XP",
    "stake_pts": "+{pt} points et +{xp} XP",
    "stake_nopts": "+{xp} XP (aucun point en local)",
    "boss_stake_note": " — points seulement à la 1re victoire du jour",
    "entry_catnip": "🌿 {name} entre dans l arène déjà gonflé à l herbe à chat !"
  },
  "chars": {
    "rocco_warn": "Méfie-toi de sa {stat} : c'est là qu'il te bouffe.",
    "rocco_70": "Petit, tu le mets K.O. avant le gong. Fais pas le malin, termine vite.",
    "rocco_55": "Tu es favori, mais les favoris qui dorment finissent au tapis. Frappe le premier.",
    "rocco_50": "Cinquante-cinquante, petit : ça se joue à qui a le plus faim. Si t'as 50 points, l'herbe à chat les vaut tous.",
    "rocco_35": "Je te mens pas : il est plus costaud. Sans herbe à chat, je ferais pas ce combat.",
    "rocco_lose": "Écoute le vieux Rocco : celui-là te brise. Retourne à la salle, prends un niveau, on en reparle APRÈS. Si tu y tiens, au moins l'herbe à chat.",
    "baratto_great": "🤑 Une affaire en or ! Tu reçois bien plus que tu ne donnes — conclus vite.",
    "baratto_good": "👍 Bonne affaire : tu y gagnes. Le Marchand approuve.",
    "baratto_even": "⚖️ Échange équitable : décide avec le cœur, pas le portefeuille.",
    "baratto_bad": "😾 Tu y perds un peu... t'es sûr ? Le Marchand fronce les moustaches.",
    "baratto_terrible": "🙀 Affaire catastrophique ! Tu donnes bien plus que tu ne reçois. Laisse tomber.",
    "baratto_empty": "Aucune carte à troquer ! Fabriques-en et reviens : au bazar on fait des affaires, pas la charité.",
    "inc_100a": "CENT POINTS ! Quelle folie magnifique ! 😼",
    "inc_100b": "Une offre royale ! Et qui ose surenchérir ?",
    "inc_50a": "Cinquante ! Le public frémit, mesdames et messieurs !",
    "inc_50b": "Belle somme ! L'enchère s'échauffe !",
    "inc_bata": "Et ça surenchérit encore ! Ils ne s'arrêtent plus !",
    "inc_batb": "Un combat au dernier point, quel spectacle !",
    "inc_starta": "Première offre sur le billot ! Qui dit mieux ?",
    "inc_startb": "C'est parti ! Adjugé à celui qui ne lâche rien !",
    "baffo_open": [
      "Miaou, recrue ! ",
      "Écoute le vieux Baffo : ",
      "Recrache la croquette et écoute : ",
      "De mon temps, pas de coussins moelleux. ",
      "Moustaches droites, oreilles dressées : "
    ],
    "baffo_empty": "La salle est vide ! Amène-moi un élève depuis l'onglet 📸 Créer.",
    "baffo_indiff_afford": "Le point faible de {name}, c'est {stat} ({val}) : entraîne-la avec le combo {combo} (60 points), tu peux te le permettre.",
    "baffo_indiff_save": "Le point faible de {name}, c'est {stat} ({val}), mais ça ne s'entraîne qu'avec le combo {combo} (60 points) : il te manque {miss} points, mets-les de côté.",
    "baffo_indiff_alt": " Ou en attendant, renforce {stat2} ({val2}) avec {food} (25 points).",
    "baffo_weak": "Le point le plus faible de {name}, c'est {stat} ({val}) : donne-lui {food}.",
    "baffo_combo": "Tu as {pts} points : le combo {combo} ({tgt}) fait grimper deux choses en un seul repos — cher mais pratique si tu es pressé.",
    "baffo_record_bad": "Avec {w} victoires et {l} défaites, il lui faut du cran, pas des câlins.",
    "baffo_unbeaten": "Il est invaincu : gare à ce qu'il ne prenne pas la grosse tête.",
    "baffo_margin": "Marge d'entraînement épuisée : seules les victoires dans le Monde débloquent des progrès.",
    "baffo_broke": "Et les caisses sont vides ({pts} points) : gagne quelques paris mondiaux.",
    "baffo_fit": "{name} est en pleine forme. Fais-le combattre, le banc ramollit les muscles.",
    "felini_open": [
      "Écoute le Manager : ",
      "J’ai flairé l’affaire : ",
      "Le ring est un échiquier : ",
      "Les chiffres parlent, petit : "
    ],
    "felini_checking": "Un instant, je consulte les registres…",
    "felini_noauth": "Connecte-toi d’abord, petit : les affaires se font avec un nom sur le contrat.",
    "felini_nocard": "Tu n’as pas de champion publié. Publie une carte et parlons affaires.",
    "felini_resting": "😴 {name} récupère : reviens quand il sera de nouveau prêt et on parlera stratégie.",
    "felini_norank": "Ton champion n’apparaît pas au classement : republie-le et reviens me voir.",
    "felini_loss_streak": "{name} a perdu {n} de suite (🧊) : retire-le du circuit un moment, emmène-le chez le Coach, et fais-le revenir affamé.",
    "felini_champ": "{name} est le CHAMPION 👑 : défends la couronne{chaser}.",
    "felini_chaser": ", et méfie-toi de {name} (#2, {elo} pts) qui piaffe",
    "felini_target": "le bon prochain combat pour {name} (#{rk}) c’est {tname} de {owner} (#{trk}, {elo} pts) : {verdict}",
    "felini_v_risky": "risqué, mais si tu le bats tu fais un carton au classement.",
    "felini_v_beatable": "sur le papier il est prenable : une victoire de gestion.",
    "felini_v_even": "un combat à égalité, de ceux que le public adore.",
    "felini_prob_low": "Mais soyons clairs : Tonton Rocco estime tes chances à seulement {p}%. J’attendrais — la salle, un niveau de plus, ENSUITE on signe le contrat.",
    "felini_prob_mid": "Les probabilités disent {p}% : match ouvert, les nerfs décideront (et peut-être l’herbe à chat 🌿).",
    "felini_prob_high": "Tonton Rocco estime {p}% de victoire : à ta portée. Vas-y et boucle le match.",
    "felini_belt": "Et retiens : celui-là a la CEINTURE 👑 — le classement ne compte pas, tu le bats et c’est TOI le champion.",
    "felini_hot": "Attention quand même : c’est un adversaire coriace, sur une série de {n} victoires 🔥.",
    "felini_cold": "Et je te le dis : il est en pleine crise (🧊 {n} défaites de suite) — le moment parfait pour frapper.",
    "felini_catnip_need": "Mon conseil du coin du ring : investis 50 points dans l’herbe à chat 🌿 avant le match — contre un pareil il faut le turbo.",
    "felini_catnip_broke": "Il faudrait de l’herbe à chat 🌿, mais les caisses pleurent ({pts} points) : soit tu trouves des points, soit tu choisis une cible plus tendre.",
    "felini_catnip_opt": "De l’herbe à chat 🌿 ? Facultatif : match à égalité, les nerfs décideront.",
    "felini_catnip_no": "Pas d’herbe à chat : il s’en sort avec ses propres pattes, garde tes points.",
    "felini_notarget": "aucune cible d’autres propriétaires au-dessus de toi pour l’instant (ou ils se reposent tous) : défends ta position, ou repasse plus tard.",
    "felini_margin": "Et il lui reste encore {n} points de marge à la salle : un bon repas avant le match n’a jamais tué personne.",
    "trader_open": [
      "Psst, l’ami : ",
      "Affaires, affaires ! ",
      "Le Marchand sait tout : ",
      "Entre nous qui nous y connaissons : "
    ],
    "trader_best": "garde bien {name}, celle-là vaut de l’or : ne la cède pas pour trois francs.",
    "trader_worst": "s’il faut vraiment donner quelque chose, commence par {name} — tu as mieux en main.",
    "trader_commons": "Tu as un tas de {rar} ({n}) : échange-en deux contre quelque chose de plus rare, crois-moi.",
    "trader_gem": "Et attention : il y a une {rar} de {owner} en vitrine — si tu as un bon double, tente l’échange avant qu’un autre ne la prenne.",
    "trader_browse": "Appuie sur «Parcourir les cartes à échanger» et montre-moi ce qui circule : je te dis s’il y a une affaire."
  }
};
